### ISSUE TITLE
Compiling the generated java class

### ISSUE THREAD

**Issue by Vaishali17** [joelittlejohn/jsonschema2pojo#1006]
Hi All,

We have a requirement where we have to generate a java pojo class dynamically using json schema.
Till now we are able to generate the class on the fly, but unable to compile the class for further processing.
For compilation classloader should get the class but as the java class is getting generated dynamically, class loader  does not get it and throws InvocationTargetException.
Is there any way of compiling the java package again like using some maven plugin or some other way?

 Thanks,
Vaishali Mangwani

**Comment by joelittlejohn** [comment]
This is outside the scope of this project, however you can look at the integration tests in this project for guidance.

**Comment by dewthefifth** [comment]
https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ConstructorsIT.java is a good example of such a class, which compiles the JsonSchema into an actual Java class which can be executed.
