### ISSUE TITLE
URL as source not working in latest releases

### ISSUE THREAD

**Issue by Arkioner** [joelittlejohn/jsonschema2pojo#1010]
The issue https://github.com/joelittlejohn/jsonschema2pojo/pull/294 works perfect if i use the 0.4.9 version of the gradle plugin but when i try to do the same with the 1.0.1 it always throw an error saying : `Cannot convert URL 'https://midomain.com/Refund-Event.json/1.json' to a file.`. Is the new version broken or i'm missing something?

**Comment by joelittlejohn** [comment]
Could you try with some other versions between 0.4.9 and 1.0.1? Maybe we could narrow this down to a particular version and see which change introduced the problem.

**Comment by Arkioner** [comment]
not right now. Moved to another project :(

**Comment by seittema** [comment]
Know this is an old thread, but I'm having the same issue with the url not working either in the latest build.  it might be with 0.4.13.  04.12 worked but 0.4.13 gave me the following: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.13:generate failed: URI scheme is not "file"

**Comment by d4kine** [comment]
*Push* maybe some will consider this open ticket. Is there a quickfix possible, also with possible authentication (basci) in mind?
