### ISSUE TITLE
Question on traversing the object graph

### ISSUE THREAD

**Issue by davidmpaz** [joelittlejohn/jsonschema2pojo#1013]
Hi,

first of all thanks for this library! This is more a question than an issue.

Would it make sense to have some kind of Visitor functionality (activated by configuration option) to apply operations to generated POJOs? 

I am thinking now on some sort of transformations or data extraction from the parsed objects. The reason why i am coming into this is that basically i would like to have some sort of functionlaity similar to XSLT transformations for XML.

If you think it could be a good idea, I would gladly make a pull request adding desired functionality. As i see it is about generating the needed interfaces with the visit and accept method and implementing those interfaces in generated classes.

If the whole story about visitor pattern is not that good i would appreciate hints or directions where too look. I have read some posts already about pattern matching but i am not sure it will do better here.

thanks in advance for your time,
David

**Comment by joelittlejohn** [comment]
I think this falls outside the scope of this project I'm afraid. There's all kinds of additions, changes and extensions we could make to Java classes, but this project really needs to remain focused on what's needed to support JSON binding. It's just not possible for us to have enough time to maintain all these additional features that related to generating different kinds of Java code according to peoples taste or the desires of their projects.

I'm not saying your suggestion is not useful, I can definitely see the value in what you're suggestion, but I'm afraid it's just outside what we reasonably support in the core of this tool.
