### ISSUE TITLE
Objects are not marked with "@Valid" (Version 1.0.1)

### ISSUE THREAD

**Issue by thorstenhilker** [joelittlejohn/jsonschema2pojo#1015]
Hi!
After I'm activating the option "includeJsr303Annotations" I expected objects in the generated class to be marked with "@Valid" as it is stated in the documentation:
http://joelittlejohn.github.io/jsonschema2pojo/site/1.0.1/Jsonschema2PojoTask.html
But the annotation is only be added to collections not to other objects.
Here my sample code:
```
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "integer"
    },
    "baz": {
      "type": "boolean"
    },
    "broadcaster": {
      "type": "object",
      "$ref": "#/definitions/Broadcaster"
    }
  },
  "definitions": {
    "Broadcaster": {
      "properties": {
        "channelCode": {
          "type": "string"
        },
        "usageMedium": {
          "type": "string"
        }
      },
      "required": [
        "channelCode"
      ]
    }
  }
}
```
Regards,
Thorsten

**Comment by thorstenhilker** [comment]
Hi!

I found the problem.
Objects referenced by ""$ref" are not annotated.
This code works:
```
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "integer"
    },
    "baz": {
      "type": "boolean"
    },
    "broadcaster": {
      "type": "object",
      "properties": {
        "channelCode": {
          "type": "string"
        },
        "usageMedium": {
          "type": "string"
        }
      },
      "required": [
        "channelCode"
      ]
    }
  }
}
```
But I think this is still an issue.
Esspecially when the code is splited into more than one file.

Regards,
Thorsten

**Comment by joelittlejohn** [comment]
When you use a ref *all* content of the schema is replaced with the contents of the ref. This means your type:object is lost, which I believe is why you have found that the Valid annotation is missing. If you put the type inside the referenced schema (it should be there anyway) I think the problem will be fixed.

In the past ref was explicitly defined this way in the spec. I'm not sure if this has changed in more recent drafts.

**Comment by thorstenhilker** [comment]
Hi!
Your proposal worked:

```
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "integer"
    },
    "baz": {
      "type": "boolean"
    },
    "broadcaster": {
      "type": "object",
      "$ref": "#/definitions/Broadcaster"
    }
  },
  "definitions": {
    "Broadcaster": {

      "properties": {
        "channelCode": {
          "type": "string"
        },
        "usageMedium": {
          "type": "string"
        }
      },
      "required": [
        "channelCode"
      ]
    }
  }
}
´´´

Thanks a lot!
Thorsten
