### ISSUE TITLE
Description not supported for #ref

### ISSUE THREAD

**Issue by ben-r** [joelittlejohn/jsonschema2pojo#1016]
I think this is kinda related to #975 

Given this schema, using the latest version 1.0.1 :

```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Globally unique ID of the ad"
    },
    "adStatus": {
      "$ref": "#/definitions/adStatus",
      "description": "Ad related status data."
    }
  },
  "definitions": {
    "adStatus": {
      "properties": {
        "visible": {
          "type": "boolean",
          "description": "When false, the ad is not visible for consumers."
        }
      }
    }
  }
}
```

the generate class will not have a description for the `adStatus` property. This is needed to describe semantics of the same reference object dependent on where it's used.

**Comment by joelittlejohn** [comment]
Hi. When $ref is used, all other properties alongside the ref are ignore. The referenced schema replaces the schema where it is used entirely, so your description in `adStatus` is lost. Try putting the description inside the `adStatus` field inside the definitions and it will work.

**Comment by ben-r** [comment]
Sometimes you may want to use the same `$ref` in several different places, albeit using the same model, the semantics might be different, for instance the absence of the property dependent on the context.
