### ISSUE TITLE
Extending "Source Type" further to XML and XSD

### ISSUE THREAD

**Issue by prabu-manickam** [joelittlejohn/jsonschema2pojo#1018]
Hello  @joelittlejohn,
Thank you very much for this wonderful tool, it saved me a lot of time. 
I wish if the project had some additional features like generating POJO from direct XML data or from the XML schema files. I really admire that we have support to add Jackson annotations that already supports parsing XML data into objects but still it is a really painful(process is not very straight forward) task to convert XML data into POJOs.
I am not sure if you have ever considered this feature already but i am unable to find them in the existing issues list. If i am silly to ask this question please advise me what am i missing.

Thanks!
Prabu

**Comment by joelittlejohn** [comment]
This has been raised a few times, but this isn't something we will include in the core of this project I'm afraid. There are a lot of alternatives for creating XML binding types from XML or XSD e.g. JAXB. It's just too far outside the scope of this project to also include code to traverse XSD and generate types, that's a whole new project. 

I'm afraid this isn't something we'll add, but of course you can fork this repo and add something to meet your own needs. If you can, please do share with others.
