### ISSUE TITLE
Trying to override enum to use int instead of Long

### ISSUE THREAD

**Issue by MikeDombo** [joelittlejohn/jsonschema2pojo#1021]
I'm trying to generate an enum backed by an `int`, however I have other objects that I want to not use the primitives. I'm using the gradle plugin and I've set `usePrimitives` to false because for most of the generated values I do want it to use Java objects instead of the primitive. 

In an enum in JSON schema I tried setting "javaType": "int" but I got the error that the primitive "int" can't be used for enum values. I also tried setting it to `java.lang.Integer`, but that just overrode the enum and instead made the whole property an Integer instead of an enum backed by Integer.

Is there any way to do what I want, or at least get closer?

**Comment by joelittlejohn** [comment]
No, it's not possible to have one class use int and everything else user Integer I'm afraid.

**Comment by MikeDombo** [comment]
That's too bad, but thanks for the response. 

What about the possibility of using the "default" field if present to set the enum value in `fromValue` instead of throwing the `IllegalArgumentException`?

**Comment by joelittlejohn** [comment]
> What about the possibility of using the "default" field if present to set the enum value in fromValue instead of throwing the IllegalArgumentException?

Sorry, could you explain more about what you're referring to here? Maybe with some code as an example? I don't know what you're referring to.

**Comment by MikeDombo** [comment]
What I mean is that if I have a JSON schema like

```
"Operation": {
      "type": "integer",
      "enum": [0,1,2],
      "javaEnumNames": ["Unknown", "Connect", "Publish"],
      "default": 0
    },
```


Then I'd like the generated class to have the `fromValue` look like: 

```
       @JsonCreator
        public static Operation fromValue(Long value) {
           Operation constant = CONSTANTS.get(value);
            if (constant == null) {
               return Operation.Unknown; // Default to 0 (Unknown)
            } else {
                return constant;
            }
        }
```

**Comment by joelittlejohn** [comment]
This really isn't what the `default` means. I don't think we should ignore illegal values and replace with the default, this sounds like a way to hide incorrect values and produce subtle, hard to diagnose bugs.
