### ISSUE TITLE
Add Support for adding default values in case of sourceType=json

### ISSUE THREAD

**Issue by pshreenath** [joelittlejohn/jsonschema2pojo#1023]
similar to: https://github.com/joelittlejohn/jsonschema2pojo/issues/970

**Comment by frontfact** [comment]
I am curious to know why for the following json source:

```
{
  "index": 0,
  "isActive": false
}
```

the output is not:

```
public class ClassName {

    private int index = 0;
    private boolean isActive = false;

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public boolean isIsActive() {
        return isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
}
```

What am I missing, is there a hidden trap ? or is the feature just not implemented
Thank you for any comment

**Comment by joelittlejohn** [comment]
@frontfact Nope, that's not how this works. We don't assume that your 'example json' defines default values. That wouldn't work in most cases.

**Comment by joelittlejohn** [comment]
Sorry, the example JSON is supposed to be a shortcut to generate types that can represent it. If you want more advanced features, like defaults, create a schema.
