### ISSUE TITLE
Add JDK6+ @ConstructorProperties annotation to constructors

### ISSUE THREAD

**Issue by ddcruver** [joelittlejohn/jsonschema2pojo#1025]
This annotation would provide serialization clues to libraries that support it. 
This annotation is defined by the JDK so no external dependencies are needed.

This annotation is supported by Jackson and Spring Framework

Reference:
https://docs.oracle.com/javase/8/docs/api/java/beans/ConstructorProperties.html

Since this uses a JDK provided class could we update the ConstructorRule to just always generate it or do you believe we require configuration parameters to turn it on/off.  I have a "always do" implementation of this already ready.

**Comment by ddcruver** [comment]
Jackson Example: https://github.com/FasterXML/jackson-databind/blob/master/src/test/java/com/fasterxml/jackson/databind/deser/creators/CreatorPropertiesTest.java

**Comment by joelittlejohn** [comment]
I think since this is part of the jdk, a config option is not needed. As long as the annotation is also available on Android.

Is there a reason this annotation is needed if the constructor params are named appropriately? It looks like this is useful when you need to use different param names to the bean property names.

**Comment by ddcruver** [comment]
About the Android...

Good catch, unfortunately Android does not provided this class.  

Evidence:
- In Android Studio I can not import it.

- The reference guide doesn't have this class. (https://developer.android.com/reference/java/beans/IndexedPropertyChangeEvent)

- Someone having a cannot find symbol class ConstructorProperites error. (https://stackoverflow.com/a/28020733/45708)

**Comment by ddcruver** [comment]
About need for annotation even if constructor parameters are named appropriately ...

Prior to Java 7, if you compiled with debug symbols the parameter names are preserved but you must access them by reading the byte-code.  This most likely would require the serialization library to add and use an additional byte-code reading library.

Java 8, introduced the parameter name feature to the reflection API, but the -parameters command line switch must be added when compiling with javac. 

I believe that adding this annotation provides better comparability when using serialization libraries that don't support getting parameter names from byte-code or do not use the new Java 8 reflection API which both rely on if you compile the code with the appropriate arguments.  ConstructorProperties is the only way a library can rely on getting parameter names in Java 7+ regardless of how the developer compiles their code.

References:
https://www.beyondjava.net/reading-java-8-method-parameter-named-reflection
https://julien.ponge.org/blog/java8-parameter-names-and-jdk-dogfooding/

**Comment by ddcruver** [comment]
With my pull request I went with it being disabled by default because of the incompatibilities with Android.

**Comment by ddcruver** [comment]
#1026 implemented this feature and it has been merged into master.
