### ISSUE TITLE
Custom Class Name and Individual JSON File List provider

### ISSUE THREAD

**Issue by panbhatt** [joelittlejohn/jsonschema2pojo#1027]
Hey Team, 
I just came across a scenario, i think which is not covered here ( and I am ready to contribute if all vetted through team members). 
Requirement: Provide a list of Schema files (or json) and generate a specified Root class in a specified Package. 
E.g. 
```xml
<configuration>
    <schemaFiles>
         <schemaFile>
            <location>${basedir}/*/request/webrequest.json</location>
            <targetPackage>a.b.c</targetPackage>
           <className>EmployeeWebRequest</className>
     </schemaFile>
         <schemaFile>
            <location>${basedir}/*/request/webesponse.json</location>
            <targetPackage>a.b.d</targetPackage>
           <className>EmployeeWebResponse</className>
     </schemaFile>
</configuration>
```

   This would help us to generate two ROOT Classes EmployeeWebRequest.java and EmployeeWebResponse.java in their corresponding packages. All the associated Subclass would be present in the same corresponding  package. 
Through this we can customize the target directory, as well as customize the name of the Class File to Generate.

**Comment by ddcruver** [comment]
@panbhatt I believe you could try executing the jsonschema2pojo plugin twice. 

Additionally you could use javaType and provide a fully qualified name for the classes not in the main root package.

**Comment by panbhatt** [comment]
Hi Team,
I have tried different methods here. 
1. Run the <execution> twice with two different ID's. 
2. Create a folder hierarchy within the src/resources/schema and rename the .json schema with the name of the class that you want. E.. a/c/Input.json and a/b/Output.json . It will automatically read the path and create two different Java files under two different Packages with just one execution.
