### ISSUE TITLE
Accessors and Mutators Generated Method Names Do Not Capitalize the First Letter

### ISSUE THREAD

**Issue by WoodenCode00** [joelittlejohn/jsonschema2pojo#1028]
We are upgrading from jsonschema2pojo 0.5.1 to 1.01 version and noticed that the naming logic is inconsistent between the two versions in regard of the method names generated for getters/setters and withProperty().
Example: we have a property with the name where the first letter is in lowercase, the second is in uppercase - mStepsNumber

In the old version, accessor and mutator methods hd the names:
 - setMStepsNumber()
 - getMStepsNumber()
 - withMStepsNumber()

In the new version, the first letter is not capitalized anymore, so we have:
 - setmStepsNumber()
 - getmStepsNumber()
 - withmStepsNumber()

Is there a property we can configure in the maven plugin to have the old styled names? Or it is a bug and you plan to fix it in the near future?

Thank you.

**Comment by joelittlejohn** [comment]
This is not a bug, it was in fact 0.5.1 that named the methods incorrectly. See *8.8: Capitalization of inferred names* in the Java Bean spec.
