### ISSUE TITLE
How to Generate @JsonRawValue

### ISSUE THREAD

**Issue by WoodenCode00** [joelittlejohn/jsonschema2pojo#1030]
We are upgrading from jsonschema2pojo 0.5.1 to 1.01 version. We noticed that in the classes 
 generated with older version, there were @JsonRawValue annotation generated on the classes with type = object in schema definition. In newer version we can not find the way to generate the annotation.
We are trying by changing the type from object to string. Seems to be working. But it would feel safer if we can generate the JsonRawValue annotation to not break the current behavior along the way.

Thank you.

**Comment by WoodenCode00** [comment]
Unfortunately, just having type:"string" did not help. We need to find a way to generate @JsonRawValue annotation on the classes.

**Comment by joelittlejohn** [comment]
This project doesn't add JsonRawValue and never has. Maybe you were using a customized version of this library? There's no reference to JsonRawValue anywhere in our code base, either now or in 0.5.1.
