### ISSUE TITLE
Online utility is very old (http://www.jsonschema2pojo.org/)

### ISSUE THREAD

**Issue by urvanov-ru** [joelittlejohn/jsonschema2pojo#1033]
It looks like online utility http://www.jsonschema2pojo.org/ uses an old version of jsonschema2pojo. It uses 0.4.37 or older. Please upgrade it to actual version.

**Comment by urvanov-ru** [comment]
I mean it has "javaType" extension. But I cannot use modern "existingJavaType" with current online tool.

**Comment by joelittlejohn** [comment]
Yes, you're right. I will update when I get a chance.

**Comment by joelittlejohn** [comment]
Done 👍
