### ISSUE TITLE
Failure Using NIST NVD JSON Schema

### ISSUE THREAD

**Issue by benjholla** [joelittlejohn/jsonschema2pojo#1034]
This is probably user error, but I was trying to use the [JSON schema released by the NIST NVD](https://csrc.nist.gov/schema/nvd/feed/1.1/nvd_cve_feed_json_1.1.schema) with the [online tool](http://www.jsonschema2pojo.org/) and it could work with the URI included in the schema. Is this not supported?

**Comment by benjholla** [comment]
Error message is: `There's a problem: URI is not absolute`

**Comment by joelittlejohn** [comment]
In the online tool, we can't resolve this ref:
```
"$ref": "CVE_JSON_4.0_min_1.1.schema"
```
How could we?

**Comment by dewthefifth** [comment]
Like joelittlejohn mentioned, the schema you linked to includes references to other schemas which there is no way of locating when you paste the schema into the online tool.

You should download your referenced schema, as well as any schemas it references, and place them in a folder together then run the tool against the folder. For example https://csrc.nist.gov/schema/nvd/feed/1.1/cvss-v3.x.json and https://csrc.nist.gov/schema/nvd/feed/1.1/CVE_JSON_4.0_min_1.1.schema are both valid links for finding referenced schemas. Unfortunately I was unable to find a single link/zip on the NIST site that provided all the schemas together. You may have to do the scraping yourself (though you could likely write something that would do the scraping for you).

The documentation already includes a number of examples on how to compile a folder/group of schemas, and there is even a CLI  version if you have an aversion to building something like a maven project that compiles them for you.

**Comment by benjholla** [comment]
This all make sense. Thank you! So I guess I was right about it being user
error.
