### ISSUE TITLE
Make enum field as String in POJO yet generate the inner enum class

### ISSUE THREAD

**Issue by mdfaizanali786** [joelittlejohn/jsonschema2pojo#1037]
Currently, enums generate inner classes within the objects they are part of. The type of these enum fields in the POJOs containing them is the enum type generated. With this implementation if someone provides wrong enum value it fails in deserialization with a very generic exception. I  have a use-case where we don't want any deserialization failures because of bad enum values. Is it possible to have type of enum fields as string in POJOs yet generate the inner enum class? 

Can it be configurable ? If not, can someone please advise how to do it by overriding one of the classes like EnumRule, ObjectRule, PropertyRule .. ?

**Comment by ddcruver** [comment]
The EnumRule could be updated to be more forgiving with possibly a default or invalid value.
or
The ObjectRule could be updated to provide builder methods that accept strings for enum properties that catch the invalid exception method.

Either of these would have to be controlled by global configuration or would have to be added to the schema as another java (jsonschema2pojo) specific extension.

**Comment by joelittlejohn** [comment]
This isn't something we need to generate in the types, it's a feature of the deserialization library. Are you using Jackson?

Support for unrecognised enum values is a feature of Jackson. Check out `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL`. Alternatively you can write your own custom deserializer to do whatever you like.
