### ISSUE TITLE
Internals - Add logging functionality to RuleFactory

### ISSUE THREAD

**Issue by ddcruver** [joelittlejohn/jsonschema2pojo#1039]
While working on #1035 I would like to log out warnings but discovered there is no good way to log inside rules.

I propose us adding a RuleLogger interface that rules can use that will delegate the logging to the given frameworks logger.  This interface can be exposed to each rule through the RuleFactory.

Maven -> org.apache.maven.plugin.logging.Log
Ant -> org.apache.tools.ant.Project.log()
Gradle -> org.gradle.api.logging.Logger
CLI -> Slf4J (the universal logging facade) w/Slf4J Simple Impl

**Comment by joelittlejohn** [comment]
I like this change, it's a good one. Thanks for the PR! It's something that I've always wanted to get around to but never ended up doing so. I've reviewed the PR and added some comments.

I'm actually going to close this ticket because we can continue discussion about this on #1040.
