### ISSUE TITLE
formatTypeMapping error on array classes

### ISSUE THREAD

**Issue by kullanici0606** [joelittlejohn/jsonschema2pojo#1043]
Hi,

We have a schema that has some properties with `"format": "base64"`. Since this is a third-party supplied schema and there are tens of this definition, we cannot replace format attribute with `"media": { "binaryEncoding": "base64" }` attribute. Therefore I wanted to try formatTypeMapping feature of maven plugin however it failed for this mapping:
```
<formatTypeMapping>
	<base64>byte[]</base64>
</formatTypeMapping>
```

with following error:

`[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.0.1:generate (default) on project JsonTest: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.0.1:generate failed: could not load java type byte[] for base64 -> [Help 1]`

I checked the code and saw that it tries to load class from class loader, however it fails for array types since java class loader cannot load array classes. However when I checked, I saw that you already have commons-lang as a dependency, therefore following code

https://github.com/joelittlejohn/jsonschema2pojo/blob/63db1db09607c10362eac1f2956e1da8326f3ab6/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/FormatRule.java#L168

can be replaced with:
`Class<?> type = ClassUtils.getClass(typeName);`

or
`Class<?> type = ClassUtils.getClass(Thread.currentThread().getContextClassLoader(), typeName);`

(both of them work same) since ClassUtils handles array classes (Documentation states that and I also tried).
I wanted to send a pull request however development environment set up took a very long time.

Could you please replace the class loading line with the provided one so that format type mapping can work for array types too?

Thanks in advance.

**Comment by joelittlejohn** [comment]
Feel free to submit a pull request for this. I agree this would be a good change.

**Comment by kullanici0606** [comment]
@joelittlejohn I submitted a pull request, could you please review it?
