### ISSUE TITLE
Enhancement: Generate common schema before other schema

### ISSUE THREAD

**Issue by pleasework-dev** [joelittlejohn/jsonschema2pojo#1045]
Is it possible to generate common schema before generating other schema?

Example: i have the following json schemas, I would like to generate the common.json in its package path before the other modules. 
1. `common.common.json`  --> Generate first
2. `moduleA.moduleA.json` --> Reference to `common.json` files
3. `moduleB.moduleB.json` --> Reference to `common.json` files

Wanted: 
1. `common.common.java`
2. `moduleA.moduleA.java` --> Reference to package path `common.common.java`
3. `moduleB.moduleB.java` --> Reference to package path `common.common.java`

While generating from the schemas, it generate moduleA.json first and generate the common.json into its package path. Is it possible to have a flag to indicate which package path to generate first?

Result: 
1. `moduleA.moduleA.java`
2. `moduleA.common.java`
3. `moduleB.moduleB.java` --> Reference to package path `moduleA.common.java`

I'm using gradle plugin btw.

**Comment by joelittlejohn** [comment]
I think you can do this with multiple invocations of the plugin. There's no other way that I know of.
