### ISSUE TITLE
Custom or additional annotations in plug in

### ISSUE THREAD

**Issue by piesoftsol** [joelittlejohn/jsonschema2pojo#1047]
Hi, How to use custom annotations like

**@ApiModelProperty(position = 1, example = "DefaultValue")**
based on json schema given.

**Comment by joelittlejohn** [comment]
You can create your own custom annotator to do this. 

There's more info here:

https://github.com/joelittlejohn/jsonschema2pojo/issues/524

and here:

https://stackoverflow.com/questions/48404800/json-to-pojo-with-custom-annotations
