### ISSUE TITLE
Is it possible can add @JsonRootName in the POJO class by this maven plugin

### ISSUE THREAD

**Issue by Jyotityagi18** [joelittlejohn/jsonschema2pojo#1048]
I have requirement that I want to add Jackson annotation(@JSonRootName) in my POJO class which is generated by json schema by this maven(jsonSchema2pojo) plugin.
Please let me know if it is possible asap?

**Comment by joelittlejohn** [comment]
You'll need a custom annotator for this. If you Google for 'jsonschema2pojo custom annotator' you'll find some examples.

**Comment by Jyotityagi18** [comment]
Please let me know in details how add this annotation through json schema .what property should be given into json schema?
