### ISSUE TITLE
Is it possible can add @JsonRootName Jackson annotation in POJO class

### ISSUE THREAD

**Issue by Jyotityagi18** [joelittlejohn/jsonschema2pojo#1049]
I have requirement that I want to add jackson annotation(@JsonRootName(value="")) in my POJO class which is generated by Json schema through jsonschema2pojo maven plugin.Please let me know is it possible or if it is possible so what is the solution?

**Comment by joelittlejohn** [comment]
You just asked this same question a few minutes ago (?). See #1048.
