### ISSUE TITLE
@JsonRootName("") is coming instead of @JsonRootName(value="") using custom annotator

### ISSUE THREAD

**Issue by Jyotityagi18** [joelittlejohn/jsonschema2pojo#1051]
Please let me know how will i add value in @JsonRootName using custom annotator. I tried but @JsonRootName("") is coming instead of @JsonRootName (value=""). Both are same or if it ia different so how should I resolve because I am facing mapping problem

**Comment by joelittlejohn** [comment]
Try `.param` on the call to `annotate`:

https://stackoverflow.com/a/21638149/125825

**Comment by joelittlejohn** [comment]
Also, this isn't the right place for JCodeModel support. Try googling "JCodeModel" or ask on StackOverflow.
