### ISSUE TITLE
Does your library support jdk 11.

### ISSUE THREAD

**Issue by ShanthkumarS079** [joelittlejohn/jsonschema2pojo#1052]
Hi,
I have updated the JDK version to 11 from JDK 8, Gradle to 6.0 and apache commons-lang to 3.9. The Gradle build is failing with an exception below. I could see that the commons-io(2.6) package in my project library.

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
        at org.jsonschema2pojo.Jsonschema2Pojo.getNodeName(Jsonschema2Pojo.java:175)
        at org.jsonschema2pojo.Jsonschema2Pojo.getNodeName(Jsonschema2Pojo.java:170)
        at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:134)
        at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:75)
        at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
        at org.jsonschema2pojo.gradle.GenerateJsonSchemaJavaTask.generate(GenerateJsonSchemaJavaTask.groovy:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)

**Comment by dewthefifth** [comment]
Do you mean you've updated your projects JDK from 8 to 11?

I just upgraded my own application to JDK11 and ran the compile and it worked, so I'm not sure what's going on with your specific project. Are you able to provide a github repo with a sample of what isn't working?

**Comment by ShanthkumarS079** [comment]
Yes, Updated projects JDK from 8 to 11.
Can you please share your build.gradle file.?
Copied below build content of my project
Please let me know if I am missing anything
--------------------

apply plugin: 'jsonschema2pojo'

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }

    dependencies {
       // classpath 'org.jsonschema2pojo:jsonschema2pojo-core:1.0.1'
       classpath 'org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:1.0.1'
       // classpath 'org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:latest.integration'

    }
}

dependencies {
    compile 'org.apache.commons:commons-lang3:3.9'
    compile 'javax.validation:validation-api:2.0.1.Final'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.9.6'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.9.0'
}

// Each configuration is set to the default value
jsonSchema2Pojo {
    // Whether to generate builder-style methods of the form withXxx(value) (that return this),
    // alongside the standard, void-return setters.
    generateBuilders = false

    // Whether to use primitives (long, double, boolean) instead of wrapper types where possible
    // when generating bean properties (has the side-effect of making those properties non-null).
    usePrimitives = false

    // Package name used for generated Java classes (for types where a fully qualified name has not
    // been supplied in the schema using the 'javaType' property).
    targetPackage = 'notifs.ops.generated.configuration.pojos'

    // The characters that should be considered as word delimiters when creating Java Bean property
    // names from JSON property names. If blank or not set, JSON properties will be considered to
    // contain a single word when creating Java Bean property names.
    propertyWordDelimiters = ['-', '_'] as char[]

    // Whether to use the java type long (or Long) instead of int (or Integer) when representing the
    // JSON Schema type 'integer'.
    useLongIntegers = false

    // Whether to use the java type BigInteger when representing the JSON Schema type 'integer'. Note
    // that this configuration overrides useLongIntegers
    useBigIntegers = false

    // Whether to use the java type double (or Double) instead of float (or Float) when representing
    // the JSON Schema type 'number'.
    useDoubleNumbers = false

    // Whether to use the java type BigDecimal when representing the JSON Schema type 'number'. Note
    // that this configuration overrides useDoubleNumbers
    useBigDecimals = true

    // Whether to include hashCode and equals methods in generated Java types.
    includeHashcodeAndEquals = true

    // Whether to include a toString method in generated Java types.
    includeToString = true

    // The style of annotations to use in the generated Java types. Supported values:
    //  - jackson (alias of jackson2)
    //  - jackson2 (apply annotations from the Jackson 2.x library)
    //  - jackson1 (apply annotations from the Jackson 1.x library)
    //  - gson (apply annotations from the Gson library)
    //  - moshi1 (apply annotations from the Moshi 1.x library)
    //  - none (apply no annotations at all)
    annotationStyle = 'jackson2'

    // A fully qualified class name, referring to a custom annotator class that implements
    // org.jsonschema2pojo.Annotator and will be used in addition to the one chosen
    // by annotationStyle. If you want to use the custom annotator alone, set annotationStyle to none.
    customAnnotator = 'org.jsonschema2pojo.NoopAnnotator'

    // Whether to include JSR-303/349 annotations (for schema rules like minimum, maximum, etc) in
    // generated Java types. Schema rules and the annotation they produce:
    //  - maximum = @DecimalMax
    //  - minimum = @DecimalMin
    //  - minItems,maxItems = @Size
    //  - minLength,maxLength = @Size
    //  - pattern = @Pattern
    //  - required = @NotNull
    // Any Java fields which are an object or array of objects will be annotated with @Valid to
    // support validation of an entire document tree.
    includeJsr303Annotations = true

    // The type of input documents that will be read. Supported values:
    //  - jsonschema (schema documents, containing formal rules that describe the structure of json data)
    //  - json (documents that represent an example of the kind of json data that the generated Java types
    //          will be mapped to)
    sourceType = 'jsonschema'

    // Whether to empty the target directory before generation occurs, to clear out all source files
    // that have been generated previously. <strong>Be warned</strong>, when activated this option
    // will cause jsonschema2pojo to <strong>indiscriminately delete the entire contents of the target
    // directory (all files and folders)</strong> before it begins generating sources.
    removeOldOutput = true

    // The character encoding that should be used when writing the generated Java source files
    outputEncoding = 'UTF-8'

    // Whether to use {@link org.joda.time.DateTime} instead of {@link java.util.Date} when adding
    // date type fields to generated Java types.
    useJodaDates = false

    // Whether to use commons-lang 3.x imports instead of commons-lang 2.x imports when adding equals,
    // hashCode and toString methods.
    useCommonsLang3 = true

    // Whether to initialize Set and List fields as empty collections, or leave them as null.
    initializeCollections = false

    // Whether to add a prefix to generated classes.
    classNamePrefix = ""

    // Whether to add a suffix to generated classes.
    classNameSuffix = ""

    // An array of strings that should be considered as file extensions and therefore not included in class names.
    fileExtensions = [] as String[]

    // Whether to generate constructors or not.
    includeConstructors = false

    // **EXPERIMENTAL** Whether to make the generated types Parcelable for Android
    parcelable = false

    // Whether to make the generated types Serializable
    serializable = false
}

**Comment by dewthefifth** [comment]
I misunderstood the original message. My test project was in maven. I'll try to reproduce with gradle.

**Comment by joelittlejohn** [comment]
No idea what's up here but I don't believe it has anything to do with JDK 11. If anyone has any more info, or if more people are experiencing this, I'm happy to reopen this.
