### ISSUE TITLE
Is JsonSchema2Pojo support xml format also?If it's possible, what will be the solution?

### ISSUE THREAD

**Issue by Jyotityagi18** [joelittlejohn/jsonschema2pojo#1056]
I want my request and response in xml format also .It's supporting json but I also want in xml format. Sorry I am posting my question again here but it's urgent.Please reply asap.

**Comment by joelittlejohn** [comment]
No, not supported. Please search the issues for 'xml' if you'd like more detail. The best option is Jackson XML output.
