### ISSUE TITLE
json schema silently fails

### ISSUE THREAD

**Issue by sousarka** [joelittlejohn/jsonschema2pojo#1058]
The following schema fails silently without generating any sources with maven plugin version 1.0.1. I've tried another json file and it works once I change the sourceType.

Here's the configuration from pom:
`<sourceDirectory>${project.basedir}\json\</sourceDirectory>
					<includeHashcodeAndEquals>false</includeHashcodeAndEquals>
                    <includeToString>false</includeToString>
					<removeOldOutput>true</removeOldOutput>
					<annotationStyle>none</annotationStyle>
					<sourceType>jsonschema</sourceType>`

Json schema:

`{
	"definitions": {
		"GetCustomerQueryResponse": {
			"type": "object",
			"properties": {
				"returnObject": {
					"$ref": "#/definitions/Customer"
				},
				"errors": {
					"uniqueItems": false,
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			}
		},
		"Customer": {
			"type": "object",
			"properties": {
				"customerName": {
					"type": "string"
				},
				"address1": {
					"type": "string"
				},
				"address2": {
					"type": "string"
				},
				"address3": {
					"type": "string"
				}
			}
		}
	}
}`

**Comment by joelittlejohn** [comment]
Hi. See #990 and #987.
