### ISSUE TITLE
Json schema with property gdsBaseData creates GdsBaseDatum.java

### ISSUE THREAD

**Issue by SvenBlendien** [joelittlejohn/jsonschema2pojo#1060]
Hi,

jsonschema2pojo seems to work fine, but there seems to be a problem with one part of a name.
I expect, that a property with the name gdsBaseData will be created as GdsBaseData.java instead it was created as GdsBaseDatum.java

What's going on? 

Here is a simplification of my schema, that runs into the same problem.

```javascript

{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"$id": "http://json-schema.org/draft-04/schema#",
	"title": "Core schema meta-schema",
	"properties": {
		"ItemBaseData": {
			"$ref": "#/definitions/ItemBaseData"
		}
	},
	"required": [
		"ItemBaseData"
	],
	"additionalProperties": false,
	"definitions": {
     		"ItemBaseData": {
				"type": "object",
				"properties": {
					"gdsBaseData": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"gln": {
									"type": "string"	
                                }
							}
						},
						"default": [
						]
					}
            	}, 
            	"required": [
				],
				"additionalProperties": false     
            }
    } 
}
```

A part of the generated code.

```java
public class ItemBaseData {

@JsonProperty("gdsBaseData")
public List<GdsBaseDatum> gdsBaseData = null;
```
You can test it on http://www.jsonschema2pojo.org/ copy the json schema. Select "JSON Schema" as "Source type" and click on preview. 

Please let me know, why this occurs and if there are other special words. It's a greate idea and an interesting way, so please provide a fix. I think nobody like this kind of surprise while coding.

Best regards,

Sven

**Comment by joelittlejohn** [comment]
When you have a property which is an array, this library singularizes the name to describe the array item. e.g. if you have an array called `records` then the item class will be called `Record`. If your array is called `data`, each item is a `Datum`.
