### ISSUE TITLE
One of my POJOs is not being generated.

### ISSUE THREAD

**Issue by GeorgeDavis** [joelittlejohn/jsonschema2pojo#1065]
Hi Joe,

I'm working on developing a microservice in IntelliJ. I am using your jsonschema2pojo generator and I am running into an odd issue. I have several different request/response json files in my resources/schema folder as directed by your instructions(getUser, deleteUser, etc.). The issue I am having is that all but one of my POJOs are being generated. I have even tried adding a test.json file to the schema folder to see if it would generate, but it is not. It seems like all new files that are added to the schema folder are being ignored, just my best guess. I have not been able to come across a previous issue like this in your issues section, stack, or any other website.

My getUserResponse.json file is the file that is not being generated. I have included the code snippet at the bottom.

My pom.xml code below:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.2.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.mongo</groupId>
	<artifactId>starter</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>starter</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			 <groupId>org.projectlombok</groupId>
 			<artifactId>lombok</artifactId>
 			<optional>true</optional>
 		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.10.1</version>
        </dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.jsonschema2pojo</groupId>
				<artifactId>jsonschema2pojo-maven-plugin</artifactId>
				<version>1.0.1</version>
    				<configuration>
        				<sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
        				<targetPackage>com.mongo.model</targetPackage>
						<useCommonsLang3>true</useCommonsLang3>
    				</configuration>
    				<executions>
        				<execution>
            				<goals>
                				<goal>generate</goal>
            				</goals>
        				</execution>
    				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
                		<source>1.6</source>
                		<target>1.6</target>
            		</configuration>
			</plugin>
		</plugins>
	</build>

</project>`

My getUserResponse.json code below:
`{
		"$schema": "http://json-schema.org/draft-07/schema#",
			"title": "Get List of Users for game name",
			"type": "array",
			"items": {
		"type": "object",
				"$ref": "userResponse.json"
	},
		"required" : [ "firstName", "lastName", "city", "state" ]
}`

The file is referencing another file, userResponse.json. That json file which is also in the schema folder is being generated correctly.

I feel like the answer to this problem is staring directly at me, any help you could provide would be great! Please let me know if I need to include any other information in the submission.

Thanks,
George

**Comment by joelittlejohn** [comment]
Hi George. That type is just an array, so in Java it's just a List. We don't generate a new type for an array.

**Comment by GeorgeDavis** [comment]
Thanks, Joe! That was it.
