### ISSUE TITLE
Outdated documentation: existingJavaType is not described

### ISSUE THREAD

**Issue by Mingun** [joelittlejohn/jsonschema2pojo#1066]
#828 was implemented more that year ago, but documentation at http://www.jsonschema2pojo.org/ still describes only `javaType`

**Comment by joelittlejohn** [comment]
The documentation at http://www.jsonschema2pojo.org/ describes the tool at http://www.jsonschema2pojo.org/, which uses an older version of this plugin. When the tool itself supports existingJavaType, we'll update the docs there too.

For the latest docs, see https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference
