### ISSUE TITLE
patternProperties not generate anything

### ISSUE THREAD

**Issue by Mingun** [joelittlejohn/jsonschema2pojo#1067]
I try to generate classes for https://github.com/kaitai-io/ksy_schema/blob/a46122664ed9bb460d805ea368ce52ab93348fdb/ksy_schema.json. Several types in that schema intended to hold of map of restricted user-defined string to some type:
* `TypesSpec`
* `InstancesSpec`
* `EnumsSpec`

So, their contains following definitions:
```json
    "TypesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^([a-z0-9_])+$": {
          "$ref": "#/definitions/TypeSpec"
        }
      }
    },
```
But generated file has no fields at all. I expect, that it will contain `Map<String, TypeSpec>`

**Comment by joelittlejohn** [comment]
Hi. There's no support for patternProperties in this library. See #182.

**Comment by Mingun** [comment]
Are you sure, that this the same problem, as in #182? This one about that existing `patternProperties` must generate field to store these properties, even if `additionalProperties` is `false`. Because `additionalProperties` applied only to properties, that do not listed in the `properties` or `patternProperties`: https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.3

> The value of "additionalProperties" MUST be a valid JSON Schema. 
>
> The behavior of this keyword depends on the presence and annotation results of "properties" and "patternProperties" within the same schema object. Validation with "additionalProperties" applies only to the child values of instance names that do not appear in the annotation results of either "properties" or "patternProperties". 

#182 is about that generated for `additionalProperties` field do not validated against `patternProperties`.

I think, there is related code:
https://github.com/joelittlejohn/jsonschema2pojo/blob/0b5b0e1a9557dc46972618e584ea9a8351898a3a/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/AdditionalPropertiesRule.java#L91-L94
It must check existent of `patternProperties` and do their work, if key exist

**Comment by joelittlejohn** [comment]
> Are you sure, that this the same problem, as in #182?

Yes, #182 and this issue #1067 are both a request to support patternProperties. We don't need two issues to track this request. We don't support patternProperties because of the many different ways in which it cannot be supported correctly in Java.
