### ISSUE TITLE
existingJavaType not used if type of object is { "$ref" }

### ISSUE THREAD

**Issue by Mingun** [joelittlejohn/jsonschema2pojo#1068]
I try to generate classes for https://github.com/kaitai-io/ksy_schema/blob/a46122664ed9bb460d805ea368ce52ab93348fdb/ksy_schema.json.

After coming with #1067 I try to workaround that bug and replace all `TypesSpec` usages in that file to Map<String, TypeSpec>`.

So, I use `existingJavaType` in following way:
```json
    "types": {
      "existingJavaType" : "java.util.Map<String, TypeSpec>",
      "description": "maps of strings to user-defined types\n\ndeclares types for substructures that can be referenced in the attributes of seq or instances element\n\nwould be directly translated into classes",
      "$ref": "#/definitions/TypesSpec"
    },
```
But in generated file `existingJavaType` is ignored and field still have type `TypesSpec`

**Comment by joelittlejohn** [comment]
When `$ref` is used, other fields are ignored. This was dictated by the JSON schema spec.

**Comment by Mingun** [comment]
But `existingJavaType` is not part of JSON schema spec. Can library handle it there as usual?

**Comment by jmax01** [comment]
I agree this should be supported:
```json

	"geoLocation": {
				   "existingJavaType": "org.geojson.jackson2.Point",
					"$ref": "https://geojson.org/schema/Point.json"
				}
```
