### ISSUE TITLE
Java class is not generated, if type not used in the schema

### ISSUE THREAD

**Issue by Mingun** [joelittlejohn/jsonschema2pojo#1069]
After I'm facing with #1067 and non-working workaround #1068 , I try to make workaround while I make workaround
![https://meme-arsenal.com/create/meme/1809535](https://www.meme-arsenal.com/memes/e8040b010ecf7f55716d7d0910ca2690.jpg)

So, I still deal with https://github.com/kaitai-io/ksy_schema/blob/a46122664ed9bb460d805ea368ce52ab93348fdb/ksy_schema.json. I add `existingJavaType` key and replace `"type": { "$ref": ... }` with `"type": "object"`. But after that type, that referenced by `$ref`, not references anywhere and class for it (`TypeSpec`) is not generated:
```json
{
  ...
  "properties": {
    ...
    "types": {
      "existingJavaType" : "java.util.Map<String, TypeSpec>",
      "description": "maps of strings to user-defined types\n\ndeclares types for substructures that can be referenced in the attributes of seq or instances element\n\nwould be directly translated into classes",
      "type": "object"
    },
    ...
```

**Comment by joelittlejohn** [comment]
Instead of using `"existingJavaType" : "java.util.Map<String, TypeSpec>"` can you instead just leave the ref to TypeSpec and change TypeSpec to allow additional properties?

**Comment by Mingun** [comment]
I would like not to do this so as not to change the scheme. But because in any case workaround for bugs is needed, I am able to do it. As part of this issue, the answer to the question is needed of whether this behavior is expected? I think not (or at least there must be a setting in the generator), because external schemas can refer to types in this schema and it is totally legal just have schema as library of types, none of which are used in the schema itself

**Comment by joelittlejohn** [comment]
Yes, this is expected behaviour. This plugin does not search for schemas that are not referenced by anything. If you use existingJavaType, you are expected to provide the classes to satisfy this.
