### ISSUE TITLE
1.0.2 Release

### ISSUE THREAD

**Issue by ddcruver** [joelittlejohn/jsonschema2pojo#1072]
Can a 1.0.2 release be made?

I would like to migrate my project to a release version of this library that includes my contributions.

It additionally looks like all your issues listed here https://github.com/joelittlejohn/jsonschema2pojo/milestone/76 are complete as well as many other additions to the library.

**Comment by ddcruver** [comment]
The 1.0.1 release was done way back in Apr 13, 2019.

**Comment by joelittlejohn** [comment]
Let's do it :+1:

**Comment by joelittlejohn** [comment]
Done. I'll update docs etc when maven central has indexed the new artifacts.
