### ISSUE TITLE
Breaking changes in gradle plugin from 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by Kichix** [joelittlejohn/jsonschema2pojo#1073]
Hi,
we were using the latest version of the gradle plugin from maven central and got the following error when generating our pojos:

 No signature of method: static org.jsonschema2pojo.Jsonschema2Pojo.generate() is applicable for argument types: (org.jsonschema2pojo.gradle.JsonSchemaExtension_Decorated) 

Going back to 1.0.1 fixed the issue.

Best Regards
Michael

**Comment by joelittlejohn** [comment]
Hmm, it's true that the signature of `org.jsonschema2pojo.Jsonschema2Pojo.generate()` has changed to include a new 'logger' object, but the gradle generate tasks were changed as well.

Is it possible that you have something cached here from the old version?

**Comment by joelittlejohn** [comment]
I'm going to close this since we don't have enough information to go on and I suspect this may be a problem with some cached classes in your build environment. If more people experience this then we can re-open.
