### ISSUE TITLE
External mapping configuration.

### ISSUE THREAD

**Issue by rloeffel** [joelittlejohn/jsonschema2pojo#1076]
I have received a json-schema from a third party company. Now I would like to configure the code generation process without modifying the original schema file. For example I need to configure a super class, but this is only possible by adding the "extends" keyword in the original file...

Is there another way to do this without modifying the original schema file? Can I add an external configuration file somehow?

**Comment by joelittlejohn** [comment]
No, there's no way to provide an external file that adds things like classes to extend. You'll have to implement this with a custom rule factory or pre-process the files and merge the schema with some additions that you define before using jsonschema2pojo.
