### ISSUE TITLE
Where "extends" property is defined in JSON schema?

### ISSUE THREAD

**Issue by Mingun** [joelittlejohn/jsonschema2pojo#1084]
**Reference** section on http://www.jsonschema2pojo.org/ describes, how `extends` keyword is translated to Java. There is also a mention of some part of the JSON schema specification(?):

> Note: the extends rule in JSON schema accepts a schema or an array of schemas - jsonschema2pojo only supports the single schema variant.

But, according to the https://github.com/json-schema-org/json-schema-spec/issues/348#issuecomment-322940347, JSON schema doesn't support inheritance and I can not find any mention of `extends` keyword on the [official site](https://json-schema.org)

Where `extends` keyword is defined in JSON schema and what values it can have?

**Comment by joelittlejohn** [comment]
`extends` is a legacy keyword that existing in JSON Schema draft00/draft01/draft02/draft03 but was removed in draft04.

We can't easily support 'allOf' with Java's type system so a lot of people still prefer to use `extends`.
