### ISSUE TITLE
Always include default constructor if isIncludeConstructors() is set

### ISSUE THREAD

**Issue by calum-maclean-ul** [joelittlejohn/jsonschema2pojo#1099]
If I set `isIncludeConstructors()` with all other constructor-related properties set to `false`, the library will not generate any constructors. In this case, I expected that a default constructor (i.e. no args) _would_ be generated. So this request is to include a default constructor in this case.
The logic for this is in `ConstructorRule.handleMultiChoiceConstructorConfiguration()`, where it seems that the default constructor is only generated when there are also other constructors.
I know that, in Java, if there are no constructors, then the compiler automatically includes a default constructor. Sometimes it can be useful for stylistic reasons to include the default constructor explicitly, for clarity. In this particular case, I wanted to add some code to the default constructor, but was surprised when there was no default constructor.
Workaround: I can add a default constructor manually if it is not already present, and then add my code to it.

**Comment by joelittlejohn** [comment]
Thanks for raising this, but I don't think we should generate all this code that's not needed. You can easily define the constructor when you need to customise it.

**Comment by calum-maclean-ul** [comment]
Thanks for the quick feedback. Fair enough, if that's what you'd prefer.
However, I'd suggest that it would be at least worth updating the documentation for `GenerationConfig.isIncludeConstructors()` to indicate that this is the case.
It was a surprise to me that I enabled "include constructors" yet no constructors were generated!
It seems that this setting is actually a global setting which enables/disables generation of the other constructors which are configured by the other methods.
