### ISSUE TITLE
Units of Measurement Support (JSR-385)

### ISSUE THREAD

**Issue by ddcruver** [joelittlejohn/jsonschema2pojo#1108]
Do you think adding native support to the Java Units of Measure API is out of scope for this project?

You can use it right now by using existingJavaType but I see some enhancements that could be made if a native implementation was made in jsonschema2pojo.

***Possible Features***

**Defining the quantity type without explicit long declaration**

Instead of:
`"existingJavaType": "javax.measure.Quantity<javax.measure.quantity.Speed>"`
This can be done: 
"javaQuantity": "Speed" 

Another example with a custom quantity type (defined already outside of jsonschema2pojo):
`"existingJavaType": "javax.measure.Quantity<com.example.git.operation.PullRequest>"`
This can be done:
"javaQuantity": "com.example.git.operation.PullRequest" 

**Helper method on builders, with default unit**
So instead of just this method:
`builder.withMaxSpeed(Quantity<Speed>)` where the user must do build a quantity like this: `Quantities.getQuantity(Number, Unit)` a helper method such as `builder.withMaxSpeed(Number)` where it would call `Quantities.getQuantity(Number, [DEFAULT_UNIT])`

**Better Equals Methods**
Instead call ``==`` for Quantities, it should call `isEquivalentTo()`

**Comment by joelittlejohn** [comment]
I don't think this is something we want in the core library, it's going to far into native support for many possible Java APIs. existingJavaType is the right way to do this if it's needed.
