### ISSUE TITLE
Setter method created with parameter of type Object for a complex property.

### ISSUE THREAD

**Issue by skamalapur** [joelittlejohn/jsonschema2pojo#1110]
I was trying to use the library to convert a JSON schema to java objects.
One of the classes generated  has the methods like 
In the JSON Schema used for creating these classes, IndividualProperties is much complex structure.  
Can someone help?

public class Data {
    @JsonProperty("IndividualTypeProperties")
    private Object individualTypeProperties;

public class Data {

    @JsonProperty("GroupTypeProperties")
    private GroupTypeProperties groupTypeProperties;
    @JsonProperty("IndividualTypeProperties")
    private Object individualTypeProperties;
    @JsonProperty("ExtensionProperties")
    private ExtensionProperties extensionProperties;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("IndividualTypeProperties")
    public Object getIndividualTypeProperties() {
        return individualTypeProperties;
    }
    @JsonProperty("IndividualTypeProperties")
    public void setIndividualTypeProperties(Object individualTypeProperties) {
        this.individualTypeProperties = individualTypeProperties;
    }
    public Data withIndividualTypeProperties(Object individualTypeProperties) {}

[Test.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/4341164/Test.txt)
 
I have attached schema Test.txt for reference. I have masked the domain specific content. Please advise.

**Comment by joelittlejohn** [comment]
This schema uses 'allOf', which is not supported by this library I'm afraid.

**Comment by skamalapur** [comment]
hi

Is there any plan to support it in near future?

Thanks.
Shrini
