### ISSUE TITLE
Can we retain the the field name as is when target Json is generated  

### ISSUE THREAD

**Issue by skamalapur** [joelittlejohn/jsonschema2pojo#1111]
I am using the JsonSchema2Pojo to create java files and then populate the java classs with values coming from different sources. Once i have populated the java classes and i generate the json, i found that the the case for fields is getting changed

for ex - 
ResourceID field gets translated to resourceID - (R changed to r)
IndividualTypeProperties:  becomes individualTypeProperties. (I changed to i)

Is there a setting which can help me with retainig the originalfield names and the case.

**Comment by skamalapur** [comment]
Any updates please?

**Comment by dewthefifth** [comment]
I'm having a little bit of difficulty understanding the question I think. Let me see if I understand correctly.

You define a schema as follows:
```
{
  "$id": "https://example.com/issues/Person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "object",
  "javaType": "com.example.jsonschema2pojo.Person",
  "properties": {
    "ResourceID": {
      "type": "String"
    },
    "IndividualTypeProperties": {
      "type": "number"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "ResourceID"
  ],
  "definitions": {
  }
}
```

But the JSON generated for the class this produces looks like follows:
```
{
  "resourceID" : "abc",
  "individualTypeProperties" : 10.0
}
```

**Comment by joelittlejohn** [comment]
The goal of this project is to allow accurate serialisation and deserialisation using a library like Jackson or Gson. It is not a goal of this project to give micro control over exactly how we generate Java source code. We use Java conventions.
