### ISSUE TITLE
How do I use gradle plugins block instead of buildScript?

### ISSUE THREAD

**Issue by AceHack** [joelittlejohn/jsonschema2pojo#1115]
Thanks.

**Comment by joelittlejohn** [comment]
I think this is answered on #896

**Comment by AceHack** [comment]
@joelittlejohn it is not answered.  I'm trying to use the hotline dsl and none of the work around's are working.  It would be great if this was published to the grade plugin repo using their standards.  Thanks.

**Comment by joelittlejohn** [comment]
Did you try the solution that was linked to:

https://stackoverflow.com/questions/51766423/cant-use-jsonschema2pojo-gradle-plugin-in-plugins-block/51769604#51769604

?

**Comment by AceHack** [comment]
Yes it is not working for grade kotlin dsl and I would not call that a solution, it's a very ugly workaround.  Please create a proper grade plugin.

**Comment by eirnym** [comment]
@AceHack go ahead and use my one https://plugins.gradle.org/plugin/com.github.eirnym.js2p
