### ISSUE TITLE
https certificate on www.jsonschema2pojo.org is invalid

### ISSUE THREAD

**Issue by mjg123** [joelittlejohn/jsonschema2pojo#1116]
```
Web sites prove their identity via certificates. Firefox does not trust this site
 because it uses a certificate that is not valid for www.jsonschema2pojo.org.
 The certificate is only valid for the following names: *.herokuapp.com, 
herokuapp.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by joelittlejohn** [comment]
Hey man. I actually had no idea there was anything listening on port 443. I'm sure we can hook heroku up to get let's encrypt certs (hopefully for free!).

**Comment by mjg123** [comment]
Cool beans! I hope it's free too. LetsEncrypt is great but I've never used it on heroku.

**Comment by joelittlejohn** [comment]
Not free, but now it's resolved https://www.jsonschema2pojo.org 🎉
