### ISSUE TITLE
What is the JSON Schema draft version supported?

### ISSUE THREAD

**Issue by renannprado** [joelittlejohn/jsonschema2pojo#1117]
So first of all, really cool work!

I would like to know what is the JSON Schema draft version supported by this library.
Of course I can just try it out, which I will probably do very soon. But would be nice if I can just by looking at the readme, for example, find out what is the version supported.

Could someone just let me know what is the version supported by this lib?
Otherwise I'll have to dig into the source code most probably.

Thanks!

**Comment by dewthefifth** [comment]
All of my schemas list themselves as draft 7 schemas, probably because I started with the examples from this plugin. 

I don't really follow the schema draft versions, and I'm not particularly aware of the specifics. It's possible that parts of draft 7 are not supported.

**Comment by joelittlejohn** [comment]
Closing, see #1339
