### ISSUE TITLE
additionalProperties: true does not work with Gson annotator

### ISSUE THREAD

**Issue by mverleg** [joelittlejohn/jsonschema2pojo#1130]
I have a definition in my json-schema (draft 7):

    "database_specific": {
      "type": "object",
      "description": "",
      "propertyNames": {
        "pattern": "^[A-Za-z][A-Za-z0-9_]*[A-Za-z0-9]?$"
      },
      "additionalProperties": true
    }

I'm invoking jsonschema2pojo 1.0.2 from Java and have isIncludeAdditionalProperties set to true.

If I use Gson annotator (and turning off constructors, toString and equals for brevity), I get:

    public class DatabaseSpecific {
    }

Whereas with the Jackson2 annotator I get:

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonPropertyOrder({})
    public class DatabaseSpecific {
        @JsonIgnore
        private Map<String, Object> additionalProperties = new HashMap<String, Object>();
    
        @JsonAnyGetter
        public Map<String, Object> getAdditionalProperties() {
            return this.additionalProperties;
        }
    
        @JsonAnySetter
        public void setAdditionalProperty(String name, Object value) {
            this.additionalProperties.put(name, value);
        }
    }

Only the second one seems correct to me.

I've reproduced this for another definition that doesn't have `propertyNames`, so it's not caused by `propertyNames`. It also happens on http://www.jsonschema2pojo.org/

Note: for my personal case I am just switching to Jackson2, but I though I'd report this in case it affects others.

**Comment by joelittlejohn** [comment]
Hi. Check out #1024 and #928
