### ISSUE TITLE
Having Camel for the class names but not for its object names when using wordDelimeter property

### ISSUE THREAD

**Issue by tanmai-h** [joelittlejohn/jsonschema2pojo#1132]
consider this json file. I want the underscore to be retained for the names of variable. But I want their class to be named using camel case. For this json file I set the Word Limiter to be empty.
```json
{
   "variable_name": {
          "key1": 1,
          "key2": 2
   },
  "another_variable": "value"
}
```

What was generated was this.  In file Example.java
```java
public class Example {

public Variable_name variable_name;
public String another_variable;
}
```
In file Variable_name.java
```java
public class Variable_name {

public Integer key1;
public Integer key2;

}
```

The "variable_name" key has been retained correctly when declaring the instance of the class. 
But the class name has become Variable_name. Whereas I want it as VariableName. (without the underscore).

**I know that passing the wordDelimeter="_" will make the class name in camel case, but that would make the variable as variableName.** 

**What I want is the class to be called VariableName AND it's instance to be kept as variable_name**

**Comment by joelittlejohn** [comment]
Hi. I appreciate what you're trying to do here, but this isn't the kind of thing we support. We can't support everyone's personal preference for how they want code to be generated - it would never end.

You do have some good options though. You can fork and modify this project, or create a custom RuleFactory and copy/modify whatever rule you need to edit to achieve what you need.
