### ISSUE TITLE
same - blank preview

### ISSUE THREAD

**Issue by testsmsprev** [joelittlejohn/jsonschema2pojo#1134]
https://github.com/joelittlejohn/jsonschema2pojo/issues/169

**Comment by testsmsprev** [comment]
Not found is returned by the url

**Comment by testsmsprev** [comment]
**http://www.jsonschema2pojo.org/generator/preview returns nothing** (per the response tab in chrome) no errors

and "not found" is when I tried to access without a post.

**Comment by testsmsprev** [comment]
This is request:

```
Request URL: http://www.jsonschema2pojo.org/generator/preview
Request Method: POST
Status Code: 200 OK
Content-Length: 698
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: www.jsonschema2pojo.org
Origin: http://www.jsonschema2pojo.org
Referer: http://www.jsonschema2pojo.org/
X-Requested-With: XMLHttpRequest
schema: {
  "err-code": "0",
  "message-timestamp": "2018-10-25 12:10:29",
  "messageId": "0B00000127FDBC63",
  "msisdn": "447547232824",
  "network-code": "23410",
  "price": "0.03330000",
  "scts": "1810251310",
  "status": "delivered",
  "to": "Nexmo CLI"
}
targetpackage: com.example
classname: Example
targetlanguage: java
sourcetype: yamlschema
annotationstyle: jackson2
usedoublenumbers: true
includeaccessors: true
includeadditionalproperties: true
propertyworddelimiters: - _
```

This is response:

(nothing to preview)

**Comment by joelittlejohn** [comment]
My guess is that you have nothing to generate in the schema you have entered.

**Comment by testsmsprev** [comment]
ah ok

**Comment by testsmsprev** [comment]
you don't handle the "rootless" flavor of some json?

**Comment by testsmsprev** [comment]
yep, if I paste what I want inside a json which has a first element, it works, if I paste it as is, it doesn't
is this some new trendy ideologically pure form of json I am not aware of?

have i been shunned for using lesser json?

**Comment by testsmsprev** [comment]
and is the lack of error a commentary on my ignorance of this fact? lol

**Comment by joelittlejohn** [comment]
Can you paste an example here? I'm not sure I understand what you mean.

**Comment by testsmsprev** [comment]
```
{
  "err-code": "0",
  "message-timestamp": "2018-10-25 12:10:29",
  "messageId": "0B00000127FDBC63",
  "msisdn": "447547232824",
  "network-code": "23410",
  "price": "0.03330000",
  "scts": "1810251310",
  "status": "delivered",
  "to": "Nexmo CLI"
}
```

**Comment by joelittlejohn** [comment]
Did you select *Source Type: JSON* ?

When I paste in this example, it works.

**Comment by testsmsprev** [comment]
OK I had to check "JSON" as the type......

.... ¯\_(ツ)_/¯

**Comment by testsmsprev** [comment]
(╯°□°)╯︵ ┻━┻

... but but... it says json in the url ..

hahahahha thanks, I'm an idiot, well, I mean that's a given but still... I mean... json... still. thanks.

**Comment by testsmsprev** [comment]
an error or a "well this sucks let's try json" would be nice.... because I am puzzled why json isn't default - egal, thanks

**Comment by testsmsprev** [comment]
How many people post an error that they get blank output? :p

**Comment by joelittlejohn** [comment]
The issue here is that your example above is also a valid schema (because schemas allow any additional properties). It's just a schema that doesn't apply any constraints and doesn't lead to any types being generated. It's the default for historical reasons really, jsonschema2pojo = json schema in, pojo out.

**Comment by joelittlejohn** [comment]
You're right though, it's a common problem. I'll add some kind of message.

**Comment by joelittlejohn** [comment]
The good news for you is that the site will remember your selection, so as far as you're concerned, JSON is now the default.

**Comment by testsmsprev** [comment]
Cool, and thanks for a neat tool, saves a lot of time testing out small pieces of code! Cheers
