### ISSUE TITLE
Add the possibility of forcing the generation of unreferenced parts declared in the #definitions

### ISSUE THREAD

**Issue by NPE78** [joelittlejohn/jsonschema2pojo#1135]
As seen here, we might want to force the generation of unreferenced parts declared in the #definitions:
https://stackoverflow.com/questions/60478946/maven-plugin-jsonschema2pojo-maven-plugin-not-generating-pojos-for-all-the-defin/62168912#62168912

As a workaround, I created a customRuleFactory but it might be useful to have a parameter (in maven-plugin for example) to force the generation of those unreferenced parts.

**Comment by rfelgent** [comment]
where can i vote for this feature ?

**Comment by joelittlejohn** [comment]
Hi, this is tracked as #1123
