### ISSUE TITLE
Are there examples of jsonschema2pojo-scalagen?

### ISSUE THREAD

**Issue by AceHack** [joelittlejohn/jsonschema2pojo#1137]
We are using sbt and scala 2.12

**Comment by kgupta26** [comment]
we are looking for one as well

**Comment by joelittlejohn** [comment]
There's no SBT plugin I'm afraid, only Maven and Gradle. The Scala generation support is somewhat experimental. I suggest you take a look at the Scala output from jsonschema2pojo.org and decide if it produces what you want.

If you want to integrate the Scala gen into your own application, you can see examples of doing it programmatically in the integration tests in this project.
