### ISSUE TITLE
Remove the duplicated generated classes with the underscores

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#114]
_Original author: prmorris...@gmail.com (June 20, 2013 08:49:37)_

I have attached an example of 2 files which generate the classes with underscores..

It would be great if the generator (maven plugin) would recognise that the things it is about to generate are identical and therefore the need to generate multiple classes with an underscore at the end is unnecessary.

_Original issue: http://code.google.com/p/jsonschema2pojo/issues/detail?id=114_

**Comment by grayside** [comment]
Frameworks such as Drupal take the approach of trying to facilitate common property naming & storage schema across different data models, but allow "application-level" formatting, titles, descriptions, and so on to vary across models.

Using a ref is a path to minimizing duplication, but it is not always reasonable. Instead, would it be possible for the generator to do some kind of namespacing by schema ID?
