### ISSUE TITLE
Incompatibility between JavaType and ClassNamePrefix or Suffix

### ISSUE THREAD

**Issue by laurent-simon** [joelittlejohn/jsonschema2pojo#1140]
The `javaType` extension property is supposed to specify a fully qualified name for the generated Java type (as said in the doc).

`classNamePrefix` and `classNameSuffix` allow to specify a prefix and a suffix for generated class names. When they are used with a JSON schema where the `javaType` property is present, there is a problem. Suffixes and prefixes are added to generated class names, has expected. But, they are also __inserted__ in class names explicitly specified using `javaType` !!!

For example, using a schema with:

```json

{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "javaType": "my.package.MyClassName",
```

with the following Gradle configuration : 

```groovy
jsonSchema2Pojo {

   classNameSuffix = "Suffix"
   classNameSuffix = "Prefix"

   // ...
}
```

Will generate a `my.package.PrefixMyClassNameSuffixe` class instead of  `my.package.MyClassName` as specified in the schema.

**Comment by joelittlejohn** [comment]
I think this is intended. The idea is that you can take some existing schemas and generate all the classes but with a suffix or prefix added to everything.

**Comment by laurent-simon** [comment]
If it is intended, then it's a very bad decision:

-  if `javaType` takes the precedence and works as documented ( " allows you to specify a fully qualified name for your generated Java type" ): Then,  If you want a prefix or a suffix, you can always add them in the `javaType` name.
- if not: There no way to specify a specific java type name !!!

Today, if you want a specific class name for a few cases, and prefixes and/or suffixes for all generated names, you can't. Because it doesn't work as documented...

**Comment by joelittlejohn** [comment]
> Today, if you want a specific class name for a few cases, and prefixes and/or suffixes for all generated names, you can't. 

This is the existing behaviour we have I'm afraid and I don't want to break any existing projects by changing it. I get that you have a use-case for which you'd like it to act differently. You might find it useful to fork and modify this behaviour.

**Comment by laurent-simon** [comment]
I understand your choice. But, the current documentation of `JavaType` is wrong and needs to be changed in this case.

When there is a prefix or suffix in the configuration, The name that you specify with `JavaType` is used as a kind of "template" but it is not used directly.

In the future,  if I need to fork, then I will probably do one of these things:

* Add a new annotation (`JavaClass` for example) and let `JavaType` for the history and backward compatibility because it is unable to cover all the uses cases.
* Add a new property in the configuration to specify the behavior of prefixes and suffixes when `JavaType` is present.
