### ISSUE TITLE
Differentiate usage of "existingJavaType"

### ISSUE THREAD

**Issue by sabroe** [joelittlejohn/jsonschema2pojo#1142]
**Context**: 

I like schema like this:

```
                "amount": {
                    "type": "string",
                    "pattern": "^([A-Z]{3}) (([0-9]{1,3}(,?[0-9]{3})*)(\\.([0-9]+))?)$",
                    "existingJavaType": "javax.money.MonetaryAmount"
                },
```

I have made a Jackson serializer and deserializer matching MonetaryAmount - works like a charm, it seems!

I generate Jackson POJOs for some kind of receiving server-side. This gets Jackson POJOs with the correct MonetaryAmount and conversion in play. Great!

**Issue**:

However, I give the JSON Schema to another project creating a matching client. For some reason, they do not really want to use and depend upon the Java type "MonetaryAmount", but are happy with just sending a JSON string like "EUR 1,000.00". If this client side happens to use Java, happens to use jsonschema2pojo too and equal to what is done on the server-side - how can they choose to ignore the presence of "existingJavaType"?

What if two parts do not agree on both using "existingJavaType"? How does one part accept this decoration while the other part chooses to not accept (to not actively accept or to actively reject) the same "existingJavaType"?

I would like some kind of option to adapt to decorations and without changing the schema. Locally for a single "existingJavaType" as well as globally for the full processing.

**Comment by eirnym** [comment]
Currently there's no way to ignore such fields also there's no way to add them separately from an external file. I asked to make it possible to use an external hint file for this in #1109, but had no luck with it by now.

**Comment by joelittlejohn** [comment]
I think the best approach here would be to simply update these files before calling jsonschema2pojo. For instance, if you want to replace `"existingJavaType"` values in a JSON file you could simply create another file to hold your replacements and merge the two.

See [How to merge 2 JSON objects from 2 files using jq?](https://stackoverflow.com/a/24904276/125825)

Alternatively, have a base schema (without any `existingJavaType` fields) which you share, and merge in your existingJavaType fields before using jsonschema2pojo.

**Comment by eirnym** [comment]
@joelittlejohn it's not possible in every case, like it won't work when you use `maven` or `gradle`

**Comment by joelittlejohn** [comment]
@eirnym Do we need two issues open to track this feature request?

**Comment by eirnym** [comment]
We don't
