### ISSUE TITLE
jsonschema2pojo schema inference versus other tools such as json-schema-inferrer

### ISSUE THREAD

**Issue by robert-dodier** [joelittlejohn/jsonschema2pojo#1144]
Hi, thanks a lot for this project, it looks really good and I'm looking forward to using it. I wonder in what ways the built-in schema inference for jsonschema2pojo compares to schemas inferred by other tools such as json-schema-inferrer. I'm not really thinking in terms of better or worse, but rather if there are differences in the range of JSON examples that can be handled, different basic assumptions, etc. 

I tried a simple example and it appears that the schema inferred by jsonschema2pojo is effectively the same as the one inferred by json-schema-inferrer, to judge by the generated Java classes, which are the same except that things are in a different order. That's encouraging, I just wonder if there's anything that can be said about what to expect when more complex examples are attempted.

It occurs to me that maybe it would be possible to dump out the inferred schema somehow, as an additional output, when the schema is inferred instead of specified. I guess that suggests another command line argument.

Thanks in advance for any light you can shed on this question!

Robert Dodier

**Comment by joelittlejohn** [comment]
We use Jackson to infer schemas from example JSON:

https://github.com/joelittlejohn/jsonschema2pojo/blob/b00b496894c9b112d1900ca06a0555d9ae0df110/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaGenerator.java#L159

We have some of our own code to navigate the objects and arrays, and when we finally get down to a simple value we can ask Jackson for a schema.

If you're interested in comparing this to the approach used in json-schema-inferrer then I think you can just look through the SchemaGenerator.java I have linked to. You might also want to wrap something around our SchemaGenerator and use that code yourself.
