### ISSUE TITLE
Question: How can embed an 'apache.avro json' schema within a json schema?

### ISSUE THREAD

**Issue by emeraldjava** [joelittlejohn/jsonschema2pojo#1146]
Hi,

I have the following json schema which outlines a structure for running an Apache Nifi flow - nifi uses used avro schema's as a fundamental component of the data flow, One requirement is we need to pass an avro schema definition as a part of the json payload. In the example below i've used the documented 'javaType' properties approach.

`{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://me.com/data-flow.schema.json",
    "title": "Nifi Flow",
    "description": "The structure of nifi flow.",
    "type": "object",
    "required": [
        "nifiFlows"
    ],
    "properties": {
        "nifiFlows": {
        "type": "array",
        "items": {
            "$ref": "#/definitions/nifiFlow"
        }
        }
    },
    "definitions": {
        "nifiFlow": {
        "properties": {
            "action": {
            "type": "string",
            "description": "If this data flow is for a full or delta load.",
            "minimum": 1,
            "enum": [
                "delta",
                "full"
            ]
            },
            "sourceSystem": {
            "type": "string",
            "description": "The source system from where we read.",
            "minimum": 1,
            },
            "sourceSchema": {
            "type": "string",
            "description": "The source schema.",
            "minimum": 1
            },
            "sourceEntity": {
            "type": "string",
            "description": "The source table or view.",
            "minimum": 1
            },
            "sourceAvroSchema": {
            "type": "object",
            "javaType": "org.apache.avro.Schema",
            "description": "The source avro schema for the table or view.",
            "minimum": 1
            },
    ...
`
This results in jsonschema2pojo generating it;s own 'org.apache.avro.Schema' class when i was hoping to reuse the Jackonson enabled class from the avro library. Is there a way to reuse an existing avro json schema definition, such that the classes generated by jsonschema2pojo maven plugin can re-use the classes in the apache.acvo api jar?

**Comment by joelittlejohn** [comment]
Yes, you should be able to use existingJavaType

**Comment by emeraldjava** [comment]
Thanks, I updated the json schema to use this and it works.

        "targetAvroSchema": {
          "type": "array",
          "items": {
            "type": "object",
            "existingJavaType": "org.apache.avro.Schema",
            "description": "The source avro schema for the table or view.",
            "minimum": 1
          }
        },

which generates the expected java method signature

`    @JsonProperty("sourceAvroSchema")
    public List<Schema> getSourceAvroSchema() {
        return sourceAvroSchema;
    }`

but i meet this serialisation error

`com.fasterxml.jackson.databind.JsonMappingException: Not an array: {"type":"record","name":"mpi_acct_rng_assgn","namespace":"com.baeldung.avro","fields":[{"name":"hostName","type":"string"},{"name":"ipAddress","type":"string"},{"name":"optString","type":["null","string"],"default":null},{"name":"rLong","type":"long"},{"name":"oLong","type":["null","long"],"default":null},{"name":"nLong","type":["long","null"],"default":-1},{"name":"timestamp_no_logical_type","type":"long"}]} (through reference chain: com.mastercard.customer.data.management.nifi.CdmDataFlowSchema["nifiFlows"]->java.util.ArrayList[0]->com.nifi.NifiFlow["sourceAvroSchema"]->java.util.ArrayList[0]->org.apache.avro.RecordSchema["elementType"])
`
Any idea on how i can ensure the avro schema blob is surrounded with suqare brackets?

**Comment by joelittlejohn** [comment]
It looks like your schema declares the value of targetAvroSchema to be an array, but it actually isn't an array in the data.
