### ISSUE TITLE
Getting List<Object> when using $ref 

### ISSUE THREAD

**Issue by Kabowyad** [joelittlejohn/jsonschema2pojo#1154]
I've got schemes
`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "javaType": "com.example.Portfolio",
  "type": "object",
  "properties": {
    "trackingId": {
      "type": "string"
    },
    "payload": {
      "type": "object",
      "properties": {
        "positions": {
          "type": "array",
          "items": [
            {
                "$ref" : "Positions.json"
            }
          ]
        }
      }
    },
    "status": {
      "type": "string"
    }
  }
}`

And
`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "javaType": "com.example.Positions",
  "type": "object",
  "properties": {
    "figi": {
      "type": "string"
    },
    "ticker": {
      "type": "string"
    },
    "isin": {
      "type": "string"
    },
    "instrumentType": {
      "type": "string"
    },
    "balance": {
      "type": "integer"
    },
    "blocked": {
      "type": "integer"
    },
    "lots": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "figi",
    "ticker",
    "isin",
    "instrumentType",
    "balance",
    "blocked",
    "lots",
    "name"
  ]
}`

As you can expect, Positions class generated successfull, but in Paylod class the next picture
`    @JsonProperty("positions")
    private List<Object> positions = new ArrayList<Object>();`

**Comment by joelittlejohn** [comment]
Can you replace this:

`[ { "$ref" : "Positions.json" } ]`

with this:

`{ "$ref" : "Positions.json" }`

We don't support union types (which are represented by an array).

**Comment by Kabowyad** [comment]
Yeah, find it too. Thanks!
