### ISSUE TITLE
CLI output wrong class name !

### ISSUE THREAD

**Issue by joliegrace** [joelittlejohn/jsonschema2pojo#1155]
**I have a Json file(WeatherJson.json)**
_{
  "latitude": 22.27,
  "longitude": 106.48,
  "timezone": "Asia/Bangkok",
  "currently": {
    "time": 1598688819,
    "summary": "Humid and Partly Cloudy",
    "icon": "partly-cloudy-day",
    "uvIndex": 4,
    "visibility": 10,
    "ozone": 274.2
  },
  "daily": {
    "summary": "Rain throughout the week.",
    "icon": "rain",
    "data": [
      {
        "time": 1598634000,
        "summary": "Humid and mostly cloudy throughout the day.",
        "icon": "rain",
        "apparentTemperatureMax": 112.11,
        "apparentTemperatureMaxTime": 1598685480
      },
...........more............_

**I open command line and run script**
_bash jsonschema2pojo -s WeatherJson.json -T JSON -a GSON -p com.test.j2p -t ClassOutput_
after run script everything fine , but I go to folder 'ClassOutput' I see a file name is 'Datum.java' , if not wrong it is 'Data.java".

**Comment by joelittlejohn** [comment]
We singularize the name when deciding what to call list items. Data is the plural of datum.
