### ISSUE TITLE
Validation of strings in a list

### ISSUE THREAD

**Issue by ehongyu** [joelittlejohn/jsonschema2pojo#1156]
Hi there,

I am newbie to this library, and found it pretty powerful. One feature, however, seems missing. I have a list of Strings, and would like to enforce a regex pattern against them. Somehow the transformed Java code is missing the pattern in json.

The following json is my example. The pattern for the single String variable`foo` is transformed as expected, but not for the list variable `bar`:
```{
  "type":"object",
  "properties": {
    "foo": {
      "type": "string",
      "pattern": "^\\d{2}:\\d{2}:\\d{2};\\d{2}$"      
    },
    "bar": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\d{2}:\\d{2}:\\d{2};\\d{2}$"      
      }
    }
  }
}
```
Below is the related transformed code, where the list `bar` is missing the expected regex pattern:
```
@JsonProperty("foo")
@Pattern(regexp = "^\\d{2}:\\d{2}:\\d{2};\\d{2}$")
private String foo;

@JsonProperty("bar")
@Valid
private List<String> bar = new ArrayList<String>();
```

Any guidance is appreciated.

**Comment by unkish** [comment]
Hi

Having `@Pattern` annotation on fields other than `CharSequence` would be incorrect according to [specification](https://beanvalidation.org/2.0/spec/#builtinconstraints-pattern):

>  The annotated {@code CharSequence} must match the specified regular expression.
>  The regular expression follows the Java regular expression conventions
>  see {@link java.util.regex.Pattern}.
> <p>
> Accepts {@code CharSequence}. {@code null} elements are considered valid.

**Comment by joelittlejohn** [comment]
Looks like this will only be possible in Bean Validation 2.0 via annotations within the lists generic type declaration.
