### ISSUE TITLE
How to make toString() configurable?

### ISSUE THREAD

**Issue by Redhunt2013** [joelittlejohn/jsonschema2pojo#1157]
I would like to include only specific fields in the `toString()` method (similar to equals and hashCode). 
`<toStringExcludes>` excludes the field from all the generated types if the property name is the same.  I'd like to make this configurable per type.

SO:  https://stackoverflow.com/questions/63838714/jsonschema2pojo-exclude-some-fields-in-tostring

**Comment by joelittlejohn** [comment]
We offer lots of source code customisation, however we just can't offer it all. I don't plan to implement this feature but thank you for raising it.

**Comment by dhpalan** [comment]
Hey @Redhunt2013 

I have a similar situation, where i want to customize the `toString()` method like this. Have you found a solution, how to do it?

```java
@Override
  public String toString() {
    ObjectMapper mapper = new ObjectMapper(); 
    return mapper.convertValue(this, JsonNode.class).toString();
  }
```

**Comment by Redhunt2013** [comment]
> Hey @Redhunt2013
> 
> I have a similar situation, where i want to customize the `toString()` method like this. Have you found a solution, how to do it?
> 
> ```java
> @Override
>   public String toString() {
>     ObjectMapper mapper = new ObjectMapper(); 
>     return mapper.convertValue(this, JsonNode.class).toString();
>   }
> ```


@dhpalan No, I haven't found a way.  My code never moved to production.  So it's dead to me.
