### ISSUE TITLE
java file first line blank when using java package

### ISSUE THREAD

**Issue by qiushics** [joelittlejohn/jsonschema2pojo#1161]
command:
```
.\jsonschema2pojo -s .\config.json -p com.demo -T JSON -t config
```

produce:
first line is blank
```

package com.demo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
```
how to resolve this?

**Comment by joelittlejohn** [comment]
Sorry, we rely on the Sun/Oracle CodeModel library to generate these files, we don't really have fine-grained control over this. If it's really bothering you you'll have to process them to remove leading newlines yourself. I suggest though that you don't worry about micro-managing this output.
