### ISSUE TITLE
Generating immutable POJO's

### ISSUE THREAD

**Issue by jhhdk** [joelittlejohn/jsonschema2pojo#1164]
Jackson supports serializing and deserializing immutable POJO's. It would be very nice if jsonschema2pojo supported generating that kind of POJO's.

Along the same lines it would be nice if jsonschema2pojo also supported generating ONLY all args constructor and while also being able to make that constructor non-public.

I have a use case where we want to implement a builder pattern implementation that can only construct valid objects.

**Comment by joelittlejohn** [comment]
We have a few other tickets tracking this.

For now, you can get some good results like:
