### ISSUE TITLE
How to generate @JsonSerialize and @JsonDeserialize annotations on a specific field?

### ISSUE THREAD

**Issue by savbiz** [joelittlejohn/jsonschema2pojo#1165]
Hi,

I can't find how to setup the Maven plugin to add the annotations `@JsonSerialize` `@JsonDeserialize` for a specific `java.time.LocalDate` field.

The tag `<serializable>` is not enough to achieve this, unfortunately..

I would like to achieve something like this in the generated Java class.

```java
@JsonSerialize(using = LocalDateSerializer.class)
@JsonDeserialize(using = LocalDateDeserializer.class)
  LocalDate deliveryDate;
```

**Comment by andrew-mcgregor** [comment]
+1 would like this too if it's not already in there somehow

**Comment by joelittlejohn** [comment]
Not possible I'm afraid, however you can configure the ObjectMapper to set serialiser and deserialiser for the Local date type. I also think there is a Jackson library for this, you can just add it to the classpath.
