### ISSUE TITLE
No Java Pojo generation for a schema masking simple type 

### ISSUE THREAD

**Issue by kartaa** [joelittlejohn/jsonschema2pojo#1167]
I have a schema for Email address, in the following JSON schema, emailAddress.schema.json. 

```
{   
"$schema": "http://json-schema.org/draft-06/schema#",   
"description": "Email addresses.",   
"type": "string",   
"format": "email",   
"examples": [     "kartaa@outlook.com"   ],   
"title": "Email address"
 } 
```

When I am trying to use the maven plugin for jsonschema2pojo to generate-sources for above json schema, it is not working. I could not find any relevant info or debug logs also.

I am expecting that for the above json schema file, I should be able to generate a Java POJO. Am I wrong in assuming as such? Is there any other way to handle what I am trying to do?

**Comment by lXaNl** [comment]
same for me

**Comment by joelittlejohn** [comment]
We don't have any special type to represent format: email. Check out the reference docs for other types we use for different format values:

https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#format
