### ISSUE TITLE
"javaEnum" has no effect when numeric values are used for "enum"

### ISSUE THREAD

**Issue by twheys** [joelittlejohn/jsonschema2pojo#1169]
Given the input schema

```
{
  "type": "integer",
  "enum": [1, 2, 3],
  "javaEnum": [
    "A",
    "B",
    "C"
  ]
}
```

I would expect to get the following java code

```
public enum MyNumberEnum {

A(1),
B(2),
C(3);

}
```

But the following is generated
```
public enum MyNumberEnum {

_1(1),
_2(2),
_3(3);

}
```

**Comment by unkish** [comment]
Provided schema seems to be invalid: generator is not aware of `"javaEnum"` node
Following nodes known do work and generate expected java code:
- `javaEnumNames`
- `javaEnums`

Sample usage:
```
  "javaEnumNames": [
    "A",
    "B",
    "C"]
```
```
  "javaEnums": [
    { "name": "A" },
    { "name": "B" },
    { "name": "C" }
  ]
```

**Comment by twheys** [comment]
Okay, thanks for the quick reply!
