### ISSUE TITLE
"extendsJavaClass" has no effect on Enum types

### ISSUE THREAD

**Issue by twheys** [joelittlejohn/jsonschema2pojo#1170]
Given the schema
```
{
  "type": "string",
  "javaType": "com.example.EnumClass",
  "extendsJavaClass": "com.example.SuperClass",
  "enum": [
    "A",
    "B",
    "C"
  ]
}
```

I would expect the result

```
public enum EnumClass extends SuperClass {

A("A"),
B("B"),
C("C");
}
```

But I get the result 

```
public enum EnumClass {

A("A"),
B("B"),
C("C");
}
```

**Comment by unkish** [comment]
According to [The Java® Language Specification: 8.9. Enum Types](https://docs.oracle.com/javase/specs/jls/se11/html/jls-8.html#jls-8.9) enums can't have superclasses.

Thus "expected result" would be a non-compliant code.

**Comment by twheys** [comment]
Okay, something I overlooked. Thanks for your answer.
