### ISSUE TITLE
mixed-type arrays

### ISSUE THREAD

**Issue by neuralsea-lab** [joelittlejohn/jsonschema2pojo#1174]
I have an array of mixed types but only the LIFO type is used instead of object (I'm using the maven plugin). Pretty sure that the online version actually generated an Object but can't replicate it. How can this be done please? (If I need to write additional generators what is the best approach to handle mixed type arrays and also to generate List<List<Object>>?)

Custom code (what is the best approach with least code)?
Use a JSON schema (I'm currently generating from JSON)?

**Comment by unkish** [comment]
Hi

Quite honestly, I'm having trouble understanding what's the issue.
Perhaps it would be possible to provide a minimal working example that demonstrates/reproduces the issue (like for example in #1152) ?

**Comment by neuralsea-lab** [comment]
No issue now. Using a JSON model I could only get a primitive type generated instead of java.lang.Object (for mixed arrays). I was able to achieve what I needed to achieve using a JSON schema with $ref as input and changing the maven plugin to jsonschema. Thank you for writing this plugin. It is a huge help.
________________________________

**Comment by unkish** [comment]
Glad to hear that You have managed to find solution :+1:
Regarding plugin: all credits go to @joelittlejohn and contributors.

**Comment by joelittlejohn** [comment]
Thanks for helping out around here @unkish!
