### ISSUE TITLE
Omit serialization for certain properties.

### ISSUE THREAD

**Issue by micharaze** [joelittlejohn/jsonschema2pojo#1177]
Is it possible to mark certain properties in the schema that they have no annotation for serialization when generating the java file?

We are using jsonschema2pojo to generate java class files with gson annotation. In code object of these classes will be serialized back to json. I would like to add properties which will not be serialized to json to use them in code only. With gson the expose anotation should be removed then.

For example, this
```JSON
{
  "type":"object",
  "properties": {
    "foo": {
      "type": "string",
      "omitSerialization": true
    },
    "bar": {
      "type": "integer"
    },
    "baz": {
      "type": "boolean"
    }
  }
}
```
should generate something like this:
```JAVA
private String foo;
@SerializedName("bar")
@Expose
private Integer bar;
@SerializedName("baz")
@Expose
private Boolean baz;
```

**Comment by unkish** [comment]
Hi

At present given functionality is not supported.
It seems that similar feature has been previously requested in  #1148
