### ISSUE TITLE
GenerateConfig  Class not found issue for Open JDK 11

### ISSUE THREAD

**Issue by psriramula** [joelittlejohn/jsonschema2pojo#1178]
faced with

`Caused by: java.lang.ClassNotFoundException: org.jsonschema2pojo.GenerationConfig
`

for JDK version to 

`<java.version>11</java.version>`

**Comment by unkish** [comment]
Hi

Would it be possible to provide a Minimal, Complete, and Verifiable Example ?

**Comment by psriramula** [comment]
Managed to resolve this, but the original issue seems there. will close this and raise new one
