### ISSUE TITLE
Allow extension in code generation for custom properties

### ISSUE THREAD

**Issue by shubhamoscar** [joelittlejohn/jsonschema2pojo#1185]
I see this library makes use of JCodeModel which does not allow editing an existing class generated from this library. The use of static class: [JsonSchema2Pojo](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonschema2Pojo.java#L43) in the library and hiding the JCodeModel within its ```generate```  method does not allow to reach me to the code-generation components.

It will be beneficial if the generate method could be broken down into several components, which allows attaching different custom hooks by the user on top of what this library does. For a start, I would like to see two hooks ```pre-generate``` and ```post-generate``` which could be reached by JCodeModel to facilitate custom code generation.

(Sample uncompiled PR to explain the idea: https://github.com/joelittlejohn/jsonschema2pojo/pull/1186)

**Comment by unkish** [comment]
Would it be possible to elaborate as to why usage of custom rule factory is not suitable?

**Comment by joelittlejohn** [comment]
This isn't something we're going to add to the core, it's too niche to maintain. It sounds like something you need, so please feel free to fork and add this and build your own version.
