### ISSUE TITLE
Build error due to 401 (unauthorized) from repo.spring.io repo

### ISSUE THREAD

**Issue by rafaelcoelho** [joelittlejohn/jsonschema2pojo#1187]
I'm facing an issue to build the project due to 401 error from `https://repo.spring.io/plugins-release/org/gradle/gradle-core/1.6/gradle-core-1.6.pom 401 Unauthorized` added as gradle-workaround on root pom.xml file:

```xml
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
            <id>gradle-workaround</id>
            <url>https://repo.spring.io/plugins-release</url>
            <snapshots>
              <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```
The issue is even happing in repo CI environment [https://travis-ci.org/github/joelittlejohn/jsonschema2pojo/builds/752114810](https://travis-ci.org/github/joelittlejohn/jsonschema2pojo/builds/752114810)

And after add a new repo entry pointing to [https://jcenter.bintray.com](https://jcenter.bintray.com) ) in pom.xml file the build goes fine as we can see from [https://travis-ci.org/github/joelittlejohn/jsonschema2pojo/builds/752119703](https://travis-ci.org/github/joelittlejohn/jsonschema2pojo/builds/752119703)

```xml
    <repositories>
        <repository>
            <id>jcenter</id>
            <name>jcenter</name>
            <url>https://jcenter.bintray.com</url>
        </repository>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
            <id>gradle-workaround</id>
            <url>https://repo.spring.io/plugins-release</url>
            <snapshots>
              <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```

Please let me know if there is any additional configuration to be done or if the fix is feasible then I will push a PR on that.

**Comment by unkish** [comment]
Maybe anonymous access error could be related to: [Permissions Changes to repo.spring.io](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020)

**Comment by joelittlejohn** [comment]
I expect we can just use Maven Central now (so remove this repo).

**Comment by rafaelcoelho** [comment]
Using only the Maven Central is still not working and not using the jcenter is still failing due to:

```text
You can keep references to /plugins-release but do not attempt to resolve an upstream dependency from that repository, or it will fail. The local repositories will always work.
```
See [repo.spring.io permission changes](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020)

**Comment by rafaelcoelho** [comment]
@joelittlejohn looks like the 401 issue is present even from master branch, can you please check the CI results from this PR #1189?

**Comment by unkish** [comment]
There seem to be several possible ways to fix this issue, here are some of my thoughts:

1\. by listing additional repository (either `jcenter.bintray.com` or `repo.gradle.org`) to allow fetching artifacts which require non-anonymous access.\
Cons:
&nbsp;&nbsp;&nbsp;&bull; neither of these repositories has all `org.gradle:*:1.6` artifacts
&nbsp;&nbsp;&nbsp;&bull; won't work if/when `repo.spring.io` will completely disallow anonymous access
Pros:
&nbsp;&nbsp;&nbsp;&bull; small change effort

2\. reach out to Trevor Marshall as suggested in [Notice of Permissions Changes to repo.spring.io, Fall and Winter, 2020](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) and see if some artifacts that are hosted only by `repo.spring.io` could be published/synchronized to other public repositories ie. `jcenter.bintray.com` or `repo.gradle.org`
Cons:
&nbsp;&nbsp;&nbsp;&bull; there's a chance it won't happen or it will take some time\
Pros:
&nbsp;&nbsp;&nbsp;&bull; small change effort

3\. Upgrade (bump-up) gradle/groovy dependencies
Cons:
&nbsp;&nbsp;&nbsp;&bull; second repository to fetch gradle/groovy artifacts would still have to be listed
&nbsp;&nbsp;&nbsp;&bull; backwards compatibility might get broken
&nbsp;&nbsp;&nbsp;&bull; medium change effort
Pros:
&nbsp;&nbsp;&nbsp;&bull; newer version of dependencies will be used

4\. alter `jsonschema2pojo-gradle-plugin` such that it would build (compile) plugin using gradle (via invocation from maven) and package/assembly would be done by maven
Cons:
&nbsp;&nbsp;&nbsp;&bull; medium change effort
&nbsp;&nbsp;&nbsp;&bull; might seem to be more "messy" as current artifact version/dependencies information would need to be passed from maven to gradle and compile output of gradle would have to be copied to maven
Pros:
&nbsp;&nbsp;&nbsp;&bull; there would be no need to define extra repository for gradle artifacts as those would be defined within gradle build scripts if needed
&nbsp;&nbsp;&nbsp;&bull; build would be handled by gradle

5\. Migrate `jsonschema2pojo-gradle-plugin` to gradle as was suggested [here](https://github.com/joelittlejohn/jsonschema2pojo/issues/1070#issuecomment-736943894), ie:
_Personally I'd use Github Actions to deploy with and let each plugin use their own build, handling that disparity in the CI._\
Cons:
&nbsp;&nbsp;&nbsp;&bull; one would have to figure out how to do the version management (releasing new version(s) and bumping \*-SNAPSHOT) between different build systems.
&nbsp;&nbsp;&nbsp;&bull; local builds would require both build systems to be present
Pros:
&nbsp;&nbsp;&nbsp;&bull; clear(er) separation
 \
 \
Please note that pros/cons are highly subjective.

**Comment by joelittlejohn** [comment]
I've upgraded things and removed the dependency on https://repo.spring.io/plugins-release

Thanks for the write up 👍
