### ISSUE TITLE
generateJsonSchema2Pojo Runs Too Early and Can't Add Depends On

### ISSUE THREAD

**Issue by PRAquilone** [joelittlejohn/jsonschema2pojo#1188]
My goal is as follows:

1) copy files to staging area (required by company)
2) generate pojos from the schemas that were copied to the staging area
3) java updater that tweaks the generated models for my company needs
4) build a jar file from the updated generated files for distribution so that we can have everyone on the same page.

To achieve this I have subprojects for each above.  The issue is that even with evaluationDependsOn step 1, step 2's generatedJsonSchema2Pojo executes first and therefore fails because the files have not been staged yet.  I have tried everything I can find on the internet and everything I can think of and it still fires just after clean and before anything else. 

Any help would be GREATLY appreciated.

**Comment by unkish** [comment]
Taking a long shot here:
This doesn't seem to be issue of `jsonschema2pojo` but rather issue of gradle project setup.

Maybe [this](https://discuss.gradle.org/t/evaluationdependson-annoyance/21783) could be helpful
