### ISSUE TITLE
JsonSchema "pattern" field for regex

### ISSUE THREAD

**Issue by Javier-Vazquez** [joelittlejohn/jsonschema2pojo#1194]
Hi joelittlejohn, first I want to thank you for such an amazing work.
I wanted to ask you -> how to use the "pattern" field for regex in jsonschema. Is this supported in this maven plugin?

for example, consider this simple jsonschema that validates that the name property has only capital letters:

``
{
  "type":"object",
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[A-Z]+$"
    }
  }
}
``

Is this possible with your plugin? And if not, do you guys know how to do this for a pojo?

PS: I am using Confluent Schema Registry for validating data with kafka, so I am sending pojos and trying to validate with jsonschema.

I appreciate very much your help :)
Regards

**Comment by eirnym** [comment]
Hi, 

In our application we use pattern to produce a string (as we require it to be stored in database) and we're validating request against json schema using json schema validator from networknt and Joni library as regex backend. (you may use any other validator as well)

java.util.regex (all versions) has a flaw we don't want to accept: `{2,3}` (this is entire pattern) is a valid regex for java, but not for any other engines

This is slightly not an answer for your question, but may help

**Comment by joelittlejohn** [comment]
This library is _only_ concerned with generating types for binding, not validating data. 

It sounds like you need to use a json schema validator against your JSON, or activate JSR-303 annotations in this library (check out `includeJsr303Annotations`) and have a look at a bean validator like hibernate-validator.
