### ISSUE TITLE
Mark generated pojos as @Generated

### ISSUE THREAD

**Issue by cyclotomic18** [joelittlejohn/jsonschema2pojo#1195]
Is there currently a way to mark code generated (via maven plugin) as @javax.annotation.Generated like we can do with plugins like jaxb, lombok, openapi ecc.? 
This is necessary to neatly exclude those pojos from code coverage.

**Comment by eirnym** [comment]
Hi, 

There was a few discussions on this topic back in a day. I encourage you to read #1162 and discussions linked there and eventually to add a PR :)
