### ISSUE TITLE
Java9+ Generated annotation cannot be found for Android projects

### ISSUE THREAD

**Issue by eirnym** [joelittlejohn/jsonschema2pojo#1212]
AGP 7+ requires Java 11 according to the [article](https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html?m=1), so I tested this java version ad well.

`jsonschema2pojo` library uses _build tool Java_ version to determine which `Generated` annotation to use. The library sets this annotation as javax.annotations.**processing**.Generated for java 9+ which can't be found in Android Java STL (Google blocks certain packages to be included).

Please note, that Java used for build tool can differ from Java you targeting at. 

To include this annotation into build I have to use an external library. While building using java8 I have to add library like `javax.annotation:javax.annotation-api`. Which library should I add for new annotation?

**Comment by joelittlejohn** [comment]
There are two options here:

1. Turn off the annotation using `includeGeneratedAnnotation = false`
2. If you're using jcenter, try `com.github.pengrad:jdk9-deps:1.0`

I think we can improve the logic here and attempt to use the target source version, but the above should help.

**Comment by joelittlejohn** [comment]
I've updated the Android gradle example here and I may change the default for the Android task.

**Comment by eirnym** [comment]
Please, use the target source version as an indicator, because the this version is quite useless otherwise (I haven't noticed any differences on this parameter)

**Comment by eirnym** [comment]
How do you indicate a default for an Android or for Java? Could it be a value _inside_ library? 

Changing this default in a plugin could lead to incompatibility problems

**Comment by eirnym** [comment]
usage of libraries like `com.github.pengrad:jdk9-deps:1.0` is less obvious than an official library I mentioned. BTW, `javax.annotation:javax.annotation-api` is highly used in enterprise applications, so if you'd use just one variant of `Generated` annotation for all versions of java, it'll be much easier to manage and have a security audit on.
