### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by eirnym** [joelittlejohn/jsonschema2pojo#1213]
Documentation for library, Maven and Gradle plugins is quite outdated and should be updated

**Comment by joelittlejohn** [comment]
Can you give some indication about why you think the documentation for the library and the Maven plugin is out of date?

For the Gradle plugin I think we have quite a few properties missing from the readme. Feel free to raise a PR.

**Comment by joelittlejohn** [comment]
I noticed that the docs for the new includeGeneratedAnnotation property were wrong in the Maven plugin. Is this what you were referring to? It should be correct now.

**Comment by eirnym** [comment]
For example, some features listed on maven documentation are not present anymore and is parcelable is still an experimental feature

**Comment by eirnym** [comment]
And please, check all defaults listed in documentation as well

**Comment by joelittlejohn** [comment]
> For example, some features listed on maven documentation are not present anymore

Which features?

**Comment by eirnym** [comment]
Please, update maven plugin as well
