### ISSUE TITLE
Add a parameter allowing to configure custom rule factories and custom annotators

### ISSUE THREAD

**Issue by HectorBst** [joelittlejohn/jsonschema2pojo#1215]
Hi,

When writting a custom Annotator or a custom RuleFactory intended to be reused across several projects, it may become necessary to be able to configure it to adapt its behavior, like jsonschema2pojo itself.

I haven't found a clean way to do this currently.

It could be interesting to add a parameter intended to receive this settings (a map to remain generic).

For example in maven this could take the following form:
```xml
<configuration>
    <!-- [...] -->
    <customRuleFactory>MyRuleFactory</customRuleFactory>
    <customConfig>
        <myConfig1>myValue1</myConfig1>
        <myConfig2>myValue2</myConfig2>
    </customConfig>
</configuration>
```

Thus the Annotator or the RuleFactory could easily access these additional options in GenerationConfig.

**Comment by joelittlejohn** [comment]
We have an open PR for this, let's discuss there: #1122.

@HectorBst are you able to possibly build a local version from https://github.com/ddcruver/jsonschema2pojo/tree/feature/add-configuration-map-for-custom-rule-factories and try it out?
