### ISSUE TITLE
Allow to override only specific parts of generation rules

### ISSUE THREAD

**Issue by HectorBst** [joelittlejohn/jsonschema2pojo#1216]
Hi,

When writing a custom RuleFactory whose goal is to keep much of the code generated by jsonschema2pojo and modify only specific parts, the only entry point we have is to make a Rule inheriting from the default Rule, override the Rule#apply method and call the parent class.

The problem is that it will cause the execution of all the standard code, but also return an object from the codemodel library, which is almost always immutable. It can then become quite difficult to modify the code of already existing methods for instance.

For example, it would be much easier to be able to only override the PropertyRule#addGetter method if we just want to modify the generation of getters, or ObjectRule#addEquals if we just want to modify the equals method (there may be a lot of other examples).

The problem is that these methods are all private, so we can't overwrite them to allow the default Rule#apply method to directly calls our custom generation.

Make these methods protected could fix this difficulty.

**Comment by joelittlejohn** [comment]
I don't think banning `private` methods from jsonschema2pojo is really viable. It also creates a huge surface area for breaking changes.

If it's not possible to call the parent and add to the result, I think the best option is to simply copy the source code of the rule and customise it.
