### ISSUE TITLE
Customize jackson strategy naming 

### ISSUE THREAD

**Issue by B-hamza** [joelittlejohn/jsonschema2pojo#1230]
Actually when using jackson2Annotator the naming set into JsonProperties are camelCase by default.
Is there any way to externalise the straregy naming of jsonProperties into configuration ? 
To be able to chose kebab-case for example.

**Comment by joelittlejohn** [comment]
Hi. I'm not sure I understand the question. 

We name fields and methods in Java using Java's naming convention (like: lowerCamelCase). Each field is annotated with `@JsonProperty("field-name")` so that whatever JSON field name is correct will be present in the output JSON.
