### ISSUE TITLE
uri format inconsistency with empty authority segment

### ISSUE THREAD

**Issue by testower** [joelittlejohn/jsonschema2pojo#1236]
JSON schema string format `uri` uses https://tools.ietf.org/html/rfc3986 which allows an empty authority, but the java type java.net.URI uses the obsolete https://tools.ietf.org/html/rfc2396 which does not allow it. For example, android and ios discovery uris  become impossible to unmarshal:
 
```
{
  "discoveryUri": "com.test.ios://"
}
```

Schema: 

```
{
  "$schema": "http://json-schema.org/draft-2020-12/schema",
  "type": "object",
  "properties": {
    "uri": {
      "type": "string",
       "format": "uri"
    }
  }
}
```

Trying to unmarshal into java.net.URI gives the following exception:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.net.URI from String value 'com.test.ios://': not a valid textual representation, problem: Expected authority at index 25: com.test.ios://
```

Is there a workaround for this?

**Comment by joelittlejohn** [comment]
Can you use the format type mapping to map uri to String?

**Comment by testower** [comment]
Maybe! I have never used it, is there any examples on it somewhere?

That said, any thoughts on the underlying issue re incompatible specs?

**Comment by joelittlejohn** [comment]
> Maybe! I have never used it, is there any examples on it somewhere?

How are you using jsonschema2pojo? (i.e. what plugin are you using?) Check the docs for your plugin and you should find something useful for the `formatTypeMapping` config option. For individual properties you can also use `existingJavaType` in the schema.

> That said, any thoughts on the underlying issue re incompatible specs?

Not really. Java's URI class is not compatible with RFC 3986, so RFC 2396 is the best URI implementation the host language can provide. jsonschema2pojo actually predates RFC 3986 being specified as the requirement for `"format": "uri"` in the JSON Schema spec, and it wouldn't be appropriate to now change the type we use here IMO. Maybe if a proposal like [this one re RFC 3986 in Java](https://cr.openjdk.java.net/~dfuchs/writeups/updating-uri/) progresses, there will be a better type we can use in future.

Of course Java's URI will suffice for most use-cases, but in the case where it doesn't, you should be able to use the `formatTypeMapping` property to choose your own path.

**Comment by testower** [comment]
Thanks I found out how to use formatTypeMapping with the maven plugin. Although it forces *all* instances of the uri format to be mapped to string I can live with that. It's not an option to modify the schema since it's outside my control.
