### ISSUE TITLE
nested sibling references causes error `Path not present: definitions` only on  https://www.jsonschema2pojo.org/, local is fine

### ISSUE THREAD

**Issue by farazoman** [joelittlejohn/jsonschema2pojo#1237]
I have a json schema that has nested references in the "definitions" property. What I mean is that I have one property defined say "PropertyA" then a second property is defined called "PropertyB" which references "PropertyA"

When I use the preview button on https://www.jsonschema2pojo.org/ then I get the error `Path not present: definitions`.

I narrowed down the problem to the nested references, i.e `"#/definitions/PropertyA"` . When running jsonschema2pojo on my local it works fine.

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Inbox Item Datalake DTO",
    "definitions": {
        "PropertyA": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "PropertyB": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/PropertyA"
                    },
                    "default": []
                }
            }
        }
    },
    "properties": {
        "FinalProperty": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/PropertyB"
            },
            "default": []
        }
    }
}
```

I saw a few posts online about using an absolute path but this is in the exact same file so nothing I could do there. Also I opened a stackoverflow question. https://stackoverflow.com/posts/67050796/edit

**Comment by joelittlejohn** [comment]
Thanks for reporting this. This is very similar to #793 but from the website we use a way of providing the schema as a string and refs are resolved a little differently.

We will have to release 1.1.1 and update the website to use it, but this should be fixed on the website soon.
