### ISSUE TITLE
Q: How to preserve top level class name

### ISSUE THREAD

**Issue by marceloverdijk** [joelittlejohn/jsonschema2pojo#1238]
E.g. having this:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "IMDb",
```

will generate a `IMDb` top level class as expected.

But:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "D3DB",
```

will generate a `D3db` class unfortunately.

Is it possible to tweak something to generate `D3DB` ?

the https://www.jsonschema2pojo.org/ generator has the option to provide the class name:
(`"Example"` by default)

![image](https://user-images.githubusercontent.com/197004/114418438-cbc37380-9bb2-11eb-8a9b-79d314852dcf.png)

But I don't think this parameter can be set using the Gradle plugin.

**Comment by joelittlejohn** [comment]
Hi Marcel. One option you could try here is adding `javaName` in the schema to choose your own class name. You can also use `javaType` to specify a fully qualified class name.

The goal of this plugin is to create types that _can_ be used for binding with JSON, not necessarily to generate the exact Java output that any user of the plugin prefers and allow full control over what Java source code is generated. The configurability and options to maintain become an endless maintenance burden.
