### ISSUE TITLE
Not able to use as a plugin for Gradle?

### ISSUE THREAD

**Issue by Anuj28282828** [joelittlejohn/jsonschema2pojo#1239]
I am trying to use your jsonschema2pojo-gradle-plugin but not able to do that as it is not able to find it in any of the plugin repositories. Is there any easy way to apply this plugin on local machine?

Trying to do this :

apply plugin: 'jsonschema2pojo'

Getting this error :

A problem occurred evaluating root project 'java-project'.
> Plugin with id 'jsonschema2pojo' not found.

Attached build.gradle in TXT format below.

[build.gradle.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/6309576/build.gradle.txt)

Requesting your kind help on this. I am kind of completely stuck.

**Comment by joelittlejohn** [comment]
Hi Anuj. We still need to publish to plugins.gradle.org because at the moment this plugin is only available at Maven Central.

Are you able to use either of these examples as a guide:
- https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/example/java/build.gradle
- https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/README.md

**Comment by Anuj28282828** [comment]
but I will not be able to use this to productionize right?
I have the JAR on artifactory but I am not able to use it the mentioned way
How do I configure Gradle to pick it up from Artifactory but still use it as a Gradle plugin?

**Comment by joelittlejohn** [comment]
> but I will not be able to use this to productionize right?

Sorry, I don't know what you're referring to here. You mean you can't use Maven Central in your production builds?

> I have the JAR on artifactory but I am not able to use it the mentioned way
> How do I configure Gradle to pick it up from Artifactory but still use it as a Gradle plugin?

Do you mean you have copied some jsonschema2pojo-gradle-plugin jar from Maven Central to your own Artifactory repository?

**Comment by Anuj28282828** [comment]
even after using mavenCentral() I am not able to apply plugin. Not sure which **Plugin repository** is it checking for?

Also, I have copied that JAR to my own Artifactory repo, but still not able to apply it.

buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }

In the above snippet, is it possible to specify any other location?

**Comment by joelittlejohn** [comment]
This seems to work fine for me:

```
apply plugin: 'java'
apply plugin: 'jsonschema2pojo'

group 'info.garagesalesapp'
version '1.0-SNAPSHOT'

buildscript {
  repositories {
    mavenCentral()
  }

  dependencies {
    classpath 'org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:1.1.0'
  }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.8.6'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}

jsonSchema2Pojo {
  targetPackage = 'example'
  annotationStyle = "gson"
}
```
