### ISSUE TITLE
1.1.1 tag

### ISSUE THREAD

**Issue by eirnym** [joelittlejohn/jsonschema2pojo#1240]
Version 1.1.1 is hot tagged, is it intended?

**Comment by joelittlejohn** [comment]
Hi @eirnym. Yes, I released 1.1.1 yesterday. We have to wait to update the project until Maven Central 'publishes' the release which normally takes a few hours. I published this late last night so I will update the docs today.

Not sure what you mean by 'hot' tagged though. Did you find a problem somewhere?

**Comment by joelittlejohn** [comment]
I don't think there's anything wrong here, but give us a shout if you see a problem.
