### ISSUE TITLE
jsonschema2pojo maven plugin  should handle symlinks

### ISSUE THREAD

**Issue by ottomata** [joelittlejohn/jsonschema2pojo#1256]
Wikimedia uses [jsonschema-tools](https://github.com/wikimedia/jsonschema-tools) to maintain versioned JSONSchema files (more info in this [blogpost](https://techblog.wikimedia.org/2020/09/17/wikimedias-event-data-platform-json-event-schemas/) ).  Our 'latest' version of a schema is just a symlink to the latest file version, e.g. latest.json -> 1.1.0.json.

I'd like to use jsonschema2pojo to generate Java POJO classes for all latest.json symlink files.  However, when I use the Maven plugin with an `includes` filter like

```
            <includes>
              <include>**/latest.json</include>
            </includes>
```

No classes are generated.  I'm pretty sure this is because [URLUtil.getFileFromUrl](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/URLUtil.java#L47) does not handle the symlink.

**Comment by ottomata** [comment]
I'll try to submit a PR soon, something like:

```java
    public static File getFileFromURL(URL url) {
        File file;
        try {
            file = new File(url.toURI());
        } catch (URISyntaxException e) {
            throw new IllegalArgumentException(String.format("URL contains an invalid URI syntax: %s", url), e);
        }

        if (Files.isSymbolicLink(file.toPath())) {
            try {
                file = Files.readSymbolicLink(file.toPath()).toFile();
            } catch (IOException e) {
               throw new IllegalArgumentException(String.format("URL is a symlink, but failed reading target %s", url), e);
            }
        }

        return file;
    }
```

**Comment by ottomata** [comment]
Huh, I'm not so sure #1257 solves my problem like I thought it would.  I tried my change but still jsonschema2pojo-maven-plugin couldn't find any content when including files that are symlinks.

I thought maybe the files were actually being loaded using `ContentResolver` instead, so I added a test to read a symlink, and it passed as is.  I don't see in the code would be causing this to happen. 

This might be an issue with how maven includes filter works?  Not sure, but I'm declining my PR for now.

**Comment by joelittlejohn** [comment]
Going to close this one as we already handle symlinks correctly (proven by your exploration). Feel free to reopen if you still have not gotten to the bottom of what was wrong.

**Comment by karsil** [comment]
I've encountered the same problem as well. My multi-module project depends on the same JSON schema and should generate the sources during the build. When working on real files it generates correctly, but fails on symlinks.
@ottomata Did you found a solution in the meantime?

**Comment by ottomata** [comment]
No, I was just experimenting with jsonschema2pojo and never got far enough to make it work.
