### ISSUE TITLE
How to get value of key when using jsonschema2pojo custom annotator on a input type of JSON

### ISSUE THREAD

**Issue by adbdkb** [joelittlejohn/jsonschema2pojo#1259]
I am creating the POJOs using jsonschema2pojo on inputtype of JSON ( not Json schema ). I need to add the APIModelProperty annotation to each primitive field and I would like to use the value as value for "example" parameter.

```java
@ApiModelProperty(example="2020-02-03T00:00:00.000Z")
```

I do not want to manually add this annotation to each field afterr the schema is generated. So, I am trying to write a custom annotator that will add this annotation. From the examples I have seen, I am trying to use the

```java
@Override
public void propertyField(JFieldVar field, 
                      JDefinedClass clazz, 
                      String propertyName, 
                      JsonNode propertyNode ) {

    System.out.println("propertyName " + propertyName);
}
```

This gives me the key names from the JSON. I have 2 questions

    I want to add the @APIModelProperty annotation to each primitive field. How do I identify that propertyName field is a primitive and
    How do I get the value of propertyName?

Example - "eventCreatedTime": "2020-02-03T00:00:00.000Z"

Thank you

**Comment by unkish** [comment]
Hi

> How do I identify that `propertyName` field is a primitive

Maybe `propertyNode.get("type")` could do the trick ?

> How do I get the value of `propertyName`

Most probably You'd have to create and use modified version `SchemaGenerator` which would pass/attach "value" with/to `propertyNode` ie:
```
public class CustomSchemaGenerator {
    ...
    private ObjectNode objectSchema(JsonNode exampleObject) {

        ObjectNode schema = this.objectMapper.createObjectNode();
        schema.put("type", "object");

        ObjectNode properties = this.objectMapper.createObjectNode();
        for (Iterator<String> iter = exampleObject.fieldNames(); iter.hasNext();) {
            String property = iter.next();
            ObjectNode schemaFromExample = schemaFromExample(exampleObject.get(property));
            schemaFromExample.put("value", exampleObject.get(property).asText());
            properties.set(property, schemaFromExample);
        }
        schema.set("properties", properties);

        return schema;
    }
    ...
```
that'd allow accessing value in custom annotator as following:
```
    public void propertyField(JFieldVar field, JDefinedClass clazz, String propertyName, JsonNode propertyNode) {
        String value = propertyNode.get("value").textValue();
        ...
```

**Comment by adbdkb** [comment]
Thanks @unkish - Do I need to extend CustomSchemaGenerator from any class?  How / where do I indicate that I want to use    this class?  Also,  I presume this will work  when generating classes from plain JSON, not json schema. Is that correct?

I would appreciate it, if you could give me an example of how I could use it.

Thanks again

**Comment by unkish** [comment]
> Do I need to extend CustomSchemaGenerator from any class

No. If at all it'd probably be `org.jsonschema2pojo.SchemaGenerator`

> Also, I presume this will work when generating classes from plain JSON, not json schema. Is that correct?

Yes

> How / where do I indicate that I want to use this class?

At present there's no possibility to pass/configure schema generator
Easiest way would be
1.  to fork given project and make necessary changes ie.: [example](https://github.com/unkish/jsonschema2pojo/tree/example/1259)
2. run smth. like `mvn package -pl jsonschema2pojo-cli -am` (you might want to change project version/classifier/...)
3. `cd jsonschema2pojo-cli\target`
4. `java -cp "jsonschema2pojo-cli-1.1.2-SNAPSHOT.jar;lib\*" org.jsonschema2pojo.cli.Jsonschema2PojoCLI  -a JACKSON2 -305 -dtt java.time.LocalDateTime -T JSON -s C:\json_test\input.json -t C:\json_test\output`

With `C:\json_test\input.json` content being something like:
```
{
  "correlationId": "212b5010-0542-447c-8c6a-7bb7a769a516",
  "Weight": 1,
  "bool": true,
  "obj": {
    "obj_field": true
  },
  "eventCreatedTime": "2020-02-03T00:00:00.000Z",
  "UserLoginID": "ffffffff-ffff-ffff-ffff-ffffffffffff",
  "RelatedID": "2ef13880-ce0d-44ea-a6b9-8da982c91b14",
  "ReceivedDate": "2021-04-29T00:00:00"
}
```

**Comment by adbdkb** [comment]
Thanks @unkish - I will use this example to do the  modifications for ApiModelProperty.  

The code you have in the example looks like below

public class Jackson2Annotator extends AbstractTypeInfoAwareAnnotator {

and

public abstract class AbstractTypeInfoAwareAnnotator extends AbstractAnnotator{

So, First question - Can I define a custom annotator in my code extending AbstractTypeInfoAwareAnnotator  instead of AbstractAnnotator.

That way, I don't have to make changes to core classes?

If that is not recommended or possible

the next question I have is how shall I modify the pom to accept this version?  Currently, the pom looks like

`<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <version>1.1.1</version>
    <configuration>
        <annotationStyle>none</annotationStyle>
        <outputDirectory>${project.build.directory}/temp/generated-sources</outputDirectory>
        <fileExtensions>json</fileExtensions>
        <removeOldOutput>false</removeOldOutput>
        <sourceType>json</sourceType>
        <generateBuilders>false</generateBuilders>
        <initializeCollections>true</initializeCollections>
        <includeAdditionalProperties>false</includeAdditionalProperties>
        <includeGeneratedAnnotation>false</includeGeneratedAnnotation>
        <includeAdditionalProperties>false</includeAdditionalProperties>
        <includeHashcodeAndEquals>false</includeHashcodeAndEquals>
        <includeToString>false</includeToString>
        <customAnnotator>com.company.custom.annotator.JSONAPIModelAnnonator</customAnnotator>
    </configuration>
<plugin>
`

Thanks again

**Comment by adbdkb** [comment]
I tried to use the <> code part in the above comment, but it still seems to ignore it. Sorry about that

**Comment by adbdkb** [comment]
Hello @unkish  -  Could you or someone please let me know, how I could use the updated version in a POM.  I would like to share this version with the team and use it in the process where we generate these classes for new jsons.

Thanks

**Comment by joelittlejohn** [comment]
@adbdkb I don't understand the question I'm afraid. unkish has provided a diff that shows exactly how to:

1. retain the `"example"` property when the SchemaGenerator creates a schema from your JSON, and then 
2. use that "example" property later in the annotator.

There is no way to do this with a customer annotator, because you need both step one and step two.

**Comment by adbdkb** [comment]
Hi,  @oelittlejohn  -  Thanks.    I understand I have to update the code as unkish  showed as  example.  What I am  trying to ask is,  in  the team - one person would make the change and then would want to share it with the team.  Currently we use the 

            <groupId>org.jsonschema2pojo</groupId>
            <artifactId>jsonschema2pojo-maven-plugin</artifactId>
            <version>1.1.1</version>

in the POM plugin.

My question is - how do I replace it with the version I would create for that jar.

Hope this clarifies my question
