### ISSUE TITLE
JSON schema with enum member with a name starting with a capital letter, causes a generation of a code that doesn't compile

### ISSUE THREAD

**Issue by yurama** [joelittlejohn/jsonschema2pojo#126]
When trying to run jsonschema2pojo on a json schema that has an enum property with a name starting with a capital letter, the generated code doesn't compile.
The compilation error is: non-static variable 'x' cannot be referenced from a static context.

That error occurs because the generated code has a private field with the same name as the enum, that is later accessed by that name from a static code block.

According to  RFC 4627 - there is no requirement for member names to start with lower case letters.

For example, for the JSON schema:

<pre><code>
{
    "type": "object",
    "properties": {
        "ExampleObj": {
            "type": "object",
            "properties": {
                "TimeFormat": {
                    "enum": [ "12h", "24h" ],
                    "description": "The referred time display format, either 12 or 24 hour clock."
                }
            }
        }       
    }
}
</code></pre>

That error occurs because the generated code has a private field with the name TimeFormat:

<pre><code>
    @JsonProperty("TimeFormat")
    private ExampleObj.TimeFormat TimeFormat;
</code></pre>

 and an enum with the same name, that tries to access that field from within a static code block (note the ExampleObj.TimeFormat.values() within the foreach loop):

<pre><code>
    @Generated("com.googlecode.jsonschema2pojo")
    public static enum TimeFormat {

        _12_H("12h"),
        _24_H("24h");
        private final String value;
        private static Map<String, ExampleObj.TimeFormat> constants = new HashMap<String, ExampleObj.TimeFormat>();

        static {
            for (ExampleObj.TimeFormat c: ExampleObj.TimeFormat.values()) {
                constants.put(c.value, c);
            }
        }
.
.
.
</code></pre>

**Comment by deepaksama** [comment]
Is there any way to get enum values as numenric?
