### ISSUE TITLE
Support jakarta.validation

### ISSUE THREAD

**Issue by ben-manes** [joelittlejohn/jsonschema2pojo#1271]
Unfortunately with the global rename, this causes large clashes when trying to upgrade projects. Can you please make this a configuration option to generate either the legacy `javax.validation` or newer `jakarta.validation` validation annotations?

PR #1258 offers an implementation, but is a harsher change by forcing the switch. A more gentle transition would be better, but this unfortunately does become a blocker.

**Comment by joelittlejohn** [comment]
Based on what I see in #1258, this one looks pretty easy to implement. I'm sure we can add `useJakartaValidation` (default false) as a new config option and reference the different package where needed.

**Comment by unkish** [comment]
Some of the caveats that might pop-up:

1. unit tests - would have to be modified to check both configurations (rather simple)
2. integration tests - having both `hibernate-validator` versions on classpath would yield conflict, so possible solutions might be:
a. use either `javax` or `jakarta` version of validator (rather simple)
b. load both `javax` and `jakarta` validator with different classloaders (rather messy)

**Comment by joelittlejohn** [comment]
Fixed by #1280
