### ISSUE TITLE
Option to use LinkedHashMap instead of HashMap to preserve additionalProperties keys order

### ISSUE THREAD

**Issue by gmlag** [joelittlejohn/jsonschema2pojo#1273]
It's quite annoying that additionalProperties values lose their initial array order when json is parsed.
Since I use the same schema classes to generate json after tweaking, I can't sort them too.

I guess it will be easy to add an option to generate LinkedHashMap instead of HashMap for additionalProperties field.

**Comment by jdimeo** [comment]
This is an easy change, and I'm not even sure it should be configurable- I think it should be the new default behavior:
https://github.com/jdimeo/jsonschema2pojo/commit/de79bf0f52bd48b5b5529173d139a37c6a29f70f

**Comment by hupfdule** [comment]
> This is an easy change, and I'm not even sure it should be configurable- I think it should be the new default behavior

I think the same way.

Do you mind creating a PR for your change?

**Comment by jdimeo** [comment]
OK I did: https://github.com/joelittlejohn/jsonschema2pojo/pull/1397/

**Comment by joelittlejohn** [comment]
Closed by #1397.
