### ISSUE TITLE
Getting ClassNotFoundException while configuring <customAnnotator> - Gradle

### ISSUE THREAD

**Issue by Anuj28282828** [joelittlejohn/jsonschema2pojo#1274]
I am getting the same error when I am using something like below, as a gradle task :

jsonschema2pojo {
    includeConstructors = true
    source = files(.....)
    customAnnotator = "com.test.JsonDeserializeAnnotator"
}

Now this class is available in the same project where the above gradle task is defined
What am I missing?

**Comment by joelittlejohn** [comment]
You need to build the class as a separate module or dependency. Jsonschema2pojo generates classes that must be compiled, so the annotator class must be available before the compilation stage of your project.

**Comment by Anuj28282828** [comment]
I tried it this way as well :

dependencies {
    implementation project(':schemas')
}

And my Annotator is coming from the other project i.e. schemas.
Still doesn't detect. Something still missing?

**Comment by unkish** [comment]
Maybe [sharing outputs between projects](https://docs.gradle.org/current/userguide/cross_project_publications.html) should be used ?

**Comment by adispennette** [comment]
I have the custom annotator in a separate modules and it is still failing because it is unable to find the class.
I don't know if there is some shifting of gradle task order that could fix this or not.

I was also curious if it would it be possible to include something like `String customAnnotator = "org.jsonschema2pojo.NoopAnnotator"` and then in the AnnotatorFactory something like
```
public Annotator getAnnotator(String className) {
        try {
            return getAnnotator((Class<? extends Annotator>)Class.forName(className));
        } catch (ClassNotFoundException e) {
            throw new IllegalArgumentException("Failed to create a custom annotator from the given class. An exception was thrown on trying to locate class.", e.getCause());
        }
    }
```
Then either the string or the class could be used.
Not sure if that would help either, but it would move the Class.forName later in the flow.

**Comment by unkish** [comment]
@adispennette would it be possible to provide sscce (Short, Self Contained, Correct (Compilable), Example) ?

**Comment by adispennette** [comment]
Hello again, 
I finally got this to work but I don't really like how I had to do it. As was mentioned above the jar had to be a compiled artifact. It also had to be added to the gradle build classpath along with any other dependencies I wanted to use inside the CustomAnotator.
```
buildscript {
    dependencies {
        classpath("com.data:emitter-schema2pojo:0.1.DEV.31488.47") {
            isTransitive = false
        }
        classpath("org.reflections:reflections:0.9.10")
    }
}
...
jsonSchema2Pojo {
    targetPackage.set("com.data.schema.generated")
    useTitleAsClassname.set(true)
    generateBuilders.set(true)
    useLongIntegers.set(true)
    targetDirectoryPrefix.set(File("src/generated/java"))
    source.setFrom(files("src/main/resources/schemas/json"))
    sourceType.set("yamlschema")
    useBigDecimals.set(true)
    includeToString.set(false)
    formatDateTimes.set(true)
    customAnnotator.set("com.data.core.annotator.XDataAnnotator")
}
```

Since module dependencies are not allowed in the classpath dependencies this makes working on the project as a whole a bit cumbersome.
If there is a more streamlined way of doing this I would appreciate the advise.

**Comment by adispennette** [comment]
Are there any future plans for an update that would remove the build class path requirement?

**Comment by almogtavor** [comment]
@joelittlejohn @adispennette can you add this case to the examples of the repo? I've couldn't manage to do this at all (while it was quite easy to succeed this with Maven)

**Comment by qigao** [comment]
inspired by comments from @adispennette and @joelittlejohn  , i found that it's not necessary to publish your artifacts, what you should do is using your module file.
sharing my gradle for  the customannotator :

```
buildscript {
    dependencies {
        classpath(vLibs.swagger.annotations.get()) //what ever your annotation used should be referred by classpath
        classpath files(project(":json-schema-annotation").jar.outputs.files.getFiles())
    }
}
dependencies {
    implementation vLibs.swagger.annotations
    implementation project(":json-schema-annotation")
}
}```

**Comment by almogtavor** [comment]
@joelittlejohn the example is still very unclear (what is `vLib.swagger.annotations` and how does it have a `.get()` method?

This issue needs to be open until the solution will be added to the example. Custom annotations are still unusable with Gradle.

**Comment by qigao** [comment]
> @joelittlejohn the example of @qigao is still very unclear (what is `vLib.swagger.annotations` and how does it have a `.get()` method?
> 
> This issue needs to be open until the solution will be added to the example. Custom annotations are still unusable with Gradle.

hello @almogtavor ,
 sorry for the confusion, this vLibs.swagger.annotations  means the library(swagger-annotation) used in my gradle file. here  is what it looks like from the toml:
 **swagger-annotations = { group = 'io.swagger.core.v3', name = 'swagger-annotations', version = '2.2.0' }**

I put libs info into a  toml file, which i believe will make my gradle more simple when sharing a lib in multi module project.

of course ,you can use it in the plain form: classpath 'io.swagger.core.v3:swagger-annotations:2.2.0'

**Comment by almogtavor** [comment]
@qigao thanks for the explanations. @joelittlejohn This one still isn't on the docs, therefore people will keep getting this error
