### ISSUE TITLE
Using org.javatuples for JSON-schema-arrays with elements of different types

### ISSUE THREAD

**Issue by maikwoehl** [joelittlejohn/jsonschema2pojo#1282]
Hello and greatings from Germany,

I'm using your jsonschema2pojo-maven-plugin to create the POJOs for a schema, that is defined as an array with different types as elements. In the documentation it is written, that the generator only supports List or Set as typed Collections for that.

As I have a valid json schema with an array and different types as elements I can't use your plugin to generate a POJO for that schema. It is possible to use the org.javatuples package to provide support for that case?

An example of my schema is:

```json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "$id":"/",
   "comment":"",
   "title":"MessageStructure",
   "type":"array",
   "description":"",
   "items":[
      {
         "type":"integer",
         "description":"This type represents the message type.",
         "enum":[
            1,
            2,
            3
         ]
      },
      {
         "type":"string",
         "description":"This type represents the source of the data of the message."
      },
      {
		 "description": "This type represents an unique identifier for the presystemId according to RFC3986.",
		 "type": "string",
		 "format": "uri"
	  },
      {
         "type":"string",
         "description":"This type represents the current timestamp of the message.",
         "format":"date-time"
      },
      {
         "type":"string",
         "description":"This type represents the unique identifier of the message.",
         "format":"uuid"
      },
      {
         "type":"string",
         "description":"This type represents the action of the message.",
         "enum":[
            "BootNotification",
            "ProvideChargingRequests",
            "ProvideChargingInformation"
         ]
      },
      {
         "type":"object",
         "description":"This type represents the payload of the message which is specified in separate JSON schemas."
      }
   ],
   "minItems":7,
   "maxItems":7
}
```

I'm awaiting the response of the community to this request.

Regards,

Maik Wöhl

**Comment by unkish** [comment]
Hi

Could you please elaborate as to what (class it's structure and relation to `org.javatuples`) would you expect to get generated for given schema?

**Comment by maikwoehl** [comment]
As org.javatuples can only support up to 10 elements, I would have something like that in mind for building that code:

```java
import org.javatuples.*;

public class JSONSchemaTuple {
    private ArrayList<String> tupleTypes;

    public JSONSchemaTuple(JSONObject schema) {
        if (schema["type"] == "array") {
            if (hasDifferentTypes(schema) && schema["items"].size() <= 10) {
                switch (schema["items"].size()) {
                /* ... */
                case 3:
                    ArrayList<String> types = readTypes(schema["items"]);
                    tupleTypes = mapToJavaPrimitivesAndLeaveComplex(types);
                /* ... */
                }
            }
        }
    }

    @Override
    public String toString() {
        if (tupleTypes.size() == 1) {
            return "Unit<" + tupleTypes.get(0) + ">";
        } /* ... */
        else if (tupleTypes.size() == 3) {
            return "Triplet<" + tupleTypes.get(0) + ", " + tupleTypes.get(1) + ", " + tupleTypes.get(1) + ">"; 
        } /* ... */
        
    }
}
```

And for the result I would propose something like that: 

```java
public class SchemaName<T> {
    private Septet<int, string, URI, Date, UUID, Element6Enum, T> tuple;

    public SchemaName(int item1, string item2, URI item3, Date item4, UUID item5, Element6Enum item6, T item7) {
        tuple = Septet.with(item1, item2, item3, item4, item5, item6);
    }

    public Septet<int, string, URI, Date, UUID, Element6Enum, T> getTuple() {
        return tuple;
    }
}
```

maxItems would select the right tuple and minItems would ensure that the constructor variants don't fall below the defined number of elements start counting with 0 for the first element in schema.

**Comment by joelittlejohn** [comment]
I don't think Jackson (or other libraries we support like GSON) can serialize or deserialize these correctly though, is that right? It's hard for us to create types that have entirely bespoke serialization and deserialization. Do you have a solution you're using for that right now?

**Comment by maikwoehl** [comment]
We have created a class that is removing the quotation marks and the [] from the JSON and splits it at the commas for now. We will get in trouble as soon as the payload contains comma values in free-text strings... 

Probably we will change the deserialization to first removing the substring of the payload by getting the data from first ,{ to end of the data. And then splitting it up by the commas.

But you're right, I see now, it is a really bespoke class we have written here.

Technically it would be possible to write a deserialization algorithm that is first stripping the object types one by one from the string by searching for ,{ to }, or }] (maintain nesting with counting opening and closing brackets) and then getting the integers and strings from the rest. 

I will try to implement a class doing that deserialization. That would solve the deserialization problem for every instance of a array-type json collection with elements of different types, I think.

The serialization we have done with concatening the integers, strings and objects together, because our object is not serializable yet as the payload can be multiple different class instances and we do some relationship checks and whatnot. Not really clean at the moment...

**Comment by joelittlejohn** [comment]
Adding some useful links:

* https://github.com/javatuples/javatuples/issues/3
* https://github.com/FasterXML/jackson-databind/issues/2020
* https://stackoverflow.com/a/32916203/125825

**Comment by maikwoehl** [comment]
Ah thank you. I've jumped from embedded systems into business development and I'm impressed constantly how elegant many things are with almost unlimited memory resources.

I will try to dig into that in the next weeks. I will come back by the 1st of August and present a status. I have to work me into the code of Jackson if I really want to present a usable class for the public, I think.

**Comment by maikwoehl** [comment]
Unfortunately I did not had the time to work on that topic. There are project deadlines to meet... 

But I will post here again, as we continue our work on the tuple de/serializers.

**Comment by maikwoehl** [comment]
By today I've got one step forward. I'm working on a type that uses the Java Reflection API to decouple the member names from the getter through annotations.

That is needed to have a universal interface for the de/serialization. I want to deserialize into a generic type, that has no member names, as we don't know the names with the array defined by the json schema above.

The ObjectContainer would be used like this:

```java
import java.io.Serializable;
import java.util.LinkedList;

public class MessageStructure extends ObjectContainer implements Serializable {
	private static final long serialVersionUID = -2579921802313002387L;
	
	@Item
	private Integer messageType;
	@Item
	private String messageSource;
	@Item
	private String messageURI;
	@Item
	private String messageDateTime;
	@Item
	private String messageUUID;
	@Item
	private String messageAction;
	@Item
	private Object messagePayload;
	
	// TODO: Use Item annotation to get a list of FieldNames from Reflection API.
	@SuppressWarnings("serial")
	private static final LinkedList<String> mappings = new LinkedList<String>() {{
		add("messageType");
		add("messageSource");
		add("messageURI");
		add("messageDateTime");
		add("messageUUID");
		add("messageAction");
		add("messagePayload");
	}};

	public MessageStructure(Integer messageType, String messageSource, String messageURI, String messageDateTime, String messageUUID, String messageAction,
			Object messagePayload) {
		super(mappings, messageType, messageSource, messageURI, messageDateTime, messageUUID, messageAction, messagePayload);
		// TODO Auto-generated constructor stub
	}

	@MemberName("messageType")
	public Integer getMessageType() {
		return (Integer) invokeMethod();
	}
}
```

The Item annotation would help generating a list automatically by instantiation of the object.

Currently I'm using six generic named fields and getters in the ObjectContainer, but I will try to store the objects into a LinkedList and index them with the internal mapping. 

The invokeMethod searches the generic getter mapped to the method and executes it. If an internal LinkedList would be possible,  I would just maintain a LinkedList with the object references passed by instantiation and index them directly without searching a generic getter. 

Just to give a hint to the inner workings:

```java
MessageStructure message = new MessageStructure(2020, null, null, null, null, null, null);
System.out.println(message.getMessageType().toString());
```

```
MethodName: getMessageType
Scope class: de.maikwoehl.tuple_serde.MessageStructure
Parent class: de.maikwoehl.tuple_serde.ObjectContainer
Caller: getMessageType
MemberName: messageType
Getter: getItem0
Methods in base: 
 - invokeMethod
 - getIndexNameFromMappings
 - getGetterNameOfMember
 - invokeMethodUnsafe
 - getItem0
Execute: getItem0
2020
```

After I have that container I can work on the deserialization and map whatever fields I get to any number (maybe limited?) of generic getters through a LinkedList or fixed generic getters. 

The end user can then define its wrapper class with semantic meaning around the container and use it's own getters. 

In jsonschema we have types and positions. So we could really generate source code that specialize the container with the types and positions. Unfortunately the title argument would [not validate in items which are not strings](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.7.7.1.2). So we could go here with generic itemX names and let the end user redefine the fields. 

So the following schema:

```json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "$id":"/",
   "comment":"",
   "title":"MessageStructure",
   "type":"array",
   "description":"",
   "items":[
      {
         "type":"integer",
         "description":"This type represents the message type.",
         "enum":[
            1,
            2,
            3
         ]
      },
      {
         "type":"string",
         "description":"This type represents the source of the data of the message."
      }
   ],
   "minItems":2,
   "maxItems":2
}
```
Would be generated as: 

```java
import java.io.Serializable;
import java.util.LinkedList;

public class MessageStructure extends ObjectContainer implements Serializable {
	private static final long serialVersionUID = -2579921802313002387L;
	
	@Item
	private Integer item0;
	@Item
	private String item1;
	
	// TODO: Use Item annotation to get a list of FieldNames from Reflection API.
	@SuppressWarnings("serial")
	private static final LinkedList<String> mappings = new LinkedList<String>() {{
		add("item0");
		add("item1");
	}};

	public MessageStructure(Integer item0, String item1) {
		super(mappings, item0, item1);
		// TODO Auto-generated constructor stub
	}
}
```

And the end user can now rename the fields or directly create its getters:

```java
@MemberName("item0")
public Integer getMessageType() {
    return (Integer) invokeMethod();
}

@MemberName("item1")
public String getMessageSource() {
    return (Integer) invokeMethod();
}
```

**Comment by maikwoehl** [comment]
I've published the type to https://github.com/maikwoehl/tuple_serde 
As a next step I have to write a ser/de for jackson or some own... I will see.

**Comment by joelittlejohn** [comment]
This is an interesting investigation @maikwoehl and I'm sure others will come across this and find it useful. I'm going to close this ticket because I don't think we will progress it in the core.
