### ISSUE TITLE
 Within Java project  can't find output file

### ISSUE THREAD

**Issue by zzhengyang** [joelittlejohn/jsonschema2pojo#1289]
When I run this demo

    public static void main(String[] args) throws IOException {

        // BEGIN EXAMPLE

        JCodeModel codeModel = new JCodeModel();

        URL source = Example.class.getResource("/schema/required.json");

        GenerationConfig config = new DefaultGenerationConfig() {
            @Override
            public boolean isGenerateBuilders() { // set config option by overriding method
                return true;
            }
        };

        SchemaMapper mapper = new SchemaMapper(new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore()), new SchemaGenerator());
        mapper.generate(codeModel, "ClassName", "com.youku.video.util", source);

        codeModel.build(Files.createTempDirectory("required").toFile());

        // END EXAMPLE

    }

OUTPUT:

`com/youku/video/util/Required.java`
 
But I can't find the output file.

**Comment by unkish** [comment]
Hi

Have you looked in tmp dir ?
Perhaps changing
```
    codeModel.build(Files.createTempDirectory("required").toFile());
```
to 
```
      File tmpDir = Files.createTempDirectory("required").toFile();
      codeModel.build(tmpDir);
      System.out.println("Output generated to: " + tmpDir);
```
would help to get temporary directory that output was generated to
