### ISSUE TITLE
"$ref" not working with custom object "array"

### ISSUE THREAD

**Issue by Anuj28282828** [joelittlejohn/jsonschema2pojo#1294]
{
 properties : {
  cars : {
   children : {
     type: array,
     items: {
      ref : Test.json
     }
    }
  }
 }
}

Here I want a List<Test> cars.
But its not working.
What am I missing

**Comment by joelittlejohn** [comment]
Not sure what is in Test.json, but you need to remove the 'children' level, or put it inside a 'properties'.
