### ISSUE TITLE
How to update the local repo to include changes made to core class in the maven build

### ISSUE THREAD

**Issue by adbdkb** [joelittlejohn/jsonschema2pojo#1305]
Hi, @unkish / @joelittlejohn - 

This question is related to answer of How to get value of key when using jsonschema2pojo custom annotator on a input type of JSON #1259

I used the code example and did the steps that @unkish recommended below

================
At present there's no possibility to pass/configure schema generator
Easiest way would be

1. to fork given project and make necessary changes ie.: example
2. Note that instead of @ApiModelProperty example values are put inside @SuppressWarnings
3. run smth. like mvn package -pl jsonschema2pojo-cli -am (you might want to change project version/classifier/...)
4. cd jsonschema2pojo-cli\target
5. java -cp "jsonschema2pojo-cli-1.1.2-SNAPSHOT.jar;lib\*" org.jsonschema2pojo.cli.Jsonschema2PojoCLI -a JACKSON2 -305 -dtt java.time.LocalDateTime -T JSON -s C:\json_test\input.json -t C:\json_test\output

What I am trying to figure out is instead of making these changes / sharing the changed classes with each team member separately, I would like to use it from a maven POM.

Is it possible and how do I do that?  Or do we have to use the command-line approach only

Currently we use the below tags

        <groupId>org.jsonschema2pojo</groupId>
        <artifactId>jsonschema2pojo-maven-plugin</artifactId>
        <version>1.1.1</version>

in the POM plugin.

Thanks

**Comment by unkish** [comment]
Hi

> Is it possible and how do I do that? 

Given question is not related to `jsonschema2pojo` project, it's about releasing/publishing maven artifacts.
Answer to the question would be yes, however specifics of it may depend on various "variables" such as for example policies of the company you're working in & etc.
 
Here are some links on given topic:
- https://stackoverflow.com/questions/12069546/how-to-properly-fork-a-maven-project/18451807
- https://stackoverflow.com/questions/10415550/what-version-label-to-use-for-a-forked-maven-project
- https://www.reddit.com/r/java/comments/2oadan/how_to_host_a_forked_maven_projects_artifacts/
