### ISSUE TITLE
Request: Define enums inside enclosing object

### ISSUE THREAD

**Issue by evanbross** [joelittlejohn/jsonschema2pojo#1325]
I am working with a large schema supplied by a 3rd party and many of the objects have enums.
Many of the enums all have the same name.
Instead of creating enums in their own files it would be great if there was an option to have them be embedded within their containing POJO.

**Comment by eirnym** [comment]
Hi, 

may I ask how do you construct the super-schema if objects have the same name? Or there's enums defined inside a properties, where properties have the same name. 

Could you share a minimalist working example for the issue

**Comment by evanbross** [comment]
It's the latter situation. The schema is about the requests and responses
of communication packets. Each message is in its own json file (128 of
them). The enum definitions are each embedded within the message
definition, but they get generated as individual java files instead of
being subclasses inside the message pojo.

Since it's a protocol defined by a standards organization changing the json
files isn't really an option for me.

Here's a quick sample of what I'm dealing with:

{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "urn:OCPP:Cp:2:2020:3:NotifyChargingLimitRequest",
  "comment": "OCPP 2.0.1 FINAL",
  "definitions": {
    "CustomDataType": {
      "description": "This class does not get 'AdditionalProperties =
false' in the schema generation, so it can be extended with arbitrary JSON
properties to allow adding custom data.",
      "javaType": "CustomData",
      "type": "object",
      "properties": {
        "vendorId": {
          "type": "string",
          "maxLength": 255
        }
      },
      "required": [
        "vendorId"
      ]
    },
    "ChargingLimitSourceEnumType": {
      "description": "Charging_ Limit. Charging_ Limit_ Source. Charging_
Limit_ Source_ Code\r\nurn:x-enexis:ecdm:uid:1:570845\r\nRepresents the
source of the charging limit.\r\n",
      "javaType": "ChargingLimitSourceEnum",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "EMS",
        "Other",
        "SO",
        "CSO"
      ]
    },
    "ChargingRateUnitEnumType": {
      "description": "Charging_ Schedule. Charging_ Rate_ Unit. Charging_
Rate_ Unit_ Code\r\nurn:x-oca:ocpp:uid:1:569238\r\nThe unit of measure
Limit is expressed in.\r\n",
      "javaType": "ChargingRateUnitEnum",
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "W",
        "A"
      ]
    },

**Comment by joelittlejohn** [comment]
Enums are already generated inside the enclosing type by default (see the request #1002). The reason you see them generated outside as a separate type is that you are using `javaType` with the enums. If you want to leave the enum inside the enclosing class but customise the name of the enum, you should ask whoever wrote this schema to use `javaName` instead.
