### ISSUE TITLE
Integer Enum Generating as String

### ISSUE THREAD

**Issue by wendycameronsend** [joelittlejohn/jsonschema2pojo#1335]
So the following is the jsonSchema definition

"TextDecorationType": {
      "title": "TextDecorationType",
      "description": " Defines the type of the text decoration. None:0,Underline:1,LineThrough:2,Overline:3.",
      "enum": [
        0,
        1,
        2,
        3
      ]
    }

What comes out is:
@Generated("jsonschema2pojo")
    public enum TextDecorationType {

        _0("0"),
        _1("1"),
        _2("2"),
        _3("3");
        private final String value;
        private final static Map<String, Style.TextDecorationType> CONSTANTS = new HashMap<String, Style.TextDecorationType>();

        static {
            for (Style.TextDecorationType c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        TextDecorationType(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        @JsonValue
        public String value() {
            return this.value;
        }

        @JsonCreator
        public static Style.TextDecorationType fromValue(String value) {
            Style.TextDecorationType constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

Which assumes all of the enum values are Strings this is not correct it should generate the fromValue with integer type.

The incoming json is:
"textDecoration": 0,

Which is json integer type

**Comment by wendycameronsend** [comment]
I thing that something like the following needs to also be generated

public static MyEnum forCode(int code) {
       for (MyEnum element : values()) {
          if (element.code == code) {
             return element;
          }
      }
      return null; //or throw exception if you like...
   }

Its problematic to add this as the code is generated

**Comment by unkish** [comment]
@wendycameronsend 

I believe that `type` definition eg: `"type": "integer"` is missing in provided example
Following snippet
```
{
  "title": "TextDecorationType",
  "description": " Defines the type of the text decoration. None:0,Underline:1,LineThrough:2,Overline:3.",
  "type": "integer",
  "enum": [
    0,
    1,
    2,
    3
  ]
}
```

would yield:
```
@Generated("jsonschema2pojo")
public enum TextDecorationType {

    _0(0),
    _1(1),
    _2(2),
    _3(3);
    private final Integer value;
    private final static Map<Integer, TextDecorationType> CONSTANTS = new HashMap<Integer, TextDecorationType>();

    static {
        for (TextDecorationType c: values()) {
            CONSTANTS.put(c.value, c);
        }
    }

    TextDecorationType(Integer value) {
        this.value = value;
    }

    @JsonValue
    public Integer value() {
        return this.value;
    }

    @JsonCreator
    public static TextDecorationType fromValue(Integer value) {
        TextDecorationType constant = CONSTANTS.get(value);
        if (constant == null) {
            throw new IllegalArgumentException((value +""));
        } else {
            return constant;
        }
    }

}
```
