### ISSUE TITLE
[Q] oneOf with null value generates unexpected property Type

### ISSUE THREAD

**Issue by marceloverdijk** [joelittlejohn/jsonschema2pojo#1336]
I have a json-schema part like:

```
"permanentNumber": {
  "oneOf": [
    {
      "type": "string",
      "minLength": 1,
      "maxLength": 2,
      "pattern": "^[0-9]{1,2}$"
    },
    {
      "type": "null"
    }
  ],
  "description": "The permanent number."
}
```

It uses the `oneOf` to either support an actual value or `null` (as the property is required in the schema).
So below cases are both valid:

```
{
  "permanentNumber": "33"
}

{
  "permanentNumber": null
}
```

Now jsonschema2pojo generates the property as an `Object` where I want it to be a `String`:

```
@JsonProperty("permanentNumber")
@JsonPropertyDescription("The permanent number.")
@NotNull
public Object permanentNumber;
```

Does this make sense and is there a way to generate a `String` instead?

**Comment by marceloverdijk** [comment]
I changed the schema to 

```
"permanentNumber": {
  "type": ["string", "null"],
  "minLength": 1,
  "maxLength": 2,
  "pattern": "^[0-9]{1,2}$",
  "description": "The permanent number."
}
```

which does seem to do the trick.

**Comment by joelittlejohn** [comment]
This project doesn't support oneOf I'm afraid. We have a simple fallback where if we see a union type like `["string", "null"]` we will take the first schema as the type, which allows for most use-cases where you are just using a union to express something optional.
