### ISSUE TITLE
What are the supported JSON Schema versions?

### ISSUE THREAD

**Issue by sergeykad** [joelittlejohn/jsonschema2pojo#1339]
Should I assume that all versions are supported?

**Comment by jamietanna** [comment]
Looking at the soure code (`git grep json-schema.org`) I've seen `draft-04` and `draft-07` explicitly tested with.

I've attempted to use `draft/2019-09` and a `$recursiveRef` and it is ignored, replacing the type with an `Object` in the generated code

**Comment by joelittlejohn** [comment]
This tool doesn't really have a specific draft level supported. We attempt to support as many keywords as possible, and the full list is here:

https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference
