### ISSUE TITLE
90% Question / 10% Issue: Modify field in generated class

### ISSUE THREAD

**Issue by three-old-coders** [joelittlejohn/jsonschema2pojo#1352]
I have a json schema with one field defined as String.
Unfortunately it contains a "," separated list of String and I want to reflect the change in the generated class.
So instead of having a String field I would prefer an String[].

I managed to add custom annotations (via customAnnotator property in my pom.xml and a CustomAnnotatorClass) to the generated class, but this is just used by Jackson later when deserialising not on class generation time. How can I change the type of a particular property in the generated classes?

See Example: @JsonDeserialize is added by the customAnnotator, so the generated part of the class is:

@JsonProperty("Value")
@JsonDeserialize(contentConverter = Deserializer_Value_ContentConverter.class)
private String value;

I would like to have:
@JsonDeserialize(contentConverter = Deserializer_Value_ContentConverter.class)
private String[] values;

Thanks in advance

Jens

**Comment by unkish** [comment]
Hi

Similarly to custom annotator (`--custom-annotator`) it should be possible to define custom rule factory (`--custom-rule-factory`) which would be responsible for providing factory/creation methods for the code generation rules

**Comment by joelittlejohn** [comment]
Yes agreed. For this kind of custom code output it's necessary to implement a custom property rule.
