### ISSUE TITLE
Support for schema draft 2020-12

### ISSUE THREAD

**Issue by TouDick** [joelittlejohn/jsonschema2pojo#1357]
Generating the POJOs from JSON schema with "$schema": "https://json-schema.org/draft/2020-12/schema" fails with message "There's a problem: Unexpected character ('}' (code 125)): was expecting double-quote to start field name (line 141, column 5)".
As observed it fails just for second object defined within "definitions" section.
Example JSON Schema file:
```{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "Data",
 "description": "Issue example",
 "type": "object",
 "properties": {
    "AAA": {
      "$ref": "#/definitions/AAA"
    },
    "complaintLetter": {
      "$ref": "#/definitions/BBB"
    },
 },
 "required": [
    "AAA",
    "BBB",
 ],
 "definitions": {
   "AAA": {
     "type": "object",
     "properties": {
        "commentText": {
          "type": "string",
          "description": "Free comment field."
        }
     },
     "required": [
        "commentText"
     ],
   },
   "BBB": {
     "type": "object",
     "properties": {
        "documentId": {
          "type": "string",
          "description": "Internal ID"
        }
     },
     "required": [
        "documentId"
     ],
   }
 }
}
```

**Comment by unkish** [comment]
Hi

I don't think it has anything to do with schema draft 2020-12, please see reply about supported schema versions: https://github.com/joelittlejohn/jsonschema2pojo/issues/1339#issuecomment-997184242
It looks however that there are superfluous commas (`,`) in schema provided, POJOs were successfully generated with following schema (with removed superfluous `,`)
```
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "Data",
 "description": "Issue example",
 "type": "object",
 "properties": {
    "AAA": {
      "$ref": "#/definitions/AAA"
    },
    "complaintLetter": {
      "$ref": "#/definitions/BBB"
    }
 },
 "required": [
    "AAA",
    "BBB"
 ],
 "definitions": {
   "AAA": {
     "type": "object",
     "properties": {
        "commentText": {
          "type": "string",
          "description": "Free comment field."
        }
     },
     "required": [
        "commentText"
     ]
   },
   "BBB": {
     "type": "object",
     "properties": {
        "documentId": {
          "type": "string",
          "description": "Internal ID"
        }
     },
     "required": [
        "documentId"
     ]
   }
 }
}
```

**Comment by eirnym** [comment]
Side note: since schema 2019 `definitions` has been renamed to `$defs`

**Comment by TouDick** [comment]
@unkish you are my hero :D
I've checked the original file so many times and missed the few commas. Schema is generated since always with plugin from a diagram, looks like the plugin has to be fixed then.
On the other hand, can we make that great tool more forgiving? Multiple validators/generators have anyway worked with the file (however are not so great like jsonschema2pojo ;) ).

**Comment by eirnym** [comment]
@TouDick json doesn't contain training commas per official specifications. I found more often to use yaml version of schema because of this
