### ISSUE TITLE
$ref along with # - Can that be used to refer to a property of another JSON file?

### ISSUE THREAD

**Issue by Anuj28282828** [joelittlejohn/jsonschema2pojo#1359]
Can I use something like below :

{
    "child1":{
        "$ref":"#another.json/properties/child2"
    }
}

This is not working for me.

**Comment by joelittlejohn** [comment]
You've made the entire path a fragment. I think you want to use this instead:

another.json#/properties/child2

**Comment by Anuj28282828** [comment]
You are right! this solved the problem. Thanks a lot for the prompt response.
