### ISSUE TITLE
How to create an enum directly and not embedded inside a class?

### ISSUE THREAD

**Issue by Anuj28282828** [joelittlejohn/jsonschema2pojo#1360]

**Comment by Anuj28282828** [comment]
So basically when I do this :
{
    description:
    type:
    properties: {
      myEnums:{
        type:string
        enum:[1,2,3,4]
      }
    }
}

and put this in a file i.e. MyEnum.json
this ultimately makes my enums available as :
MyEnum.MyEnums.1

Can I not have MyEnums.1 directly?

**Comment by unkish** [comment]
Hi

It is possible to have enum generated directly as root, please see [following example](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-integration-tests/src/test/resources/schema/enum/enumAsRoot.json).

```
{
  "description": "Description",
  "javaType": "myEnums",
  "type": "string",
  "enum": [
    1,
    2,
    3
  ]
}
```

**Comment by eirnym** [comment]
@unkish 

Let's say the only field `a`of root object refers to this enum. Then json `{"a": 1}` won't pass a validator as `a` is not string, while  `{"a": "1"}` because it doesn't match enum

**Comment by Anuj28282828** [comment]
thanks @unkish - your comment solved my issues. However should  I keep the thread open for @eirnym 's question and issue?

**Comment by joelittlejohn** [comment]
You just have a problem in your schema and nothing can satisfy it right now, but it's not important to the question of 'enum as root'. Check out the examples unkish linked to. You want type: integer if you have integers in the enum.
