### ISSUE TITLE
@Generated annotation generator ignores target Java version

### ISSUE THREAD

**Issue by eirnym** [joelittlejohn/jsonschema2pojo#1361]
When use jsonschema2pojo generator with **runtime** java version 9+ it's impossible to generate classes for older versions of java, even target version is set to 1.7 or 1.8. 

It's quite unfortunate for our project (which uses java 11+) to use detached module only to publish models compatible with java 1.8

Both maven and gradle generators are affected.

**Comment by jrevillard** [comment]
Same issue here indeed

**Comment by XN137** [comment]
same issue here since we are building on java 11 but target java 8
i'd agree that `targetVersion` should be considered when deciding which `@Generated` annotation to use

i could potentially provide a PR if there is agreement on the suggestion

**Comment by drekbour** [comment]
+1 `targetVersion` is an explicit command from the developer to ignore the runtime and "do what I say not what I do"
