### ISSUE TITLE
Generated classes don't use diamond <> operator

### ISSUE THREAD

**Issue by Fuzzo** [joelittlejohn/jsonschema2pojo#1375]
Generated code looks like:
`private Map<String, Object> additionalProperties = new HashMap<String, Object>();`
but should produce the following:
`private Map<String, Object> additionalProperties = new HashMap<>();`
because the types in the constructor are redundant.

**Comment by unkish** [comment]
Hi

It's not as straightforward as it seems.

1. Diamond operator was introduced in Java 1.7, however generator still supports generating Java 6 compatible source code (see [DynamicPropertiesRule](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DynamicPropertiesRule.java#L116-L121))
2. At present source is being produced by [`com.sun.codemodel`](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/pom.xml#L347-L351) library which is not "diamond operator aware"

Given the above adding support for diamond operator would require either a lot of effort or dropping support for generating Java 6 sources.
