### ISSUE TITLE
Java Integer, Long, BigInteger or BigDecimal generation from NUMBER(X,Y) JSON Schema type based on X and Y

### ISSUE THREAD

**Issue by ondrejlerch** [joelittlejohn/jsonschema2pojo#1377]
Currently `jsonschema2pojo` always generates Java `BigDecimal` for `NUMBER(X,Y)` type JSON Schema even if `Y=0`.

We suggest following more fine-tuned generation of Java types for `NUMBER(X,Y)`:
* For `NUMBER(X,0)` where `X <= 9` generate Java `Integer`
* For `NUMBER(X,0)` where `X >= 10` and X <= 18 generate Java `Long`
* For `NUMBER(X,0)` where `X >= 19` generate Java `BigInteger`
* For `NUMBER(X,Y)` where `Y != 0` generate Java `BigDecimal`

PS: We have JSON schema from third party with lots of `NUMBER(X,0)` definitions and we were not able to persuade them to use `integer`. This results in lots of Java `BigDecimal` in our code with redundant conversions there and back which makes us unhappy.

Many thanks!

**Comment by eirnym** [comment]
Hi @ondrejlerch 

Could you please provide an example Json Schema with version number to see what you want to achieve?

**Comment by marcelmatula** [comment]
Hi @eirnym 

I am @ondrejlerch  coworker. Here is an example (note that, you have to rename "txt" to "json", since json ext was not allowed to be attached as file)

[SimpleTypes.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/8047901/SimpleTypes.txt)
[TestListRes_v1.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/8047902/TestListRes_v1.txt)

as you can see there is a "number" type with "multipleOf": 1.0 - which indicates that it will be "whole number" in java long or int.

So general rules could be:
If "multipleOf" is real number or is not defined or both min/max are not defined -> generate BigDecimal
If "multipleOf" is any whole number -> generate Long, long, Integer, int or BigInteger based on  minimum/maximum/exclusiveMinimun/exclusiveMaximum and optionality

Optionality Long vs long, Integer vs int:
if property is mandatory -> generate java int/long
if property is optional -> generate java Integer/Long

for picking Long/long vs Integer/int vs BigInteger use Long.MIN/MAX, Integer.MIN/MAX

Thanks

**Comment by eirnym** [comment]
"number" type in json schema by definition means it's decimal (float, double and BigDecimal)

If you want integers (int or long in Java), "integer" type is for disposition.

**Comment by marcelmatula** [comment]
@eirnym that's not correct. Look here - https://json-schema.org/understanding-json-schema/reference/numeric.html#number

"The number type is used for any numeric type, either integers or floating point numbers."

**Comment by joelittlejohn** [comment]
@marcelmatula The less magic we have in defining how these types should be generated the better. This idea of using int/long for number when `multipleOf` is a whole number is interesting but this really isn't how you are supposed to represent whole numbers. Yes type 'number' allows for any number, but if you *require* that a number is an integer then you should use `"type": "integer"`. 

I appreciate this would be useful for you. However I think more people would be annoyed by this as would be pleased by it, and I feel it's an odd choice to change the type. I'm going to close this as it isn't really something I'm interested to add into jsonschema2pojo.

**Comment by marcelmatula** [comment]
@eirnym It is not magic at all but best practice - do maximum checks and validations at compile time (not runtime).
Your current generator generates too broader java types by ignoring "multipleOf" and "min.max" setting at scheme - which makes possible to create invalid objects and putting burden to consumer to do additional/not necessary runtime validation and making customer code more complex/messy and polluted.

We suggested to do slight improvement and make consumer code less error prone and cleaner. It is not convenient only for our case but for all.

Example.
        "DATATYPE_NUMBER_38_DEFINITION": {
            "type": "number",
            "multipleOf": 1.0,
            "minimum": -99999999999999999999999999999999999999.0,
            "maximum": 99999999999999999999999999999999999999.0
        }

For that you generate BigDecimal but it should be based on schema in fact BigInteger.

Now I can setup your generated object 
yourGeneratedObject.setField(3.14) and there is no issue to compile it even it is definitely invalid state based on schema.

I understand that it is not possible to satisfy all json schema restrictions in generator but we should at least try to be at close as possible.

Also understand that, suggested  improvement should be reasonable incorporated into generator to not break already generated code used by other projects.

**Comment by eirnym** [comment]
Why not to do the same with integer type?

**Comment by eirnym** [comment]
In most cases I met so far you less likely to meet `number` type with simple float and decimal meaning mixed, than in typical usage scenario. Thus I'd suggest to use `existingJavaType` extension field for manual override  or make a custom `RuleFactory` to override the field type in automated way.

**Comment by eirnym** [comment]
Also be very careful providing such huge numbers for constrains, as for most languages in most cases, they will be read as general floats/doubles (depending on a language and a library). It could be important not only for generators but also for libraries validating the input.
