### ISSUE TITLE
Generated code uses Set and does not preserve order of elements in lists

### ISSUE THREAD

**Issue by tomasbjerre** [joelittlejohn/jsonschema2pojo#1384]
# Problem
I use this library to parse sarif report files. The contain a list of artifacts, and a list of violations. The violations refer to the artifacts by index.

Problem is when this library stores the lists as `Set`. Which does not preserve order. And I cannot find the referenced element in the list of artifacts.

The issue I try to solve: https://github.com/tomasbjerre/violations-lib/issues/143

# Solution

Can this library be changed to use `List` instead of `Set`?
Can I use `formatTypeMapping` for this? I tried but did not get it working:

```
  formatTypeMapping = [
    "artifacts": "java.util.List"
  ]
```

And also tried:
```
  formatTypeMapping = [
    "array": "java.util.List"
  ]
```

**Comment by eirnym** [comment]
`LinkedHashSet` used does preserve the order

**Comment by tomasbjerre** [comment]
Great!
