### ISSUE TITLE
How to generate pojo file with jsonInclude at property level 

### ISSUE THREAD

**Issue by DineshSarvey** [joelittlejohn/jsonschema2pojo#1388]
Hi - I have set InclusionLevel as NON_EMPTY in build.gradle and it applies to the whole class.
I want to override this inclusion level for one of the jsons such that it is set to ALWAYS.I do not want to change the inclusion level in build.gradle as it would impact other Pojo files.
How can I override the inclusion level or is there a way that I can generate pojo files with jsonInclude set to ALWAYS at property level rather than class.

**Comment by joelittlejohn** [comment]
Not possible with any addition to the schema or change in configuration I'm afraid. There is one configured inclusion level and this is set whenever JsonInclude is used.

Customisation like this is always possible by writing a custom annotator though. You can then have full control over when and how properties receive a JsonInclude annotation.
