### ISSUE TITLE
Add `builder` method to create a new instance of the builder

### ISSUE THREAD

**Issue by josejulio** [joelittlejohn/jsonschema2pojo#1396]
When using (in the context of the maven builder) `useInnerClassBuilders` and `generateBuilders` set to `true` it would be nice to have a `builder` method to generate a new builder. 

i.e.
Instead of:
```java
new MyGeneratedObject.MyGeneratedObjectBuilder()
    .withFoo("bar")
    .build();
```

Have something like:
```java
MyGeneratedObject.builder()
    .withFoo("bar")
    .build();
```

It could be an opt-in by a new setting e.g. `addBuilderMethodForInnerClassBuilders`.

I'm supposing the same applies for the core, but haven't checked all the details other thant the [BuilderRule](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/BuilderRule.java) file where I suppose it needs to be modified.

**Comment by joelittlejohn** [comment]
No need for a setting for this. We can add the method in a way that does not break existing code, and I agree it would be nice to include it.
