### ISSUE TITLE
Even "patch" version change breaks ABI

### ISSUE THREAD

**Issue by eirnym** [joelittlejohn/jsonschema2pojo#1400]
Project doesn't follow semver or any other standard. Even "patch" version (third number) breaks API

**Comment by joelittlejohn** [comment]
We're missing some vital information here.

**Comment by eirnym** [comment]
You've upgraded your library with minor patch adding a new parameter to an API interface. Thus all applications using previous version of library are not compatible.

If this library follows semver specification, this change makes it at least a minor change. Change for patch version only means, API, ABI and general behavior stay the same, only some internals has been patched (e.g. some dependencies has been updated or some refactoring has been done without changing public API and ABI).

**Comment by joelittlejohn** [comment]
I don't follow semver for this library as so many changes are potentially breaking. Versioning approach is closer to breakver.

But, however, I don't treat every interface defined in this code base as subject to a strict versioning regime (even breakver). If you integrate deeply with interfaces defined here, embed this code within your own, then yes you may see breaking changes on upgrading. We don't split code into an API with strict change control and a private API without, we don't have a public API.

That said, I try not to break APIs that are likely to be used by integrators. I still don't know which API you're referring to.

**Comment by eirnym** [comment]
could you please write backward compatibility policy somewhere? even a short sentence like you wrote here

**Comment by eirnym** [comment]
this was about change in `GenerationConfig`.

**Comment by joelittlejohn** [comment]
Can you be more specific about which change it was? I'm trying to refer back but have been unsuccessful in finding it. It's certainly one of the interfaces I would avoid breaking if possible.

**Comment by eirnym** [comment]
this change was in `GenerationConfig`.

**Comment by joelittlejohn** [comment]
Yes, but what was the change?

**Comment by eirnym** [comment]
You've added an additional parameter. It's enough to break the ABI

**Comment by joelittlejohn** [comment]
To what method? And what was the parameter?

**Comment by eirnym** [comment]
In that interface useJakartaValidation has been added for configuration for JasonSchema2Pojo.generate method. 

For such change I expect minor version changed as per semver specification, not patch. 

Whatever compatibility version policy you have, please, drop this info in top-level documentation. This will signal users of your library how deep to dig into changelog. E.g. for patch version almost nobody reads it.
