### ISSUE TITLE
 exception in thread main java.lang.illegalargumentexception path not present com

### ISSUE THREAD

**Issue by zhuxindong** [joelittlejohn/jsonschema2pojo#1407]
when i use a command line “jsonschema2pojo --source-type JSON --source resource\json --target java-gen --package com.example.types --annotation-style JACKSON2” ;
it throw a exception: 
" exception in thread main java.lang.illegalargumentexception path not present com
at org.jsonschema2pojo.fragmentresolver.resolve(fragmentresolver.java:54)
.....

**Comment by zhuxindong** [comment]
ps: my json file is a trivy scan report file

**Comment by unkish** [comment]
Judging by exception there's a high chance that it's a duplicate of #1404
