### ISSUE TITLE
Annotations @DecimalMin @DecimalMax aren't generated for Float/Double types

### ISSUE THREAD

**Issue by bachu1983** [joelittlejohn/jsonschema2pojo#1418]
Annotations @DecimalMin @DecimalMax aren't generated for Float/Double types however I can add them manually and they work properly.

Schema:
```
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "numberfield": {
        "type": "number",
        "maximum": 90.0,
        "minimum": 0.0
      },
      "integerfield": {
        "type": "integer",
        "maximum": 90,
        "minimum": 0
      }}
    
  }
}
```

Generated POJO class:
```
package com.example;

import javax.annotation.Generated;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({ "numberfield", "integerfield" })
@Generated("jsonschema2pojo")
public class Example {

    @JsonProperty("numberfield")
    public Float numberfield;

    @JsonProperty("integerfield")
    @DecimalMin("0")
    @DecimalMax("90")
    public Integer integerfield;

}
```

**Comment by unkish** [comment]
Hi

I believe it was a deliberate decision, please see comment in [MinimumMaximumRule](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinimumMaximumRule.java#L69-L72) 


Also quote from javadoc(s)[^1][^2][^3][^4]:

>  Note that double and float are not supported due to rounding errors (some providers might provide some approximative support). 

**NB!** Note the text within parenthesis:
_**some** providers **might** provide **some** approximative support_


[^1]: https://docs.oracle.com/javaee/7/api/javax/validation/constraints/DecimalMin.html
[^2]: https://docs.oracle.com/javaee/7/api/javax/validation/constraints/DecimalMax.html
[^3]: https://jakarta.ee/specifications/platform/9.1/apidocs/jakarta/validation/constraints/decimalmin
[^4]: https://jakarta.ee/specifications/platform/9.1/apidocs/jakarta/validation/constraints/decimalmax

**Comment by dstevick14** [comment]
Would it make sense to add a configuration item like "legacyFloat" to allow this if desired?
