### ISSUE TITLE
missing Java code generation

### ISSUE THREAD

**Issue by Markus-Elfring** [joelittlejohn/jsonschema2pojo#1419]
I am trying the current software release out.

```
Markus_Elfring@…:~/Downloads/Freeware/jsonschema2pojo-1.1.2/bin> sh jsonschema2pojo -s ~/Test/JSON/Schemas/GTIN-simple-Schema1.json -t ~/Bau/JSON/Schemas/GTIN
```

Now I wonder why I do not see that desired Java source files were generated in the specified target directory according to my simple JSON schema example.

```JSON
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/GTIN-13",
  "type": "string",
  "pattern": "^[0-9]{13}$"
}
```

:crystal_ball: How should the tool implementation be improved further?

**Comment by unkish** [comment]
Hi

What would be the expected generated output for given schema ?

**Comment by Markus-Elfring** [comment]
:thought_balloon: I would expect that some Java code should be generated for the validation of an input string according to the specified regular expression.
I became curious how the corresponding source code would look like.

**Comment by joelittlejohn** [comment]
This library doesn't perform validation. This is a huge task, and one best left to schema validation libraries.

You might be interested to look at JSR 303 though (or Jakarta validation) as the annotations can be turned on in jsonschema2pojo. You can then use a bean validator.

**Comment by Markus-Elfring** [comment]
>This library doesn't perform validation.

I wonder how this feedback fits to the desire for data type safety which should be achieved together with [complete applications of the JSON schema specification (including the usage of patterns)](https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions "Description for the usage of JSON object properties").

:crystal_ball: Will the support evolve any further for the data processing with regular expressions?
