### ISSUE TITLE
Fix questionable error message for the application of a source file name filter

### ISSUE THREAD

**Issue by Markus-Elfring** [joelittlejohn/jsonschema2pojo#1422]
I am trying the current software release out.

```
Markus_Elfring@…:~/Downloads/Freeware/jsonschema2pojo-1.1.2/bin> sh jsonschema2pojo -s ~/Test/JSON/Schemas/*Schema1.json -t ~/Bau/JSON/Schemas
Was passed main parameter '/home/Markus_Elfring/Test/JSON/Schemas/Staffelstufe-reduced-Schema1.json' but no main parameter was defined
Usage: jsonschema2pojo [options]
…
  * -s, --source
       The source file(s) or directory(ies) from which JSON Schema will be read
…
```

How does the shown error message fit to the applied source file name filter according to the presented help information? :thinking:

:crystal_ball: Can affected implementation details be improved further?

**Comment by unkish** [comment]
This seems to be a bug.

It's roughly equivalent to `java -jar jsonschema2pojo-cli-1.1.2.jar -s A.json B.json -t output`

I think that https://github.com/joelittlejohn/jsonschema2pojo/blob/2d55620ac925ff7406f2982a2c37d49a6697cd20/jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java#L60 should have `variableArity = true`

Workaround pass `-s` several times eg:
`java -jar jsonschema2pojo-cli-1.1.2.jar -s A.json +s B.json -t output`
