### ISSUE TITLE
Generated attribute takes first type on types list.

### ISSUE THREAD

**Issue by Jummartinezro** [joelittlejohn/jsonschema2pojo#1425]
Consider the following jsonSchema:
```json
  {
        "type" : "object",
        "properties" : {
            "foo" : {
                "type" : ["boolean", "string","number","integer"]
            }
        }
    }
```

In this case generated attribute `foo` will have as type `Boolean`:

```java
package com.example;

import javax.annotation.Generated;

@Generated("jsonschema2pojo")
public class Example {

public Boolean foo;

}
```

I noticed that, if type is not specified in jsonSchema, foo takes the type `Object`:

```json
  {
        "type" : "object",
        "properties" : {
            "foo" : {
            }
        }
    }
```
Result:

```java
package com.example;

import javax.annotation.Generated;

@Generated("jsonschema2pojo")
public class Example {

public Object foo;

}
```
There's a way of having the last result (without changing the jsonSchema) when a list of types is passed ?

**Comment by Jummartinezro** [comment]
Maybe related to #676 ?

**Comment by eirnym** [comment]
Yes, it's directly related and the answer will be the same

**Comment by joelittlejohn** [comment]
Often people use union types like: `["boolean", null]`, where the result is an optional value. In this case, it's obviously desirable to just take the first item. It would probably be better if use we use the following logic for union types:

1. Remove `null` values.
2. If one value remains, use this as the type; If multiple values remain, use Object as the type.

**Comment by eirnym** [comment]
Logic of taking first type should be changed, as a user can pass `["null", "boolean"]` and should have the same result
