### ISSUE TITLE
useTitleAsClassname ignores character

### ISSUE THREAD

**Issue by Stromner** [joelittlejohn/jsonschema2pojo#1429]
Schema definition:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "myTestClassV1_0",
}
```
This will generate a class with the name **myTestClassV10** instead of **myTestClassV1_0**

**Comment by joelittlejohn** [comment]
This is because of the default 'property word delimiters'. Underscore is assumed to separate words, and is then used to create camel case names.

If you set property word delimiters to only space and hyphen (something like that) then you should see the underscore is retained.

**Comment by Stromner** [comment]
That did it, many thanks :)
