### ISSUE TITLE
CustomAnnotator

### ISSUE THREAD

**Issue by steowens** [joelittlejohn/jsonschema2pojo#143]
I would like to be able to write a custom annotator to enable the addition of Mongo properties by specifying custom mongo information in the json schema.  Is there currently a way to do this?  If not would it be possible to add such a feature to the plugin?  Basically the logic would be:
1. Do everything that the existing plugin does 
2. For specific data types and properties call a custom annotator to read the data in the json schema and apply additional annotations as deemed appropriate to the annotator.

The callbacks should provide the ability to annotate, fields, methods and types with additional annotations based on what is in the Json Schema definition.

**Comment by locofrank** [comment]
"Error:(7, 27) error: package org.jsonschema2pojo does not exist"

Is there an example of how to include a custom annotator in your project?

**Comment by evonsdesigns** [comment]
@locofrank I wrote an [explanation on SO](https://stackoverflow.com/a/48411162/1002222) for getting custom annotator working.
