### ISSUE TITLE
$id of the schema in the generated java class

### ISSUE THREAD

**Issue by mirsilstan** [joelittlejohn/jsonschema2pojo#1447]
Hi, 
Is there a way to populate the $id of the schema that generated a certain java class in the class itself?
It may be useful for various use cases, for example a CloudEvent has a field called dataschema which identified the schema that data adheres to.
Thanks!

**Comment by mirsilstan** [comment]
In the end I used the custom annotator and added the $id as the property of a custom annotation belonging to the generated class.
But it would have been great if the $id could actually be a field of the class itself.

**Comment by unkish** [comment]
Hi

There's an [open PR](https://github.com/joelittlejohn/jsonschema2pojo/pull/1330) for storing id as static member variable

**Comment by TF88641** [comment]
> In the end I used the custom annotator and added the $id as the property of a custom annotation belonging to the generated class. But it would have been great if the $id could actually be a field of the class itself.

Any chance you could share your CustomAnnotator code? The CloudEvent use case is just what I was after for accessing $id...

**Comment by mirsilstan** [comment]
Here it is:

```
public class EventAnnotator extends AbstractAnnotator {
    public void propertyInclusion(JDefinedClass clazz, JsonNode schema) {
        var idField = schema.get("$id");
        if (idField == null) {
            return;
        }

        var idValue = idField.textValue();

        var segments = idValue.split("/");
        var segment = segments[segments.length-1];
        segments = segment.split("\\.");
        segment = segments[0];

        clazz.annotate(Event.class)
                .param( "type", segment)
                .param("dataSchema", idValue);
    }
}
```

And you need to add the following line to the configuration tag of the plugin jsonschema2pojo-maven-plugin
To prevent a chicken and egg problem, the annotator needs to be in another Maven module.

```
<customAnnotator>your.package.name.EventAnnotator</customAnnotator>
```
