### ISSUE TITLE
Generation of POJO field for long JSON type

### ISSUE THREAD

**Issue by alexanderst** [joelittlejohn/jsonschema2pojo#1448]
Hello,
we are using jsonschema2pojo-maven-plugin and have issue with long type in JSON. Field annotated with "type":"long" is converted to Object type of field in resulting POJO, Is it expected to work this way or can we customize it somehow to make it produce Long Java type?
By the way, "type":"int" is working as we expect - Integer is in POJO. 

Thanks.

**Comment by joelittlejohn** [comment]
There is no "long" type in JSON schema, since integers can accommodate large values. I think you want useLongIntegers, or javaType: long.

**Comment by alexanderst** [comment]
Sorry, looks like too basic. And thank you for quick answer, it's working now.
