### ISSUE TITLE
Set All values null 

### ISSUE THREAD

**Issue by SulemanAli303** [joelittlejohn/jsonschema2pojo#1449]
there should be a checkpoint while creating the model if the user checks that point then it should be assigned null values in every property of the model.

**Comment by unkish** [comment]
Hi

There is already [null-collections](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java#L177) (default `false`)/[initializeCollections](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java#L500-L505) (default `true`) flag

**Comment by joelittlejohn** [comment]
@SulemanAli303 did you want all properties, that already have an implicit value null to also be explicitly assigned null?

If so, I'm afraid we won't add this feature. I don't like this style as it's unnecessary additional noise. There's no reason to assign all properties null, they're already null.
