### ISSUE TITLE
Multiple Packages

### ISSUE THREAD

**Issue by steowens** [joelittlejohn/jsonschema2pojo#145]
Is there a way to configure the maven plugin to generate schemas in multiple packages?  For example instead of:

``` xml
<configuration>
   <sourceDirectory>${basedir}/src/main/resources/schema/catalog</sourceDirectory>
   <targetPackage>com.my.domain.catalog</targetPackage>
</configuration>
```

Why cant we have:

``` xml
<configuration>
    <sources>
        <source>
           <directory>${basedir}/src/main/resources/schema/catalog</directory>
           <targetPackage>com.my.domain.catalog</targetPackage>
        </source>
        <source>
           <directory>${basedir}/src/main/resources/schema/auth</directory>
           <targetPackage>com.my.domain.auth</targetPackage>
        </source>
   </sources>
</configuration>
```

**Comment by eallais** [comment]
Have this issue with v0.4.26. Maven plugin seems not generated the package when used in jenkins but worked in local machine. Any ideas?

**Comment by mdnuro** [comment]
Hello,

I'm trying to solve similar problem using gradle jsonschema2pojo 1.0.1 .
 I have two sets of json schemas that need to be generated in two distinct packages. 
 eg : resource:json.abc and resource:json.xyz should generate POJO in packages com.build.abc and com.build.xyz respectively.

To achieve this, we put the json schemas in two different folders eg /json/xyz and json/abc and configure
targetPackage ="com.build".

but when I run gralde command it didn't generate POJO in separate package but rather all POJOs created in default package.

Is there anything I'm missing? any additional configuration needed? please help us with your expertise 

Thanks in advance !

**Comment by joelittlejohn** [comment]
Do the schemas have `javaType` inside them?

**Comment by mithunj43** [comment]
Hello,

Even I am facing same issue mentioned by @mdnuro and I am using Gradle plugin  1.0.1. Seems like this fix/feature is not moved to Gradle plugin. 

@joelittlejohn Since its not generating in proper packages I have added javaType in json schema as work around and its generating in proper packages.

**Comment by gravindran2412** [comment]
Is it possible to create package for a subdirectory inside subdirectory to create a common target Package?
For example:
schema > category1 > typeA > schema_file1
schema > category2 > typeB > schema_file2
schema > category1 > typeB > schema_file3
schema > category2 > typeC > schema_file4

when I tried to give source = files("${sourceSets.main.output.resourcesDir}/schema")
and targetPackage = "com.app"

it generates imports i wrong packages.
