### ISSUE TITLE
Is it possible to add custom annotations on a generated class?

### ISSUE THREAD

**Issue by giovanniberti** [joelittlejohn/jsonschema2pojo#1452]

**Comment by unkish** [comment]
Hi

It's not possible to that with configuration options, there is a [PR ](https://github.com/joelittlejohn/jsonschema2pojo/pull/1394) proposing adding annotations with via configuration options (which has drawbacks/limitations).
There are however several possibilities how that could theoretically be achieved:

- by using/piggyback'ing `customAnnotator` such that would override `public void propertyInclusion(JDefinedClass clazz, JsonNode schema)` or usage of `CompositeAnnotator` (if generating pojo's programmatically).

**NB!** This solution won't annotate `enum`'s
```java
    public class CustomAnnotator extends Jackson2Annotator {

        public CustomAnnotator(GenerationConfig generationConfig) {
            super(generationConfig);
        }

        @Override
        public void propertyInclusion(JDefinedClass clazz, JsonNode schema) {
            // add custom annotations
            clazz.annotate(Deprecated.class);
            // delegate the rest to super class
            super.propertyInclusion(clazz, schema);
        }
    }
```
- by using/providing `customRuleFactory` which would return customized (extended) `ObjectRule` and `EnumRule` capable of adding desired annotations.

**Comment by giovanniberti** [comment]
Thanks! :)
