### ISSUE TITLE
Please add support for allOf

### ISSUE THREAD

**Issue by KangoV** [joelittlejohn/jsonschema2pojo#1459]
I'm trying to use this tool to generate classes for the [OASIS STIX 2.1 schema](https://github.com/oasis-open/cti-stix2-json-schemas). This uses `allOf` everywhere in the schema definitions. Is this something that can be easily achieved?

**Comment by eirnym** [comment]
If it's possible to edit the schema before generation, putting `extends` along `allOf` (with almost the same contents) helped me to generate classes using this tool

**Comment by joelittlejohn** [comment]
Hi Darren. This request has been raised a few times. Feel free to add a vote to #91.

I understand that many schemas use allOf/anyOf/oneOf, but these concepts are not easily translated to Java and make more sense in the context of validation rather than data binding.
