### ISSUE TITLE
Gradle detected problem that can lead to incorrect results being produced

### ISSUE THREAD

**Issue by marceloverdijk** [joelittlejohn/jsonschema2pojo#1462]
I'm using Kotlin (both custom sources and Kotlin Gradle DSL) with jsonschema2pojo.

All seems to be generated as expected but I get this problem from the build execution:

```
> Task :buildSrc:generateJsonSchema2Pojo
Execution optimizations have been disabled for task ':buildSrc:generateJsonSchema2Pojo' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/my-project/buildSrc/build/generated-sources/js2p'. Reason: Task ':buildSrc:compileKotlin' uses this output of task ':buildSrc:generateJsonSchema2Pojo' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

I checked the mentioned link but it does not help.

Is anyone else seeing this , or know what to do?

**Comment by eirnym** [comment]
With current version of gradle plugin from this repo you need to setup dependency by yourself.

**Comment by marceloverdijk** [comment]
@eirnym thx for quick reply, but what do you mean exactly?

**Comment by eirnym** [comment]
I recommend an official gradle [user guide](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html). Usually, plugins do this by themselves, but implementation in this repository doesn't.

**Comment by marceloverdijk** [comment]
But what do you mean with 'setup dependency by yourself'?

I've used this Gradle plugin working a Groovy project without problems..
Now using it with a Kotlin project gives this warning...

**Comment by eirnym** [comment]
Your observations are correct. This is happening due to fact, that Groovy translates to Java and then compile, it has no it's own compilation tasks. While Kotlin has it's own compiler (which can produce not only Java classes)

**Comment by marceloverdijk** [comment]
On SO I found a similar issue here: https://stackoverflow.com/questions/70733770/execution-optimizations-have-been-disabled-for-task-compilegsonviews

Based on that I added the below to my project and the warning/problem is gone now:

```

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    mustRunAfter(tasks.named("generateJsonSchema2Pojo"))
}
```

**Comment by eirnym** [comment]
If this concludes the issue, could it be closed?
