### ISSUE TITLE
Is it possible to ignore unknown enum values in schema json?

### ISSUE THREAD

**Issue by alinagb** [joelittlejohn/jsonschema2pojo#1480]
After a basic enum schema is generated, the enum class has
```
    @JsonCreator
    public static MyEnum fromValue(String value) {
        MyEnum constant = CONSTANTS.get(value);
        if (constant == null) {
            throw new IllegalArgumentException(value);
        } else {
            return constant;
        }
    }
```
And in my case it is possible to pass an unkown value, but the code will throw IllegalArgumentException. I'd like it just to be ignored or having a default value.

Is there any possibility to just ignore unknown values or set a default value in the json schema?
```
 "properties": {
   "myEnum": {
      "type": "array",
       "items": {
            "type": "string",
             "enum": ["one", "two", "three"]
         }
    }
}
```

**Comment by joelittlejohn** [comment]
I think you want this Jackson feature:

DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL

**Comment by joelittlejohn** [comment]
No, I don't think there's any way to express this in a schema. By definition, and enum means 'only these values and no other'.

**Comment by unkish** [comment]
It should be possible to "customize" `EnumRule` behavior by extending/overriding methods in latter and providing instance of it through extended `RuleFactory`:
https://github.com/joelittlejohn/jsonschema2pojo/blob/25bfc76091ed8f1deaac91a6d1f479ec4a3db6ee/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java#L300-L308
