### ISSUE TITLE
jsonSchema2Pojo customAnnotator not working

### ISSUE THREAD

**Issue by jaya-sinha-db** [joelittlejohn/jsonschema2pojo#1488]
Kindly help on the issue below:

Scenario:
I need to include @Document annotation on generated class via jsonschema2pojo plugin.
For that I have the below configs:

1> in build.gradle
inside plugins {
id 'org.jsonschema2pojo'
}

2> all related dependencies added.

3> Its generating the pojo classes.
4> Added below in build.gradle to add @Document on the generated classes
jsonSchema2Pojo {
    includeGeneratedAnnotation = false
    annotationStyle = none
    customAnnotator = 'com.x.y.z.utility.customAnnotation.DocumentAnnotator'
}
Unable to load class 'com.db.chnpipeln.payments.utility.customAnnotation.DocumentAnnotator'.

5> Tried with  DocumentAnnotator class in same project and different project as well.

6> Tried without single quotes:
jsonSchema2Pojo {
    includeGeneratedAnnotation = false
    annotationStyle = none
    customAnnotator = com.x.y.z.utility.customAnnotation.DocumentAnnotator
}
But get error saying:
> Could not get unknown property 'none' for generateBuilders = false
  includeJsonTypeInfoAnnotation = false
  usePrimitives = false
  source = []
  targetDirectory = null
  targetPackage = 
  propertyWordDelimiters = [-,  , _]
  useLongIntegers = false
  useBigIntegers = false
  useDoubleNumbers = true
  useBigDecimals = false
  includeHashcodeAndEquals = true
  includeConstructors = false
  constructorsRequiredPropertiesOnly = false
  includeRequiredPropertiesConstructor = false
  includeAllPropertiesConstructor = true
  includeCopyConstructor = false
  includeToString = true
  toStringExcludes = []
  annotationStyle = jackson
  useTitleAsClassname = false
  inclusionLevel = class org.jsonschema2pojo.InclusionLevel
  customAnnotator = org.jsonschema2pojo.NoopAnnotator
  customRuleFactory = org.jsonschema2pojo.rules.RuleFactory
  includeJsr303Annotations = false
  includeJsr305Annotations = false
  useOptionalForGetters = false
  sourceType = jsonschema
  removeOldOutput = false
  outputEncoding = UTF-8
  useJodaDates = false
  useJodaLocalDates = false
  useJodaLocalTimes = false
  dateTimeType = null
  dateType = null
  timeType = null
  parcelable = false
  serializable = false
  initializeCollections = true
  classNamePrefix = 
  classNameSuffix = 
  fileExtensions = []
  includeGetters = true
  includeSetters = true
  targetVersion = null
  includeDynamicAccessors = false
  includeDynamicGetters = false
  includeDynamicSetters = false
  includeDynamicBuilders = false
  formatDates = false
  formatTimes = false
  formatDateTimes = false
  customDatePattern = null
  customTimePattern = null
  customDateTimePattern = null
  refFragmentPathDelimiters = #/.
  sourceSortOrder = OS
  formatTypeMapping = [:]
  useInnerClassBuilders = false
  includeConstructorPropertiesAnnotation = false
  includeGeneratedAnnotation = false
  useJakartaValidation = false
        of type org.jsonschema2pojo.gradle.JsonSchemaExtension.

Custom Annotator Implementation:
public class DocumentAnnotator extends AbstractAnnotator{

    @Override
    public void propertyField(JFieldVar field, JDefinedClass clazz, String propertyName, JsonNode propertyNode) {
        super.propertyField(field, clazz, propertyName, propertyNode);
        clazz.annotate(Document.class);
    }

**Comment by unkish** [comment]
Hi

My assumption would be that `annotationStyle = "NONE"` should be used.

Tried with following simple project:

- `build.gradle`
```gradle
import com.fasterxml.jackson.databind.JsonNode
import com.sun.codemodel.JDefinedClass
import com.sun.codemodel.JFieldVar
import org.jsonschema2pojo.AbstractAnnotator

class Annotator extends AbstractAnnotator {

    @Override
    void propertyField(JFieldVar field, JDefinedClass clazz, String propertyName, JsonNode propertyNode) {
        super.propertyField(field, clazz, propertyName, propertyNode)
        clazz.annotate(Deprecated.class)
    }
}

plugins {
    id 'java'
    id 'org.jsonschema2pojo' version('1.2.1')
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

jsonSchema2Pojo {
    annotationStyle = "none"
    includeGeneratedAnnotation = false
    customAnnotator = Annotator
    // Note: this is just to reduce generated output to bare minimum
    includeHashcodeAndEquals = false
    includeToString = false
    includeAdditionalProperties = false
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'
    implementation 'org.jsonschema2pojo:jsonschema2pojo-core:1.2.1'
}
```
- `src\main\resources\json\test.json`
```json
{
  "type": "object",
  "properties": {
    "a_property": {
      "type": "string"
    }
  }
}
```

Yielding following result:
```java
@Deprecated
public class Test {

    private String aProperty;

    public String getaProperty() {
        return aProperty;
    }

    public void setaProperty(String aProperty) {
        this.aProperty = aProperty;
    }

}
```

**Comment by joelittlejohn** [comment]
You can embed Java classes directly into the build.gradle?! Nice! :exploding_head:

**Comment by joelittlejohn** [comment]
As unkish mentioned, you want `annotationStyle = "NONE"` not `annotationStyle = none`.
