### ISSUE TITLE
Custom data type generated as object in 1.2.1

### ISSUE THREAD

**Issue by prndrsn** [joelittlejohn/jsonschema2pojo#1495]
I'm not sure if this is a bug introduced with #1456 or if the new behaviour is expected.

We have this schema:

        "Content": {
            "type": [
                "object",
                "string"
            ],
            "additionalProperties": true,
            "description": "Contains the unstructured inventory contents."
        }

This used to generate a Content data type, but is now being generated as Object. Not sure if the new jsonschema2pojo behaviour is correct and we need to adapt, or if this is a fault in the fix for #1456

**Comment by joelittlejohn** [comment]
Yes, I think you're right about this being related to #1456.

How do you support a String value for this field if the value in Java is Content. Do you add a custom ser/deser implementation for this?

**Comment by prndrsn** [comment]
So, this is very very old code and after some internal discussion we have concluded that this was probably a mistake in our original schema declaration that just happened to work because of the old jsonschema2pojo behaviour combined with the fact that the value is actually always Object in our application.

**Comment by joelittlejohn** [comment]
I'm going to tentatively close this one.
