### ISSUE TITLE
jsonschema2pojo does not generate pojo for semi large json schema

### ISSUE THREAD

**Issue by rami-nk** [joelittlejohn/jsonschema2pojo#1500]
When trying to generate a java implementation for a more or less large json schema the tool just generates nothing.
I tried it with these json schemas:
- https://unpkg.com/@camunda/zeebe-element-templates-json-schema@0.5.0/resources/schema.json
- https://github.com/elixir-europe/json-schema-validator/blob/master/examples/schemas/references/very-large-schema.json

Here you can see the generation of nothing: 
![Bildschirm­foto 2023-03-08 um 09 39 23](https://user-images.githubusercontent.com/58343300/223664252-c890f5b7-462c-4694-9919-3a4259211c95.png)

I also tried using the maven plugin, but it also just generates an empty directory inside the target folder.

**Comment by joelittlejohn** [comment]
Hi. The problem here is that the file is not a schema, but is being used as a container for other schemas. In each case, the file itself doesn't represent any type at all and so nothing is generated. See https://github.com/joelittlejohn/jsonschema2pojo/issues/419.

**Comment by rami-nk** [comment]
Ok thanks, I'll look at it again! Would be nice to get any error message tho and not just nothing
