### ISSUE TITLE
Create enum without value

### ISSUE THREAD

**Issue by marialenak** [joelittlejohn/jsonschema2pojo#1502]
When generating an enum through jsonschema2pojo sometimes it's more useful (for serialization and deserialization purposes) to NOT have values. Now the enums are generated like that:

![image](https://user-images.githubusercontent.com/54451561/228206012-342dfa8b-b635-42ce-90de-bc382aaa6b81.png)
![image](https://user-images.githubusercontent.com/54451561/228206509-365b84c3-20c6-4a25-93f5-26a26bc2e43d.png)

Ideally, there should be a field to indicate whether we need values to be generated or not. Generated example following:

![image](https://user-images.githubusercontent.com/54451561/228206960-9a0e62f2-9645-43cb-a218-5fb8c866ed98.png)

**Comment by eirnym** [comment]
Value is used to map between Java and JSON. 

Why do you want to remove it? If value has been removed, how do you imagining mapping between Java and JSON?

**Comment by joelittlejohn** [comment]
@marialenak In this case, I assume you would prefer this:

```java
public enum ExampleStatus {
     AStatus, BStatus, CStatus;
}
``` 

Is that right?

This is possible, but it doesn't follow the long-standing conventions for Java enum naming. With jsonschema2pojo, we cannot attempt to support every possible preferred way of writing Java source code. Our intention is to create a _correct_ approach that maps between JSON and Java and follows Java conventions. It is not the intention of this library to allow endless configurability to get the exact Java source code that you prefer, as that is too big a task and would create a system that is far harder to extend and maintain. See JAXB for a similar approach - the goal is to provide a correct implementation, not to allow generation of whatever source code style you prefer.

So I'm going to close this one, but thanks for the suggestion and feel free to raise another.

**Comment by adrien1212** [comment]
@joelittlejohn thank you for your work
I have the same problem and you say

> This is possible

I don't find where I can do it with.
Can you explain which part of the code needs to be changed (e.g. create a custom EnumRule and override some method, etc ...)

**Comment by unkish** [comment]
@adrien1212 you could create a custom `EnumRule` and override methods that generate code you don't need, eg:

- `addConstructorAndFields`
- `addFactoryMethod`
- `addFieldAccessors`
- `addToString`
- `addEnumConstants`
