### ISSUE TITLE
Add support for generic type arguments to javaType

### ISSUE THREAD

**Issue by stackmagic** [joelittlejohn/jsonschema2pojo#151]
I'm trying to generate a Map field and it seems this is possible but not quite the way I want it.

AdditionalProperties could generate a Map[String, MyType] which is exactly what I'd want, the problem is the map field is not supposed to be named "additionalProperties" and I haven't found a way to rename additionalProperties (plus you can only have one of those).

The second thing I tried is to use javaType. That creates a map alright but the parametrization is missing, it's just "Map". Adding the generics to the javaType causes an error.

Neither solution is fully satisfactory. For now, I'll just stick to the plain map because I don't want the field-naming of my internal and external data models to drift apart. Since this is a message I'll only serialize, never de-serialize I can simply assign the map to be serialized and it'll work just fine but I still think it's a hack and a proper solution with generics would be nice.

edit: make generics args visible, github swallows lower-than and greater-than signs

**Comment by brentryan** [comment]
@joelittlejohn Have you or anyone tried adding support for something similar to this, but where the actual object type you're generating supports generics?  So my schema would look like this:

{
    "type": "object",
    "javaType": "MyGeneric<T>",
    "properties": {
        "fields": {
            "type": "array",
            "items": {
                "javaType": "T"
            }
        }
    }
}

And this would generate a class like:

public class MyGeneric<T> {
 ....
}

**Comment by joelittlejohn** [comment]
Not a simple thing to implement :) I'd be a little concerned we're getting to the point where we're really just writing Java in a more terse syntax. Scala or Groovy might be a better option at this point.

So no I haven't tried this and I haven't seen any girl that attempts this.
