### ISSUE TITLE
Support for different access modifiers

### ISSUE THREAD

**Issue by LukaszMalinowski** [joelittlejohn/jsonschema2pojo#1510]
Hi,

Is there any way to implement different access modifiers in generated classes? I think it would be really nice to be able to generate package-private classes, right now I think the only option is to generate public classes. Are there any plans for this?

**Comment by joelittlejohn** [comment]
No, no plans to support it I'm afraid. I've given a rationale for why on quite a few issues, and I'll copy it here for info:

> With jsonschema2pojo, we cannot attempt to support every possible preferred way of writing Java source code. Our intention is to create a correct approach that maps between JSON and Java and follows Java conventions. It is not the intention of this library to allow endless configurability to get the exact Java source code that you prefer, as that is too big a task and would create a system that is far harder to extend and maintain. See JAXB for a similar approach - the goal is to provide a correct implementation, not to allow generation of whatever source code style you prefer.
