### ISSUE TITLE
javaType as Long does not work with latest version but works with 0.4.x

### ISSUE THREAD

**Issue by nikhilbhalwankar** [joelittlejohn/jsonschema2pojo#1538]
```json
"type": "integer",
"javaType": "Long"
```
This correctly creates Long object in `0.4.x`. However it does not work with the latest version. If I want some objects as Integer and come as Long then this does not work with latest version.

**Comment by unkish** [comment]
Hi

There were a lot of changes between `0.4.x` and current version including breaking changes.
`javaType` has been separated into `existingJavaType` and `javaType`, see #828.

Please use [`existingJavaType`](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#existingjavatype) when referring existing java types, eg:
```json
"type": "integer",
"existingJavaType": "Long"
```
