### ISSUE TITLE
Different classes are generated for the same named attribute at a different JSONPath location

### ISSUE THREAD

**Issue by ulviugur** [joelittlejohn/jsonschema2pojo#1559]
Hi,

I have the same attribute ("lastEdit") at different location in the JSON tree and POJO converter creates 2 different classes : **LastEdit__1** and **LastEdit**.

Is there a way to declare that both of these attributes are the same and no need to create a dedicated new Class ? Could not find anything relevant in the "Reference" section.

Cheers,
Geo

**Comment by unkish** [comment]
Hi

> Is there a way to declare that both of these attributes are the same and no need to create a dedicated new Class ?

In case source type is `JSON` and the structure is similar to defined [here](https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-integration-tests/src/test/resources/json/propertiesSameName) then at present it's not possible
