### ISSUE TITLE
Comparison method is created for each array type declared in JSON sample file

### ISSUE THREAD

**Issue by ulviugur** [joelittlejohn/jsonschema2pojo#1564]
Hi,

it looks like json2pojo creates a comparison method **_(equals(Object other))_** for arrays defined in the sample JSON file which leads to a compiler error. I would like to suppress the generation of such methods as it currently does not makes sense for my use case (yet).

In my 24 pojo classes, I have this same issue in 23 of them and the last one is called an "Object" which is also a red flag for me.

Any ideas how to fix this ?

Cheers,
Geo

**Comment by unkish** [comment]
Hi

It's really hard to say anything without having an example that would showcase issue at hand

**Comment by unkish** [comment]
Closing due to lack of feedback.
 Please feel free to reopen if you still have questions.
