### ISSUE TITLE
Generation failure after upgrade

### ISSUE THREAD

**Issue by AllenF88** [joelittlejohn/jsonschema2pojo#1568]
Hi all

Upgrading from v 1.1.0 to 1.2.1 I now get this error: **generate failed: Path not present: Single Sided** 

here is the implementation in the pom file.
```xml
<plugin>
	<groupId>org.jsonschema2pojo</groupId>
	<artifactId>jsonschema2pojo-maven-plugin</artifactId>
	<version>1.2.1</version>
	<configuration>
		<sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
		<targetPackage>com.#####.integration.consumers.generated</targetPackage>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```
Any ideas? 

[Stacktrace.log](https://github.com/joelittlejohn/jsonschema2pojo/files/12931939/Stacktrace.log)

**Comment by unkish** [comment]
Hi

It's rather hard to say what might be the cause without minimal sample schema which would reproduce the issue

**Comment by joelittlejohn** [comment]
Yes, are you able to provide a small snippet @AllenF88? Something that sticks out immediately is that the property name contains a space, I wonder if we have some poor handling of spaces when looking up a property. This is surprising as I'm sure we have tests for that.

**Comment by AllenF88** [comment]
Hi all. Apologies I thought I closed this yesterday. The issue was in one of the schemas, a ? snuck into the field name. this wasnt an issue on the older version though. But its better that its being validating.

**Comment by unkish** [comment]
Properties with ? will be supported in next build (fixed with https://github.com/joelittlejohn/jsonschema2pojo/pull/1522)
