### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by yeikel** [joelittlejohn/jsonschema2pojo#1569]
Hello there, 

When is the next release? 

I am looking for this commit in particular https://github.com/joelittlejohn/jsonschema2pojo/commit/67728c002ebe7fd6941b34af348eac005f616382 and the latest release is from February 

I understand that I can overwrite it for now but it is not ideal

Thanks in advance!

**Comment by henryju** [comment]
1.2.2 has been released 2 weeks ago
