### ISSUE TITLE
Wiki Reference page broken?

### ISSUE THREAD

**Issue by jeremywall-davis** [joelittlejohn/jsonschema2pojo#1577]
On December 5th I was looking at https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference without any problems, now it's the 7th and it's returning a 500 error message. GitHub status is all green. Any ideas what's wrong?

**Comment by jeremywall-davis** [comment]
I figured it's GitHub's fault. I just wanted to bring up the issue in case the wiki page was changed and something new happened to break something.

**Comment by unkish** [comment]
Closing as per reporter issue was caued by GitHub
