### ISSUE TITLE
Allow BigDecimal and BigInteger to be used for number and integer properties

### ISSUE THREAD

**Issue by akushe** [joelittlejohn/jsonschema2pojo#161]
My Json schema has Geo coordinates which have been mapped as follows

```json
        "lat": {
            "description": "Latitude",
            "type": "number",
            "required" : true
        },
        "lng": {
            "description": "Longitude",
            "type": "number",
            "required" : true
        }
```

These get transformed as Double. Can a configuration be added to transform them as BigDecimal as precision is critical for me
The Jackson ObjectMapper also has a feature 
DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS

**Comment by mifernandez** [comment]
Hello,
the "useDoubleNumbers" configuration (developped by abloomston) could be added a future release ? 
Thanks,

**Comment by joelittlejohn** [comment]
Hi @mifernandez, `useDoubleNumbers` has been included in this plugin since 0.4.0.

**Comment by mifernandez** [comment]
Hi,

Sorry I would ask for 'useBigDecimalNumbers' which not seem to on latest version.

**Comment by rozhok** [comment]
+1 for this. Useful for money-related things.

**Comment by xandrox** [comment]
+1 we need this too, same reason like rozhok
