### ISSUE TITLE
How to declare one field as Map?

### ISSUE THREAD

**Issue by zjffdu** [joelittlejohn/jsonschema2pojo#1611]
I know in jsonschema2pojo additionalProperties is java Map, but how can I declare one specific field also as Map? e.g. I want the following field config to be a Map.

```
{
  "type":"object",
  "properties": {
    "config": {
        "type" : "string"
    }
  }
}
```

**Comment by joelittlejohn** [comment]
One option is to say: `"existingJavaType": "java.util.Map<String,String>"`

**Comment by zjffdu** [comment]
Thanks @joelittlejohn
