### ISSUE TITLE
When I click preview in website [https://www.jsonschema2pojo.org/], it doesn't work. 

### ISSUE THREAD

**Issue by whoooami** [joelittlejohn/jsonschema2pojo#1624]
Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> ((index):1003:36)
    at k (jquery.min.js:2:16934)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:17721)
    at Function.ready (jquery.min.js:2:12438)
    at HTMLDocument.D (jquery.min.js:2:9843)

**Comment by unkish** [comment]
Tried out with "defaults", worked fine.
Could it have been smht. temporary ?

**Comment by joelittlejohn** [comment]
The only way I can imagine this might happen is if the browser or network has some kind of corporate policy that is stopping the Javascript on the page from working properly.

**Comment by whoooami** [comment]
Thanks, Boss. It turns out my network that can't load some scripts correctly. Sorry.

**Comment by unkish** [comment]
Provided schema
```json
{
    "sign": "0ee4246d6112a21e39304c7b1463fb11",
    "content": {
        "senderLat": "41.794102",
        "senderLng": "123.370956"
    }
}
```

Does not seem to be a JSON Schema, thus `sourcetype=jsonschema` should be replaced with correct value `sourcetype=json`
