### ISSUE TITLE
json schema draft-04 specification support

### ISSUE THREAD

**Issue by kspmmitt** [joelittlejohn/jsonschema2pojo#1648]
Hello,

Can you please confirm and provide some documentation whether draft-04 specification is supported or not?
Also please share documentation for supported or not supported items?
Rgds,
Kamal

**Comment by unkish** [comment]
Hi

Please check [schema feature support](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#schema-feature-support) wiki page.
