### ISSUE TITLE
java version for generated source code

### ISSUE THREAD

**Issue by kspmmitt** [joelittlejohn/jsonschema2pojo#1650]
Hello,
Which java version is used for generating source code? Can it be customized to support java 17 and it will use java 17 features?
Rgds,
Kamal

**Comment by joelittlejohn** [comment]
Hi Kamal. No, unfortunately there is no support for Java 17 features. We use an underlying code generation library called CodeModel, and it does not support Java 17 features. It is the same code generator used by jaxb.
