### ISSUE TITLE
Preview does not work on Chrome

### ISSUE THREAD

**Issue by jaydeepw** [joelittlejohn/jsonschema2pojo#169]
I had the settings as shown in the screenshot attached. Clicking preview does not show up anything.

![screen shot 2014-04-14 at 11 42 51 pm](https://cloud.githubusercontent.com/assets/1368272/2698923/8038ad36-c400-11e3-9877-88e92b83c3f7.png)

**Comment by testsmsprev** [comment]
same error

**Comment by joelittlejohn** [comment]
@testsmsprev The site appears to be working fine in Chrome. Either you have the wrong source type (if you are seeing a blank preview) or you have something else blocking communication on your network (if you see no preview box at all).

You could try opening the Developer Tools in Chrome and checking the Console and Network tabs.

**Comment by joelittlejohn** [comment]
Also, if you're seeing a blank preview, make sure you actually have a schema in the input box. If you just have `{"definitions":{...}}` then the object you have pasted does not include a main schema to generate.
