### ISSUE TITLE
Incomplete output on glTF schema

### ISSUE THREAD

**Issue by dlabz** [joelittlejohn/jsonschema2pojo#181]
Tried to generate java classes for glTF (https://github.com/KhronosGroup/glTF), but only  3 classes are generated. No exceptions or errors are shown.
I might be doing something wrong.

**Comment by joelittlejohn** [comment]
$ref is supported for additionalProperties, however the problem here is an error in the schema. For additionalProperties to take effect at all as a schema rule, the schema must be `"type": "object"`.
