### ISSUE TITLE
Support transliteration to ASCII to avoid extended characters in Java source code

### ISSUE THREAD

**Issue by schlumpfling42** [joelittlejohn/jsonschema2pojo#190]
Hi,
again a german issue. If I define an enum with words that contain umlauts:
"enum" : ["Herr", "Frau", "Fräulein"],
the class is generated, but cannot be compiled because it generates an enum with an invalid name:
FRÃ„ULEIN("Fr\u00e4ulein");

What can I do to avoid that issue?

**Comment by joelittlejohn** [comment]
This hasn't been much of a problem after all. No intention of implementing this at present because it doesn't seem to affect enough people.
