### ISSUE TITLE
Nested generics not honoured

### ISSUE THREAD

**Issue by tcharman** [joelittlejohn/jsonschema2pojo#196]
Using 0.4.2, I am trying out generics.  I have declared as follows:
```json
"javaType": "java.util.Map<java.lang.String, java.util.Map<java.lang.String, java.lang.String>>",
```
When I try this, the generated class doesn't have the second > on the end of the type, so renders a compile error (in the attribute, the getter and the setter).

**Comment by stowns** [comment]
+1
