### ISSUE TITLE
Creating a list of objects with class name as “S”

### ISSUE THREAD

**Issue by niharikavy** [joelittlejohn/jsonschema2pojo#213]
Problem : If I have the class name as "s", POJO is not generated for it.

I have tried using the maven plugin as well as http://www.jsonschema2pojo.org/
Both give errors while generating the pojos.

Error from plugin execution: Execution goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.0:generate failed: String index out of range: 0 -> [Help 1]

Other observations : It works for other letters.
If it is not an array type, then plain object works too, but not as an array

Sample excerpt of schema

``` json
{ 
  "type": "object",
  "id": "http://jsonschema.net/abc",
  "required": true,
  "description": "Some description",
  "properties": {
  "s": {
          "type": "array",
          "id": "http://jsonschema.net/abc/s",
          "required": true,
          "items": {
            "type": "object",
            "id": "http://jsonschema.net/price/abc/0/",
            "required": true,
            "description": "sales price object of an item",
            "properties": {
               "ip": {
                "type": "number",
                "id": "http://jsonschema.net/price/p/s/0/value",
                "required": true,
                "description": "some desc"
              }
             }
            }
    }
  }
}
```

**Comment by tanarun1234** [comment]
I tried in version 0.5.0 and also in 1.1.1 , it still doesnt work. It does not geneate with 's' at the end .

My class name is ColleagueRelationships  , but it just generated it as "ColleagueRelationship.java" . It removed 's' at the end from ColleagueRelationship(s)

**Comment by joelittlejohn** [comment]
@tanarun1234 yes, this is the expected behaviour. If you have an array of client relationships, then a single item within that array is assumed to be a client relationship.
