### ISSUE TITLE
Support "javaType" for things that are not "type": "object"

### ISSUE THREAD

**Issue by dflemstr** [joelittlejohn/jsonschema2pojo#223]
There is nothing that says that only `"type": "object"` things can have `"javaType"`. For example, I would want a Joda `DateTime` to be serialized as an integer (letting Jackson handle the actual conversion) but this is not possible to express right now.

**Comment by joelittlejohn** [comment]
I've generalised the implementation in #287 to allow for any schema type to be overridden using `javaType` (not just integers and numbers).
