### ISSUE TITLE
Option to create a constructor with all of the required fields

### ISSUE THREAD

**Issue by monksy** [joelittlejohn/jsonschema2pojo#231]
At the moment it's a little messy with creating new instances of the POJOs with the builders. Could we get an option that would create an additional constructor to define the required fields?

Right now to create something of the following schema: 

     Obj { name: asdf, age: 32; state:NC} 

You would have to invoke it by: (with builders enabled)

    new Obj().withName("asdf").withAge(32).withState("NC")

Rather than [what I'm suggesting]

    new Obj("asdf", 32, "NC")

**Comment by andrewmains12** [comment]
Took a stab at this [here](https://github.com/joelittlejohn/jsonschema2pojo/pull/283)

**Comment by joelittlejohn** [comment]
Closed by #283
