### ISSUE TITLE
Property with type string and format date-time should output ISO8601 Date instead of Timestamp

### ISSUE THREAD

**Issue by jmc-rs** [joelittlejohn/jsonschema2pojo#247]
If we have a property of type string with format date-time defined like this

``` json
"properties": {
        "generatedAt": {
            "id": "http://jsonschema/generatedAt#",
            "type": "string",
            "format": "date-time",
            "minLength": 1
        },
```

the code generated for that property will be

``` java
@JsonProperty("generatedAt")
private Date generatedAt;
```

When the property gets serialised, the value produced is a timestamp in milliseconds..(default Jackson behaviour)
Since the type specified is a string with a date-time format I would expect this to produce an ISO8601 Date string

This can be solved by annotating the generated property with:

``` java
@JsonProperty("generatedAt")
@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'", timezone="GMT")
private Date generatedAt;
```

**Comment by unkish** [comment]
Looks like this issue may be closed as #380 was superseded by #643 that was merged into master in 2016.
