### ISSUE TITLE
ClassNotFoundException when attempting to use a custom annotator from a project dependency

### ISSUE THREAD

**Issue by Cuneytt** [joelittlejohn/jsonschema2pojo#256]
Trying to generate POJOs from JSON examples (not schemas) using the following maven configuration:

``` xml
                <groupId>org.jsonschema2pojo</groupId>
                <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                <version>0.4.5</version>
                <configuration>
                    <sourceDirectory>src/main/resources/json</sourceDirectory>
                    <outputDirectory>${project.build.sourceDirectory}</outputDirectory>
                    <targetPackage>com.test.applications.service.model</targetPackage>
                    <sourceType>JSON</sourceType>
                    <generateBuilders>true</generateBuilders>
                    <includeHashcodeAndEquals>false</includeHashcodeAndEquals>
                    <annotationStyle>NONE</annotationStyle>
               </configuration>
```

this generates POJOs as expected without any annotations but still generates the addtionalProperties:

``` java
private Map<String, Object> additionalProperties = new HashMap<String, Object>();
```

I know disabling this is possible through schema declaration through `"additionalProperties": false`
but in my case I generate from json examples.

I tried to use a custom Annotator that will override the AbstractAnnotator and run it through maven:

``` java
public class CustomNoopAnnotator extends AbstractAnnotator{
    @Override
    public boolean isAdditionalPropertiesSupported() {
        return false;
    }
}
```

and additional config in maven:

``` xml
<customAnnotator>com.test.application.generator.CustomNoopAnnotator</customAnnotator>
```

this class is another module and the module I am trying to generate POJOs from has a dependency to this module.

I get java.lang.ClassNotFound exception with this setup.

I'd appreciate any feedback as to how to disable additionalProperties HashMap from being generated using JSON source type.

**Comment by sundhar-perumal** [comment]
I am using 0.4.12v of jsonschema but still i face the same problem.

Simple, 
  1. I had a maven project with jsonschema 0.4.12 dependancy. 
  2. I created a custom annotator and configured in maven build plugin
  3. But I still get NoClassDefFoundError.. 

Looks like Jsonschema2PojoMojo when creating new URLCLassloader it doesnt copy the parent loaded classes. 

Suggest what could be the solution

**Comment by joelittlejohn** [comment]
Did you add the module that contains the custom annotator as a dependency on the plugin?

**Comment by sundhar-perumal** [comment]
Hi, yes adding the annotator module <dependency> inside <plugin> solved the problem.., Thanks for the suggesstion.

But why would a plugin require to define all its dependency inside it. Ideally, it should pick any other dependency from global dependecies list.
