### ISSUE TITLE
Support Jackson Mixin Annotation Generation

### ISSUE THREAD

**Issue by bowenwr** [joelittlejohn/jsonschema2pojo#276]
I typically use Jackson's mixins to keep my domain objects as clean and portable as possible. I've been factoring out the JSON annotations to mixins myself. This is a great tool, but it would be that much nicer if it could put the annotations in separate mixins!

**Comment by joelittlejohn** [comment]
Unfortunately, we can't support every different preference in how to generate code. We have a way that works, and although I can see you're keen on mixins, that's not what we use. It's too much maintenance effort to support many different styles of output code, and if we only have one output style, mixins are not going to be it. Thanks for raising this though, always nice to hear from users.
