### ISSUE TITLE
Unable to load class 'com.googlecode.jsonschema2pojo.NoopAnnotator'.

### ISSUE THREAD

**Issue by kdawgwilk** [joelittlejohn/jsonschema2pojo#277]
I'm running:
Android Studio (1.0.0)
Gradle 2.2.1
with
classpath "org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:0.4.7"
classpath "com.android.tools.build:gradle:1.0.0"

and I'm getting this error:

Error:Unable to load class 'com.googlecode.jsonschema2pojo.NoopAnnotator'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<strong>Re-download dependencies and sync project (requires network)</strong></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<strong>Stop Gradle build processes (requires restart)</strong></li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by nenick** [comment]
i'm faced the same issue and found a line at my `build.gradle` file 
`customAnnotator = 'com.googlecode.jsonschema2pojo.NoopAnnotator'` a google search  led me to https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-gradle-plugin where this line exist as an example. 

Solution is to replace it with `org.jsonschema2pojo.NoopAnnotator`

**Comment by joelittlejohn** [comment]
Good spot, thanks! I've fixed the readme.
