### ISSUE TITLE
please allow adding @XmlRootElement annotation to generated classes

### ISSUE THREAD

**Issue by pkonce** [joelittlejohn/jsonschema2pojo#278]
I had to add this manually in order to parse with com.sun.jersey.api.client.getEntity(Generated.class);

**Comment by ltoinel** [comment]
I need a Jaxb compatibility with the Pojo generated by Jsontoschema.

Any idea to inject jaxb annotations into the generated pojo ?

**Comment by joelittlejohn** [comment]
You can create an instance of this interface:

http://joelittlejohn.github.io/jsonschema2pojo/javadocs/0.4.8/org/jsonschema2pojo/Annotator.html

(see the other implementations for an idea of how to achieve what you need)

Once you have a class that implements this interface, you can instruction jsonschema2pojo to use it using the `customAnnotator` config option.
