### ISSUE TITLE
Maven plug-in documentation missing for 0.4.7

### ISSUE THREAD

**Issue by ddossot** [joelittlejohn/jsonschema2pojo#279]
This URL http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.7/generate-mojo.html 404s.

**Comment by joelittlejohn** [comment]
Thanks for mentioning this. There seems to be a bug in GitHub's gh-pages support that means that sometimes updates are not seen. I've been able to fix this by deleting the gh-pages branch from github.com and pushing it again.
