### ISSUE TITLE
jsonschema2pojo giving invalid jar files as output, the jar file is only 22 bytes and does not open as a jar file

### ISSUE THREAD

**Issue by asjdk213** [joelittlejohn/jsonschema2pojo#281]
jsonschema2pojo giving invalid jar files as output, the jar file is only 22 bytes and does not open as a jar file

Opening the jar file in notepad gives the output "PK                  "

**Comment by joelittlejohn** [comment]
My first guess it's that there was no content. Could you show the example
schema so that I can verify what types it should create?

Also, if you use the preview option do you get any classes down in the
preview dialog?

**Comment by joelittlejohn** [comment]
Yes, what you have is an empty jar file. I think the schema you have used did not cause any types to be generated. Often this is caused by using JSON but not selecting "Source type: JSON".
