### ISSUE TITLE
I write "g_id", but when I generate, it changes to "gId", what happen?

### ISSUE THREAD

**Issue by angelen10** [joelittlejohn/jsonschema2pojo#284]
#Json:
```javascript
[{"id":"1","imgUrl":null,"g_id":"11"}]
```
#Generate:
```javascript
……
private String gId;
……
/**
* 
* @return
* The gId
*/
public String getGId() {
return gId;
}

/**
* 
* @param gId
* The g_id
*/
public void setGId(String gId) {
this.gId = gId;
}
```

**Comment by joelittlejohn** [comment]
jsonschema2pojo recognises delimiters like spaces, hyphens and underscores. This means you can have json properties that look like `this_is_my_property` and these can be represented in java like `thisIsMyProperty`. The annotations in the code will ensure that the json produced from your types still produces the correct name.

If you don't want this to happen, try emptying out the propertyWordDelimiters value (or setting it to some other value like `#`).

**Comment by angelen10** [comment]
OK, Thank you.
