### ISSUE TITLE
Add "implement parcelable" option for android, and override toString option

### ISSUE THREAD

**Issue by premnirmal** [joelittlejohn/jsonschema2pojo#285]
implementing the Parcelable interface would be useful for Android developers, and overriding `toString()` for debugging purposes

**Comment by joelittlejohn** [comment]
Hi, we have #127 open to cover this. I've actually implemented a proposed solution in the `parcelable` branch. If you install a snapshot from this branch you can try it out.

**Comment by premnirmal** [comment]
@joelittlejohn thanks!
