### ISSUE TITLE
Unable to preview/convert or create jar of the input JSON

### ISSUE THREAD

**Issue by nikhilsinghal1990** [joelittlejohn/jsonschema2pojo#288]
Hey

Its been a month or two since when i am not able to create pojo classes due to some JS error on click of either preview / jar.
Its not some thing significant rather just some missing style class issue.
Please look into it.

**Comment by joelittlejohn** [comment]
Hi. Could you give me some details? A screenshot would be helpful. Also, what browser are you using? The app works in Chrome, Firefox and Safari but I don't know about Internet Explorer. I expect it works in  IE10.

What is the JS error you're seeing?

**Comment by nikhilsinghal1990** [comment]
Hey

I was using latest chrome. But that was on my office desktop, now i just
checked from my home PC and it works fine.
Could have been some browser cache issue earlier.

Thanks Joe.

**Comment by joelittlejohn** [comment]
okay, thanks for reporting back.
