### ISSUE TITLE
Schemas referring to another schema are generated once only

### ISSUE THREAD

**Issue by samskiter** [joelittlejohn/jsonschema2pojo#289]
I have several schema that all refer to another schema in their root. Like so:

request1.schema.json:
```
{
    "id": "http://blah.com/schema/request1.schema.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "request 1",
    "description": "The first request",
    "$ref": "push.schema.json#"
}
```

request2.schema.json:
```
{
    "id": "http://blah.com/schema/request1.schema.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "request 2",
    "description": "The second request",
    "$ref": "push.schema.json#"
}
```

push.schema.json:
```
{
    "id": "http://blah.com/schema/push.schema.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "push stuff",
    "description": "push it push is",
    "type": "object",
    "additionalProperties": false,
    "required": ["code"],
    "properties": {
        "code": {
            "type": "string"
        }
    }
}
```

The java generated has only request1_schema.java. This is presumably because the generator has noticed that request2 is just a ref to the same thing.

Would it be possible to EITHER:
generate request1.java AND request2_schema.java
OR
generate push_schema.java

I would prefer the former as this allows be to change my schemas at a later date and have that reflected in the generated Java.

**Comment by joelittlejohn** [comment]
Hi Sam,

Yes, that is indeed why only one is generated. The only way to solve this
at present is to invoke the plugin twice (once for request1.schema.json and
once for request2.schema.json).
