### ISSUE TITLE
Maven: Specify http url as sourceDirectory

### ISSUE THREAD

**Issue by jvasiljevich** [joelittlejohn/jsonschema2pojo#293]
We are planning to leverage jsonschema2pojo within a microservice project.  The goal is to be able to integrate our individual microservices using only their respective schemata, without sharing any jars between the services.  This library is a great fit for that, with one little snafu: our schemata are currently stored behind a RESTful api.  Ideally, we'd like to be able to specify a http url as the schema source, and generate the POJOs from there.  Something like this:

```xml
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <version>0.4.7</version>
    <configuration>
        <sourceDirectory>http://myschemalocation.com/schema/target-schema</sourceDirectory>
        <targetPackage>com.example.types</targetPackage>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Currently, this doesn't work because the GenerationConfig interface is expecting a list of java Files.  However, since further downstream the ContentResolver seems to accept a URL, this seems like it would be a trivial issue to address.

Is this already being worked on?

**Comment by joelittlejohn** [comment]
Closed by #294.
