### ISSUE TITLE
Generating POJOs from JSON source type using maven plugin

### ISSUE THREAD

**Issue by irislove** [joelittlejohn/jsonschema2pojo#295]
Hi,

Is there a way to generate POJOs from a JSON example file instead of JSON schema file using maven plugin? Looking at your maven plugin source code, sourceType seems to be hardcoded to jsonschema and there is no setter method for this private field. 

https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Many Thanks,

Iris

**Comment by joelittlejohn** [comment]
Hi, yes this is possible. This is a private field with no setter only because Maven mojo config args work in this way.

These docs will be useful:

http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.8/generate-mojo.html
