### ISSUE TITLE
Didn't generate all of the properties

### ISSUE THREAD

**Issue by Smitty010** [joelittlejohn/jsonschema2pojo#297]
I tried using the website generator to generate pojos for the schema: http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json.  If you do that, you'll see it doesn't generate all of the properties.  In particular, if you look at the "object" and the "renditions" properties, you'll see that there are no sub-property objects being generated.  Similarly, it doesn't generate the items in "organisation" (even though it generated them in "person").  I wonder if it has something to do with the sub-properties in different json objects having the same name.  Cheers.

**Comment by joelittlejohn** [comment]
Hi. It looks to me link renditions only uses patternProperties. This library doesn't support pattern properties.

When I use schema you have given at www.jsonschema2pojo.org I see the following generated for "organisation":

```java
@JsonProperty("organisation")
private List<Organisation> organisation = new ArrayList<Organisation>();
```

and 

```java
public class Organisation {

/**
* The name of the organisation
* 
*/
@JsonProperty("name")
private String name;
/**
* The relationship of the content of the news object to the organisation
* 
*/
@JsonProperty("rel")
private String rel;
/**
* The identifier of a scheme (= controlled vocabulary) which includes a code for the organisation
* 
*/
@JsonProperty("scheme")
private URI scheme;
/**
* The code for the organisation in a scheme (= controlled vocabulary) which is identified by the scheme property
* 
*/
@JsonProperty("code")
private String code;
/**
* Symbols used for a finanical instrument linked to the organisation at a specific market place
* 
*/
@JsonProperty("symbols")
private List<Symbol> symbols = new ArrayList<Symbol>();

etc
```

I can't see anything wrong here, but maybe I'm missing something?

I also noticed that you have a property called "object" in your schema and this is causing a class called "Object" to be generated. It seems like this will confuse matters and I wonder if we should treat "Object" as a reserved word, which would mean your class would be called "Object_".

**Comment by joelittlejohn** [comment]
Closing for now as I can't initially see what's wrong here. Feel free to provide more info and I'll investigate. Cheers.
