### ISSUE TITLE
Array types are ignored inside generics in javaType

### ISSUE THREAD

**Issue by kkuo** [joelittlejohn/jsonschema2pojo#299]
I have a json schema that looks like this:
```json
    "properties": {
        "media": {
            "javaType" : "java.util.Map<String,String[]>",
            "type":"object"
        }
}
```

In 0.4.7 this was generated:
```java
    @JsonProperty("media")
    public Map<String, String[]> getMedia() {
        return media;
    }
```
In 0.4.8 this was generated:
```java
    @JsonProperty("media")
    public Map<String, String> getMedia() {
        return media;
    }
```

**Comment by joelittlejohn** [comment]
Hi, I don't understand where String[] is coming from. Is there more to this schema that you have not shown?

**Comment by joelittlejohn** [comment]
Ah, GitHub has removed the content between &lt; and > in your schema. Yes, I think this is a bug. 0.4.8 now supports nested generics but clearly there is something wrong with array types.

**Comment by kkuo** [comment]
Any idea if we don't want to rely on JavaType to define a map of String to String[], how to do it in plain ole json schema?

**Comment by joelittlejohn** [comment]
The way to achieve this in your schema would be like this:
```json
"properties" : {
  "media" : {
    "type" : "object",
    "additionalProperties" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    }
  }
}
```

This would imply that the value of `media` is an object that can have properties with any name but that all their values must be string arrays. This would of course mean that you would have an additional map in your Java:

```java
public class Media {

private Map<String, List<String>> additionalProperties = new HashMap<String, List<String>>();

public Map<String, List<String>> getAdditionalProperties()...

public void setAdditionalProperty(String name, List<String> value)...

}
```
