### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Smitty010** [joelittlejohn/jsonschema2pojo#301]
Just a couple of thoughts.

1. Regarding pattern objects in schemas, it might be nice to have an option that generates an example of the object that has the pattern name (if it's an object or an array).  If you look at the Rendition object in http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json, it would be nice to have a pojo with those 6 properties in it.  Then the actual renditions can be created by hand as classes that extend this object.
2. When someone specifies "-T JSON" (generate from JSON instead of schema), you could run strings through something like joda's iso8601 parser and see if it parses as a date/time.  If it doesn't throw an exception, then you can generate it as a date field.
3. Would be nice of have the option to generate java Calendar instead of java Date.  Eventually, it would be good to have the new java.Time class.
4. Lowest on my priority list is that you read in Json and output a json schema.  I'm guessing you're close to having that ability in the code.

Just suggestions.  This is a useful program especially given the trend to json away from xml.

Cheers

Scott

**Comment by joelittlejohn** [comment]
Hi Scott, thanks for your feedback! I think 2 and 3 could easily be added and would each make a nice addition. If you could raise a separate issue for each of these, or feel free to just submit a PR, that would be great.

I'm not sure about 1, this seems like a bit of a hack and I'm not sure people will use or understand this feature. Finally, I think 4 falls outside of the goals of this project. Something simple along the lines you've suggested could easily be achieved in a separate maven plugin using Jackson.

**Comment by Smitty010** [comment]
I understand your concerns about 1.  If I were doing it, I'd probably make it an option, and there would be a rather large, bold comment on the generated object explaining what needed to be done and including a TODO mark.  The alternative is to that the programmer has to flesh out the entire object by hand (which is what I did to implement it for the project I had to do).  Since the referenced json schema wasn't mine to modify, my only options were to create the object by hand or create a hacked version of the json schema.  I'll raise new issues for all 3 and you can reject this one if you like.   Cheers
