### ISSUE TITLE
Make the fields used in hashcode and equals generation configurable

### ISSUE THREAD

**Issue by d4rxh4wx** [joelittlejohn/jsonschema2pojo#309]
https://github.com/joelittlejohn/jsonschema2pojo/pull/241#issuecomment-58324684

**Comment by ltoinel** [comment]
+1

**Comment by joelittlejohn** [comment]
Hi all, how would you propose configuring this? Would you like to add a field to each property, have a global configuration value containing a list of field names, or do something like include only 'required' fields?

**Comment by d4rxh4wx** [comment]
Hi. I would go with a list of field names. In that way, you can see in one place which fields are participating to equals and hashcode.

**Comment by joelittlejohn** [comment]
@d4rxh4wx do you mean in the object itself? like:

```json
{
  "type" : "object",
  "javaHashcodeEqualsFields" : ["foo","bar"]
}
```

**Comment by d4rxh4wx** [comment]
Yes. That sounds good.

**Comment by mikaelec** [comment]
+1

How about an option for using super classes' fields for equals and hashCode?

**Comment by skarian92** [comment]
Hi
So any updates on the problem.How can I configure HashcodeEqualFields??

**Comment by rozhok** [comment]
+1 I don't like to include dependency to commons-lang and want to see plain java8 equals/hashCode like 
```java
@Override
public boolean equals(Object o) {
    if (this == o) {
        return true;
    }
    if (o == null || getClass() != o.getClass()) {
        return false;
    }
    Message that = (Message) o;
    return Objects.equals(type, that.type) &&
            Arrays.equals(updated, that.updated) &&
            Arrays.equals(deleted, that.deleted) &&
            Objects.equals(content, that.content);
}
@Override
public int hashCode() {
    return Objects.hash(type, updated, deleted, content);
}
```

**Comment by szhem** [comment]
+1 

I'd like hashcode, equals and toString with java8 style too

**Comment by joelittlejohn** [comment]
We now have equals, hashCode and toString methods that do not depend on commons-lang, and we also allow fields to be excluded from these (see `excludedFromEqualsAndHashCode` schema extension).
