### ISSUE TITLE
Want to remove @JsonInclude(JsonInclude.Include.NON_NULL) from generated class

### ISSUE THREAD

**Issue by hverma11** [joelittlejohn/jsonschema2pojo#314]
Hi ,
 
I want to remove the @JsonInclude(JsonInclude.Include.NON_NULL) or change it to @JsonInclude(JsonInclude.Include.ALWAYS) so that properties will always gets included in the marshalled object.

Please provide suggestions.

Regards,
Hemant

**Comment by joelittlejohn** [comment]
If you set `<annotationStyle>none</annotationStyle>` you could then create your own custom annotator that extends this class:

https://github.com/joelittlejohn/jsonschema2pojo/blob/jsonschema2pojo-0.4.9/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java

but overrides the `propertyInclusion` to do something different.

**Comment by hverma11** [comment]
Thanks ! Makes sense and I tried the same.However getting ClassNotFoundException

<plugins>
		<plugin>
			<groupId>org.jsonschema2pojo</groupId>
			<artifactId>jsonschema2pojo-maven-plugin</artifactId>
			<version>0.4.9</version>
			<configuration>			
				<sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
				<targetPackage>com.govt.nzqa.mqa.schema</targetPackage>
				<annotationStyle>none</annotationStyle>				<customAnnotator>com.annotator.CustomJackson2Annotator</customAnnotator>				
			</configuration>
			<executions>
				<execution>
					<goals>
						<goal>generate</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
		
	</plugins>

Caused by: java.lang.ClassNotFoundException: com.annotator.CustomJackson2Annotator
