### ISSUE TITLE
Getting ClassNotFoundException while configuring <customAnnotator>

### ISSUE THREAD

**Issue by hverma11** [joelittlejohn/jsonschema2pojo#315]
Getting ClassNotFoundException :	

                      <configuration>			
				<sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
				<targetPackage>com.govt.nzqa.mqa.schema</targetPackage>
				<annotationStyle>none</annotationStyle>
				<customAnnotator>com.mqa.CustomJackson2Annotator</customAnnotator>				
			</configuration>

**Comment by joelittlejohn** [comment]
You should be able to use this feature by adding `<dependencies>` (with a dependency that points to whatever module holds com.mqa.CustomJackson2Annotator) into the plugin configuration.

**Comment by joelittlejohn** [comment]
Hi. The annotator isn't a project dependency, is a dependency of the
plugin. If you move the dependency inside the plugin element (add a
<dependencies> element there), this will work.

**Comment by HH-Man** [comment]
Thank you, it works now!
