### ISSUE TITLE
'javaInterfaces' which contain generics produce syntactically incorrect imports 

### ISSUE THREAD

**Issue by sberriman** [joelittlejohn/jsonschema2pojo#317]
If is have:
```json
"javaInterfaces" : [
    "com.example.IMyThing<String>"
]
```

Then the generated class incorrectly contains:
```import com.example.IMyThing<String>;```

It does however correctly state:
```public class MyThing implements IMyThing<String>```

This is a necessary usecase for me where an existing set of interfaces, currently used for RMI, are being JSON wrapped for web exposure.

**Comment by joelittlejohn** [comment]
Simon, could you explain what the problem is here? I don't currently understand what's wrong with this import.

**Comment by sberriman** [comment]
Sorry - I forgot to escape the angle brackets. Edited correctly now.

**Comment by joelittlejohn** [comment]
Yes, it doesn't surprise me that this doesn't work. We don't dig deeply into the string value here, we just tell CodeModel to use the string as a type verbatim.

I'll take a look at this for the next release though. I've recently done some work to support endlessly nestable generics in javaType so it should be possible to reuse that here.
