### ISSUE TITLE
Generating inner classes

### ISSUE THREAD

**Issue by nikto123** [joelittlejohn/jsonschema2pojo#318]
When I try to generate java classes from schemas containing definitions of inner classes, they simply get ignored. For example the following input

    {  
        "TestInnerClass":{  
            "title":"TestInnerClass01",
            "type":"object",
            "additionalProperties":false,
            "properties":{  
                "var":{  
                    "type":"string"
                }
            }
        }
    }

and the same goes for another case that I need to get working

    {  
        "definitions":{
            "TestInnerClassA":{  
                "title":"TestInnerClass01",
                "type":"object",
                "additionalProperties":false,
                "properties":{  
                    "var":{  
                        "type":"string"
                    }
                }
            },

             "TestInnerClassB":{  
                "title":"TestInnerClass02",
                "type":"object",
                "additionalProperties":false,
                "properties":{  
                    "var":{  
                        "type":"string"
                    }
                }
            }
        }
    }

**Comment by joelittlejohn** [comment]
You need to refer to these schemas in some way (e.g. `$ref`). This plugin wont do anything with inner nodes of this kind.
