### ISSUE TITLE
default tag doesn't works for empty string

### ISSUE THREAD

**Issue by jakubwierzbowski** [joelittlejohn/jsonschema2pojo#320]
myString : { "type":"string", "default":""}
will generate:

```
private String v;
```

instead of:
```
private String v = "";
```

**Comment by joelittlejohn** [comment]
Thanks for reporting this. We'll get this fixed for the next version. I simply didn't anticipate people doing this so at the moment the plugin only applies the default if the string is not empty.

**Comment by jakubwierzbowski** [comment]
@joelittlejohn PR opened, please review

**Comment by m8r-ubnc5g** [comment]
any update here?

**Comment by m8r-ubnc5g** [comment]
Is this really fixed? I'm using  jsonschema2pojo-ant in version 0.4.15 an I see that there will be no field or getters if the string value in json is empty.
