### ISSUE TITLE
Allow subclasses with no properties

### ISSUE THREAD

**Issue by mikaelec** [joelittlejohn/jsonschema2pojo#326]
As it is now, when trying to generate a class without properties, it is simply skipped.

In our project we have a schema as follows:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "SensorModule",
  "javaType": "dk...SensorModule",
  "extends": { "$ref": "datamodule.schema.json" },
  "properties": {
    "empty": { "type": "string", "description": "This is a hack to force class to be generated" }
  },
  "additionalProperties": false
}
```
Where we've added a dummy-property to force generation. Without the "empty" property, it is skipped by the generator.

**Comment by joelittlejohn** [comment]
This should work, you just need `"type": "object"`in your schema.

**Comment by mikaelec** [comment]
Oh, thanks, will try this tomorrow. :+1:
