### ISSUE TITLE
Use Gson @SerializedName annotation on ALL fields, even when JSON name matches Java name

### ISSUE THREAD

**Issue by smaspe** [joelittlejohn/jsonschema2pojo#327]
gson uses `@SerializedName("json_name")` when the name of the json field and the name of the java field are different. (already present to do the snake case to camel case)

It is also useful when the java code is obfuscated and the name of the java field is modified.

**Comment by joelittlejohn** [comment]
This should already be supported. Could you explain more about how you're
using jsonschema2pojo? Are you using annotationStyle=gson?

**Comment by smaspe** [comment]
I am using the online tool. By checking the Gson annotation style box, I do have `SerializedName ` annotations for fields that don't have the same name in schema and java (such as `field_name` -> `fieldName`), but I would like to have that annotations for all fields, as the actual java field name will be obfuscated.

**Comment by joelittlejohn** [comment]
Ah, I see what you mean. Feel free to submit a pull request for this.

**Comment by PNagesh** [comment]
Hi ,

The @SerializedName doesnt seem to be working for an int value. I'm using java 8 and gson2.2.3. Any  suggestions would be of great help.

**Comment by joelittlejohn** [comment]
@PNagesh I could be wrong, but I don't think you have diagnosed the problem correctly here. There's no reason that `@SerializedName` would fail to work for properties that have an int value when using Gson. Or do you mean using an int as the property key? This is not allowed in JSON.
