### ISSUE TITLE
More options for type mapping. (i.e. Java nio classes). 

### ISSUE THREAD

**Issue by dzonekl** [joelittlejohn/jsonschema2pojo#334]
Currently 'format' allows mapping to some java types. 
How about an option to provide the qualified name of a Type. (As in my case, I would like to map to one of the Java 7 nio types, LocalDateTime). This could look like this:  

"type:"string"
"format":"java.time.LocalDateTime"

**Comment by dzonekl** [comment]
so now I read there is a "javaType" keyword, but is not in the wiki reference guide. That seems to do the trick?

**Comment by joelittlejohn** [comment]
Hi Christophe. The wiki reference guide has an 'Extensions' section which describes the various additional keys added by jsonschema2pojo:

https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#extensions

Cheers

**Comment by dzonekl** [comment]
Ah, sorry I missed that. Thank You. 
BTW, I noticed serialization with jackson failed for a LocalDate Object, is there support for this on jsonschema2pojo level? (which could for example generate:  @JsonSerialize(using = CustomLocalDateTimeSerializer.class))

**Comment by joelittlejohn** [comment]
Hi, no there's no explicit support for this. We don't want to take control
of the serialization to this degree as each project may want to do this
differently. You need to add the jackson-datatype-joda module if you want
to serialize LocalDate.
