### ISSUE TITLE
Support $merge to combine properties from multiple schemas

### ISSUE THREAD

**Issue by dzonekl** [joelittlejohn/jsonschema2pojo#335]
Sometimes, I don't want to wrap the properties from a $ref inside a new property, but would like to mix-them-in. Is this supported? If not, could it perhaps be? 

For example: 

1) This creates a new property "test, which references ViewTest. 

```
"properties":{
    "test":{
        "$ref":"../tests/ViewTest.schema.json",
        "description":"Reference to a test"

    }
},
```

2) A mixin variant perhaps like this (Not wrapped in "properties"), 

```
    "test":{
        "$ref":"../tests/ViewTest.schema.json",
        "description":"Reference to a test"

    }
```

...would produce the properties van ViewTest directly as members in the target class. 
Hope, My question is sufficiently clear :-)

Thanks for this great project!

**Comment by joelittlejohn** [comment]
Hi, I'm not sure I understand what you're proposing here :)

You have a property on an object called 'test' and the schema for its values is in ../tests/ViewTest.schema.json. So instead of having a property on the object, what exactly do you want  in the mixin example?

**Comment by dzonekl** [comment]
Ok, I guess, the reference, shoudn't be wrapped in a propery "test" 
so perhaps something like this: 

"javatype":"ClassWithMixedInProperties"
"mixin":{
"$ref":"../tests/ViewTest.schema.json",
        "description":"Reference to a test"
}

so here...the properties from ViewTest would become properties of ClassWithMixedInProperties. 
The class ViewTest would disappear from ClassWithMixedInProperties altogether, as we are only interested to mixin it's props. 

perhaps an even better syntax would be: 

"javatype":"ClassWithMixedInProperties"
"properties":{
        "irrelevant":{        
        "$mixin":"../tests/ViewTest.schema.json",
        "description":"Reference to a test"
        }
}

does it make sense? If not I will work out the java to make it 100% clear.

**Comment by joelittlejohn** [comment]
Ah, so you'd effectively like to merge two schemas together?

We don't support it, but this is how I'd like to support `allOf`. Simple gather together all the schemas specified, deep merge them together then generate a type from the result.

**Comment by dzonekl** [comment]
yes, merging indeed. so with some degree of control where would allOf appear in a jsonschema?

**Comment by brentryan** [comment]
fyi, this is also part of a change that's being suggested for draft5 of json schema.  A new "merge" keyword.

**Comment by joelittlejohn** [comment]
Thanks @brentryan, I'm going repurpose this ticket slightly as I think $merge is the way to go if we do want to implement this.

**Comment by sharkvan** [comment]
Since it looks like $merge has not made it into draft 5 or 7, is there any intention to support the current recommended what to merge subschemas using allOf?

**Comment by joelittlejohn** [comment]
Closing this as `$merge` was not a successful addition to JSON Schema.
