### ISSUE TITLE
useJodaDates is ignored in Gradle Plugin

### ISSUE THREAD

**Issue by chriskessel** [joelittlejohn/jsonschema2pojo#337]
I'm using 0.4.10. The grade plugin config says:
    boolean useJodaDates = true

gradle generateJsonSchema2Pojo --debug says:
    useJodaDates = false

I know the rest of the config is being parsed since it's using GSON annotations, using Long integers, and so forth.

Using Joda dates works correctly from the command line version (using the -j flag).

**Comment by chriskessel** [comment]
Ah, figured it out. Obvious now that I've seen it. The example gradle plugin README.md (https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/README.md) config mistakenly shows:
boolean useJodaDates = true

But it should just be:
useJodaDates = true

Similarly for a number of other items in the example: removeOldOutput, outputEncoding, useCommonsLang3, and initializeCollections.

**Comment by joelittlejohn** [comment]
Wow, ha, good spot. We're really making it hard for people :)
