### ISSUE TITLE
jsr310 support (Date & Time)

### ISSUE THREAD

**Issue by ben-manes** [joelittlejohn/jsonschema2pojo#339]
As the JDK8 replacement to JodaTime, it would be nice if the `java.time` types were optionally code generated for date type fields.

**Comment by armtuk** [comment]
Second this - need java 8 date time, given that JDK 7 is actually deprecated, and java.util.Date is basically fundamentally broken, this should definitely be an option.

**Comment by ben-manes** [comment]
Unfortunately it gets messy because Android will probably never upgrade to Java 8. So the [Android backport](https://github.com/JakeWharton/ThreeTenABP) may need to be supported too.

**Comment by dmiorandi** [comment]
+1

**Comment by ctrimble** [comment]
Implemented in #469

**Comment by ben-manes** [comment]
Nice job, thanks!
