### ISSUE TITLE
using Optional  for non-required values

### ISSUE THREAD

**Issue by holsky** [joelittlejohn/jsonschema2pojo#342]
Currently getters of optional properties return null values when the property is not set. Are there any plans to change this to use Java 8 Optional? I would prefer this over the javadoc comment (required) since that is easily overlooked. 
(If not I might go about implementing that :-)

**Comment by holger-s** [comment]
Currently getters of optional properties return null values when the property is not set. Are there any plans to change this to use Java 8 Optional? 
(If not I might go about implementing that :-)
