### ISSUE TITLE
Handling required as a list correctly

### ISSUE THREAD

**Issue by holger-s** [joelittlejohn/jsonschema2pojo#345]
Currently it seems like "required" fields are properly handled as per json schema v3. However using the "required" list does not work:

"required" : ["locality", "region"],

Since this is not on a node-level, but on a class level I am not sure where to tackle the problem. If you give me a hint I will gladly submit a pull request

**Comment by joelittlejohn** [comment]
Hi there. Support for the `required` rule specified as an array was added by #325, so this should be working for you in 0.4.11. If you aren't yet using this version, could you update and try again?

**Comment by joelittlejohn** [comment]
Feel free to reopen if you're still having problems with 0.4.11

**Comment by holger-s** [comment]
no works like a charm :)
