### ISSUE TITLE
More sophiscated way to detect corresponding type for integer type in json schema?

### ISSUE THREAD

**Issue by entertainyou** [joelittlejohn/jsonschema2pojo#352]
Hi, given JSON like the following

    {
      "foo": 1,
      "bar": 10000000000000000
    }

The type for foo is ``Integer``, however the type for bar is ``Integer`` too, it's it possible to check the value for key, and set type to Long if necessary(even the use long integers is not turned on)?

**Comment by joelittlejohn** [comment]
This isn't really possible with the current JSON support. We generate a schema for the JSON, then generate types from the schema. In this case the schema type is `integer`, so the only way to produce a long is using `useLongIntegers` I'm afraid.
