### ISSUE TITLE
`android.os.BadParcelableException: ClassNotFoundException when unmarshalling` Error Parcelable codes

### ISSUE THREAD

**Issue by simpleton** [joelittlejohn/jsonschema2pojo#354]
I found the pojo generate the json array's parcelable code  like below:
`instance.addresses = ((List<Address> ) in.readValue((List.class.getClassLoader())));`

Maybe, should change to `parcel.readList(myclassList, getClass().getClassLoader());`

**Comment by joelittlejohn** [comment]
Would it be possible for you to manually edit your generated class and let
me know if using readList fixes the problem?

**Comment by simpleton** [comment]
OK, wait a moment.

http://stackoverflow.com/questions/18126249/badparcelableexception-classnotfoundexception-when-unmarshalling-myclass-wh

**Comment by simpleton** [comment]
Yep, it works. 
I change the read code to : 
`in.readList(instance.addresses, Address.class.getClassLoader());`

And chang the write code like below:
`dest.writeList(addresses);`
