### ISSUE TITLE
Allow get/set methods to be disabled, use public fields instead

### ISSUE THREAD

**Issue by simpleton** [joelittlejohn/jsonschema2pojo#355]
In Android platform, we've to face to 64K method issue. 
Is there any method in pojo could disable generate the get/set method, access the parameter directly.

Thx~

**Comment by joelittlejohn** [comment]
Hi, this is only currently possible using a custom RuleFactory. This sounds
like a good enhancement though, happy to accept a PR that allows the plugin
to generate public fields and no accessor methods.
