### ISSUE TITLE
How could I get the SNAPSHOT lib for gradle

### ISSUE THREAD

**Issue by simpleton** [joelittlejohn/jsonschema2pojo#357]
I want to use the latest plugin for my project, I didn't find the snapshot version's gradle path in readme.
How to get it? Thx~

**Comment by ben-manes** [comment]
Currently this project doesn't auto-publish to Sonatype's snapshot repository after a successful travis build. So instead you need to build it locally.

`mvn install` the snapshot, add `mavenLocal()` to your repositories, and then use `latest.integration` as the plugin's version. The [example](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/example/java/build.gradle) project does this for ad hoc testing purposes.

**Comment by simpleton** [comment]
Okay, Thank you for your feedback. But the  `mavenLocal()` didn't work now. That's a other issue #363 .
