### ISSUE TITLE
Is there any method to define the generated class name and path?

### ISSUE THREAD

**Issue by simpleton** [joelittlejohn/jsonschema2pojo#358]
I met a sick case. 
At firstly, I put a `UserInfo.json` in folder `pojo/user/`.  It will generate the `UserInfo.java` file in  `mypackage.pojo.user`.
And then , I create a new json called `Order.json` in `pojo/order/`. There is a parameter called `UserInfo` which is a simple `$ref` to `pojo/user/UserInfo.json`. I found the `UserInfo.java` will be generate in `mypackage.pojo.order`. It will cause a lot of import error in my existed source code.

Is there any method to define the generated class name and path? 
Thank you~

**Comment by joelittlejohn** [comment]
Have you tried adding javaType to your schema? It allows you to specify
fully qualified class name.

**Comment by simpleton** [comment]
javaType will generate a empty class if the class is not existed at that time.

**Comment by joelittlejohn** [comment]
Not sure what you mean by this. When used in a schema, javaType defines the
FQCN. You need to use it the schema your are pointing $ref to.

**Comment by simpleton** [comment]
cool, I make some misunderstanding at last comment. It works for me. Thank you. wish u have a nice weekend.
