### ISSUE TITLE
JsonSchema2pojo doesnot generate POJO

### ISSUE THREAD

**Issue by SaranyaVaradhan** [joelittlejohn/jsonschema2pojo#366]
I was given a pojo like below, 

    {

	"id": "yyy",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"packages": 
	{
		"id": "#/packages",
		"description": "XXX",
		"type": "object",
		"properties": 
		{
			"xx": 
			{
				"description": "Total number of elements in the collection.",
				"type": "integer",
				"minimum": 1,
				"minLength": 1
			}
            ..............
            ...............			
		},
		"additionalProperties": false,
		"required": 
		[
			"xx",
			...
            ... 
		]
	}
    }

When trying to generate POJO with the `Jsonschema2POJO` I just see the package being created with no class files in it. Even no exceptions occur.

When I add a "properties" around the "packages" tag then it generates the pojo but if any other json references this json i get a `"Path not present:packages"` error and moreover it makes the schema invalid.

I want to understand if there is any limitation with the tool on the schema version? Or is there any modifications that has to be done in the jsons provided to make it work with the tool. Please suggest.

**Comment by joelittlejohn** [comment]
Because your schema is hidden inside `packages`, it cannot be seen by jsonschema2pojo. If you want to use this schema, either put it at the root of the file use a $ref to point to it from somewhere else (like `"$ref":"#/packages"`.

**Comment by SaranyaVaradhan** [comment]
Thanks Joe, adding a "ref" did the work.
