### ISSUE TITLE
Autodetect integer type vs long type using maximum/minimum rules

### ISSUE THREAD

**Issue by maksimlikharev** [joelittlejohn/jsonschema2pojo#375]
there is not much slack for the long usage, you either force everything to it or use format  "utc-millisec" 

json schema provides hint,
"minimum" and "maximum"

would be nice to use it and generate data type appropriately.

**Comment by benjefferies** [comment]
@joelittlejohn I have implemented the logic for this enhancement. I can raise a pull request to get this merged back in if you're happy with that. Have ran "mvn install" locally and all tests are passing including the tests I have added.
