### ISSUE TITLE
Allow disabling additionalProperties generation with a global config option

### ISSUE THREAD

**Issue by jfarcand** [joelittlejohn/jsonschema2pojo#376]
Assume you work with an existing set of JSON files that you can't modify. If you be useful to be able to set
```xml
<additionalProperties>false</additionalProperties>
```
in `pom.xml` so the Java Object is generated without `additionalProperties` and without the needs to change the original JSON.

**Comment by joelittlejohn** [comment]
Thanks for raising this. It sounds like a really simple change, I don't see a problem with including this.

**Comment by jfarcand** [comment]
@joelittlejohn That would make it super simple to automate something like
```
JSON Feeds => jsonschema2pojo => Java Object => Cassandra Mapper => Save to Cassandra
```
Right now the Datasax's Cassandra driver complains about
```java
Exception in thread "main" java.lang.IllegalArgumentException: Cannot find matching getter and setter for field 'additionalProperties'
	at com.datastax.driver.mapping.ReflectionMapper$ReflectionFactory.createColumnMapper(ReflectionMapper.java:230)
	at com.datastax.driver.mapping.AnnotationParser.convert(AnnotationParser.java:160)
```
Thanks for the fast answer!

**Comment by joelittlejohn** [comment]
Another benefit of doing this: at present if you use source type 'JSON' there's no way to indicate that you want to disable additional properties, so it's not possible to turn them off. With this change they could at least be turned off globally.
