### ISSUE TITLE
Unable to parse Swagger 2.0 JSON Schema using online form http://www.jsonschema2pojo.org/

### ISSUE THREAD

**Issue by aruizca** [joelittlejohn/jsonschema2pojo#381]
You can find the schema here: https://raw.githubusercontent.com/swagger-api/swagger-spec/master/schemas/v2.0/schema.json or here http://54.69.214.189/v2/schema.json
I was able to generate the pojos using: 

```
'org.jsonschema2pojo:jsonschema2pojo-core:0.4.13'
```

but the end result is wrong

**Comment by aruizca** [comment]
I was wrong. The parsing process finishes but there are missing POJOs

**Comment by AlexanderYastrebov** [comment]
Online generator says `There's a problem: Path not present: definitions`

**Comment by samuelfac** [comment]
you can generate using: https://github.com/swagger-api/swagger-codegen

Or people implements the same rulles on jsonschema2pojo.

**Comment by unkish** [comment]
@joelittlejohn I believe this issue can be closed as www.jsonschema2pojo.org generated output with content from [link](https://raw.githubusercontent.com/swagger-api/swagger-spec/master/schemas/v2.0/schema.json) provided in comment (not sure whether all classes got generated)

**Comment by AlexanderYastrebov** [comment]
Old but gold, thank you folks for bringing up memories :smile:
