### ISSUE TITLE
Could we make com.google.android a runtime dependency?

### ISSUE THREAD

**Issue by vanDonselaar** [joelittlejohn/jsonschema2pojo#384]
Hi @joelittlejohn, thank you for your great work on this project so far.
Today I was curious why my artifacts grew with 12M after upgrading to the latest `jsonschema2pojo` version and it turned out that `com.google.android` `android` was added as a transitive compile dependency. (see https://github.com/joelittlejohn/jsonschema2pojo/commit/e7733e98bab009a48f7d41b0c1e19fa1b0eed70a#diff-906c17c246c6f4f2a015305eaf37d20fR26).
Could you mark that dep as a runtime dependency with:

```xml
<scope>runtime</scope>
```
Or does that break stuff?

**Comment by joelittlejohn** [comment]
Are you embedding jsonschema2pojo into your own project? The best option
here would be to simply exclude the android dependency.

I'm reticent to remove this dependency as it's an odd thing to have to add
a project dependency to use a plugin. The plugin classpath and the projects
compile classpath are not the same thing and I'd prefer to avoid
introducing confusion here.

**Comment by vanDonselaar** [comment]
> The best option here would be to simply exclude the android dependency.

At first I was uncertain if it would break some functionality but I ended up excluding it from the project. Works fine! Thanks.

> The plugin classpath and the projects compile classpath are not the same thing and I'd prefer to avoid introducing confusion here.

Makes sense. :+1:
