### ISSUE TITLE
Allow custom names to be supplied when creating an enum

### ISSUE THREAD

**Issue by kerr23** [joelittlejohn/jsonschema2pojo#385]
Howdy,

Having a heck of a time figuring out how to use enums as i'd like:

The examples show:
"myEnum" : {
                "type" : "string",
                "enum" : ["one", "secondOne", "3rd one"]
            }

but what I really want is
myEnum = {
ONE (1),
TWO (2),
THREE (3) 
}

Thanks

**Comment by joelittlejohn** [comment]
Ah, there's no feature that allows you to specify custom names for your
enums. The tool will simply generate a java-safe name from the given value.

**Comment by kerr23** [comment]
Ah thanks! Do you think that a custom type would work in this case?

**Comment by joelittlejohn** [comment]
It's just about possible (custom type, plus custom Jackson serializer) but
would be very complicated solution I think.

I'd suggest just using 1, 2, 3. You'll get underscores added as a prefix to
make a Java-safe name. I guess this may have been an example and not the
actual values you have. Either way, I'd simply allow the plugin to decide a
name and don't get to particular about the code produced. It's never going
to be as perfect as a hand-written API, but you'll get most benefit if you
go with the flow. Hopefully the generated values are at least
human-readable on some level.

**Comment by kerr23** [comment]
Well, imagine a status flag where in the database it's represented as 1,2,3,4 but in the app it's ACTIVE/PENDING/CANCELLED/REMOVED. That's really all i'm trying to make happen. The custom type + custom jackson serializer seems like it may be too complicated to be good. I'll try to think of something else. Thanks!

**Comment by joelittlejohn** [comment]
I guess ideally you'd like some way of annotating the enum values to dictate the Java names. Since the values sit alone in a plain array, there's no real opportunity to add additional metadata. I guess we could have something alongside the enum values like:

```json
{
  "type" : "integer",
  "enum" : [1, 2, 3, 4],
  "javaEnumNames" : ["ACTIVE", "PENDING", "CANCELLED", "REMOVED"]
}
```

**Comment by kerr23** [comment]
Yeah something like that would be awesome. I think then mybatis/jackson would "just work"
