### ISSUE TITLE
add copy code button in the generated code dialog to copy codes easily

### ISSUE THREAD

**Issue by ajaykmeher** [joelittlejohn/jsonschema2pojo#387]
Hi,

One of wonderful project but still has room for enhancement. This is not an issue but an enhancement for the website. Please add copy generated code button in the generated code dialog.

**Comment by joelittlejohn** [comment]
Done. When you click Preview now, you'll see a 'Copy to Clipboard' button. Try a hard refresh if this doesn't show.

Thanks for the suggestion!
