### ISSUE TITLE
Object generator does not produce camel-case attribute if starting by @

### ISSUE THREAD

**Issue by d4rxh4wx** [joelittlejohn/jsonschema2pojo#388]
Hi

If i write a json schema like this one, with an attribute starting by @:

```
{
  "type":"object",
  "properties": {
    "@id": {
      "type": "string"
    }
  }
}
```

Java object is generated with an attribute starting by an uppercase I ("Id" instead of "id"):

```
@JsonProperty("@id")
private String Id;
```

This was tested with 0.4.10, and with http://www.jsonschema2pojo.org/

**Comment by antoine-richard** [comment]
It seems like when a property starts with an [illegal character](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/NameHelper.java#L30) or an underscore, it ends up to an UpperCamelCase attribute in Java.

It looks like a bug to me. I'm working on a PR.

**Comment by joelittlejohn** [comment]
I haven't checked the code yet, but I must admit I'm a little surprised by this one. I would have expected `_Id` as typically we replace illegal chars with underscores.

I think this probably means that the propertyWordDelimiter config is being applied _after_ chars are escaped, which I think is wrong.

**Comment by antoine-richard** [comment]
Yes, illegal chars are replaed first.

**Comment by antoine-richard** [comment]
Simply switching the order of the operations brings some questions:

* should  `@id` translate to `_id` or `_Id` ?
* What about the getter/setter : `get_Id` / `set_Id` ?
* What is expected for an illegal character in a middle of a property (`foo@bar`) ?


Isn't it better to treat illegal chars like this:

* Starting illegal chars are squashed: `@id` -> `id` / `getId` / `setId`
* Other illegal chars are treated like underscores: `foo@bar` -> `fooBar` / `getFooBar` / `setFooBar`

This is the behavior implemented today, except for `@id` which translates to `Id`/ `getId` / `setId`.

**Comment by antoine-richard** [comment]
To be clear, today's behavior is:  `@id` => `Id`/ `getId` / `setId`.
It doesn't work for us in our Jackson serialisation. `Id` and `getId` are considered as two distinct properties (we expect `getId` to be the setter of `id` not `Id`).

I looked into switching the order of the operations as you mentionned. It brings some questions:

* should  `@id` translate to `_id` or `_Id` ?
* What about the getter/setter : `get_Id` / `set_Id` ?
* What is expected for an illegal character in a middle of a property (`foo@bar`) ?

What do you think about treating illegal chars like this?

* Starting illegal chars are squashed: `@id` -> `id` / `getId` / `setId`
* Other illegal chars are treated like underscores: `foo@bar` -> `fooBar` / `getFooBar` / `setFooBar`

**Comment by joelittlejohn** [comment]
This works as expected on the latest version:

```java
public class Example {

@JsonProperty("@id")
private String id;

@JsonProperty("@id")
public String getId() {
return id;
}

@JsonProperty("@id")
public void setId(String id) {
this.id = id;
}

}
```
