### ISSUE TITLE
Can't handle enum values that only differ by a symbol

### ISSUE THREAD

**Issue by deanmorin** [joelittlejohn/jsonschema2pojo#389]
I have a `Grade` enum with the values `A` and `A+`.

When it generates the java file, it seems that it tries to give the same enum name to both values. This results in the invalid java below (specifically `A("A", "A+")`:

JSON schema snippet:

    "grade": {
      "description": "blah blah blah",
      "enum": [
        "A",
        "A+",
        "B",
        "C",
        "D",
        "E",
        "F"
      ],
      "schemaVersion": 1,
      "tag": [
        "some_tag"
      ],
      "type": "string"
    },

Generated POJO snippet:

    @Generated("org.jsonschema2pojo")
    public static enum Grade {

        A("A", "A+"),
        B("B"),
        C("C"),
        D("D"),
        E("E"),
        F("F");

**Comment by joelittlejohn** [comment]
We're restricted by Java to a small range of chars here so we simply can't support certain inputs automatically (certainly not in a way that produces legible output). For instance, another problematic example would be `"enum": ["A+", "A#"]`.

I'm going to mark this as a wontfix, and suggest that anyone who has this problem should use the new `javaEnumNames` extension property. It allows you to choose custom names for your constants.
