### ISSUE TITLE
Option for generating CamelCase names

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#39]
_Original author: winson.q...@gmail.com (January 25, 2012 19:35:34)_

There is currently no way to ask jsonschema2pojo to generate the camel case names. This will be great feature.

We should also be abl to specify this as the default on higher level (like the class level) so we don't have to do that for every property.

_Original issue: http://code.google.com/p/jsonschema2pojo/issues/detail?id=39_

**Comment by djarnis73** [comment]
I'm in the process of converting some maven project to gradle and got bitten by the fact that that gradle plugin does not have a default value for this setting. Is that an oversight or by choice?

When adding the property like:
```groovy
jsonSchema2Pojo {
    propertyWordDelimiters = "- _"
}
```

The generated code was the same as with the maven plugin. If I can figure out how to set a default value in the gradle plugin I can submit a PR.

**Comment by thachhoang** [comment]
@djarnis73 There's an open ticket for this bug: #162.
