### ISSUE TITLE
"extends" keyword created incorrect POJO

### ISSUE THREAD

**Issue by osvaldor** [joelittlejohn/jsonschema2pojo#393]
I have this defined in my json schema, but the generated pojo for class X instead extends from XParent not Y. How can I resolve this?

"extends": 
    {
      "$ref": "#/definitions/model::domain::controlevent::ops::y"
    }

**Comment by joelittlejohn** [comment]
Where $refs are used, it's recommended to use `javaType` in the referenced schema to control Java type names. For more info see #164.
