### ISSUE TITLE
[Maven Plugin] define the parent className of a json schema.

### ISSUE THREAD

**Issue by theyankee76** [joelittlejohn/jsonschema2pojo#396]
Hi,

When I use the schemaMapper to generate a pojo, I'm able to define the className of the generated pojo. It's very convenient to avaid weird className.
When I want to generate pojo by using the maven plugin, the className is automatically computed from the fileName. 
In my case, I have some schema url like http://localhost/models/customer-v0.0.1 . This example will generate a class CustomerV00. But I would prefer to have a class named Customer. 

So, would it possible to such configuration available with the maven plugin ? Or at least would it possible to use the title included in the schema if present ?

Best regards,
Sébastien

**Comment by joelittlejohn** [comment]
Hi Sébastien. You can achieve this using `javaType` in the parent schema.

**Comment by theyankee76** [comment]
Hi,

Sure but how to do it without adding specific fields in my schema ?

Thanks,

**Comment by joelittlejohn** [comment]
There's no other way to dictate the class name of the parent I'm afraid.

**Comment by theyankee76** [comment]
Maybe you could use the title of the schema which is a generic field ?
