### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ok11** [joelittlejohn/jsonschema2pojo#399]
Well, not really a bug report, rather a question. Is there a special reason to have a dependency on the whole android platform? It is a 12M jar, additionally packaged, which does not make much sense if you are not running on android, rather in the Web world.
Would it be possible to separate concerns and introduce two flavors of the core?

T&R, ok11

**Comment by joelittlejohn** [comment]
HI ok11, this is a dependency of the plugin as opposed to a dependency for your project. If you are embedding jsonschema2pojo as a library, you can exclude the Android dependency. If you are using jsonschema2pojo as a plugin/tool (Maven, Ant, Gradle, CLI etc) then you have no need to add the Android dependency to the project that uses the _output_ of these plugins.

Maven makes it difficult to have a dynamic dependency. We support generating types for Android (and we build the code required [by referring to parts of the Android SDK](https://github.com/joelittlejohn/jsonschema2pojo/blob/f1f44464b5491a21664416a530a579639e447029/jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/ParcelUtils.java)) and this is why the dependency exists.
