### ISSUE TITLE
Support class inheritance with 'extendsJavaType'

### ISSUE THREAD

**Issue by ahanin** [joelittlejohn/jsonschema2pojo#402]
I found `javaInterfaces` rule useful, but, unfortunately, it doesn't meet all my needs. When generating POJOs I sometimes want them to inherit already existing class, that is not generated from schema, therefore `extends` is not enough.

The solution to this could be a new `extendsJavaClass` rule to compliment `javaInterfaces`, which would take a java type to extends. Generics should be supported too. This way, another feature, is maybe required - reference a class being generated. `extends` and `extendsJavaClass` must be mutually exclusive.

Example (article.schema):

    { "type": "object",
      "extendsJavaClass": "tld.example.Pageable<${this}>" }

`${this}` (or any other placeholder) would have to be replace by the actual class name being generated, e.g.:

    public class ArticlePageable extends Pageable<Article> {
      // ...
    }

**Comment by ahanin** [comment]
The proposed change is reflected in a pull request: https://github.com/joelittlejohn/jsonschema2pojo/pull/403

**Comment by brentryan** [comment]
You can use extends with a javaType field and it works fine with existing classes. Did you try this?

**Comment by ahanin** [comment]
I tried with the latest snapshot and it didn't work for the type. Can you
give an example?

**Comment by joelittlejohn** [comment]
@ahanin an example of what @brentryan is talking about would be:

```
{
  "type" : "object",
  "extends" : {
    "type" : "object",
    "javaType" : "com.example.MyExistingType"
  }
}
```

It's a bit of a workaround and is a bit more intrusive in the schema than you were hoping. I was happy to merge as people have asked about this kind of feature in the past, and it's possible to implement this as a nicely isolated extension property.

**Comment by ahanin** [comment]
Ah, nice. Good to know. I am perhaps documentation blind :)

**Comment by anhquande** [comment]
It works only when using maven jsonschema2pojo:generate.
But when i use "maven clean install", the existing class is changed (generated) by the plugin. That is what it is not supposed to do.

**Comment by ahanin** [comment]
@anhquande would you create a relevant issue?

**Comment by evonsdesigns** [comment]
If you reference a class from one of the dependencies, like where the custom annotator would live, you don't need to add phase.
