### ISSUE TITLE
Add serializable as an optional/configurable option

### ISSUE THREAD

**Issue by samskiter** [joelittlejohn/jsonschema2pojo#404]
Hi, it would be great to be able to mark all my POJOs as serializable. I saw you used to have this feature by default, but removed it (for good reason). In my case, I know that all my POJOs are serializable but don't want to have to mark them all up in the JSON schema. The experimental Parcelable feature isn't working for me either...

Could you maybe add a serializable option to generation? If you prefer, a javaInterfaces option that applies to all POJOs, on top of what they ask for in the schema would be great, but the nice thing about serializable being separate is you could potentially also generate the serialVersionID...

Thanks!

Sam

**Comment by joelittlejohn** [comment]
Sounds like a good, simple config option to add. Happy to accept a PR for this.

Not sure what we should do about generating a serialVersionID (whether to make this random, and different each run, or try to do something more clever). For your use-case, do you care?

**Comment by samskiter** [comment]
Nope, dont care. maybe worth looking what intelliJ does (i think its a random generation)

**Comment by samskiter** [comment]
Working on it here: https://github.com/samskiter/jsonschema2pojo (might submit a pr early, so it's easy to see the diff while working on it)

**Comment by ctrimble** [comment]
Related to #405

**Comment by joelittlejohn** [comment]
Fixed by #549
