### ISSUE TITLE
java.lang.ClassNotFoundException: org.jsonschema2pojo.GenerationConfig

### ISSUE THREAD

**Issue by ArunGan** [joelittlejohn/jsonschema2pojo#407]
I am getting the below error when i compile my pom.xml using mvn clean install command . Can you please help to resolve this ? I have tried using jsonschema2pojo-core as project dependancy and also tried using it as plugin dependancy but i am getting the same error . 

        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfigu
redMojo(DefaultMavenPluginManager.java:474)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:92)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: org/jsonschema2pojo/GenerationConfig
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
1)

POM.XML

![image](https://cloud.githubusercontent.com/assets/13987144/9504386/381f41d4-4bf1-11e5-87f3-dbd30d92838c.png)

**Comment by ArunGan** [comment]
It works by adding the plugin dependancy before the plugin declaration

**Comment by ArunGan** [comment]
I should also add the below dependancy for complete working code

 <plugin>
            <dependencies>
                <dependency>
                    <groupId>org.jsonschema2pojo</groupId>
                    <artifactId>jsonschema2pojo-core</artifactId>
                    <version>0.4.10</version>
                </dependency>
                <dependency>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                    <version>3.3.2</version>
                </dependency>
                <dependency>
                    <groupId>commons-lang</groupId>
                    <artifactId>commons-lang</artifactId>
                    <version>2.4</version>
                </dependency>
                <dependency>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                    <version>2.0.6</version>
                </dependency>
                <dependency>
                    <groupId>org.apache.maven.shared</groupId>
                    <artifactId>maven-shared-utils</artifactId>
                    <version>0.6</version>
                </dependency>
                <dependency>
                    <groupId>com.sun.codemodel</groupId>
                    <artifactId>codemodel</artifactId>
                    <version>2.6</version>
                </dependency>
                <dependency>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                    <version>2.4</version>
                </dependency>
            </dependencies>

**Comment by denlap007** [comment]
Thanks! Worked fine for me too! Added the extra dependencies stated above and the error's gone.

**Comment by joelittlejohn** [comment]
I'm confused by this. If you are using the maven plugin there should be no need at all to add `jsonschema2pojo-core` to your project's dependencies. I'm wondering if the `jsonschema2pojo-core` jar for 0.4.14 in your local repository is corrupt?

Rather than adding `jsonschema2pojo-core` as a project dependency, try simply deleting `~/.m2/org/jsonschema2pojo` to clear out your local repository and build the project again.

**Comment by denlap007** [comment]
At the time, I did not use the Maven plugin, so I had to manually add the libraries.
