### ISSUE TITLE
Duplicate Methods Generated, "-" Characters in Node Names Lead to Compilation Errors

### ISSUE THREAD

**Issue by ironlotus** [joelittlejohn/jsonschema2pojo#409]
I was trying to create a POJO class from your code at jsonchema2pojo.org. I'm attempting to map financial queries from the yahoo finance api.

What I did was paste the regular json response from a query to the Yahoo servers for information on the microsoft stock, which I am attempting to create a POJO out of. 

[This](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%3D%22MSFT%22%20&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys) was the query I used. 

This generates 10 classes, with the "Quote.java" class generating duplicate methods. The first instances of said methods are at lines 278, 288, 292. The second instance occurs at 1978, 1988, 1992.

**Comment by ironlotus** [comment]
After examining the given query response further, I suppose that the real issue would be that the given response issues a value to the same (symbol) field twice. The generator reflects by also generating the same code twice in different places.

Also, the generated code is not compilable because a lot of the node names use - .. which is not permitted to be part of a namespace within Java. The generator creates field names with these - characters, thus leading to my compiler yelling at me all over the place.  

It seems that this is actually two corner cases in one.

**Comment by joelittlejohn** [comment]
Thanks for raising this and describing/investigating the problem further.

I'm not sure what you're referring to with the `-` chars. You mention that the generator 'creates field names with these - characters' however this plugin will actually replace illegal chars like `-` with an underscore. Alternatively, if you have `-` in your propertyWordDelimiters then it will remove the `-` character and make the character following the hyphen uppercase in the field name (hyphen is one of the default delimiters, so this is the default behaviour).

Regarding duplicate 'symbol' field, I'm not sure this is a problem we should attempt to fix. Your JSON is not invalid (strictly speaking) however there is no Java type that can be used to represent this data. None of the data binding libraries supported by this project (Jackson 1.x/2.x, Gson) could represent this data accurately. At least the compile error produced accurately describes the problem.
