### ISSUE TITLE
Maven Extensibility

### ISSUE THREAD

**Issue by Jonbond009** [joelittlejohn/jsonschema2pojo#413]
Unable to create pojo from plain json NOT json schema.

Are there configurations for the plugins to convert regular json to a pojo like what happens at the original webpage? Is there also configurations to add those same check boxes in maven i.e. for gson or jackson?
Would really like the idea of dynamically creating java objects from json data.

**Comment by joelittlejohn** [comment]
Yes, all these configuration options are available. The full documentation for the Maven plugin is here: 

http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.14/generate-mojo.html

If you want to generate POJOS from JSON instead of JSON Schema, use:

```
<sourceType>JSON</sourceType>
```
