### ISSUE TITLE
Generate classes and fill them with data from JSON

### ISSUE THREAD

**Issue by Kuci** [joelittlejohn/jsonschema2pojo#414]
Hello, I would like to use this library not only for generating Java classes, but for filling them with data from the JSON too.

Let's say I have this JSON saved as database.json:
```
[
    {"firstName":"John", "lastName":"Doe"},
    {"firstName":"Anna", "lastName":"Smith"},
    {"firstName":"Peter", "lastName":"Jones"}
]
```
Now, I would like to produce classes Person and Database, where Database holds a field `Person[] persons` which will be initialized, for example, like this:
```
Person[] persons = new Person[] {
	new Person("John", "Doe"),
	new Person("Anna", "Smith"),
	new Person("Peter", "Jones")
};
```
Is this possible ?

**Comment by joelittlejohn** [comment]
No this isn't possible, this library is designed to be used with a data binding library like Jackson or Gson. Check out [Jackson databind](https://github.com/FasterXML/jackson-databind/) the ObjectMapper class that it provides will do what you need. Once you have generated your types using jsonschema2pojo, you can use the ObjectMapper to create instances from JSON data.

**Comment by Kuci** [comment]
Well, I don't wanna do that at runtime, I just want to have it hard coded it generated classes. I don't need to parse JSONs at runtime.

**Comment by joelittlejohn** [comment]
It sounds like what you need doesn't relate to JSON at all then, and is
more a question of general purpose Java generation. This library isn't
intended to do that kind of thing.
