### ISSUE TITLE
The following valid JSON does generate the class files

### ISSUE THREAD

**Issue by arya6000** [joelittlejohn/jsonschema2pojo#417]
The following is valid JSON, but jsonschema2pojo does not generate java classes for this.

["AjaxResponse","OK","UPLOADED",{"FileName":"8.jpg","Size":101376,"Id":"7swJ1kTeJEJtiQAx","SpaceLeft":26235904}]

**Comment by joelittlejohn** [comment]
Hi. Unfortunately this plugin can't generate types for arrays with mixed content. This is a good example where we can't create a common super-type between these values. When we encounter an array, we use the first element to decide the type.

**Comment by arya6000** [comment]
Thanks for the explanation. Are there any plans to add support for this?

**Comment by joelittlejohn** [comment]
I'm interested to know, what Java output would to like to be generated here?
