### ISSUE TITLE
generateJsonSchema2Pojo task fails with unclear exception

### ISSUE THREAD

**Issue by Kuci** [joelittlejohn/jsonschema2pojo#418]
I've been working on a projects which contains a buildSrc project and a subproject. If the buildSrc project uses codemodel library and the subproject uses jsonschema2pojo gradle plugin, then build of the subproject fails with the following error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Subproject:generateJsonSchema2Pojo'.
> com.sun.codemodel.JClass.narrow(Lcom/sun/codemodel/JType;)Lcom/sun/codemodel/JClass;
```

**Comment by Kuci** [comment]
I've just solved the problem. The thing was my buildSrc project had been using different version of codemodel library than jsonschema2pojo gradle plugin.

**Comment by joelittlejohn** [comment]
Thanks for reporting anyway, will be a useful result on Google for anyone that has the same problem.
