### ISSUE TITLE
Is there a size limitation?

### ISSUE THREAD

**Issue by dinesh-seattle** [joelittlejohn/jsonschema2pojo#419]
Joe,

I just love your tool but it doesn't love me back!

I use a schema of 1006 lines. Could that be the issue? Please let me know. 

I tried the site, CLI and Java API. I don't see an error/warn/exception, but i don't see a file in the target location. Can you please help me out?

**Comment by ctrimble** [comment]
@dinesh-seattle I am not aware of a size limitation, at least not at 1006 lines.  You have provided very little information here to provide help.  Can you get a simple schema to work?

**Comment by joelittlejohn** [comment]
@dinesh-seattle I think the problem here is that although this file contains a lot of schemas within it (inside the `definitions` property) it is not itself a schema. There is no object at the route which references the schemas held in definitions in any way. This tool will look at the root of this schema and find that there are no types to generate.

**Comment by dinesh-seattle** [comment]
@ctrimble @joelittlejohn  Thanks for your responses.

@ctrimble - I can't share more details here due to some corporate restrictions.
@joelittlejohn - I see what you are saying. I can ask the other team the origin of the file. But do you think it is still a valid json schema, even though it is not processed by jsonschema2pojo?

**Comment by joelittlejohn** [comment]
I'd say this document has valid schemas inside it, but it isn't itself a schema, it's just a json document that contains some schemas.

If I created a second document like this:
```json
{
  "$ref" : "http://api-integration.staples-sparx.com/docs/hog/heart-of-gold.json#/definitions/minimal-hog-request"
}
```

Then I'd have a document that actually contained a schema, and this document would cause something to be generated. I see also that your document contains use of keywords like `allOf`. These aren't supported by this library. I think you may not get on well trying to automatically generate types from this document.
