### ISSUE TITLE
Issue when two arraykeys are the same name but with different case

### ISSUE THREAD

**Issue by arya6000** [joelittlejohn/jsonschema2pojo#420]
If the same json contains two arrays with the same name but with a different case jsonschema2pojo creates two files with the same name but with different case which causes issues on Windows OS since Windows sees both files with the same name. Here is an example

                        "replyTo":{ 
                        }
                        "replyto":{  
                        }

So in the example above both arrays have the same name but with different cases. This results in jsonschema2pojo to create two files one called replyTo,java and one called replyto.java.

When extracting the jar file Windows complains that the file replyTo.java already exists.

**Comment by joelittlejohn** [comment]
As a workaround, you can fix this using `"javaType"` inside the `"replyto"` property schema.

To be honest, it's not easy for us to change. Java is simply not case insensitive when it comes to its own classpath so we don't get the expected exception thrown when we try to create a type that is a case-insensitive match to an existing type.

The same problem exists for Windows users when using JAXB.

**Comment by joelittlejohn** [comment]
Thanks for reporting this by the way, it's useful to at least have this issue appear in Google search results.
