### ISSUE TITLE
Generation Finishes without Exceptions, But no Source is Generated!

### ISSUE THREAD

**Issue by jricardoferreira** [joelittlejohn/jsonschema2pojo#421]
Hi,

Recently I tried to use the jsonschema2pojo utility tool to create the equivalent Java POJOs from a JSON schema, and for some reason that I cannot understand, no source-code is generated, even without any possible errors during the usage.

I tried to generate the source-code using the online, the CLI and the Java API methods, but none of them seem to work with this specific JSON schema. Here is the link to try this JSON schema out:

https://dl.dropboxusercontent.com/u/28422322/SalesCloudDescribe.json

Would someone mind to take a look please?

Thanks,

Ricardo Ferreira

**Comment by joelittlejohn** [comment]
Hi Ricardo, I took a look at your file.

This doesn't seem to be a schema, it seems to be a file that has some schemas within it (inside `attributes`?). This tool can't find these as it has no knowledge of the format of this file. You need to give this tool a schema (or example JSON).

The schemas that I do see deeply nested in this data look strange, there are schemas with `type: string` that also have properties defined (properties only make sense for type: object).

I can't really make any sense of this file. You might be better off getting some example JSON and using source type 'json'.

**Comment by joelittlejohn** [comment]
Maybe you could explain what this file is supposed to be and where it came from?
