### ISSUE TITLE
Update jsonschema2pojo.org to the latest version of jsonschema2pojo

### ISSUE THREAD

**Issue by successhawk** [joelittlejohn/jsonschema2pojo#422]
I used the CLI tool and it supports JSON Schema 4, but the very cool online demo only support version 3.  

You lost me at first because I thought the tool/framework was outdated when I tried the demo. So, this is the main reason you would want to update the demo.  It was a week later that I downloaded the CLI and tried it, only because I couldn't find any alternatives.
Thanks!

**Comment by joelittlejohn** [comment]
Good point. There are also a load of flags and config options that aren't supported by the online tool because they've been added recently and the webapp hasn't been updated in a long time.

Note: we don't support anything like all of v4, only some minor parts of it.

**Comment by successhawk** [comment]
Would it be possible for you to provide a section in the product
documentation of what features of JSON Schema 4 is NOT supported?  I'd hate
to find out the hard way.

**Comment by joelittlejohn** [comment]
The only part of v4 that is supported is `required`:

https://github.com/joelittlejohn/jsonschema2pojo/issues/91#issue-15901954

**Comment by joelittlejohn** [comment]
Website update it's done. It's now using 0.4.15 with a few more config options in the UI.
