### ISSUE TITLE
"extends" schema resolution assumes current schema is at root of file

### ISSUE THREAD

**Issue by markdingram** [joelittlejohn/jsonschema2pojo#425]
Example of a schema that currently fails (also checked with http://www.jsonschema2pojo.org)

```json
{
  "definitions": {
    "parent": {
      "type": "object",
      "properties": {
        "propertyOfParent": {
          "type": "string"
        }
      }
    },
    "child": {
      "type": "object",
      "extends": {"$ref": "#/definitions/parent"},
      "properties": {
        "propertyOfChild": {
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "child": {"$ref": "#/definitions/child"}
  }
}

```

**Comment by wsalembi** [comment]
Can you please release 0.4.16 quickly. All our schemas that use 'extends' are broken when we upgrade 0.4.14 to 0.4.15. 

error:
org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.15:generate failed: Path not present

**Comment by joelittlejohn** [comment]
Hi, I'm just waiting for one more PR to be merged.

It wasn't clear to me that this was a regression introduced in 0.4.15, or
that this change necessarily fixes that problem. Could you provide a schema
that is affected by this? I'd like to confirm that this is now working and
add a test case around it.

It would be helpful if you could mvn install the current snapshot and test
it in your project.

If you are having problems with 0.4.15 I recommend you stick with 0.4.14.

**Comment by wsalembi** [comment]
My schema is very similar to the new integration test in 0.4.15 (jsonschema2pojo-integration-tests/src/test/resources/schema/extends/extendsSchemaWithinDefinitions.json)

I confirm everything is working with the current snapshot. I tested it.
