### ISSUE TITLE
brew install jsonschema2pojo doesn't work on El Capitan, Mac mini

### ISSUE THREAD

**Issue by coderextreme** [joelittlejohn/jsonschema2pojo#438]
brew install jsonschema2pojo doesn't work on El Capitan, Mac mini

**Comment by joelittlejohn** [comment]
Hi, what's the error? I didn't create this recipe (and I don't know much
about the structure of brew recipes) but maybe it hasn't been extended to
El Cap yet (?)

**Comment by joelittlejohn** [comment]
I think the best place to report problems like this is probably here: Homebrew/homebrew#41949

It may also be worth asking @kikuchy if she/he knows about why this formula might not work on El Cap.
