### ISSUE TITLE
$ref in the root causes a failure

### ISSUE THREAD

**Issue by samskiter** [joelittlejohn/jsonschema2pojo#440]
We sometimes have empty schemas that simply refer on to another schema. (The referee schema has a specific name that we use for some other of our systems, but sometimes it doesn't need to define anything new, so we just make it ref somewhere else).

It's perfectly valid in json schema to have:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Answer",
  "$ref": "./answer2.json"
}
```
But this will crash JsonSchema2Pojo with a stackoverflow :(

Sorry!

I'm not sure how to resolve this though. should it make a new class that is a subclass of the referred to class?

```
public class Answer extends Answer2
{
...
}
```

**Comment by ctrimble** [comment]
Reference only schemas should probably generate nothing.  That would be consistent with the way references are handled for properties.

**Comment by joelittlejohn** [comment]
I'm going to close this one as it's effectively the same problem as the open issue #128.
