### ISSUE TITLE
jar files unable to download on chrome,ie and edge

### ISSUE THREAD

**Issue by arshad115** [joelittlejohn/jsonschema2pojo#445]
Chrome marks the site as malicious and does not allow jar files to be downloaded. Please submit a request to review your site http://www.jsonschema2pojo.org/ to Google so they can mark it safe. On Edge and IE nothing happens when you click to download the jar files.

**Comment by joelittlejohn** [comment]
Thanks for reporting this, I wasn't aware of this problem. 

This appears to be new protection in Chrome that simply doesn't allow jar files to be downloaded from unknown sites. I'm not seeing any 'malicious site' warning, only the message _"Example-sources.jar" may harm your browsing experience, so Chrome has blocked it"_.

I'll submit the necessary report to Google and see what happens. It might also be possible to fix this by switching to .jar or .tar.gz.

**Comment by joelittlejohn** [comment]
I've switched this from .jar to a .zip extension. This fixes the problem for me. Thanks again for reporting this.

**Comment by joelittlejohn** [comment]
Note: if you're still having problems here, try a hard refresh to clear your cache. The HTML and JS has changed here so you'll need the latest of both.
