### ISSUE TITLE
jsonschema2pojo.org: refs within definitions to other definitions fails

### ISSUE THREAD

**Issue by chefhoobajoob** [joelittlejohn/jsonschema2pojo#446]
This schema fails with "URI is not absolute":

    {
      "definitions": {

        "RefA": {
          "properties": {
            "something": {
              "type": "string"
            }
          }
        },

        "RefB": {
          "properties": {
            "b2a": {
              "$ref": "#/definitions/RefA"
            }
          }
        }
      },

      "type": "object",
      "properties": {
        "root2RefB": {
          "$ref": "#/definitions/RefB"
        }
      }
    }

**Comment by joelittlejohn** [comment]
Hi, which version are you using? (or are you using the web app?) There was an issue like this fixed recently.

**Comment by chefhoobajoob** [comment]
Ok - I'll keep my eye out for it.  Thanks!

**Comment by joelittlejohn** [comment]
I've updated the site to the latest plugin version (0.4.16) so you should be good to go. I've tested your schema and seen some generated output.

**Comment by chefhoobajoob** [comment]
Ok, it seems that while it does seem to generate types for the schema above, it runs into a different (?) problem with the schema below.

The error I'm getting from the site is: `There's a problem: Path not present: definitions`. Should I open a separate issue?

```
{
   "$schema": "http://json-schema.org/draft-04/schema#",

   "definitions": {
     "NameValuePair": {
       "properties": {
         "name": {
           "type": "string"
          },
          "value": {
            "type": "string"
          }
       },
       "required": ["name", "value"]
     },
     "Namespace": {
       "type": "string",
       "pattern": "^[a-zA-Z_]([0-9a-zA-Z-_.])+[a-zA-Z0-9_]$"
     },
     "Name": {
       "type": "string",
       "pattern": "^[a-zA-Z_]([0-9a-zA-Z-_])+[a-zA-Z0-9_]$"
     },
     "Version": {
       "type": "string",
       "pattern": "^\\d+\\.\\d+\\.\\d+(-([0-9A-Za-z-.]*[0-9a-zA-Z])+)*$"
     },
     "Thing": {
       "properties": {
         "namespace": { "$ref": "#/definitions/Namespace" },
         "name": { "$ref": "#/definitions/Name" },
         "version": { "$ref": "#/definitions/Version"}
       },
       "required": ["namespace", "name", "version"]
     },
     "ThingList": {
       "type": "array",
       "items": { "$ref": "#/definitions/Thing" },
       "minItems": 1
     }
   },
  "type": "object",
  "properties": {
    "things": { "$ref": "#/definitions/ThingList" }
  },
  "required": ["things"]
}
```

**Comment by chefhoobajoob** [comment]
For reference, I can drop that schema [here](http://www.jsonschemavalidator.net/) with the object below, and it parses the schema and validates the object without error, so I don't think the problem is in the schema definition itself:

```
{
  "things": [
    {
       "namespace": "wonky.butt-nugget",
       "name": "bubbly",
       "version": "1.2.3-rc.1"
    }
  ]
}
```

**Comment by joelittlejohn** [comment]
Thanks for the update. I've had a look into this and I can definitely see a problem. It relates to how nested refs are resolved when there is no file but just a string given directly to the plugin (this is how the website works).

I've resolved this using your example so it will be released in the next version. Cheers

**Comment by chefhoobajoob** [comment]
ok - thanks!
