### ISSUE TITLE
Is there any way to merge the pojos rather than creating multiple classes with the saperation of "_" symbol while creation of Pojos from JSON (not schema), If two Json files contains same sub json object?

### ISSUE THREAD

**Issue by sandeepmeenuga** [joelittlejohn/jsonschema2pojo#450]
JSONs:
=========
{
	"person" : {
            "name" : "sandeep",
	    "id" : 12,
	    "address" : {
		"add1" : "ab",
		"add2" : "cd",
		"state" : "up",
		"country" : "India"
	}
   }
}

{
	"employee" : {
              "name" : "rajesh",
	      "id" : 13,
	      "address" : {
		  "add1" : "xy",
		  "state" : "ap"
	}
    }
}

classes:
========

public class Address{
private String add1;
private String add2;
private String state;
private String country;

//setters and getters

}

public class Address_ {
private String add1;
private String state;
}

rather than creating multiple classes(with "_" symbol) is there any way to merge the existing class If we get another "address" json object in another json file.

[JSONFiles.pdf](https://github.com/joelittlejohn/jsonschema2pojo/files/43701/JSONFiles.pdf)

**Comment by joelittlejohn** [comment]
See #453
