### ISSUE TITLE
addtionalProperties type should map to HashMap<String,String>

### ISSUE THREAD

**Issue by dantran** [joelittlejohn/jsonschema2pojo#451]
Not sure my post at https://groups.google.com/forum/#!topic/json-schema/jyJBdqQziqo not showing so I place it here

This json schema structure

    "attributes" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "string"
      }
    },

is mapped  private Map<String, String> attributes = new HashMap<String, String>();  by swagger-codegen

however, jsonchema2pojo creates a new class with the following structure. And I think is not correct. is it a bug in jsonchema2pojo.  Is there a work around?

public class Attributes {

    @JsonIgnore
    private Map<String, String> additionalProperties = new HashMap<String, String>();

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    @JsonAnyGetter
    public Map<String, String> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, String value) {
        this.additionalProperties.put(name, value);
    }

    public Attributes withAdditionalProperty(String name, String value) {
        this.additionalProperties.put(name, value);
        return this;
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(additionalProperties).toHashCode();
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Attributes) == false) {
            return false;
        }
        Attributes rhs = ((Attributes) other);
        return new EqualsBuilder().append(additionalProperties, rhs.additionalProperties).isEquals();
    }

}

**Comment by dantran** [comment]
my bad, i posted on the wrong group :-)

**Comment by joelittlejohn** [comment]
Hi, this isn't a bug, this is simply how this library supports additional properties. There are some good reasons for this, one is that adding a property to the schema will not cause so much change in your model.

If you're free to change the schema, one alternative is to use javaType and specify `java.util.Map<String,String>`.

**Comment by dantran** [comment]
that is very interesting, for our case we have a component started out with a set of POJO, one of them has HasMap<String,String> data structure,   the POJO is fed into jackson jsonschema to generate the schema spec, however, on the way back to POJO ( by a client) jsonschema2pojo converts it to new wrapper class of the hashMap.

**Comment by joelittlejohn** [comment]
So you start with Java, create JSON schema, then convert the JSON schema back to Java? What's the reason you can't use the Java you started with?

**Comment by dantran** [comment]
the rest client side is not allowed to use the internal POJO, instead they have to use json schema spec

**Comment by joelittlejohn** [comment]
I find it strange that you start with a JSON Schema, then create POJOs from it, then generate a new JSON Schema from the POJOs. If the last step ignores Jackson annotations then there are many ways in which the output will be invalid (the schema generation _must_ not ignore JsonProperty and JsonValue annotations.

I'm happy to accept a PR for this if you want to add a `useUppercaseEnums` config flag (default: `true`).

**Comment by dantran** [comment]
I think your reponse is is wrong issue which should be #452, i will follow up with at that issue

**Comment by joelittlejohn** [comment]
Ah yes, thank you! I've copied this over.

**Comment by joelittlejohn** [comment]
On this one, this is simply a difference in implementation of these two plugins. I think you'll find quite a few differences over time, but since client and server do not share code, I suppose this is not a problem.
