### ISSUE TITLE
Avoid the underscore classes(using JSON not JSONSchema)

### ISSUE THREAD

**Issue by sandeepmeenuga** [joelittlejohn/jsonschema2pojo#453]
I am trying to generate pojos for a json like this 

```json
{
    "order": {
        "id": "1234",
        "objType": "order",
        "priceInfo": {
            "currencyFormat": "$0.00",
            "currency": "USD",
            "amount": "70.91",
            "isDiscounted": true
        },
        "shippingGroups": [
            {
                "id": "1234",
                "objType": "shippingGroup",
                "priceInfo": {
                    "currencyFormat": "$0.00",
                    "currency": "USD"
                }
            }
        ]
    }
}
```

the generator ends up creating two clasees PriceInfo and PriceInfo_

What would be the best way to just generate one PriceInfo. Also in some cases i might have the second priceInfo object have an extra property. I would like to have one PriceInfo with 3 properties rather then two price info objects.

**Comment by joelittlejohn** [comment]
The generator does not know that priceInfo in the outer object, and priceInfo in the inner object are the same, hence it generates a second class and disambiguates them using the `_` character.

Your options here are either:

1. Merge the JSON before you give it to the plugin
2. Use a schema instead, and use a `$ref`
