### ISSUE TITLE
Covariant builders - copy builder methods from superclass, with narrow return type

### ISSUE THREAD

**Issue by blizznets** [joelittlejohn/jsonschema2pojo#455]
In case I have, for example, super class for all my responses with such schema (Response.json):

	{
	  "$schema": "http://json-schema.org/draft-04/schema",
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
		"error": {
		  "type": "integer"
		}
	  }
	}

and some response that extends it (SomeResponse.json):

	{
	  "$schema": "http://json-schema.org/draft-04/schema",
	  "type": "object",
	  "additionalProperties": false,
	  "extens": {
		"$ref": "Response.json"
	  }
	  "properties": {
		"whatEver": {
		  "type": "string"
		}
	  }
	}

builder method "withError" will be generated for Response only.
So I've got __compilation error__ when tried to do something like this:

	new SomeResponse().withError(0).withWhatEver("somethnig");

But if withError override in each subclass - it will work.

	public class SomeResponse extends Response{
		...
		
		public SomeResponse withError(Integer error) {
			super.setError(error);
			return this;
		}
		
	}

Is it possible to fix it?
Thanks a lot so helpfull tool!

**Comment by joelittlejohn** [comment]
This sounds possible. I'm interested to know if this is something people regularly run in to, as no-one has mentioned this in the past.

Rather than trying to find the setters, the simplest implementation would probably be:

* For each withXxx method in the superclass, introduce a withXxx method on the subclass
* The implementation in the subclass would:
    * call super.withXxx, passing the arg straight through
    * cast the returned value to narrow the type

**Comment by blizznets** [comment]
@joelittlejohn Thanks for reply.
Just one question: m.b. better just return "this", and ignore result of calling super.withXxx(), with out type casting?

**Comment by joelittlejohn** [comment]
Even better, I like it!

**Comment by blizznets** [comment]
@joelittlejohn great! )
I'll waiting for new version with fix!

**Comment by joelittlejohn** [comment]
@blizznets I'm happy to accept a pull request if you want to fix this.

**Comment by blizznets** [comment]
@joelittlejohn ok )
Could you please assist me and help to find entry point to fixing it?

**Comment by joelittlejohn** [comment]
Which part are you having trouble with?

**Comment by joelittlejohn** [comment]
Closed by #458.
