### ISSUE TITLE
Question: how to influence generated class/field names

### ISSUE THREAD

**Issue by chefhoobajoob** [joelittlejohn/jsonschema2pojo#457]
I have a schema which defines an object with a property whose value must be an instance of a v4 schema defining an object. The definition looks like so:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
  	"Schema": {
      "properties": {
        "$schema": {
          "type": "string",
          "format": "uri",
          "enum": ["http://json-schema.org/draft-04/schema#"]
        },
        "type": {
          "type": "string",
          "enum": ["object"]
        }
      },
      "required": ["$schema", "type"]
    }
  },
  "properties": {
    "schema": { "$ref": "#/definitions/Schema" }
  },
  "required": ["schema"]
}
```

The generated code for this schema includes the `$` character in field and type names, but I'd like for it to use some other character. Is there a way to control this? I'm using the gradle plugin to generate the classes.

**Comment by chefhoobajoob** [comment]
...looking to avoid problems that may arise due to the answer to [this StackOverflow question](http://stackoverflow.com/questions/19529603/any-risk-using-a-single-dollar-sign-as-a-java-class-name).

**Comment by joelittlejohn** [comment]
No, this isn't possible I'm afraid. You can customize any type name using javaType, but you can't customize field names I'm afraid.

**Comment by chefhoobajoob** [comment]
Ok - I'll try something else. Thanks!
