### ISSUE TITLE
Description conflicts do not resolve correctly.

### ISSUE THREAD

**Issue by steowens** [joelittlejohn/jsonschema2pojo#460]
In the current implementation if you have a construct such as:
Bar.json
``` 
{
   "type":"object",
   "properties":{
        "barProperty": {
              "$ref":"Foo.json",
              "description":"The bar property description."
        } 
    }
 }
```
Foo.json
```
{
    "type":"object",
    "description":"A general description of foo."
   "properties":{
   }
}
```

When Bar.java is generated the barProperty will receive the description "A general description of foo." rather than the description "The bar property description."  This is in spite of the fact that the Foo description does not account for context but the bar property description does.

**Comment by joelittlejohn** [comment]
I'm afraid this is actually as specified in JSON Schema. When you use a ref, the *entirety* of the current node is replaced by the contents of the schema that the ref refers to.
