### ISSUE TITLE
Databases element of type array generated class name Databasis instead of Database

### ISSUE THREAD

**Issue by rpatrick00** [joelittlejohn/jsonschema2pojo#461]
I have a schema that has a property defined like this:

<pre>
                "databases": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": { "type": "string" },
                            "nodes": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": { "type": "string" },
                                        "connectString": { "type": "string" }
                                    }
                                }
                            }
                        }
                    }
                }
</pre>

The code being generated is generating a class named "Databasis" instead of "Database" (singular form of "databases").  How can I get the generator to generate the correct name?

**Comment by joelittlejohn** [comment]
Closed by #462
