### ISSUE TITLE
Problem with multiple generated pojos in Spring-Boot project

### ISSUE THREAD

**Issue by scheung38** [joelittlejohn/jsonschema2pojo#463]
In a Spring Boot project I tried 

jsonschema2pojo -a JACKSON2 -s address.json -T JSON

But the generated Definition is not resolved, is it because there is ambiguity in a Spring-Boot project hence it doesn't know what Definitions to import from?

private Definitions definitions;

Because hovering over Definitions I get 

Definitions -> default package
Definitions -> org.springframework.data.reste.webmvc.json.JsonSch...
Definitions -> com.sun.tools.internals.we.wsdl.document
Definitions -> com.sun.xml.internals.we.writer.document

This could be why I am getting multiply copies of the Pojos?

![screen shot 2015-12-11 at 17 45 55](https://cloud.githubusercontent.com/assets/1273014/11751192/ea4265f2-a02f-11e5-886d-f5b071d63ba9.png)

**Comment by joelittlejohn** [comment]
Multiple classes called 'Definitions' are not a problem for this plugin, as they have different fully qualified names. 

I think you'll need to give an example of you input. I suspect that you are using a JSON file as input to this plugin, and that 'security' appears in many different parts of this JSON file.

**Comment by scheung38** [comment]
for example, myexample.json would look something like this:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#"
  ,"definitions": {
    "_country" : {
      "title": "country.field.label"
      ,"type": "string"
      ,"enum": [
        "country.enum.UK"
        ,"country.enum.DE"
       ]
      ,"format": "country"
      ,"minLength": "2"
      ,"maxLength": "2"
    }
  }
}
```

**Comment by scheung38** [comment]
Or is the order of pojo generated dependent on how the data is structured?

**Comment by joelittlejohn** [comment]
Tried this at jsonschema2pojo.org and I don't see any problem with the generated output. I'm going to close this as we don't have enough to go on.
