### ISSUE TITLE
$ref creates classes with _ instead of using the existing standalone class when .. is used in path

### ISSUE THREAD

**Issue by ddossot** [joelittlejohn/jsonschema2pojo#467]
Using `0.4.17` Maven plugin.

When referencing an object schema from another object (say from a property) I end up with two classes for the schema, one named after it and one named after the property name from the reference point. I similarly end up with duplicate classes ending with `_` when referencing schemas in array types.

To work around this, I had to use `javaType` in all referenced schemas to make sure only one class gets generated.

To be frank, I find this weird because I've been using jsonschema2pojo for a while and this behaviour is new to me.

**Comment by joelittlejohn** [comment]
Thanks for reporting this, does this occur in 0.4.16? It would be useful if we could narrow this down.

**Comment by joelittlejohn** [comment]
If you fancy a challenge, you could try a `git bisect` to find the offending commit :)

**Comment by ddossot** [comment]
I've tried versions up to `4.0.10` and I still get the same behaviour: duplicated classes get generated with a different name, on some cases it's the referring field name and on some cases it's appended with `_`.

I guess it's safe to assume I must be doing something stupid because others would have reported the problem long ago.

**Comment by joelittlejohn** [comment]
@ddossot Did you work out what was going wrong here? Do you think it was down to an error in your input or an error in the plugin?

**Comment by ddossot** [comment]
Thanks for poking me, it actually got me thinking and I believe I know what's going on.

I've refactored my multi module Maven in a way that schemas are in a different module than where jsonschema2pojo codegen happens. So I went from a situation where the directory that contains the schema files was defined relatively to one where it is defined absolutely. In the former case, the same schema loaded directly from the source dir and via a $ref yields a single Java class. In the latter case, it's as is the same schema is not being resolved as being the same file when loaded from the source dir and via $ref.

That's why I had to add Java class names in them, to force codegen to create a single class. But that's kind of ugly.

Do you think it's a bug? That can be solved? Any other workarounds? My schemas don't contain an id field: do you think it could help solve the issue (I'm on the road and can't try myself).

**Comment by dadrus** [comment]
It seems to me that this issue is also solved by the commit referenced by #481. Would you please check it?

**Comment by ddossot** [comment]
@dadrus Just tried with a fresh build of `0.4.19-SNAPSHOT` but to no avail: I still end up with duplicated classes ending with `_`

**Comment by dadrus** [comment]
@ddossot The corresponding code is available in my forked repository in the *schema_id_support* branch.

**Comment by ddossot** [comment]
@dadrus Just tried and same behaviour: duplicated class ending with `_`, even if the `id` field is set.

**Comment by rozhok** [comment]
I have a bit different issue but with same result: 
given two schema files - address.json and custom_address.json
when I run jsonschema2pojo
then I've got Address.java and Address_.java files as results.

**Comment by dadrus** [comment]
@ddossot Could you please send me your schema (or an example) which I can use to check?

**Comment by ddossot** [comment]
@dadrus While working on creating a minimal example that shows the issue, I've found out that the trigger to the problem is actually to use `..` in the `sourceDirectory` path.

So, to reproduce, access schemas with:

    <sourceDirectory>${basedir}/../my-schemas</sourceDirectory>

and you will get duplicated classes with `_`

**Comment by ddossot** [comment]
I have decided to close the issue because, now that the root cause is identified (`..` in path), the fix IMO should be to avoid using this kind of path navigation and instead use fully resolved absolute paths.

In my case, it's as trivial as using `${project.parent.basedir}` instead of `${project.basedir}/..`

**Comment by vinothswaminathan** [comment]
The above issue happens, if the json has nested classes with the same class objects.
eg. 
{routes: {"origin" : {"address":"1st street", "boundary" : {"lat":123, "lng":345}}, "destination":{"address":"2nd street", "boundary":{"lat":893, "lng":192} }

the resulting files for boundary class would be Boundary.java Boundary_.java

Is there any way to override any function in NameHelper class to avoid this ? probably allow it to overwrite the file with same name (without _) or stop writing to the same file again ?

**Comment by thachhoang** [comment]
@vinothswaminathan you can use [the `javaType` property](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#javatype) to let the plugin know those objects should be the same type.
