### ISSUE TITLE
Datetype plugin parameter/argument not working

### ISSUE THREAD

**Issue by swapdh** [joelittlejohn/jsonschema2pojo#471]
Hi,
I am trying to use dateType parameter to use java.time.LocalDate for dates but it doesn't work instead it creates a string type. I am using Java 8 and 0.4.18 version of jsonschema2pojo plugin. 

I am not sure if I need to set another parameter or I am using wrong name.
I peeked in to source code and I didn't see Parameter set for dateType which I guess used JCommander to set parameters for GenerationConfig.

could you please advice, I really need to use java.time.LocalDate instead joda LocalDate.

Thanks.

**Comment by joelittlejohn** [comment]
Maybe @dmiorandi could offer some help here?

**Comment by dmiorandi** [comment]
Hi  @swapdh, I'm not using directly jsonschema2pojo but I'm using raml-jaxrs-maven-plugin that create an instance of org.jsonschema2pojo.DefaultGenerationConfig directly and it works, so core is ok.
Could be a specific cli issue.

Could you provide you cli command to check in same condition?

**Comment by joelittlejohn** [comment]
This should be fixed in 0.4.22.

**Comment by swapdh** [comment]
Thanks Joe for fixing it. I had work around it earlier using
CustomRuleFactory.
