### ISSUE TITLE
Tool is not generating POJO for the below JSON data

### ISSUE THREAD

**Issue by manjunathrao** [joelittlejohn/jsonschema2pojo#472]
Hey Joe,

Thank you for all your efforts for putting up this epic tool. I was just trying your tool by using the JSON data from the link: "http://demo.codeofaninja.com/tutorials/json-example-with-php/index.php"

I did copy paste the entire thing inside the text box and when I chosse "Preview", nothing is being displayed. Am I missing anything?

Thanks, 
Manjunath

**Comment by manjunathrao** [comment]
Sorry  for the spam, i had the options mis-selected. It is working fine now. Thank  you.

**Comment by joelittlejohn** [comment]
Thanks for mentioning that you resolved this.
