### ISSUE TITLE
How to use gradle jsonschema2pojo plugin in android studio？

### ISSUE THREAD

**Issue by ecitshark** [joelittlejohn/jsonschema2pojo#474]
I has used other plugins in android studio .but this plugin i can not use
Thanks!

**Comment by joelittlejohn** [comment]
Could you explain what you mean by 'can not use'? What's stopping you? Are you getting an error?

**Comment by joelittlejohn** [comment]
I wonder if #495 is the kind of change you need? 0.4.20 should come with improved Android support. It would be useful if you could try this version when it is released (or install a 0.4.20-SNAPSHOT locally and try it).
