### ISSUE TITLE
Enums with only one value should be constant

### ISSUE THREAD

**Issue by sebastian-r** [joelittlejohn/jsonschema2pojo#477]
As an enhancement:
If a property in JSON schema is of type enum with only one value, it represents a constant value.
This should result in

``` java
public static final ...
```

**Comment by s13o** [comment]
I'm not agreed with it
Enum in schema can be easily extended\changed in a future. In this case the type of related field in POJO has to be changed. Not nice to have such improvement at all :(

**Comment by joelittlejohn** [comment]
Agree, it's best that these types do not change as an enum grows. In newer drafts of JSON schema, this approach has also been superceded by `const`.
