### ISSUE TITLE
how to add build/generated-sources java files to project

### ISSUE THREAD

**Issue by spark85** [joelittlejohn/jsonschema2pojo#478]
First off I want to thank you for creating this awesome plugin!  Will definitely save me hours on my project.  

How do you add the generated files to your java source files?  I have tried adding this line to my build.gradle file -- java.srcDirs += ['${project.buildDir}/generated-sources/js2p']

and this is my target directory -->   targetDirectory = file("${project.buildDir}/generated-sources/js2p")

Should I have even have to do this?  Why aren't java files under build/generated-sources being picked up by my project? 

Thanks!
David

**Comment by ctrimble** [comment]
Have you taken a look at the example?  https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/example/java/build.gradle

**Comment by joelittlejohn** [comment]
@spark85 I believe this will be fixed by #495 when it's released in 0.4.20. It would be very useful if you could install a 0.4.20-SNAPSHOT locally and let me know if it solves your problem.
