### ISSUE TITLE
ConstructorsIT fails under Windows

### ISSUE THREAD

**Issue by dadrus** [joelittlejohn/jsonschema2pojo#486]
Jsonschema2PojoRule fails in classNameToPath on Windows with IllegalArgumentException "character to be escaped is missing" in the second replaceAll. Because of this ConstructorsIT fails as well.

**Comment by joelittlejohn** [comment]
I'm not a Windows user but thanks for reporting these issues. I would certainly like the tests to work everywhere.

I'm wondering if you have any time to look into a fix for these and submit a pull request? I don't have easy access to a Windows development.

**Comment by dadrus** [comment]
Here is the first one. I'll see weather the others can be fixed on a short notice as well.

**Comment by joelittlejohn** [comment]
Great, thanks!

**Comment by joelittlejohn** [comment]
Fixed by #488.
