### ISSUE TITLE
Question: How to refer to the json schema from a dependancy jar file in the sourceDirectory pom.xml 

### ISSUE THREAD

**Issue by ArunGan** [joelittlejohn/jsonschema2pojo#491]
I am using jsonschema2pojo-maven-plugin-0.4.10 . I have two maven modules - One is module_schema and another one is module_application . The JSON files are in the module_schema and the project dependency is added in the module_application's pom.xml . The maven pluginjsonschema2pojo  used in the module_application's pom.xml to generate the java classes. How to refer to the json schema files in the module_schema project , when i compile i am getting error as the file path is not found in module_application but actually the  json schema files in the dependency JAR(module_schema). Does this plugin require that the JSON schema files to be physically available in the same project where it is being used ?

**Comment by joelittlejohn** [comment]
If you have schema files on the classpath, you can refer to these like classpath://

**Comment by dadrus** [comment]
Using classpath means, the json schema files are poluted with java elements. Would something like
https://github.com/highsource/maven-jaxb2-plugin/wiki/Referencing-Resources-in-Maven-Artifacts be maybe more prefereable?

**Comment by joelittlejohn** [comment]
@dadrus I don't think this issue is related to `$ref` values inside the shema. It relates to how the plugin can reference schemas from another module as input. The plugin can read input files from classpath (and resolve relative refs from then on) by using a `classpath://` URI as the source.

**Comment by ArunGan** [comment]
Thank You John , Can you check my syntax ? I am getting below error , 
 <groupId>org.jsonschema2pojo</groupId>
                <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                <version>0.4.10</version>
                <configuration>
                    <sourceDirectory>classpath://src/main/resources</sourceDirectory>
                        <targetPackage>com.examples.bean</targetPackage>
                </configuration>

[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.10:generate (default) on project , Unable to parse source: classpath://src/main/resources: unknown protocol: classpath

**Comment by ctrimble** [comment]
My references look like this:

```
{
  "$ref": "resource:/path/to/schema.json"
}
```

**Comment by joelittlejohn** [comment]
* Anything in src/main/resources will be added to the root of the classpath by Maven, so I suspect that your schemas are actually in:

    `classpath:/schemafile.json`

    Try opening the jar file for this schemas artifact and checking where the schemas actually are.
* You can't refer to directories in this way, only individual schema files (as there's no way to list the directory contents via the classpath).
* Looking deeper into the code here, I do think this feature may be restricted to use in `$ref` only. We pass the input to the generator as a URL, so this cannot support protocols like `resource` and `classpath`.

    You might be able to workaround this by using an empty schema with just a `$ref` inside, but you'd have to do this for every schema you want to generate.

Another option here would be to simply copy and extract the artifact as part of your maven build, then use the extracted files as your input.
