### ISSUE TITLE
Avoid first letter capitalization if property starts with an underscore

### ISSUE THREAD

**Issue by giacgbj** [joelittlejohn/jsonschema2pojo#493]
If you have a property which starts with an underscore, the resulting Java variable's first letter is capitalized.
The underscore is not an illegal character and, in any case, I'd expect the resulting Java code should follow Java naming conventions, which require lowercase first letter.

This issue is related to #388.

**Comment by joelittlejohn** [comment]
Tested this at jsonschema2pojo.org with the latest version (1.1.0). This looks to work correctly now.

If you have underscore present in your 'propertyWordDelimiters', then the underscore is stripped (as it is assumed to be a separator):

```java
public class Example {

@JsonProperty("_id")
private String id;

@JsonProperty("_id")
public String getId() {
return id;
}

@JsonProperty("_id")
public void setId(String id) {
this.id = id;
}

}
```

If you want to retain underscores in the Java name, just remove the underscore from propertyWordDelimiters:

```java
public class Example {

@JsonProperty("_id")
private String _id;

@JsonProperty("_id")
public String get_id() {
return _id;
}

@JsonProperty("_id")
public void set_id(String _id) {
this._id = _id;
}

}
```
