### ISSUE TITLE
Generate referrable constants for field names from schema

### ISSUE THREAD

**Issue by Chessray** [joelittlejohn/jsonschema2pojo#497]
Would it be possible to include an option to generate constants with the JSON property names from the schema?

Background: We're using JSON schemas in Camel routes and must refer to certain elements for things like splitting. Would be nice if the generator created constants with the respective property names so we can ensure consistency at compile time if the schema changes.

**Comment by joelittlejohn** [comment]
I'm araid I don't see this being included in the core of this project as it simply doesn't provide a wide enough benefit to justify the extra feature being maintained. You might find it useful to use this project as a guide on how to use CodeModel to generate such an enum. It would be quite easy to read the JSON and do this.

**Comment by harel-e** [comment]
+1 to this request.
I currently need to maintain a separate constants class. 
I hope you'll reconsider.
