### ISSUE TITLE
The upper case JSON names

### ISSUE THREAD

**Issue by dinya007** [joelittlejohn/jsonschema2pojo#502]
There is a bug with JSON filed name converting.

If JSON filed name consist of upper case characters then result Java field name also consist of upper uase characters.

I'll create a pull request which fixes this bug.

Thank you.

**Comment by dinya007** [comment]
I don't have enough permissions for creating new branch

**Comment by joelittlejohn** [comment]
Hi. The way to do this with GitHub is to fork this project, create a branch on your fork, add commits there then submit a pull request.

If you Google for 'how to pull request' I think GitHub have a guide. Hope this helps.

**Comment by thachhoang** [comment]
Duplicated and fixed by #563.

**Comment by joelittlejohn** [comment]
@safar What version are you using?
