### ISSUE TITLE
Can't Avoid Generating Upstream Classes

### ISSUE THREAD

**Issue by EngineerBetter** [joelittlejohn/jsonschema2pojo#505]
I have two schemata: `Address` and `Account`.

`Account` has an `Address` field. In order to allow my schemata to develop independently they each exist in their own Maven project.

`Account` depends on the Maven project for `Address`, and the `$ref` for the address field looks up the `Address` schema via classpath resolution.

When I generate sources for `Account` it _also_ generates another `Address` class. This is superfluous as I already have that in the `Address` project, and I don't need a separate one creating.

I can see that the gap is that when the plugin is generating sources for `Account` it can't possibly know that `Address` exists as a class on the classpath, as it can't be sure what package that class was put in. I'd suggest an assumption that all dependee classes exist in the same package, or possibly allow this to be configured.

**Comment by joelittlejohn** [comment]
One solution you can use here is the javaType keyword in the Address schema. It's a good idea to use this whenever you intend to use $refs. If javaType contains a type name that is already oh the classpath, no new type wewill be generated.

You may not like having to add java-related content into your schema, but it really is a good idea to give each schema a canonical/universal java name. It's the best solution available here I think.

**Comment by EngineerBetter** [comment]
Thanks! I'll run this past the rest of the team, and see what the consensus is regarding allowing Java-specific stuff into the schemata.

In the mean time I've been doing ungodly things with the Maven Clean Plugin :)
