### ISSUE TITLE
Regression: when a extending a schema with a redefinition of the same field, with methods should be generated only once

### ISSUE THREAD

**Issue by peterhendriks** [joelittlejohn/jsonschema2pojo#507]
When upgrading from version 0.4.16 to a higher release we've encountered the following issue: when redefining the same field as in a extended schema, the corresponding "with" method is generated twice: once with a @Override, and once without. This means the generated code does not compile. Not that the get and set are generated once, but without an @Overrride, although these methods also override base methods.

In 0.4.16, only the "with" method without the Override annotation is generated. We currently use this to restrict and default certain fields in subtypes, this blocks us from upgrading to a higher release.

Full example given the following two schema's:
```javascript
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "type": "object",
  "javaType": "BaseEvent",
  "properties": {
    "eventType": {
      "type": "string",
      "required": true
    }
  },
  "additionalProperties": false
}

{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "type": "object",
  "javaType": "SpecificEvent",
  "extends": {
    "$ref": "BaseEvent.schema.json"
  },
  "properties": {
    "eventType": {
      "type": "string",
      "required": true,
      "pattern": "^search$",
      "default": "search"
    }
  },
  "additionalProperties": false
}
```
The following erroneous code gets generated:
```java
public class SpecificEvent  extends BaseEvent
{
    @NotNull
    @JsonProperty("eventType")
    @Pattern(regexp = "^search$")
    private String eventType = "search";

    @JsonProperty("eventType")
    public String getEventType() {
        return eventType;
    }

    @JsonProperty("eventType")
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public SpecificEvent withEventType(String eventType) {
        this.eventType = eventType;
        return this;
    }

    @Override
    public SpecificEvent withEventType(String eventType) {
        super.withEventType(eventType);
        return this;
    }
}
```

**Comment by joelittlejohn** [comment]
Thanks for reporting this. I suspect this was caused by the changes related to #455.

**Comment by peterhendriks** [comment]
Thanks for the quick fix!

**Comment by joelittlejohn** [comment]
No problem. Check out 0.4.20 that is available in central now.
