### ISSUE TITLE
jsr310 Not Working in Maven Plugin

### ISSUE THREAD

**Issue by jharnach** [joelittlejohn/jsonschema2pojo#511]
I apologize if this isn't the appropriate place to raise this issue. 

I see that in [this issue](https://github.com/joelittlejohn/jsonschema2pojo/issues/339) JSR310 (java Time API) support was added, but I'm not seeing a way to use it from the Maven plugin. The wiki didn't specify it but looking at the source I assumed I'd just have to add something like this:

`<dateTimeType>java.time.LocalDateTime</dateTimeType>`
` <dateType>java.time.LocalDate</dateType>`

to my Maven plugin configuration. I'm building under Java 8, but the plugin isn't generating java.time.* class members, just java.util.Date ones. The plugin works fine otherwise.

What do I need to do to get the Maven plugin to generate pojos with java.time.* class members ?

**Comment by joelittlejohn** [comment]
My first guess would be that the this feature is not working correctly in combination with another configuration option you are using.

It might be useful to take a look through the integration test for this feature:

https://github.com/joelittlejohn/jsonschema2pojo/blob/de57cc68d6fbaf46eb131aa790270550066d1b16/jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomDatesIT.java
 
and the schema that this test uses:

https://github.com/joelittlejohn/jsonschema2pojo/blob/de57cc68d6fbaf46eb131aa790270550066d1b16/jsonschema2pojo-integration-tests/src/test/resources/schema/format/formattedProperties.json

It would be useful if you could provide the full configuration you're using to invoke the plugin.

**Comment by jharnach** [comment]
Sure thing, here's the relevant section of the POM. I should note we've been successfully using the plugin since 0.4.16, with Joda support. We're only trying to use this feature now that we've moved to Java 8. Joda support worked in Java 8 before the configuration change too.

```
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
     <artifactId>jsonschema2pojo-maven-plugin</artifactId>
     <version>0.4.20</version>
     <configuration>
        <includeToString>false</includeToString>
        <initializeCollections>true</initializeCollections>
        <annotationStyle>none</annotationStyle>
        <includeHashcodeAndEquals>false</includeHashcodeAndEquals>
        <includeDynamicAccessors>false</includeDynamicAccessors>
        <includeJsr303Annotations>true</includeJsr303Annotations>
        <sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
        <sourcePaths>
             <sourcePath>request/MyRequest.json</sourcePath>
             <sourcePath>response/MyResponse.json</sourcePath>
        </sourcePaths>					
        <targetPackage>com.mypackage</targetPackage>
        <outputDirectory>${basedir}/src/main/java</outputDirectory>
        <removeOldOutput>true</removeOldOutput>
        </configuration>
	<executions>
		<execution>
		    <goals>
	                <goal>generate</goal>
		   </goals>
	        </execution>
	</executions>
</plugin>
```

Also, it doesn't look like there's an integration test for java.time.* classes. Am I reading the test wrong ?

**Comment by joelittlejohn** [comment]
Yes, there's no test for those classes as the project itself doesn't
require Java 8. I thought it might be useful to just check the general
approach. Interesting that this only affects those classes but not the Joda
classes, I can't think why this would be.

I'll have a play around and see if I can work out what's happening here.

Thanks for reporting this. I might add a couple of tests that run only when
Java 8 is detected. These would at least be runnable by Travis CI.

**Comment by dadrus** [comment]
What about bindings (as a new feature)? This could enhance the usage of the plugin and remove some complexity.

E.g.
```xml
<formatBindings>
    <binding>
        <jsonType>date-time</jsonType>
        <javaType>java.time.ZonedDateTime</javaType>
        <typeAdapter>my.package.DateTimeAdapter</typeAdapter>
    </binding>
    <binding>
        <jsonType>utc-millisec</jsonType>
        <javaType>java.time.Instant</javaType>
        <typeAdapter>my.package.UtcMillisecAdapter</typeAdapter>
    </binding>
</formatBindings>
```

Comparable things can be done for media encoding and also for user defined types. The `typeAdapter` above is gson specific. For Jackson one woulde define `serializer` and `deserializer` elements. In both cases the adapters or (deserializer) would be optional if the used json library natively supports the (de)serialization of the defined `javaType`.

**Comment by joelittlejohn** [comment]
@dadrus this could certainly be useful, although I do think we have most use-cases covered by the current configuration options (we do need to work out what the underlying issue is here).

**Comment by dadrus** [comment]
I agree. My comment is not really related to the issue. One thing I remember to have encountered in the code is that usage of defaults with java.time  seems to be impossible. The implementation assumes, the corresponding classes are constructable via constructor, which is true for joda and java Date, but not for java.time classes. But this is also not related to the issue here

**Comment by ctrimble** [comment]
@dadrus https://github.com/FasterXML/jackson-datatype-jsr310

**Comment by joelittlejohn** [comment]
@jharnach Could you please test this again with 0.4.22?

**Comment by jharnach** [comment]
@joelittlejohn Excellent, I'm able to use the Java 8 Time API with this plugin now. Thanks!

**Comment by joelittlejohn** [comment]
@jharnach Thanks go to @mmyslyvtsev !
