### ISSUE TITLE
Add a property from schema to the class as an extension 

### ISSUE THREAD

**Issue by ankhia** [joelittlejohn/jsonschema2pojo#512]
Hi, I'm using this library for generate classes from json, 
In the class I need to know the table in database where the data is gonna be stored. But, I don't want to put it like an attribute (property) .. I want to do it in the json header, like the extension adds the package. There's someway to put my own extension to this header. Maybe my english is too bad for understand so the example it will be

```json
{
	"$schema":"http://json-schema.org/draft-04/schema#",
	"type":"object",
	"extendsJavaClass":"com.test.json4java.modelo.ObjetoNegocio",
	
**"tableName":"city"**
	
"properties":{
		"idCiudad":{
			"type":"integer",
			"minimum":1
        },
		"nombreCiudad":{
			"type":"string"
        },
        "departamento":{
        	"$ref":"departamento.json"
        }
	},
    "required":["idCiudad","nombreCiudad"]
}
```

Is like a property but added to the class from header in a way that no matter how many properties you have, you will always have this one ... Like a constant, but not inside the "body".
Can I do something like this right now? 
Sorry for my english... thank you in advance.

**Comment by joelittlejohn** [comment]
The best way to achieve this would probably be a custom annotator. This method, for instance, could be used to read your `tabeName` property from the schema and add something to the class being generated:

```java
void propertyInclusion(JDefinedClass clazz, JsonNode schema);
```

**Comment by ankhia** [comment]
So many thanks!!!! That works perfectly! :)
