### ISSUE TITLE
Extends and allOf referered json schemas should be recognized for all json schema types

### ISSUE THREAD

**Issue by CroniD** [joelittlejohn/jsonschema2pojo#515]
Version 0.4.20

Given json schemas like

NonEmptyString.json

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"type": "string",
		"minLength": 1
	}

OnlyLetters.json

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"extends": {
			"$ref": "NonEmptyString.json"
		},
		"allOf": [{
			"$ref": "NonEmptyString.json"
		}],
		"pattern": "^[a-zA-Z]$"
	}

MyClass.json

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"type": "object",
		"properties": {
			"foo": {
				"$ref": "OnlyLetters.json"
			}
		}
	}

Expected generated class should be

	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Generated("org.jsonschema2pojo")
	@JsonPropertyOrder({
		"foo"
	})
	public class MyClassV1 {

		@JsonProperty("foo")
		@Size(min = 1)
		@Pattern("^[a-zA-Z]$")
		private String foo;
	}

but was

	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Generated("org.jsonschema2pojo")
	@JsonPropertyOrder({
		"foo"
	})
	public class MyClass {

		@JsonProperty("foo")
		@Size(min = 1)
		private Object foo;
	}

**Comment by joelittlejohn** [comment]
Thanks for raising this as it may help others who are Googling. This library doesn't support allOf I'm afraid - we have a few other open tickets to cover this so I'm closing this one.
