### ISSUE TITLE
Enums defined in a separated file should not be generated as member type where it is first referenced

### ISSUE THREAD

**Issue by CroniD** [joelittlejohn/jsonschema2pojo#516]
Version 0.4.20

Given json schemas like

MyEnums.json

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"type": "string",
		"enum": [
			"One",
			"Two",
			"Three"
		]
	}

MyClass.json

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"type": "object",
		"properties": {
			"foo": {
				"$ref": "MyEnums.json"
			}
		}
	}

expected generated classes should be

	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Generated("org.jsonschema2pojo")
	@JsonPropertyOrder({
		"foo"
	})
	public class MyClass {

		@JsonProperty("foo")
		private MyClass .Foo foo;
	}

and

	@Generated("org.jsonschema2pojo")
	public enum Foo {

		ONE("One"),
		TWO("Two"),
		THREE("Three");
		private final String value;
		private final static Map<String, MyClass .Foo> CONSTANTS = new HashMap<String, MyClass .Foo>();

		static {
			for (MyClass .Foo c: values()) {
				CONSTANTS.put(c.value, c);
			}
		}

		private Foo(String value) {
			this.value = value;
		}

		@JsonValue
		@Override
		public String toString() {
			return this.value;
		}

		@JsonCreator
		public static MyClass .Foo fromValue(String value) {
			MyClass .Foo constant = CONSTANTS.get(value);
			if (constant == null) {
				throw new IllegalArgumentException(value);
			} else {
				return constant;
			}
		}
	}

but was

	@JsonInclude(JsonInclude.Include.NON_NULL)
	@Generated("org.jsonschema2pojo")
	@JsonPropertyOrder({
		"foo"
	})
	public class MyClass {

		@JsonProperty("foo")
		private MyClass .Foo foo;

		@Generated("org.jsonschema2pojo")
		public enum Foo {

			ONE("One"),
			TWO("Two"),
			THREE("Three");
			private final String value;
			private final static Map<String, MyClass .Foo> CONSTANTS = new HashMap<String, MyClass .Foo>();

			static {
				for (MyClass .Foo c: values()) {
					CONSTANTS.put(c.value, c);
				}
			}

			private Foo(String value) {
				this.value = value;
			}

			@JsonValue
			@Override
			public String toString() {
				return this.value;
			}

			@JsonCreator
			public static MyClass .Foo fromValue(String value) {
				MyClass .Foo constant = CONSTANTS.get(value);
				if (constant == null) {
					throw new IllegalArgumentException(value);
				} else {
					return constant;
				}
			}
		}
	}

If an enum is defined inline, lets say in the "definitions" object, then it should be a member type.

**Comment by joelittlejohn** [comment]
When you use $ref values, it's recommended that you use `javaType` as the types generated can be unpredictable and are dependent on the order in which the schemas are read. This is the current behaviour of $ref.

If you separate your enums from your other schemas, you could generate these first. Alternatively, use `javaType` to ensure that every schema has a universal, predictable Java name.
