### ISSUE TITLE
Cannot generate POJO for docker compose JSON schema

### ISSUE THREAD

**Issue by bergtwvd** [joelittlejohn/jsonschema2pojo#519]
Tried to generate POJO for:
https://github.com/docker/compose/blob/master/compose/config/config_schema_v1.json

Does not appear to work, not sure why.

I'd like to get a Java Class with getters and setters for the properties.

**Comment by joelittlejohn** [comment]
This schema uses patternProperties, which is not supported by
jsonschema2pojo.

Might want to direct this plugin at #/definitions/service inside that
schema, and build the outer object yourself.
