### ISSUE TITLE
POJO not created with json with gradle task generateJsonSchema2Pojo

### ISSUE THREAD

**Issue by ssmadhu** [joelittlejohn/jsonschema2pojo#520]
POJO classes are created with json schema but does not work with json.
I am using jsonschema2pojo-gradle-plugin and this is my section in build.gradle
jsonSchema2Pojo {
    source = files("${sourceSets.main.output.resourcesDir}/config/ImportExport.json")
    targetDirectory = file("${project.projectDir}/src/main/java")
    targetPackage = 'com.trimble.fsm.tools.schemas'
    annotationStyle = 'gson'
    sourceType = 'json'
    outputEncoding = 'UTF-8'
}

When i run the task generateJsonSchema2Pojo, and give the source point to a json schema, it works but when i give a json file , pojo classes are not created.

**Comment by joelittlejohn** [comment]
Hi. Which version of jsonschema2pojo are you using?

**Comment by ssmadhu** [comment]
Sorry.I was trying with 0.4.0. It works with 0.4.21.
