### ISSUE TITLE
Required property doesn't seem to work

### ISSUE THREAD

**Issue by ianhj0392** [joelittlejohn/jsonschema2pojo#521]
I'm using the old version of JSON Schema 'required' usage (the boolean value on each individual field) as I remember reading this tool requires (though this may be out of date).  When I set a variable as required, I'll notice in the auto-generated comment in the resulting java file the "(Required)" string, but no enforcement of this requirement seems to be present other than in the comment (and is treated by ObjectMapper in the same fashion as non required fields).

**Comment by joelittlejohn** [comment]
Yes, there's no enforcement of this. These types aren't really designed to enforce the schema constraints, we only read the structural rules in a schema to create a Java type that is able to bind to the data. If you're interested in enforcing these constraints, you may want to look into the JSR-303 support.

There was a feature request raised to enforce this constraint via parameters in the Jackson annotation: #429. This would need to be implemented for both v3 and v4 (old and new) 'required' style.

**Comment by mikegg89** [comment]
adding <includeJsr303Annotations>true</includeJsr303Annotations> to the configuration in the plugin worked for me.
<configuration>
	<sourceDirectory>...</sourceDirectory>
	<targetPackage>...</targetPackage>
	<includeJsr303Annotations>true</includeJsr303Annotations>
</configuration>
