### ISSUE TITLE
Generated enum start with underscore

### ISSUE THREAD

**Issue by npipaliya** [joelittlejohn/jsonschema2pojo#522]
Hello,
I noticed jsonschema2pojo plugin generates enum which start with underscore if I have enum value start with number.
**Json Schema:**
{
    "type": "object",
    "properties": {
        "ExampleObj": {
            "type": "object",
            "properties": {
                "accountType": {
                    "enum": [ "401A", "401B" ],
                    "description": "The referred time display format, either 12 or 24 hour clock."
                }
            }
        }       
    }
}
**Generated POJO:**
@Generated("org.jsonschema2pojo")
public static enum AccountType {

_401_A("401A"),
_401_B("401B");
private final String value;
private final static Map<String, ExampleObj.AccountType> CONSTANTS = new HashMap<String, ExampleObj.AccountType>();

static {
for (ExampleObj.AccountType c: values()) {
CONSTANTS.put(c.value, c);
}
}
private AccountType(String value) {
this.value = value;
}

I want them to generate 401A("401A") instead _401_A("401A"). Can you please help with that?

**Comment by joelittlejohn** [comment]
Unfortunately Java does not allow these identifiers to start with a number, hence the underscore.
