### ISSUE TITLE
Add Moshi to annotation styles

### ISSUE THREAD

**Issue by johnjohndoe** [joelittlejohn/jsonschema2pojo#523]
It would be great if you could add [Moshi](https://github.com/square/moshi) to list of _Annotation styles_ and output the POJOs accordingly.

/cc @square @JakeWharton

**Comment by joelittlejohn** [comment]
I had not heard of Moshi before now, but this should be quite simple to implement. There's an [Annotator interface](https://github.com/joelittlejohn/jsonschema2pojo/blob/f289d5c5eb448dd7c07c4b60caf11bfb8e89deb5/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Annotator.java), and we'd simply need a MoshiAnnotator that's similar to the [Jackson2Annotator](https://github.com/joelittlejohn/jsonschema2pojo/blob/f289d5c5eb448dd7c07c4b60caf11bfb8e89deb5/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java) or the [GsonAnnotator](https://github.com/joelittlejohn/jsonschema2pojo/blob/f289d5c5eb448dd7c07c4b60caf11bfb8e89deb5/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GsonAnnotator.java).

You can create this annotator yourself and activate it via configuration. I'd happily accept this as s contribution to the core though too (assuming the dependencies this would introduce are sane).

**Comment by johnjohndoe** [comment]
@joelittlejohn Thanks for the entry point. I will look into this.

**Comment by johnjohndoe** [comment]
I prepared a first draft on [this branch](https://github.com/johnjohndoe/jsonschema2pojo/tree/moshi-integration). Can you please guide me with the [enum test](https://github.com/johnjohndoe/jsonschema2pojo/commit/5ac876f3d64a1114a94a2f87a117010673e7c8c7#diff-7d9d08cab453826c6f857034b9585b4aR111)?

**Comment by joelittlejohn** [comment]
It looks like you've done very well so far to me.

Re the enum test, what you're trying to do here is use an enum value generated by jsonschema2pojo and see if this actually produces the correct JSON output.

So the assertion [here](https://github.com/johnjohndoe/jsonschema2pojo/commit/5ac876f3d64a1114a94a2f87a117010673e7c8c7#diff-7d9d08cab453826c6f857034b9585b4aR106) should be something like: 

_when I use Moshi to serialize `instance` to JSON, does the value `"4 ! 1"` appear in that output like I expect?_

**Comment by joelittlejohn** [comment]
Another good test would be:

_when I use Moshi to parse some JSON that includes `"enumProperty": "4 ! 1"`, do I see that the value is correctly coerced to the enum value?_

**Comment by johnjohndoe** [comment]
My problem is that *typeWithEnumProperty.json* contains a schema description. I actually do not fully understand what you do to generate POJO from it. I simply used your software with actual JSON documents.

**Comment by joelittlejohn** [comment]
[typeWithEnumProperty.json](https://github.com/joelittlejohn/jsonschema2pojo/blob/66ab825c695d2c9b8e877c1f4a8270d5b5d234fa/jsonschema2pojo-integration-tests/src/test/resources/schema/enum/typeWithEnumProperty.json) simply describes an object, that has one property called 'enum_Property', the property is a string and may only have one of these values: 

`"one"`, `"secondOne"`, `"3rd one"`, `"4 ! 1"`.

So instances of this Java type have a field called enumProperty and it's type is an enum.

The question is really, does Moshi support this kind of thing? Looking at [this EnumJsonAdapter](https://github.com/square/moshi/blob/d29036f3b72915f9d07d2d38b5439d980839eb2b/moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java#L215) I think it does. You just need the *@Json* annotation on each enum constant to specify the strings above. You can do this by implementing this method in the Moshi1Annotator:

```
void enumConstant(JEnumConstant constant, String value);
```

**Comment by johnjohndoe** [comment]
I updated the branch. A test run on the console with _typeWithEnumProperty.json_ looks good so far. 
However, I don't get which types I need to work with when setting up Moshi and an adapter in `enumValuesAreSerializedCorrectly()`. Please find my draft once again on [the branch](https://github.com/johnjohndoe/jsonschema2pojo/tree/moshi-integration).

**Comment by johnjohndoe** [comment]
Ah, understood. The map is just a convenience format to access the values for the test assertion. I updated the branch.

**Comment by joelittlejohn** [comment]
@johnjohndoe I think you're probably all done here. Would you like to submit a pull request from your branch?
