### ISSUE TITLE
How to include a custom annotation on generated classes

### ISSUE THREAD

**Issue by jaabio** [joelittlejohn/jsonschema2pojo#524]
I'd like to add the [immutables annotation](https://immutables.github.io/) (`@Value.Immutable`) to generated classes.  Are there any other options to do so besides modifying the jsonschema2pojo source and implementing a custom Annotator?
Thanks!

**Comment by joelittlejohn** [comment]
Hi, you can do this without modifying the source of the core project. If you implement a custom annotator you can simply include this on your classpath and activate it using the [customAnnotator](http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.21/generate-mojo.html#customAnnotator) config option.

**Comment by jaabio** [comment]
@joelittlejohn Thanks for the response.  I've implemented a subclass of AbstractAnnotator.  I want to apply the annotation at the class level.  I've looked at a couple of the existing Annotator implementations, but they seem to be operating at the field level.  Any suggestions for finding information on implementing class level annotations?

**Comment by joelittlejohn** [comment]
Either of these methods could be used to add a class level annotation:

```java
void propertyOrder(JDefinedClass clazz, JsonNode propertiesNode);
void propertyInclusion(JDefinedClass clazz, JsonNode schema);
```

**Comment by jaabio** [comment]
@joelittlejohn Perfect! Thanks.

**Comment by digitalbuddha** [comment]
@jaabio would it be possible to share your implementation I also use immutables and do a lot of manual fixing after generating my classes

**Comment by jaabio** [comment]
@digitalbuddha sorry, i don't have access to that code anymore.  and i only got as far as implementing the custom annotator.  i didn't actually use the annotator because i had problems configuring my classpath.  but other than than it was 2 or 3 lines of code.  really simple.

**Comment by locofrank** [comment]
I'd love an example annotator -- I'm stuck trying to create one

**Comment by jaabio** [comment]
I'm sorry, I no longer have access to that code :(

**Comment by ctrimble** [comment]
This is an older example, but here is a custom type annotator I was using to deserialize java.util.Set as java.util.LinkedHashSet, before this feature was merged into the project.

```
import java.util.LinkedHashSet;
import java.util.Set;

import org.jsonschema2pojo.AbstractAnnotator;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JFieldVar;

public class CustomTypeAnnotator extends AbstractAnnotator {

  @Override
  public void propertyField( JFieldVar field, JDefinedClass clazz, String propertyName, JsonNode propertyNode ) {
    super.propertyField(field, clazz, propertyName, propertyNode);

    if( field.type().erasure().equals(field.type().owner().ref(Set.class)) ) {
      field.annotate(JsonDeserialize.class)
        .param("as", LinkedHashSet.class);
    }
  }
}
```

I built this in its own module and then included it in my configuration:

```
        <plugin>
          <groupId>org.jsonschema2pojo</groupId>
          <artifactId>jsonschema2pojo-maven-plugin</artifactId>
          <version>0.4.4</version>
          <dependencies>
            <dependency>
              <groupId>ANNOTATOR_GROUP_ID</groupId>
              <artifactId>ANNOTATOR_ARTIFACT_ID</artifactId>
              <version>ANNOTATOR_VERSION</version>
            </dependency>
           ...
          </dependencies>
          <configuration>
            <customAnnotator>FULLY_QUALIFIED_ANNOTATOR_NAME</customAnnotator>
            ...
          </configuration>
          ...
        </plugin>
```

This was enough to get custom annotations on the java.util.Set fields.  Hope this helps!

**Comment by locofrank** [comment]
Thank you - it took me a minute to realize that this has to be created
outside of my project and then included somehow.

**Comment by locofrank** [comment]
I've created my Annotator (just a test version) and now I'm getting class
not found from jspnschema2pojo.

how did you modify the gradle file to add your annotator to the classpath?
where did you add your jar?

Thanks,
Frank

**Comment by locofrank** [comment]
solved that by putting this in build.gradle

classpath files("${project.rootDir}/LocoAnnotator.jar")

**Comment by DiggidyDale** [comment]
@locofrank I was wondering if you show an example of your build.gradle as I am having the same issue but can't seem to get it to work

**Comment by krajkumar303** [comment]
I have provided my approach on the below issue.
#758 https://github.com/joelittlejohn/jsonschema2pojo/issues/758

Add the jar as a dependency to the plugin which will resolve the classNotfound error.

**Comment by shinedeveloper** [comment]
The jar dependency will not work if you clean & build your project from the beginning.
There is an easier fix:
- buildSrc/src/main/java/com/example/MyCustomAnnotator.java
- buildSrc/build.gradle

The `build.gradle` will then look like:
```
repositories {
    mavenCentral()
}

dependencies {
    implementation(
            'org.jsonschema2pojo:jsonschema2pojo-core:1.2.2',
            'com.sun.codemodel:codemodel:2.6'
    )
}
```
