### ISSUE TITLE
Synchronize Gson version

### ISSUE THREAD

**Issue by johnjohndoe** [joelittlejohn/jsonschema2pojo#526]
I noticed that different _Gson_ versions are used throughout the source:

- [`compile 'com.google.code.gson:gson:2.4'`](https://github.com/joelittlejohn/jsonschema2pojo/blob/76bc09a4c545c5b370422b18bd2d226a84d28e9d/jsonschema2pojo-gradle-plugin/example/android/app/build.gradle#L45)
- [`compile 'com.google.code.gson:gson:2.5'`](https://github.com/joelittlejohn/jsonschema2pojo/blob/76bc09a4c545c5b370422b18bd2d226a84d28e9d/jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle#L44)
- [`<gson.version>2.2.4</gson.version>`](https://github.com/joelittlejohn/jsonschema2pojo/blob/76bc09a4c545c5b370422b18bd2d226a84d28e9d/pom.xml#L55)
- [`* Gson 2.2.4`](https://github.com/joelittlejohn/jsonschema2pojo/blob/76bc09a4c545c5b370422b18bd2d226a84d28e9d/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotationStyle.java#L51)

I am not sure if this is intentional.

**Comment by joelittlejohn** [comment]
Thanks. Yes, I expect it would be less confusing if these versions were synchronized in these examples. It doesn't really matter what version we use, as long as it has compatible annotations. The version used by the jsonschema2pojo core obviously doesn't have any impact on the version used by end users (they compile the generated types against their own version).
