### ISSUE TITLE
Add option to make all field private

### ISSUE THREAD

**Issue by frakc** [joelittlejohn/jsonschema2pojo#527]
If I uncheck "Include getters and setters", field are generated as public.
Can you add an option to always generate field as private fields?

**Comment by joelittlejohn** [comment]
Hi. I'm interested to know, what do you intend to do with classes that have no accessor methods and only private fields?

**Comment by joelittlejohn** [comment]
Going to close this for now as I don't think this is worth pursuing.

**Comment by frakc** [comment]
@joelittlejohn in normal cases - nothing:)
But most IDE has option to generate getters and setters, but not all of them has plug-ins with functionality your project provide. Thus it is more comfortable to copy fileds without overscrolling for getter and setters (which will be generated in one click)
