### ISSUE TITLE
Array item type being ignored in favor of field name

### ISSUE THREAD

**Issue by alevinetx** [joelittlejohn/jsonschema2pojo#532]
I have a very simple schema that references another type as the items type for the array:

    "properties": {
    	"projects" : {"type" : "array",
    				   "items" : { "$ref" : "ProjectSummary.jsd" }}
    				
    }

The generated Java, however, isn't creating a List[ProjectSummary], but rather List[Project].  If I change the $ref file name to a non-existing file, I get the expected "Cannot find.... " error.  If I change the field name from "projects" to anything else, ie "projected", I still get a resultant List[Projected].

I'm using version 0.4.22-SNAPSHOT.  If I can provide more information, please let me know what that would be.

Thank you.

**Comment by joelittlejohn** [comment]
This is by design, it's simply the way that types are named by this project. The only way to solve this would be to use the `javaType` rule inside the ProjectSummary.jsd.
