### ISSUE TITLE
Add oneOf/anyOf support for HAL/Hypermedia Schema support

### ISSUE THREAD

**Issue by justjacksonn** [joelittlejohn/jsonschema2pojo#534]
I am trying to figure out how the schema listed here: http://hyperschema.org/mediatypes/hal might work with JSONSchema2Pojo. From a few other issues, it appears that currently anyOf,oneOf, etc are not supported. This makes it impossible to built a model that represents a links response type that can support an array of either a single link via the keyword being the rel name, or a link with multiple hrefs associated with it.

Right now I think the best that can be done is just an array of links each with the rel key inside the link, instead of acting as the property key. For a little more clarity, how would the JSON Schema for the below example appear and still work with JSONSchema2Pojo.
```
{
  "someKey": "someValue",
  "_links": {
    "self": {
      "href": "...",
      "type": "..."
    },
    "prev": [
      {"href": "...."},
      {"href": "...."}
    ]
  }
}
```

**Comment by joelittlejohn** [comment]
It's very difficult to map that schema to Java in any way. Thanks for raising this, but we have many other tickets covering allOf/anyOf/oneOf so I'm going to close this one.
