### ISSUE TITLE
full implementation

### ISSUE THREAD

**Issue by amorenew** [joelittlejohn/jsonschema2pojo#541]
Hi
i wonder if you could make full implementation lifecycle to android and ios
i mean models and model view and calling too
i can help you by the best libraries in android and ios swift

**Comment by joelittlejohn** [comment]
Hi @amorenew could you explain more about what you mean by 'full implementation'? I don't understand what you're asking for here.

**Comment by amorenew** [comment]
i mean convert json to models
and models view that call it in java and swift language too

**Comment by amorenew** [comment]
MVC 
Model - ModelView - ViewController - View

**Comment by amorenew** [comment]
you will make Model and ModelView only with utils too

**Comment by joelittlejohn** [comment]
That sounds like it would be best implemented as another project. That other project can _use_ jsonschema2pojo if it needs to.

**Comment by amorenew** [comment]
i understand you but i am only a mobile developer native ios and android 
i can't fork and modify your library because it's hard to me but i can help in calling the web service to the models and other utils with it

**Comment by joelittlejohn** [comment]
You may not need to modify this library, only integrate it into whatever else you write.

It's not a goal for this project to provide a full lifecycle development experience for Android and iOS, and it's not something that is useful for me. If you can find more engineers to work with then I suggest you build this with a group of people that want such a tool.
