### ISSUE TITLE
Internal references are not working properly

### ISSUE THREAD

**Issue by kayahr** [joelittlejohn/jsonschema2pojo#542]
I noticed that jsonschema2pojo can't handle a large JSON schema I have and which can be successfully used by validators. I always got this error message:

    There's a problem: Path not present: definitions

I stripped down the schema bit by bit to find the part which is responsible for the problem and when I found it there was no error and even no complicated structure. It was only a simple (and correct) property reference. The reason for the failure was the reference level (It was referenced from a referenced type which was referenced from the root type).

Here is a small test schema to reproduce the problem:

    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "definitions": {
            "def1": {
                "type": "object",
                "properties": {
                    "prop1": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            },
            "def2": {
                "type": "object",
                "properties": {
                    "prop2": {
                        "$ref": "#/definitions/def1"
                    }
                },
                "additionalProperties": false
            },
            "def3": {
                "type": "object",
                "properties": {
                    "prop3": {
                        "$ref": "#/definitions/def2"
                    }
                },
                "additionalProperties": false
            }
        },
        "type": "object",
        "properties": {
            "prop": {
                "$ref": "#/definitions/def3"
            }
        },
        "additionalProperties": false
    }

Paste this into the online jsonschema2pojo and watch it fail. If you change the root reference from `def3` to `def2` then it works. Looks like jsonschema2pojo can follow references only two levels deep. It fails when a third level reference is found.

**Comment by joelittlejohn** [comment]
Please retest with 0.4.23.
