### ISSUE TITLE
element of type "array" not generating List

### ISSUE THREAD

**Issue by srperetz** [joelittlejohn/jsonschema2pojo#545]
I have the following 3 JSON files:

foo.json:
```javascript
{
    "description" : "Foo",
    "type":"array",
    "items": {
        "$ref": "bar.json"
    }
}
```

bar.json:
```javascript
{
    "description" : "Bar",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "baz": {
            "$ref": "baz.json"
        }
    },
    "additionalProperties": false
}
```

baz.json:
```javascript
{
    "description" : "Baz",
    "type": "object",
    "properties": {
        "someProp": {
            "type": "string"
        }
    },
    "additionalProperties": false
}
```

I am expecting to get 3 generated classes:

1. Foo.java
  * Should contain an element of type `List<Bar>`.
2. Bar.java
  * Should contain elements `String name`, `String version` and `Baz baz`.
3. Baz.java
  * Should contain element 'String someProp`.

What I actually get is:

1. Foo.java
   * Contains elements `String name`, `String version` and `Baz baz`.
2. _**NO**_ class file Bar.java
3. Baz.java as expected

If I modify foo.json as follows...
```javascript
{
    "description" : "Foo",
    "type":"array",
    "items": {
        "type": "object",
        "properties": {
            "bar": {
                "$ref": "bar.json"
            }
        },
        "additionalProperties": false
    }
}
```

...then I do get Bar.java, and it looks as expected.  However, now, I get Foo.java with a simple element `Bar bar` instead of `List<Bar> bar`.

Please help!  What am I doing wrong here?

Thanks,
Sam

**Comment by samskiter** [comment]
Hmmm, not sure what the correct behaviour should be but i don't think you quite have your schema set up right.

What you have right now says: 

> `Foo` is an array containing `Bar`s

And you said you expect:

> Foo should contains an element of type List<Bar>

You haven't named that element anywhere in your schema?

I think you might want:


```
{
    "description" : "Foo",
    "properties": {
        "someProp": {
            "type":"array",
            "items": {
                "$ref": "bar.json"
            }
        }
    }
}
```

Where `someProp` is the name of the element.

Does that help?

**Comment by srperetz** [comment]
That's perfect, thanks!
