### ISSUE TITLE
Please increase schema length constraint more than 51200 chars

### ISSUE THREAD

**Issue by RamNareshN** [joelittlejohn/jsonschema2pojo#551]
I have a large schema which is more than 51K chars. While generating pojo's using this schema I am getting below length constraint.

_**There's a problem: Your input was larger than 51200 characters, try making this a bit smaller.**_

Could you help me out to execute my large schema.

**Comment by joelittlejohn** [comment]
If you have larger schemas it's best to use one of the plugins to generate code (CLI, Maven, Gradle). The website isn't really there to process large amounts of data.

**Comment by RamNareshN** [comment]
Thank you Joe.

**Comment by pieinfosystems** [comment]
Hi, 
Do you have some ready project to clone, to generate pojo from json schema?

**Comment by annemariepeek** [comment]
I'm trying to generate a pojo from a larger schema via a gradle task, and unfortunately I'm having issues generating. For files with 51k characters and less the gradle task works, so I know I configured it correctly. For the large file the gradle build is successfull, however I don't get the generated output. Is there something I am missing in my gradle task? 

```
plugins {
    id 'java'
    id "org.jsonschema2pojo" version "1.2.1"
}

dependencies {
    ... other dependencies
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.3'
    implementation 'org.jsonschema2pojo:jsonschema2pojo-core:1.1.1'
    implementation 'org.jsonschema2pojo:jsonschema2pojo-cli:1.1.1'
}

sourceSets {
    generated {
        java {
            srcDir "path/to/dir/GeneratedAdaptiveCard"
        }
    }
}

task generateAdaptiveCardClasses(type: JavaExec) {
    main = 'org.jsonschema2pojo.cli.Jsonschema2PojoCLI'
    classpath = sourceSets.main.runtimeClasspath
    args = [
            '--source', "path/to/json/adaptive-card.json",
            '--target', "path/to/target/GeneratedAdaptiveCard",
            '--package', 'com.teams.adaptivecards',
            '--generate-builders',
    ]
}

```

The schema in question is this `[adaptive-card.json ](https://github.com/microsoft/AdaptiveCards/blob/main/schemas/1.5.0/adaptive-card.json)` file from Microsoft (unfortunately there isn't a java SDK for Adaptive Cards). 

Thank you!

**Comment by joelittlejohn** [comment]
I don't know if any limit when using the gradle plugin. The limit only applies to the online generator at jsonschema2pojo.org.

Do you see any errors?

**Comment by annemariepeek** [comment]
No errors. The build is successful however there is no output. The adaptive card schema version 1.1.0 works, however I suspect it's because that schema is significantly smaller (1.1.0 also generates on  jsonschema2pojo.org). Also the flags --info and --debug are quite unhelpful and don't signal any errors

**Comment by unkish** [comment]
It seems that referred schema v. `1.5.0` does not generate any output as it has only 2 "keywords" under root:
```json
    "definitions": {
    ...
    },
    "anyOf": [{
            "allOf": [{
                    "$ref": "#/definitions/AdaptiveCard"
                }
            ]
        }
    ]
```

**Note** that at present jsonschema2pojo does not process
* `definitions` keyword, there is a [PR](https://github.com/joelittlejohn/jsonschema2pojo/pull/1523) to add support for it
* `anyOf`, `allOf`, `oneOf` keywords. There's a [proposal](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Proposal-for-allOf,-anyOf-and-oneOf) and an [open issue](https://github.com/joelittlejohn/jsonschema2pojo/issues/392).
See also https://github.com/joelittlejohn/jsonschema2pojo/issues/1534
