### ISSUE TITLE
Dafult value for enum.

### ISSUE THREAD

**Issue by anuragpro** [joelittlejohn/jsonschema2pojo#552]
As per reference guide, there is no way to set default value for enum.
https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#default

Is this supported?
 Example: 
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "string",
    "default": "com.company.Fruit.APPLE",
    "javaType": "com.company.Fruit",
    "enum": 
    [
        "APPLE",
        "MANGO"
    ]
}
```

This generates:
```java
private Fruit fruit = null;
//getters and setters

I want it to generate:
private Fruit fruit = com.company.Fruit.APPLE;
//getters and setters
```

**Comment by joelittlejohn** [comment]
This isn't currently supported, but I think it could be. I think though your schema should be:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "string",
    "default": "APPLE",
    "javaType": "com.company.Fruit",
    "enum": 
    [
        "APPLE",
        "MANGO"
    ]
}
```

and we should infer the specific enum constant from the value.

**Comment by anuragpro** [comment]
thanks, after auto generating the enum, it worked. Earlier i was referring to self created enum in same package.

**Comment by joelittlejohn** [comment]
Thanks for reporting back! 👍
