### ISSUE TITLE
Add new annotator for Mongo db entities generated by the json schema.

### ISSUE THREAD

**Issue by Vijendra07Kulhade** [joelittlejohn/jsonschema2pojo#553]
This new feature will help jsonschema to use further to generate entities with spring data annotations.
These entities will be directly used by spring data for mongo db. 
Example.
```
@Document
@Generated("org.jsonschema2pojo")
public class Address {

    @Field("c1")
    private String postOfficeBox;
}
```

**Comment by joelittlejohn** [comment]
Should be simple enough to implement this. Take a look at the Annotator interface and some of the existing implementations. There's no need for this to be part of the core, you could implement and release this yourself as a separate module.

**Comment by joelittlejohn** [comment]
A good custom annotator for someone to write, but not part of the core of this project.
