### ISSUE TITLE
Improve naming through extends keyword

### ISSUE THREAD

**Issue by samskiter** [joelittlejohn/jsonschema2pojo#554]
**Problem**
The extends keyword just adds "Parent" to the end of the refrencing schema name. It seems that from any ref, a decent name could be generated deterministically (as it is in JsonSchema2Pojo.java).

The only gap I can see in the current naming rules is for an embedded referenced schema.

So this schema might cause issues:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": { "$ref": "#/definitions/address" }
  }
}
```

And this is just a generalisation of the same thing with the extends keyword, e.g.:

```
test.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",
  "extends": { "$ref": "#/definitions/address" },
}
```

In the first case, the referenced address schema would be Billing_Address.java, which is a bit misleading, but not terrible,

In the second it would be called TestParent.java which is a pretty useless name.

**Proposal**

Come up with a deterministic way of naming schemas, not dependent on the route to that schema.

Currently JsonSchema2Pojo.java can come up with a good name from the path and target package for a given schema file. E.g. if the root directory is `/my/path/to/schema`, the target package is `a.b.c` and the schema is present at `/my/path/to/schema/d/test.json` - the generate class would be `a.b.c.d.Test`.

Now if test.json, the path to the address schema is `/my/path/to/schema/d/test.json#definitions/address` - could this create a class named: `a.b.c.d.Test.definitions.Address` ? I.e. use the jsonRef elements to name/position the class.

In the first example above, test.java looks like:

```
package a.b.c.d;

import a.b.c.d.definitions.Address;

public class Test {
    public Address billing_address;
    public Address shipping_address;
}
```

In the second, it looks like:

```
package a.b.c.d;

import a.b.c.d.definitions.Address;

public class Test extends Address {
}
```

**Comment by samskiter** [comment]
@joelittlejohn This would be a breaking change right? what do you think?

**Comment by dredwolff** [comment]
Why not just make the entities defined in the "definitions" section inner classes?  Instead of Test.definitions.Address you would have Test.Address, and the Java class would closely mirror the JSON schema definition

**Comment by samskiter** [comment]
Gosh it's been a while since I looked at this. I remember [this](https://github.com/joelittlejohn/jsonschema2pojo/pull/561) change was still in for review and I think would help with extends as it started to create some context of where each schema lives....

I think you need definitions because `definitions` isn't a keyword it's just used commonly. How would you cope with:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "someDefinitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },
  "someOtherDefinitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": { "$ref": "#/definitions/address" }
  }
}
```
?

**Comment by zygimantus** [comment]
So what is the solution not to generate "Parent" in the class name?

**Comment by joelittlejohn** [comment]
@zygimantus use javaType in the schema.

**Comment by joelittlejohn** [comment]
I'm going to close this one since if anyone wants to customise the names that jsonschema2pojo chooses it can be done with Java javaType. Also in 1.0.0 we improved the naming when $refs are used.
