### ISSUE TITLE
Constructors are incompatible with extends keyword

### ISSUE THREAD

**Issue by samskiter** [joelittlejohn/jsonschema2pojo#555]
If schema A extends schema B and schema A has properties X,Y and Z and schema B has properties L,M and N and `includeConstructors` is set to true, the constructor of B correctly has arguments for L, M and N but the constructor of A only has arguments for X,Y and Z.

I would expect A to have LMNXYZ in its constructor.

Looking at the code, this looks non-trivial to fix.

**Comment by joelittlejohn** [comment]
Closed by #558
