### ISSUE TITLE
generated class is not have methods from super interface

### ISSUE THREAD

**Issue by muskaanu** [joelittlejohn/jsonschema2pojo#556]
I am using javaInterfaces to add my static interface to generated code. my interface extends 1 more interface. So generated code is not implementing methods from super interface. How can we achieve that?

**Comment by joelittlejohn** [comment]
There's nothing in this tool that will generate methods for these interfaces. Things that appear in javaInterfaces will be added to your class but that's all.

There are a couple of code-level hooks into this library which would allow you to implement some methods if you want. Take a look at the customAnnotator and customRuleFactory.
