### ISSUE TITLE
JSON to JSONSchema

### ISSUE THREAD

**Issue by cemo** [joelittlejohn/jsonschema2pojo#562]
Hi, 

Thanks for your project. It helped me a lot.
I am currently using your plugin in workflow of generating my pojo's from JSON files. However I would like to create JSONSchema by JSON files and then I would like to customize for my needs. 

Thanks

**Comment by joelittlejohn** [comment]
The only tool that I know that can do this is Jackson. It's able to create JSON Schema from JSON data (it's largely how our JSON support works).

This isn't the goal of this project, but you could certainly create a Maven plugin to do this very easily.
