### ISSUE TITLE
Schema "excludes" is not honored when it is referenced in another jsonschema

### ISSUE THREAD

**Issue by thirugnanamsubbiah** [joelittlejohn/jsonschema2pojo#572]
When we explicitly exclude a schema from POJO generation, should that be honored even when it is referenced in another schema or not?

**Change 1:** Make excluded.json invalid
tsubbiah$ git diff src/test/resources/schema/filtering/excluded.json

@@ -1,3 +1,4 @@
+**-an invalid schema file that should not be included.**
 {
     "$schema": "http://json-schema.org/draft-04/schema#",
     "description": "a schema that should be exluded.",

**Change 2:** Include excluded.json in included.json

@@ -5,6 +5,9 @@
     "properties": {
         "prop": {
             "type": "string"
+        },
+        "refExcluded": {
+            "$ref": "excluded.json"
         }
     }
 }

**Run the functional test** in jsonschema2pojo-integration-tests: mvn clean verify

**Failed with below error:**
Results :

Tests in error:
  shouldNotProcessExcludedFiles(org.jsonschema2pojo.integration.filtering.FilteringIT): Unexpected exception, expected<java.lang.ClassNotFoundException> but was<java.lang.IllegalArgumentException>
  shouldIncludeNestedFilesWithFiltering(org.jsonschema2pojo.integration.filtering.FilteringIT): Error parsing document: file:/Users/tsubbiah/public-git/jsonschema2pojo/jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/**excluded.json**
  shouldFilterFiles(org.jsonschema2pojo.integration.filtering.FilteringIT): Error parsing document: file:/Users/tsubbiah/public-git/jsonschema2pojo/jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/excluded.json

Tests run: 358, Failures: 0, Errors: 3, Skipped: 0

**Comment by ctrimble** [comment]
The includes/excludes feature in the maven plugin is intended to control the files discovered while scanning the file system.  The have no effect on schemas discovered through "$ref" keywords.

**Comment by thirugnanamsubbiah** [comment]
Makes sense. 

It would be helpful to document the same in the maven plugin parameters page (on "excludes") at http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.23/generate-mojo.html

It took some time for me to find out why "excludes" not working (caused by $ref).

**Comment by ctrimble** [comment]
The plugin documentation will be updated in the next release.
