### ISSUE TITLE
Generate Long data types

### ISSUE THREAD

**Issue by Eitol** [joelittlejohn/jsonschema2pojo#574]
**Problem**
When I try to generate a POJO using a json containing a large number, which exceeds the maximum value of an integer, the output should contain a data type **Long** instead of **Integer.**

For example:
From this JSON:
{
   "ExpirationDate" 1464226168974
}

The data type associated with the field "expirationDate" must be of type Long, but is generated Integer

**Comment by joelittlejohn** [comment]
There's a config option for this. Try useLongIntegers.
