### ISSUE TITLE
Properties with no name cause an exception during generation

### ISSUE THREAD

**Issue by shishram** [joelittlejohn/jsonschema2pojo#576]
trying to convert Json to POJO and getting Internal server error. Please check.

**Comment by joelittlejohn** [comment]
Could you give me an example of the schema?

**Comment by shishram** [comment]
Here is the Server response which I am trying to convert POJO classes

{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 1,
      "created_by": "id@gmail.com",
      "role_position": "role",
      "title": "Hero",
      "description": "Hero Hero Hero Hero Hero Hero Hero Hero Hero Hero Hero Hero",
      "min_age": 24,
      "max_age": 28,
      "required_gender": "Male",
      "job_type": "type",
      "required_information_to_apply": {},
      "submission_deadline": "2016-05-31",
      "likes": false,
      "images": [
        {
          "title": "bat1.jpg",
          "image": "/media/images/batman_share.jpg",
          "thumbnail": "/media/CACHE/images/images/batman_share/7c0cfe3169b92b575621f44d89ddcd2b.jpg",
          "is_private": false,
          "image_type": "Generic"
        }
      ]
    },
    {
      "id": 2,
      "created_by": "id@gmail.com",
      "role_position": "female lead",
      "title": "Heroine",
      "description": "Heroine Heroine Heroine Heroine Heroine Heroine Heroine Heroine Heroine",
      "min_age": 24,
      "max_age": 28,
      "required_gender": "Other",
      "job_type": "Paid",
      "required_information_to_apply": {
        "": "",
        "Pics": "5",
        "Voice clip": "2"
      },
      "submission_deadline": "2016-05-31",
      "likes": false,
      "images": [
        {
          "title": "bat2.jpg",
          "image": "/media/images/batman_share.jpg",
          "thumbnail": "/media/CACHE/images/images/batman_share/7c0cfe3169b92b575621f44d89ddcd2b.jpg",
          "is_private": false,
          "image_type": "Generic"
        }
      ]
    }
  ]
}

**Comment by joelittlejohn** [comment]
Looks like this is caused by:

```json
      "required_information_to_apply": {
        "": "",
        "Pics": "5",
        "Voice clip": "2"
      },
```

Do you need an empty property in there that has no name or is this an error?

**Comment by joelittlejohn** [comment]
This isn't one I intend to fix (as I think in the vast majority of cases, this is an error).
