### ISSUE TITLE
Remove javax.annotation.Generated as it doesn't ship with Android

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#577]
The goal of adding this annotation is to let tools know that this is generated source and hence probably shouldn't be considered for things like static code analysis. This annotation doesn't ship with Android's Java though, which causes [annoyance for Android developers](http://stackoverflow.com/questions/37046649/pojos-generated-by-jsonschema2pojo-have-annotation-which-android-studio-doesnt).

Let's stop adding `javax.annotation.Generated` entirely.

**Comment by farmazon3000** [comment]
Having this annotation is fine in Android because I can mark (for example for future developers of my code) that they can simplify they lives with it so I'd live it - as you can see in SO it can be easily solved in gradle (with adding a dependency) - however it would be nice to have a checkbox to enable/disable generation of this annotation.

**Comment by samskiter** [comment]
It would be removed for only Android projects by default by adjusting the configuration in `GenerateJsonSchemaAndroidTask`

**Comment by joelittlejohn** [comment]
@farmazon3000 As you say, it's nice to advertise the existence of this project, but this error will waste a lot of engineering time. It's simply not worth sending people to Google and forcing them to add an extra dependency. This annotation hasn't proven useful enough IMO to warrant the annoyance, it's such a trivial thing to break people's projects over.

I like the idea of forcing this off for Android projects. I'm happy to introduce a configuration option here and set the default as described by @samskiter.

**Comment by Clans** [comment]
+1 for removing this

**Comment by joelittlejohn** [comment]
More problems caused by having this annotation: 

https://github.com/andrewkandzuba/jsonschema2pojo-plugin-jdk9

**Comment by ankon** [comment]
FWIW: I actually appreciated the `Generated` annotation on the generated files, because it made Eclipse aware that these files should not be edited.
