### ISSUE TITLE
Java Name is not producing desired output.

### ISSUE THREAD

**Issue by muskaanu** [joelittlejohn/jsonschema2pojo#578]
"bills": {
    "javaName": "models",
    "type":"array",
    "$ref": "../bills.json"
    }

I want to have getModels() and setModels() in generated code. but its generating getBills() and setBills(). Any suggestion how this can be resolved? using 0.4.23 version of  jsonschema2pojo-maven-plugin

**Comment by joelittlejohn** [comment]
When you use a ref, this replaces the *entire* schema at that level (this is according to the JSON schema spec). The only solution here is to use javaName inside bills.json.
