### ISSUE TITLE
Adding custom field String schemaPath

### ISSUE THREAD

**Issue by abhijeetkushe** [joelittlejohn/jsonschema2pojo#579]
Is there a way in which I can add a custom field Schema which stores the path of the json schema file (present in the same jar)
We wanted to use that to create a JsonSchema object belonging to the below repo and use that for validation
https://github.com/fge/json-schema-validator
There are 2 advantages of doing this: 
1) Tighter coupling between the schema version and the Pojo 
2) json schema validation using draft v4 which is not supported by this repo

**Comment by joelittlejohn** [comment]
There's no way to add arbitrary Java output to your types I'm afraid. Of course one option would be to *add a String property to the schema that has a default value* which is the path you need, like:

```json
{
  "type" : "object",
  "properties" : {
    "schema" : {
      "type" : "string",
      "default" : "/path/to/my/schema.json"
    }
  }
}
```

This would show up in the JSON data when using this type which may not be what you want, but it would certainly mean that the path was always available.

You could also *implement a custom annotator* to do this. The annotator can add anything it likes to the generated Java type. Usually the annotator just adds Java annotations, but any of the annotator methods that receive a JDefinedClass could easily add a field to the class too. For examples, see:

https://github.com/joelittlejohn/jsonschema2pojo/blob/873890e93c781d8ee428a765f1ced06c7db36d54/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java
