### ISSUE TITLE
[Possible Bug] Converting enum of variable length values using jsonschema2pojo

### ISSUE THREAD

**Issue by namannigam** [joelittlejohn/jsonschema2pojo#580]
The problem statement is described here as well - [SO-37527859](http://stackoverflow.com/questions/37527859/converting-enum-of-variable-length-values-using-jsonschema2pojo)
 To cut short in brief, I am unable to create/convert a JSON which could result in a similar POJO as following -

```
public enum Info {
    TITLE(45),
    ADDRESS(100),
    NAME(45);

    private Integer maxLength;

    Info(Integer maxLength) {
        this.maxLength = maxLength;
    }

    public Integer getMaxLength() {
        return maxLength;
    }
}
```

**Comment by joelittlejohn** [comment]
This project is about representing JSON data. It looks like your values are (45, 100, etc) exist only in the Java world and not in the JSON. 

This project can't be used to generate arbitrary additional Java I'm afraid, you'll have to maintain some mapping outside your generated types as anything not in the JSON will not be accommodated.
