### ISSUE TITLE
Allow anyOf/oneOf/allOf with one value instead of extends

### ISSUE THREAD

**Issue by christianbalzer** [joelittlejohn/jsonschema2pojo#583]
"extends" was removed in draft 4. Can you allow anyOf, oneOf, allOf with one value only to allow for the same functionality (inheritance)? That way, the JSON schemas would remain compliant with the latest draft of the spec...

http://json-schema.org/latest/json-schema-validation.html#anchor145

**Comment by jmattheis** [comment]
+1

**Comment by ddotpdot** [comment]
absolutely. lot of raml specs I see are structuring their schemas with allOf anyOf. same for $ref support.

**Comment by joelittlejohn** [comment]
Already open as #91.
