### ISSUE TITLE
Is there a way we can define an existing field as deprecated?

### ISSUE THREAD

**Issue by mankr1981** [joelittlejohn/jsonschema2pojo#588]
We have requirement to take one of the existing field as an array now but to keep the back compatibility with existing client created a new field as an array instead of modifying existing one but want to define the existing field as deprecated.
Do we have a way to declare the field as deprecated today?

**Comment by joelittlejohn** [comment]
No sorry, there is no support for deprecation in the JSON Schema spec (there is some discussion of this on the JSON Schema mailing list if you're interested in why it has been omitted so far). This plugin isn't intended to be a general purpose Java code generator so this isn't something I would look to include in the jsonschema2pojo core.

If you wanted to do this yourself, you could create a custom annotator.
