### ISSUE TITLE
Add Custom Annotator To ClassPath

### ISSUE THREAD

**Issue by sathi-007** [joelittlejohn/jsonschema2pojo#594]
hi joe,
Can u please add a example lib with Custom Annotator enabled with gradle plugin. or explain how to add custom annotator.. I am getting error when i tried to add custom annotator in build.gradle file. Please help me..

**Comment by joelittlejohn** [comment]
Sorry, Gradle is not my area of expertise. If you have worked this out, it would be useful if you could post a comment here to help anyone else that finds this via Google.
