### ISSUE TITLE
Adding symbols, JSON->JAVA?

### ISSUE THREAD

**Issue by amitabhuddi** [joelittlejohn/jsonschema2pojo#596]
When I am trying to convert json scheme to java object and I have an enum which are symbols like ":", "<", etc. The problem there is that when these enums are converted to java, they are done as : "__EMPTY__(":", "\u2265", "<");" and this token __EMPTY__ is generating an error which is correct since the names to these symbols cant be found. Any solutions for this problem? Thanks in advance.

**Comment by amitabhuddi** [comment]
PS. I am using Maven plugin to do that.

**Comment by joelittlejohn** [comment]
Could you give me an example?

**Comment by amitabhuddi** [comment]
I have something like this in my json scheme: 
**"operation": {
                        "type": "string",
                        "enum": [ ":", "≥", "<" ]**
when this is converting to java object i get something like this: 
**public enum Operation {

__EMPTY__(":", "\u2265", "<");
private final String value;
......**

**Comment by joelittlejohn** [comment]
Ah, I see. There are no characters in your enum that are valid in a Java identifier.

If you can change the schema, you can add some meaningful names to your enum values using `javaEnumNames` like this:

https://github.com/joelittlejohn/jsonschema2pojo/blob/f23641fb5a492d86f2e8de001299f21353601df8/jsonschema2pojo-integration-tests/src/test/resources/schema/enum/enumWithCustomJavaNames.json

In this case we don't really have anything useful in the schema to use as a Java identifier. There's still a bug though, you should probably have got:

```java
EMPTY(":"),
EMPTY_("\u2265"),
EMPTY__("<")
```
