### ISSUE TITLE
Overriding a class?

### ISSUE THREAD

**Issue by amitabhuddi** [joelittlejohn/jsonschema2pojo#597]
Another problem that I am facing is that for example class A use another class B generated automatically from Json scheme to java code (maven plugin). There is another class C that generates the class class B but with other parameters that are used from class B, which are special for C. 
class A -> class B
class C -> class _B
class D -> class __B, and so on. Classes A, C and D are supposed to use the same class B. 
Is there any solution?

**Comment by joelittlejohn** [comment]
You should look into using $ref for this. Just make sure you give each file
a definitive Java class name using javaType.
