### ISSUE TITLE
Add extension to force generated classes to implement additional interface(s) 

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#60]
_Original author: ottofoni...@gmail.com (July 08, 2012 11:47:30)_

It may be convenient to ask generator to place super class (or interface) reference into generated DTO, for instance

_Schema_
{
...
  &quot;javaType&quot;:&quot;model.json.Buffer&quot;,
  &quot;javaSuper&quot;:&quot;model.AbstractModel&quot;,
  &quot;javaInterfaces&quot;: [&quot;java.io.Serializable&quot;,&quot;api.CustomContract&quot;],
  &quot;properties&quot;:{
    &quot;id&quot;:{
      &quot;type&quot;:&quot;integer&quot;,
      &quot;id&quot;:&quot;id&quot;
    },
    &quot;title&quot;:{
      &quot;type&quot;:&quot;string&quot;,
      &quot;id&quot;:&quot;title&quot;
    }
...
  &quot;type&quot;:&quot;object&quot;
}

_Generated_
...
public class Buffer extends AbtractModel implements Serializable, CustomContract {
    private int id;  
    private String title;
...

It may also generate stub implementations of interface methods automatically if any.

_Original issue: http://code.google.com/p/jsonschema2pojo/issues/detail?id=60_

**Comment by zmeda** [comment]
Can someone please provide an example how to add already existing class into classpath with gradle? Thanks

**Comment by algomaster99** [comment]
Hi! Does this feature exist in the maven-plugin? I cannot seem to find it [here](https://joelittlejohn.github.io/jsonschema2pojo/site/1.1.1/generate-mojo.html).
