### ISSUE TITLE
Using jsonschema2pojo doesn't seem to work for json schemas generated from JAXB objects with Jackson

### ISSUE THREAD

**Issue by edeandrea** [joelittlejohn/jsonschema2pojo#600]
So I'm trying a 2-step process. I have a set of JAXB objects which I've used Jackson to generate JsonSchemas for (see the attached file - Inside it - Header.java is the JAXB-generated file that the xjc compiler generated. Header.json is the json file that was generated using Jackson's JsonSchema).

This is how I generated the JsonSchema (this is all wrapped in a Gradle plugin, so the code is in Groovy):
```groovy
ObjectMapper objectMapper = new ObjectMapper()
objectMapper.setSerializationInclusion JsonInclude.Include.NON_EMPTY
objectMapper.registerModule new JaxbAnnotationModule()
objectMapper.enable SerializationFeature.WRAP_ROOT_VALUE
objectMapper.enable DeserializationFeature.UNWRAP_ROOT_VALUE
objectMapper.disable SerializationFeature.WRITE_DATES_AS_TIMESTAMPS

def schemaGenerator = new JsonSchemaGenerator(objectMapper)
def newClassLoader = new GroovyClassLoader()
newClassLoader.addClasspath project.sourceSets.main.output.classesDir.absolutePath

def jsonSchema = schemaGenerator.generateSchema Class.forName('package.Header', false, newClassLoader)
def file = project.file "$pathToJaxbSourceDir/Header.java"
project.file("$pathToJsonSchemaDir/$file.name".replace('.java', '.json')).text = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString jsonSchema
```

I'd copy/paste my gradle build code for configuring the jsonSchema2Pojo closure, but simply pasting the .json file into your web-based thing (http://www.jsonschema2pojo.org/) - nothing is generated.

[files.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/386300/files.zip)

**Comment by joelittlejohn** [comment]
Hi. The json file you have is not a schema, but it has a schema inside it. You need to give jsonschema2pojo a schema, that is, the map value inside `"ObjectSchema"`.

**Comment by edeandrea** [comment]
If that is the case - then Jackson's conversion from JAXB -> JsonSchema didn't work correctly. I was not in control of the source - what I showed is what Jackson spit out...

**Comment by viksoffice** [comment]
jsonschema2pojo.org isn't generating any class.
