### ISSUE TITLE
Gradle no possibility to specify the ClassName

### ISSUE THREAD

**Issue by jmattheis** [joelittlejohn/jsonschema2pojo#603]
The plugin takes the filename without the extension and set it as class name. This should be possible to configure.

Example.json
```
{
  "type": "object"
}
```

Results in:
```
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({

})
public class Example {
    // additional properties stuff
}
```

**Comment by thachhoang** [comment]
You can override the class name with [`javaType`](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#javatype):

```java
{
    "javaType" : "com.other.package.CustomTypeName",
    "type" : "object"
}
```

**Comment by jmattheis** [comment]
When using just the [embedded version](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Getting-Started#using-jsonschema2pojo-within-your-java-project-embedded) there is also the possiblilty to define the java class name inside the method without the extra property inside the json schema

**Comment by thachhoang** [comment]
@jmattheis If either of those methods work for you, we can close this.

**Comment by thachhoang** [comment]
See also #217.
