### ISSUE TITLE
Additional Properties does not work with gson

### ISSUE THREAD

**Issue by deanmorin** [joelittlejohn/jsonschema2pojo#604]
I have `annotationStyle` set to `gson`.

The generated classes do not have `getAdditionalProperty()`/`setAdditionalProperties(a, b)`.

If I remove the `annotationStyle` option (using the default), then these methods are generated as expected.

**Comment by thachhoang** [comment]
Gson doesn't support dynamic properties the way Jackson does with the annotations `@JsonAnyGetter` and `@JsonAnySetter`. There was a similar discussion in #186.
