### ISSUE TITLE
Reverse the converter? (POJO to JSON)

### ISSUE THREAD

**Issue by rafistrauss** [joelittlejohn/jsonschema2pojo#606]
Perhaps should be its own tool, but I think it could be useful to generate JSON files from Java classes.

**Comment by joelittlejohn** [comment]
Hi. Do you mean generate JSON Schema files? If so I think you might be looking for this:

https://github.com/FasterXML/jackson-module-jsonSchema

If you want to generate JSON from Java instances, then you can use this:

https://github.com/FasterXML/jackson-databind

**Comment by rafistrauss** [comment]
Thanks! Really helpful
