### ISSUE TITLE
equals and hashcode invokes super even if superclass has no fields

### ISSUE THREAD

**Issue by ashish-sharma09** [joelittlejohn/jsonschema2pojo#610]
I can see in the previous pull requests that it was fixed to invoke super equals and hashcode due to older versions not doing the same. This is working all right except for the case (as ours) where top most class in the hierarchy has no fields hence no equals and hashcode implementation generated for the same and the immediate childs of this class ends up calling Objects equals and hashcode which in effect nullifies everything if not comparing same instances.

Due to this issue we are not able to use the latest version of the library. Can this be looked into as soon as possible?

Many thanks and let me know if there are any questions with regard to the same.

**Comment by joelittlejohn** [comment]
Sounds like we need to not call super if the superclass is Object. Happy to accept a PR for this.

**Comment by ashish-sharma09** [comment]
That sounds all right. Let me know once we have fix for this available.

**Comment by joelittlejohn** [comment]
Something is strange here as the implementation already checks whether the current type extends Object:

https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java#L403

https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java#L531

When I generate some types on http://www.jsonschema2pojo.org/ I see no call to super() in the topmost class. Could you provide an example of your input and show the output? What version are you using?

**Comment by ashish-sharma09** [comment]
Sorry, I may not have been clear in my explanation earlier. The issue arises when topmost class in the hierarchy is empty (i.e. it has no fields) and the immediate children of this class invokes super in their equals and hashcode implementation. This call to super gets propagated to Object since topmost empty class do not have equals and hashcode in it. Following are examples for your reference:

The Schema is as follows:
Child
```
{
	"title": "Child",
	"javaType": "com.some.package.Child",
	"type": "object",
	"extends": {
		"$ref": "empty-parent.json"
	},
	"required": true,
	"additionalProperties": true,
	"default": {}
}

```
Parent
```
{
	"title": "Parent",
	"type": "object",
	"required": true,
	"javaType": "com.some.parent.package.Parent",
	"additionalProperties": false
}

```
The generated classes for above will look something like:

Child
```


@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({

})
public class Child
    extends Parent
{

    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().appendSuper(super.hashCode()).append(additionalProperties).toHashCode();
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Child) == false) {
            return false;
        }
        Child rhs = ((Child) other);
        return new EqualsBuilder().appendSuper(super.equals(other)).append(additionalProperties, rhs.additionalProperties).isEquals();
    }
}

```

Parent:

```
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({

})
public class Parent {


    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

}
```

As you can see in Child class above we have **appendSuper** but Parent class has no equals and hashcode, so this call gets propagated to Object.

We have a special case where we need to have empty parent class.

Let me know if there is any doubt.

**Comment by thachhoang** [comment]
ObjectRule does [check for Object superclasses](https://github.com/joelittlejohn/jsonschema2pojo/blob/47ba591d1128c45e0731ab615ef7a455b6a1ab37/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java#L531).

Object.equals will be used if the root class does not have any fields (e.g. `includeAdditionalProperties` set to false) and does not override equals. We can fix this by checking if equals is overridden at any ancestor of a class before using super.equals. We can follow JClass._extends all the way up to Object.

That leaves one edge case: what should the library do if any generated class inherits from an existing non-Object class (because of `javaType`)?

**Comment by ashish-sharma09** [comment]
Sounds fine to me. Checking for overridden equals in the ancestor should take care of this edge case.

**Comment by thachhoang** [comment]
Generated classes are represented in the code model as JDefinedClass. Classes referenced by `javaType` properties will appear as JReferencedClass, which is private.

@joelittlejohn you can get at it with reflections to check for overridden equals, but do we want to rely on non-public API?

**Comment by joelittlejohn** [comment]
The issue I see with reflecting on the parent class (to see if it extends equals) is that this can change. The parent class can be modified to extend equals later, even if it didn't when the types were generated. I prefer to avoid generating different output based on the current context if at all possible as this is often a source of confusion.

I think we should try to stick the following rules, that are based on the content of the input only:

1. If the type extends Object, don't call super.

2. If the type does not extend Object, call super.

3. Always generate hashCode and equals when generating a type. In practice this means we remove this check:

        if (fields.isEmpty()) {
                return;
        }

The problem reported here tells me that overriding hashCode and equals is important, even if the type has no fields.
