### ISSUE TITLE
Default enum value

### ISSUE THREAD

**Issue by vehpsr** [joelittlejohn/jsonschema2pojo#616]
Hi guys.
need help and fail to Google this case.

doc on 'default' feature says

> Default values are supported for the JSON Schema properties of type string, integer, number and boolean; for enum properties; for properties with format of utc-millisec or date-time; for arrays of any of these types.

with table of examples.
though it has **for enum properties;** I fail to find example or force it to work with any amount of guessing.

    "properties": {
        "day": {
            "javaType": "com.test.model.WeekDay",
            "default": "TUE"
        }
    }

'WeekDay' is enum from external lib, and 'TUE' -- enum value.
result is `private WeekDay day = null;`
expected `private WeekDay day = TUE;`

I'm I missing something obvious or there is no way to do this?

jackson 2.3.3
jsonschema2pojo 0.4.18

Thanks and Regards.

**Comment by vehpsr** [comment]
as far as I understand 'default' for enum scope only works in:

    "properties": {
        "day": {
            "type": "string"
            "enum": ["mon", "tue"],
            "default": "tue"
        }
    }

does exist any workaround for my case?

**Comment by joelittlejohn** [comment]
We don't make use of enums that we haven't created. In this case it's not clear how we should create an enum value from the given string (to use as a default).

If you let jsonschema2pojo generate this enum, then the plugin will understand and support it.

**Comment by vehpsr** [comment]
yes, I see that your point is valid.
was just expected something like `@QueryParam`, to init object if declared type has a constructor that accepts a single String argument or static valueOf(...), fromString(...) methods, etc.

is there no possible workaround to inject 'some java code' ? like:

    "properties": {
        "day": {
            "javaType": "com.test.model.WeekDay",
            "default": com.test.model.WeekDay.TUE
        }
    }

see no other alternative than convert field to String :(

**Comment by evonsdesigns** [comment]
@vehpsr Did you ever find a solution to this? When I set "default" for my enum, the value is always set to null. I have tried a bunch of different things:
```
"javaType": "com.test.model.WeekDay",
"default": "com.test.model.WeekDay.TUE"
"default": "TUE"
"default": "WeekDay.TUE"
```
Nothing works!

**Comment by vehpsr** [comment]
@evonsdesigns sorry, didn't use schema2pojo for a long time now.
as far as I can say its impossible (unless you have option to move your enum declaration to `.json` too)
```
"$ref": "my-enum.json",
"default": "ENUM_VALUE"
```
_though not sure that this will work_

**Comment by evonsdesigns** [comment]
@vehpsr No problem. I tried that and did not have any luck:

```json
MyEnum.json

{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "string",
  "enum": ["A", "B"],
  "javaEnumNames": ["A", "B"]
}
```
and
```json
Implementing Object.json
{
...
   properties: {
     ...
    "resourceType": {
      "default": "A",
      "$ref": "./resource.json"
    },
   }
}
```

Comes out as
`private MyEnum myEnum = null;`

My solution at this point is use boolean properties to accomplish my goal. My enum only consisted of two items anyway.
