### ISSUE TITLE
javaName in definitions generates invalid code

### ISSUE THREAD

**Issue by ben-manes** [joelittlejohn/jsonschema2pojo#620]
Below is an example with four coordinates for an image transform. If the `point` does not include a `javaName` then the class is called `TopLeft`. To fix this the name is defined, but that leads to the get/set methods of `topLeft`, `topRight`, etc. to be called `getPoint` and `setPoint`. The fields are properly named, but the duplicate method names results in invalid Java code. Interestingly the fluent methods (`withX`) are properly named.

```json
{
  "type": "object",
  "javaName": "PerspectiveTransform",
  "properties": {
    "topLeft": {
      "$ref": "#/definitions/point"
    },
    "topRight": {
      "$ref": "#/definitions/point"
    },
    "bottomLeft": {
      "$ref": "#/definitions/point"
    },
    "bottomRight": {
      "$ref": "#/definitions/point"
    }
  },
  "definitions": {
    "point": {
      "javaName": "Point",
      "type": "object",
      "properties": {
        "x": {
          "type": "integer"
        },
        "y": {
          "type": "integer"
        }
      }
    }
  }
}
```

```java
/**
 * 
 * Corresponds to the "topLeft" property.
 * 
 * @return
 *     The point
 */
@JsonProperty("topLeft")
public Point getPoint() {
    return topLeft;
}

/**
 * 
 * Corresponds to the "topLeft" property.
 * 
 * @param point
 *     The topLeft
 */
@JsonProperty("topLeft")
public void setPoint(Point topLeft) {
    this.topLeft = topLeft;
}

public PerspectiveTransform withTopLeft(Point topLeft) {
    this.topLeft = topLeft;
    return this;
}

/**
 * 
 * Corresponds to the "topRight" property.
 * 
 * @return
 *     The point
 */
@JsonProperty("topRight")
public Point getPoint() {
    return topRight;
}

/**
 * 
 * Corresponds to the "topRight" property.
 * 
 * @param point
 *     The topRight
 */
@JsonProperty("topRight")
public void setPoint(Point topRight) {
    this.topRight = topRight;
}

public PerspectiveTransform withTopRight(Point topRight) {
    this.topRight = topRight;
    return this;
}
```

**Comment by ben-manes** [comment]
Perhaps `javaType` is more appropriate here. However if defined in the definition then no `Point` class is generated. It has to be extracted into its own `point.json` file.

**Comment by ben-manes** [comment]
Even then it is extremely finicky. Sometimes a build works, but a little later it stops generating the code.

**Comment by ctrimble** [comment]
I have been resolving this situation with an external schema file and setting `javaType`.  I would assume you could keep the schema in the definitions section and just put `javaType` on that schema.

**Comment by ben-manes** [comment]
I tried that and it worked, but then I changed the code slightly and it failed. Then reverting back it continues to fail. So there's something non-deterministic in the evaluation.

**Comment by ctrimble** [comment]
I haven't seen anything like that.  The `javaType` setting is the authority about what something should be named.  Perhaps you have two schemas being mapped to the same name?

**Comment by ben-manes** [comment]
No, for example I've seen cases fixed by changing the name so that dependent code is generated first, assuming alphanumberic ordering. So if I change to "apoint" it works, but may fail with "point" since that ordered after "perspective". Having not dug into the codegen I'm unsure why the name, hash, etc. can cause differences in the output. Ideally it should be naively spitting out code with a minimalistic graph evaluation.

**Comment by ctrimble** [comment]
I have seen those naming changes happen when JsonSchema2Pojo is creating the name, but when `javaType` is present, it should be stable.

**Comment by ben-manes** [comment]
Its only stable when the `javaType` output resides in a different package structure from the types being named automatically. It appears to not generate the javaType file, or perhaps deletes it in a later phase, resulting in a failure.

**Comment by ben-manes** [comment]
I think part of the problem might be due to daemon builds, e.g. Gradle. I suspect there is some cache somewhere in the code generator not being flushed between executions. That would explain some of the non-deterministic behavior I've been seeing.

**Comment by ben-manes** [comment]
I'm going to close this as its too vaguely defined to be actionable and there are probably a few problems at work.

I think there might be some static data being cached, which is okay assuming its a one-off execution. That fits Ant and Maven but not Gradle, SBT, Bazel, etc. which use a daemon JVM to have a warm process to rebuild with. Since they may have multiple worker JVMs at once, this gets worse if builds bounce between executors with only some builds failing. So reviewing to remove any static mutable state would reduce frustrations.

**Comment by joelittlejohn** [comment]
@ben-manes there definitely is cached data that accumulates as the plugin executes. To help in the situation you've described, we could clear this cached data when plugin execution is complete. My only concern would be parallel executions.

A better option would be to get rid of this static cache and attach the schema store (cache) to the rule factory so that there's one per execution.

**Comment by ben-manes** [comment]
Since Gradle 3.0 turns on the daemon by default and is pushing further toward on parallel tasks, I think more users are going to hit this. So attaching the schema store to the execution sounds like a good change.

**Comment by thachhoang** [comment]
Are we already using one schema store per execution? The rule factory is created using its no-arg constructor which looks like:

```java
public RuleFactory() {
    this(new DefaultGenerationConfig(), new Jackson2Annotator(), new SchemaStore());
}
```

**Comment by joelittlejohn** [comment]
@thachhoang Yes, you're right. The static caching I was thinking of was refactored some time ago. I think this is worth diagnosing, particularly given what you've described about Gradle 3.0 (and other modern build tools) @ben-manes.

Re the original problem, javaType is appropriate here, not javaName. Java name is specifically used when you want to control the java field name (so it doesn't make sense to refer to that in many places, in the same class). The fact that the withXxx method didn't match the getter/setter is a bug.

**Comment by ben-manes** [comment]
grep'ing through the code, I couldn't find any static mutable state. However I am facing a failure every few builds due to `Point` not being generated. To fix it, I stop the daemon using `gradle status --stop` and the next compile is successful.

**Comment by ctrimble** [comment]
Grasping at straws here, but this sounds like either a HashMap is being used where a LinkedHashMap would be better or like a synchronization issue.

I could only find two `HashMap`s being created, and both look appropriate for their usage:

```
./jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java:421:        Map<String, JVar> classFieldParams = new HashMap<String, JVar>();
./jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java:30:    protected Map<URI, Schema> schemas = new HashMap<URI, Schema>();
```

However, it does look like there is a missing `synchronized` declaration in the [SchemaStore](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java#L80-L118).  That method modifies the `schemas` map, but the other methods accessing that map are synchronized.

**Comment by ben-manes** [comment]
I tried extracting my schemas into a self-contained project to provide and debug with. Unfortunately I can't reproduce the problem there, but every other build in my main project is corrupt. I could try running it against a SNAPSHOT and report back.

**Comment by joelittlejohn** [comment]
Two other areas of potential static state are:

1. Something inside CodeModel. I think this one is unlikely as I've never noticed any such thing.

2. The classpath. I wonder if this relates to resources being built and added to the classpath for later builds - these things not being cleaned. Not generating a type could certainly be explained by using javaType and jsoncshema2pojo finding that type on the classpath.

**Comment by ben-manes** [comment]
Currently I'm using a single module, monolithic project. I haven't need to broken it into multiple modules yet, which should simplify the classpath.

This seems to work,

```
$ gradle status --stop && gradle compileJava
// change a private method to public
$ gradle clean compileJava
```

But if I drop the `clean` then it fails, and all subsequent builds are corrupt until I stop the daemon.

It does work if I change `removeOldOutput = true` to false. That works because the `Point` had been generated before, so the subsequent builds would see it.

**Comment by ben-manes** [comment]
I received a new error in Gradle unless the daemon is restarted. Maybe this helps track down the staleness?

```
Caused by: java.lang.IllegalStateException: Property type hasn't been added to JDefinedClass before calling addConstructors
        at org.jsonschema2pojo.rules.ObjectRule.addConstructors(ObjectRule.java:443)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:143)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:66)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
        at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
        at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:109)
        at org.jsonschema2pojo.Jsonschema2Pojo.generateRecursive(Jsonschema2Pojo.java:111)
        at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:73)
        at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
        at org.jsonschema2pojo.gradle.GenerateJsonSchemaJavaTask.generate(GenerateJsonSchemaJavaTask.groovy:65)
```
