### ISSUE TITLE
uniqueItems types should require/simulate LinkedHashSet in setter

### ISSUE THREAD

**Issue by andrewmellinger** [joelittlejohn/jsonschema2pojo#621]
When I set the type of a list to "uniqueItems" it sets the underlying structure to a LinkedHashSet which is what I expect.  But the get and set methods are exposed as Sets, which weakens the contract to the caller.

This isn't a bug that the code does anything wrong directly, but it would be more communicative to the user if it exposed that those types were LinkedHashSet.  (POLA)  I can imagine many developers introducing a defect because they weren't aware of the desired ordering guarantee.

In an ideal world Java would have an OrderedSet interface that could be used...

**Comment by joelittlejohn** [comment]
Hmm, I'm not sure I agree. The schema dictates that these items be unique - this is the contract, hence the requirement to supply a set. The schema says nothing about the ordering, but it's a nice trait of the types that they maintain the ordering of the data that was parsed.

If you choose to set an unordered set, then you won't get ordering in the output. If you choose to set an ordered set, then you will get ordering.

Could you walk me through a scenario in which this would do something unexpected?

**Comment by joelittlejohn** [comment]
I think there are good reasons to implement a setter like this:

```
void setFoo(Set<Bar> foo) {
    this.foo = new LinkedHashSet(foo);
}
```

to avoid unexpectedly mutating the collection later, however this doesn't really have any impact on ordering. If you pass an unordered set, then you will not get any ordering guarantees, and if you pass an ordered set then you will.

**Comment by andrewmellinger** [comment]
The more I think about it, the more I think Set<> is fundamentally the wrong thing to return. You say the schema says nothing about ordering, but since 'uniqueItems' is a modifier on array, I'm pretty sure the ordering is implied by that. I actually couldn't find anything in the core specification on uniqueItems and I only found in the validation specification.  That being said, the core must still hold true; that arrays are ordered.  I wouldn't expect a validation keyword to implicitly remove other requirements.

Yes, you are absolutely right that copying to a LinkedHashSet under the hood would be meaningless; the damage is already done.

Thoughts?
-Andrew

**Comment by joelittlejohn** [comment]
I think I practice the way the types are currently generated produces the result we need. I'm struggling to think of a scenario in which this is a problem. The two use-cases for these types are deserialization (from JSON) and serialization (to JSON):

1. **You deserialize incoming JSON with your types.**
    The field by default is a LinkedHashSet. It maintains the order of the incoming array when used in Java and when serialized again.
2. **You build an object in Java-land and serialize it to JSON**
    Either you set an ordered Set, or an unordered set. Your choice, and the resulting array order will either be undefined or exactly as you asked. Either way, this choice is made by the Java programmer and there is no JSON array until one is serialized.

I don't see a compelling reason to make this change. The Java types do not express all the rules of the schema (unfortunately, there is no OrderedSet), but they do accurately reflect the data in all the required circumstances IMO.

**Comment by joelittlejohn** [comment]
Note, there is more discussion of this on #569
