### ISSUE TITLE
$ref with absolute path from sourceDirectory

### ISSUE THREAD

**Issue by doofmars** [joelittlejohn/jsonschema2pojo#631]
Is there a possibility to use absolute paths from sourceDirectory for all schemas?

For instance schema A which references schema B:

sourceDirectory: `/Usr/somepath/project/schemas` 
folder of schema A in sourceDirectory: `/a/schemaA.json` 
folder of schema B in sourceDirectory: `/b/schemaB.json` 

Will give an exception because the lookup path will be `/b/schemaB.json` since the $ref to schemaB in schemaA is `/b/schemaB.json`.

One solution could be to have an option to combine sourceDirectory + refPath.

Is there any other possibility?

EDIT: I need this feature for another tool which sadly dose not seems to cooperate with relative paths.

**Comment by joelittlejohn** [comment]
I think your only option here is to fork and customise the code for this project. This isn't how refs work so I don't see us ever supporting this in the core. This library being open source however means you could modify how these refs resolve in your own custom version.
