### ISSUE TITLE
Nested Class References using @DBRef for MongoDB Persistence

### ISSUE THREAD

**Issue by opncity** [joelittlejohn/jsonschema2pojo#633]
Hi

I like to explain what I am looking for with a small example, please let me know if there is a solution for what I am looking for? I tried looking online but couldn't find anything.

I have the following schema, its pretty simple, a Person object and that can have one or more Roles.

```
{
	"title": "Person",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"gender": {
			"type": "string"
		},
		"email": {
			"type": "string"
		},
		"roles": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/Role"
			}
		}
	},
	"definitions": {
		"Role": {
			"title": "Role",
			"properties": {
				"name": {
					"type": "string"
				}
			}
		}
	}
}
```

When I create classes using jsonschema2pojo library, Person class is generated correctly as follows.

```
public class Person {

@JsonProperty("name")
private String name;
@JsonProperty("gender")
private String gender;
@JsonProperty("email")
private String email;
@JsonProperty("roles")
private List<Role> roles = new ArrayList<Role>();
........ 
}
```

However, I like to save Person & Roles in separate collections in my Mongo DB, I would like to use @DBRef as follows:

```
public class Person {
.
.
@DBRef(db="role")
@JsonProperty("roles")
private List<Role> roles = new ArrayList<Role>();
.
.
}
```

How can I achieve this?

Currently I have been using jsonschema2pojo to generate classes, I have a big schema and that changes frequently. I have been generating classes & manually inserting the @Id & @DBRef, so if there is a mechanism to insert those while generating classes, it will make my life lot easier, plz let me know if this can be done / if you like to incorporate such an enhancement soon.

Thanks in advance

**Comment by thachhoang** [comment]
You can use a [custom annotator](http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.27/generate-mojo.html#customAnnotator).

**Comment by joelittlejohn** [comment]
I agree with @thachhoang. This isn't a general purpose Java generation library so things like DBRef (that are not related to JSON) are out of scope. However, that said, the custom annotator feature lets people add whatever annotations they like to their types. If you can publish your custom annotator publicly it would probably help others.

If there is a method missing from the annotator that you need (you find that you can't hook in to the right place to add your annotation) then we could think about adding this to the core. You can use the existing annotators (e.g. [Jackson2Annotator](https://github.com/joelittlejohn/jsonschema2pojo/blob/3d8c325a2e38afbbf312b9f2183c3a947ad13e41/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java)) to understand how these are implemented.
