### ISSUE TITLE
Support for generics at class level

### ISSUE THREAD

**Issue by garganshul** [joelittlejohn/jsonschema2pojo#634]
We want support for generics at class level. Like following example

```json
{
  "type":"object",
  "generics": [{
     "name": "T",
     "extends": "Book"
  }],
  "properties": {
    "foo": {
      "javaType": "java.util.Map<String,T>",
      "type": "object"
    }
  }
}
```

```java

package com.example;

import java.util.Map;
import javax.annotation.Generated;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

@Generated("org.jsonschema2pojo")
public class Example<T extends Book> {

  @SerializedName("foo")
  @Expose
  private Map<String, T> foo;
}
```

**Comment by joelittlejohn** [comment]
@garganshul I'm afraid this library is not a general purpose Java generation library. The goal of this project is not to support every kind of Java construct or style, only to support those that are required for binding to JSON.

You could probably achieve what you need by implementing a custom RuleFactory and extending or replacing some of the existing rule classes. Alternatively, you can fork and modify this project.

I don't see a compelling reason that this change is needed to support binding JSON so I'm going to close this. Please feel free to add further justification if you think that this should be added to the core.
