### ISSUE TITLE
Web form is not working

### ISSUE THREAD

**Issue by bretpeterson** [joelittlejohn/jsonschema2pojo#635]
It's throwing 

Failed to load resource: the server responded with a status of 404 (Not Found)
http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js

Uncaught TypeError: $(...).tooltip is not a function
Uncaught TypeError: $(...).button is not a function

**Comment by joelittlejohn** [comment]
Hi. Seems to be working fine for me now. 

I guess this could be something wrong with your proxy (if you're using one) or it was some downtime from bootstrapcdn.com. If it was the latter, they seem to have fixed it.
