### ISSUE TITLE
There's a problem: trying to create the same field twice

### ISSUE THREAD

**Issue by CoolMind** [joelittlejohn/jsonschema2pojo#636]
Hello!
If we have a JSON with similar attributes, distinguished only by letter case, for instance,
`{"code":200,"Code":"ABC"}`
then we get an error:

> There's a problem: trying to create the same field twice: code

**Comment by joelittlejohn** [comment]
Could you advise on what you'd like to happen here? If we provide a workaround, this looks like a recipe for terrible confusion for whoever is using the Java types you have generated. I must admit, I don't feel compelled to fix this.

**Comment by CoolMind** [comment]
You are right, this confusion occurs only with the first letter, that in Java usually differentates a class and a variable. In my case no problem has happened when I made a class with these two variables, but if you are sure in general they may appear, then don't touch this behaviour.

**Comment by CoolMind** [comment]
Also wanted to say. In a case of Gson a result contains "@SerializedName("attribute")" everywhere. That's not optimal, but in the case of different first letter it may help. Why don't use it?

**Comment by CoolMind** [comment]
Ha-ha, haven't fixed, just closed.

**Comment by joelittlejohn** [comment]
@CoolMind maybe I'm misunderstanding the discussion above. It seems like this is agreed to be a confusing structure that shouldn't be supported by this tool.

If you want something to change here, please give an example of what Java output you'd like to see from this tool.

**Comment by CoolMind** [comment]
@joelittlejohn sorry, I thought you could use @SerializedName("Code") in the second case. Something like (in case of GSON):

```
public class Example {

    private Integer code;

    @SerializedName("Code")
    private String code2;
    ...
}
```
