### ISSUE TITLE
why my computer do not display right?

### ISSUE THREAD

**Issue by CrazyManDF** [joelittlejohn/jsonschema2pojo#638]
![unnamed qq screenshot20161023145949](https://cloud.githubusercontent.com/assets/15359159/19624612/64ce3968-9931-11e6-9a1c-3144a9300cfd.png)

**Comment by CrazyManDF** [comment]
i have solved this problem, it`s my network problem

**Comment by joelittlejohn** [comment]
:thumbsup:
