### ISSUE TITLE
Could you add setter and getter based on lombok project?

### ISSUE THREAD

**Issue by lucalas** [joelittlejohn/jsonschema2pojo#639]
The complete request is written in the title, could you add setter and getter based on lombok project?

example:

@setter @getter String myString

Thanks for attention!

**Comment by thachhoang** [comment]
There was another discussion on Lombok support at #166.

**Comment by joelittlejohn** [comment]
Hi @lucalas if you're interested in Lombok, please add a +1 to #166 and explain more about what you'd like supported. I don't currently think this is mainstream enough for this library to support but I'd be interested to hear your views.
