### ISSUE TITLE
Allow getters & setters to be activated independently

### ISSUE THREAD

**Issue by lkishor** [joelittlejohn/jsonschema2pojo#640]
Most of the times when we are reading data from JSON, we don't need setters.
As data is populated automatically by the libraries such as GSON.
So it will be great if we have **separate option** for creating getters & setters.

It will give user more control, over what is being generated.

**Comment by budius** [comment]
+1 for this. I was looking for documentation and feature requests for this exact feature.

**Comment by joelittlejohn** [comment]
Fixed by #759
