### ISSUE TITLE
Object Mapper not mapping to jsonschema2pojo classes

### ISSUE THREAD

**Issue by BGBGBG** [joelittlejohn/jsonschema2pojo#641]
Hi,

I ran jsonschema2pojo against my JSON. It created around 20 Java classes.
However when I run ObjectMapper against one of the classes it does not 
populate the object. It only populated "additionalattributes" (sp?). I try
running ObjectMapper with some of the other classes and only "additionalattributes" 
get populated. 

Is there something I am doing wrong? 

Thanks

**Comment by joelittlejohn** [comment]
Are you still having this problem? I can't think of anything that would stop the types produced by this library from working with the ObjectMapper (we have a lot of tests that use the ObjectMapper with our generated classes).

Maybe a question on StackOverflow that shows your code would be best.

**Comment by BGBGBG** [comment]
Hi. Yes it is still a problem. -- thanks
Please ignore any blatant typos. 


// How Call POJO
GenerationConfig config new DefaultGenerationConfig()
{
	@Override
	public boolean isGenerateBuilders()
	{
		return true;
	}
	public SourceType getSourceType()
	{
		return SourceType.JSON;
	}
	};
	SchemaMapper mapper = new SchemaMapper(new RuleFactory(config, new Jackson2Annotator(), new SchemaStore()), new SchemaGenerator());
	mapper.generate(codeModel, "ClassName", "com.example", source);
	codeModel.build(new File("output"));



// How Call ObjectMapper
byte[] jsonData = ...my java code goes here...
ObjectMapper objectMapper = new ObjectMapper();
ClassName p = objectMapper.readValue(jsonData, ClassName.class);


//JSON
{
"myid": 11111,
"myType": "Food",
"myFieldObject": 
{
	"myFields":
	[
		{
			"field1": "HARD",
			"field2": "TACO"
		}
	 ]
}
}


//Three class created
ClassName.java, Myfieldobject.java, MyField.java


//Some of the class information
ClassName.java
	@JsonProperty("myid")
	private Integer myid;
	@JsonProperty("myType")
	private String myType;
	@JsonProperty("myfieldobject")
	private Myfieldobject myfieldobject;
	@JsonIgnore
	private Map<String, Object> additionalproperties = new HashMap<String, Object>();



Myfieldobject.java
	@JsonProperty("myFields")
	private List<MyField> myFields = new ArrayList<MyField>();
	@JsonIgnore
	private Map<String, Object> additionalproperties = new HashMap<String, Object>();


MyField.java
	@JsonProperty("field1")
	private String field1;
	@JsonProperty("field2")
	private String field2;
	@JsonIgnore
	private Map<String, Object> additionalproperties = new HashMap<String, Object>();

**Comment by BGBGBG** [comment]
Well once again I overlooked something. I had old class files from previous runs in my path and this was causing the issue. Thanks. Feel free to delete this if you wish.

**Comment by joelittlejohn** [comment]
@BGBGBG Thanks for reporting back and closing this.
