### ISSUE TITLE
Configuring code generation to write nulls for missing properties

### ISSUE THREAD

**Issue by martinjoconnor** [joelittlejohn/jsonschema2pojo#642]
Using the latest version of the Maven plugin with a simple `Address` class I get the following generated code with Jackson 2 annotations:

```
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
    "post-office-box",
    ...
})
public class Address {
...
```

I would really like missing properties to be serialized as `null` but the default inclusion of the  `@JsonInclude(JsonInclude.Include.NON_NULL)` annotation prevents that. 

Even if I override the property in the object mapper as follows:

```
    ObjectMapper mapper = new ObjectMapper();
    mapper.setSerializationInclusion(JsonInclude.Include.ALWAYS);
    Address address1 = mapper.readValue("{\"post-office-box\": \"232\", \"extended-address\": \"an extended\",  " +
      "\"street-address\": \"123 Main St\", \"locality\": \"a locality\", " +
      "\"region\": \"a region\", \"postal-code\": \"666\", \"country-name\": null }", Address.class);

    address1.setCountryName(null);

    mapper.writeValue(outputAddressFile, address1);
```

I still do not get nulls in the output JSON.

Is there a way to override this default behaviour?

Thanks
Martin

**Comment by joelittlejohn** [comment]
There's no current way to override this behaviour in this tool. We'd have to implement #629.  

There was a possible solution mentioned here though:

https://github.com/joelittlejohn/jsonschema2pojo/issues/629#issuecomment-250645527

Configure the ObjectMapper.
