### ISSUE TITLE
@Generated("org.jsonschema2pojo") gives error in GSON

### ISSUE THREAD

**Issue by Aexyn** [joelittlejohn/jsonschema2pojo#648]
may be this annotation is removed from GSON. I am using it in android and intellij is unable to find the reference. Also I don't think there is any need for this.

**Comment by thachhoang** [comment]
The annotation is `javax.annotation.Generated` and the plugin no longer adds it since #577 / version 0.4.26.

**Comment by joelittlejohn** [comment]
Indeed. You can either upgrade or use the solution here: http://stackoverflow.com/a/37102725/125825.

Cheers

**Comment by Aexyn** [comment]
I generated it from http://www.jsonschema2pojo.org/ . may be that site was using old plugin.. Anyway thanks :)

**Comment by joelittlejohn** [comment]
Ah, I see. Thanks for mentioning this. I'll update the site (and maybe add some more config options).

**Comment by Aexyn** [comment]
yeah. You can add option to whether to generate getter/setter comments or not :p Just saying  ;)
