### ISSUE TITLE
CSS glitch at jsonschema2pojo.org

### ISSUE THREAD

**Issue by hkjin81** [joelittlejohn/jsonschema2pojo#652]
Hello,
Thanks for the great tool and website. Recently, I found a glitch at jsonschema2pojo.org css stylesheet but I couldn't find where to report this.
I'm using Safari on a Mac but I don't think this is about browser(not tested).

When I click preview button, a modal appears. If I reduce window height, top of the preview modal goes through window's top(top of the modal clipped). It means I can't see whole preview modal if it doesn't have enough height(can't be scrolled).

Here is my solution and if you think it's good please apply to the site.

index.css
```
...
#preview-modal {
    width: 60%;
    height: 80%;
    margin: 0;
    top: 10%;
    left: 20%;
}
...
```

**Comment by joelittlejohn** [comment]
Thanks @hkjin81, I've applied this (the site source is in the `gh-pages` branch of this repo).

**Comment by joelittlejohn** [comment]
Great fix btw, works perfectly!
