### ISSUE TITLE
oneOf support

### ISSUE THREAD

**Issue by monami555** [joelittlejohn/jsonschema2pojo#653]
Hello there!
Is "oneOf" supported by jsonschema2pojo? From what I see it looks like not. Are there plans to support it?
Monika

**Comment by thachhoang** [comment]
Full support of "oneOf" is quite difficult (#392). We might be able to deal with some simple cases, like #583. As far as I know, no one's actively working on this.

**Comment by joelittlejohn** [comment]
This is currently tracked as #392.
