### ISSUE TITLE
Initialise String object with empty string "" instead of null

### ISSUE THREAD

**Issue by Aexyn** [joelittlejohn/jsonschema2pojo#654]

**Comment by joelittlejohn** [comment]
@Aexyn this isn't something that's going to be added to the core I'm afraid, it isn't a general requirement to initialise a string to a specific value like this without this being part of the schema. If you want the specify this in your schema, you should be able to add:

```
"default" : ""
```

Alternatively, if you want to customize the behaviour of this plugin you can do this with a custom rule factory.
