### ISSUE TITLE
Getting issue when response is case senstive

### ISSUE THREAD

**Issue by Karan-nassa** [joelittlejohn/jsonschema2pojo#658]
When any of the key is in caps letter then it shouldn't generate the response in the same pattern. 
For Example Response:

{
"Message" : "Success"
"data" : null
}

Expected outcome: 'M' of key 'Message' should be in caps letter instead of 'message' .

**Comment by joelittlejohn** [comment]
Can you show me the schema or json you are using, and also the .java file that was generated by jsonschema2pojo?

**Comment by joelittlejohn** [comment]
Also, what version of this library are you using?

**Comment by joelittlejohn** [comment]
I'm afraid I can't help with this without more information. This plugin supports properties of any case and will preserve the case of the JSON properties by applying the correct annotations to the types it generates. If you are seeing something different, please provide some more info.

**Comment by joelittlejohn** [comment]
Hi. When we generate types we annotate them so that they are serialized to JSON correctly. JSON can include all kinds of keys that cannot be represented in Java, e.g.
```json
{
  "this key" : "this value"
}
```

In the Java types we follow Java conventions, but the annotations ensure that the correct JSON output is produced.

In your case, for example, I see the following output:
```java
@JsonProperty("Foo")
private String foo;
```

The `@JsonProperty` annotation ensures that the ouput JSON will contain `Foo` (uppercase F).

**Comment by Karan-nassa** [comment]
Hi joelittlejohn,

Thanks for confirmation :+1: 

Still, I'm not clear with the above information. 

Please see the screenshot am sending in attachment below. Please address me what option should I clicked to get 'P' alphabet of 'Property' instance should be capital.

If you are saying I should use @JsonProperty("Property") then how I can add JsonProperty in our pojo.

Regards,
Karan Nassa
karan@ucreate.co.in

![screenshot](https://cloud.githubusercontent.com/assets/15867097/21177101/a930fa58-c20f-11e6-82e1-5820748a4f6c.PNG)

**Comment by joelittlejohn** [comment]
I'm not sure what your screenshot is supposed to show.

You don't have to add `@JsonProperty("Message")` yourself, it's added by jsonschema2pojo. Just enter the following and click Preview and you will see it:

```
{
  "type":"object",
  "properties": {
    "Message": {
      "type": "string"
    }
  }
}
```

**Comment by Karan-nassa** [comment]
When I put this response on your website :
{
  "type":"object",
  "properties": {
    "Message": {
      "type": "string"
    }
  }
}

I get response when I tap on preview button then it displays me 

-----------------------------------com.example.Properties.java-----------------------------------

package com.example;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Properties {

@SerializedName("Message")
@Expose
private Message message; //I want this message of 'M' in capital letter by default when I create pojo.

public Message getMessage() {
return message;
}

public void setMessage(Message message) {
this.message = message;
}

}

Please see my comment correspond to 
@SerializedName("Message")
@Expose
private Message message;

**Comment by joelittlejohn** [comment]
If you use Gson, the following part ensures that the JSON output had the correct case:

```java
@SerializedName("Message")
```

**Comment by joelittlejohn** [comment]
I think you might find it useful to consult the Gson documentation to get a better idea of its capabilities before you start using jsonschema2pojo to generate classes. You may find it difficult to understand what jsonschema2pojo generates and why, until you read more about Gson.

**Comment by Karan-nassa** [comment]
okay thanks a lot
