### ISSUE TITLE
Generate classes in multiple-modules Gradle project

### ISSUE THREAD

**Issue by cristic83** [joelittlejohn/jsonschema2pojo#661]
When generating classes by specifying the javaType, if the classes are on the classpath they are not generated. This approach does not work when the we have a multi-module Gradle project, in which one module defines a class A (that is not generated using jsonschema2pojo) and the second module generates a class B that contains a field of type A because in Gradle you can't have the output of project A on the buildscript classpath of project B (we can't define in the buildscript closure a classpath project(":A") dependency).

**Comment by joelittlejohn** [comment]
Hi @cristic83. I'm not a Gradle user but this sounds very strange to me, are you sure about this?

Are you saying you can't have two modules in a project where one depends on the other? I'd be very surprised if that was the case (for example, how would you build an EAR project?).

**Comment by cristic83** [comment]
Hi Joe, 
Yes, we can have the two projects depend on one another in Gradle, but the buildscript section is a bit different, because it contains code that is needed to build a project. In the use case described above, the project B has a compile dependency on project A : compile project(":A"), but the buildscript dependency section would also need to add that dependency (just like in the examples section of jsonschema2pojo the external dependency jodatime was added) using something like classpath project(":A"). That's why the Gradle jsonschema2pojo plugin can't assume that project dependency to be on the buildscript classpath, while the external dependencies like joda can be on the buildscript classpath.

**Comment by joelittlejohn** [comment]
Ah, so this is about a module being on the classpath _of the plugin_ rather than on the classpath of the module? In Maven we solve the problem like this:

https://github.com/joelittlejohn/jsonschema2pojo/blob/9c451f2f3669efc7632499f211d87ade43dedba4/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java#L621

Is there something equivalent in the Gradle world?

**Comment by joelittlejohn** [comment]
@cristic83 What do you suggest doing here by the way? I don't see anything that can be fixed here right now.

**Comment by joelittlejohn** [comment]
Unless you can describe something you actually want done to the project here, I don't see anything to do here. It sounds like you have described a Gradle limitation.

**Comment by cristic83** [comment]
@joelittlejohn : Sorry for the delayed reply. I am not completely sure on how to approach this, but I think one way would be to have a flag named generateClass or something like that, besides the javaType field, to control whether a class should be generated or not. This would make sense if we know that class is on the classpath. This field could have the default value to false to not brake the existing behavior.
