### ISSUE TITLE
can your app do the reverse?

### ISSUE THREAD

**Issue by TahorSuiJurisBenYAH** [joelittlejohn/jsonschema2pojo#663]
Hi, can your app do the reverse?  Provide the code to serialize a bean to JSON?

jsf managed bean accessing MySQL remote database - how to create JSON array to feed

http://stackoverflow.com/questions/41142802/jsf-managed-bean-accessing-mysql-remote-database-how-to-create-json-array-to-f

Any suggestions greatly appreciated.

Jon

**Comment by joelittlejohn** [comment]
I think Jackson would help you here. If you just have some Java object that you want to serialize as JSON, then Jackson or Gson is what you need.

**Comment by TahorSuiJurisBenYAH** [comment]
thank you
