### ISSUE TITLE
Support URI format properties with a default value using URI.create

### ISSUE THREAD

**Issue by ben-manes** [joelittlejohn/jsonschema2pojo#664]
```json
{
  "type":"object",
  "properties": {
    "type": {
      "type": "string",
      "format": "uri",
      "default": "abc"
    },
    "types": {
      "items": {
        "type": "string",
        "format": "uri"
      },
      "uniqueItems": true,
      "type": "array",
      "default": [ "/abc/efg" ]
    }
  }
}
```

This generates the fields,
```java
@JsonProperty("type")
private URI type = null;
@JsonProperty("types")
@JsonDeserialize(as = java.util.LinkedHashSet.class)
private Set<URI> types = new LinkedHashSet<URI>(Arrays.asList(null));
```

But when the `format` is removed it generates a a String value,
```java
@JsonProperty("type")
private String type = "abc";
@JsonProperty("types")
@JsonDeserialize(as = java.util.LinkedHashSet.class)
private Set<String> types = new LinkedHashSet<String>(Arrays.asList("/abc/efg"));
```

Can we support creating default URIs? Presumably they could be private static fields.

**Comment by joelittlejohn** [comment]
Absolutely, I think we can do this. I was a little surprised that this wasn't already supported :) I think `URI.create` will be sufficient. Of course the default will will have to be a valid URI to avoid an exception.

I'm not really convinced about creating private static fields. I think we should simply assign these fields like:
```java
@JsonProperty("type")
private URI type = URI.create("http://my/default");
```

with no indirection whatsoever.

**Comment by joelittlejohn** [comment]
I've changed the title here as I think this will be more helpful in the changelog.
