### ISSUE TITLE
Date-time generates incorrect java code 

### ISSUE THREAD

**Issue by maxmikeibx** [joelittlejohn/jsonschema2pojo#670]
```json
"meterValue": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "timestamp": {
                        "type": "string",
                        "format": "date-time"
                    },
```
In the above fragment the timestamp object is generated as Date, when it should be String; e.g.
```java
@SerializedName("timestamp")
@Expose
private Date timestamp;
```

**Comment by thachhoang** [comment]
By default an object with `"format":"date-time"` would [generate a `java.util.Date` field](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#format). If you want the field to be a string, you can set [dateTimeType](http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.29/generate-mojo.html#dateTimeType) to "java.lang.String".

**Comment by joelittlejohn** [comment]
Closing this as it's the expected behavior. Thanks for providing the above useful advice @thachhoang.

**Comment by maxmikeibx** [comment]
I'm sorry if I wasn't clear - if the format is String and the type is date-time json2POJO generates a Date, not a String, as expected. It's still a very useful piece of software; I can fix those manually. Just thought it might trip up others.

**Comment by maxmikeibx** [comment]
Actually this default behavior is puzzling since everything else with type:String will be converted to String.
As an aside a java Date is a non-portable object across time-zones, unless both the source TZ and the destination TZ are specified. This can only be done in UTC, and Date does not specify midnight Jan 1 1970 as UTC.

**Comment by joelittlejohn** [comment]
The link given above by @thachhoang shows how `format` affects the Java type. There are a few format values that cause this tool to use a type other than String. This helps constrain Strings and give useful, typed values in Java.

There are many configuration options available for dates in this tool. You can use Date, String, Joda DateTime, or any other type you need.
