### ISSUE TITLE
Map object not being generated?

### ISSUE THREAD

**Issue by fcarriedos** [joelittlejohn/jsonschema2pojo#675]
Hello,

Trying to generate POJOs having Map<String, String> members with following JSON-Schema results in the POJO not obtaining the member:

`
{
  "title": "maptest",
  "type": "object",
  "patternProperties": {
    ".{1,}": { "type": "string" }
  }
}
`

Am I missing something, is this not implemented for some reason?

Thanks in advance for your time!

**Comment by joelittlejohn** [comment]
This library doesn't support the `patternProperties` rule. You can workaround this with a rule like:

```json
{ 
  "title": "maptest", 
  "type": "object",
  "javaType" : "java.util.Map<String,String>", 
  "patternProperties": {
     ".{1,}": { "type": "string" } 
  } 
}
```

**Comment by fcarriedos** [comment]
Perfectly working! Excellent! 👍
