### ISSUE TITLE
AnnotationStyle.NONE still includes JSON annotations in produced classes

### ISSUE THREAD

**Issue by fcarriedos** [joelittlejohn/jsonschema2pojo#677]
Hello!

I generate my POJOs configuring the mapper as follows:

`
			@Override
			public AnnotationStyle getAnnotationStyle() { // set config option by overriding method
				return AnnotationStyle.NONE;
			}
`

But the POJOs still include annotations such as: 

`
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "resourceId",
    "timestamp",
   ...
})
`

Am I perhaps missing any other configuration step or is this an issue?

**Comment by joelittlejohn** [comment]
Hmmm. Somehow I don't think you're using the GenerationConfig you think you have created. This works at jsonschema2pojo.org (when I select *Annotation style: None*).

Which version are you using?

**Comment by joelittlejohn** [comment]
Can't investigate this without some more info I'm afraid. I haven't been able to replicate your problem so I think it may be an issue with old sources not being cleared or something else that means you're using the wrong configuration.

**Comment by fcarriedos** [comment]
Hello,

Wow you are blazing fast attending the project! My credits!!! 👍 

Now, there you go the relevant code is pretty much the one available in the ["Quick start"](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Getting-Started#using-jsonschema2pojo-within-your-java-project-embedded) section of the documentation of the project:

`
	public static void main(String[] args) throws IOException {

		GenerationConfig config = getConfig();
		
			URL source = bp.toURI().toURL();

			JCodeModel codeModel = new JCodeModel();
			SchemaMapper mapper = new SchemaMapper(new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore()), new SchemaGenerator());
			mapper.generate(codeModel, bp.getName().replace(".json",  ""), PACKAGE_NAME, source);

			codeModel.build(outputDir);						

		}

	}


	private static GenerationConfig getConfig() {

		return new DefaultGenerationConfig() {
			@Override
			public boolean isGenerateBuilders() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isUseLongIntegers() { // set config option by overriding method
				return true;
			}
			@Override
			public boolean isUseDoubleNumbers() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeHashcodeAndEquals() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeToString() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeJsr303Annotations() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeJsr305Annotations() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isUseJodaDates() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isUseJodaLocalTimes() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isUseCommonsLang3() { // set config option by overriding method
				return false;
			}			
			@Override
			public boolean isParcelable() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isSerializable() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isInitializeCollections() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isUseBigDecimals() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeConstructors() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isConstructorsRequiredPropertiesOnly() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeAdditionalProperties() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeDynamicAccessors() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isFormatDateTimes() { // set config option by overriding method
				return false;
			}
			@Override
			public boolean isIncludeAccessors() { // New fancy way to call getters and setters
				return true;
			}
			@Override
			public AnnotationStyle getAnnotationStyle() { // set config option by overriding method
				return AnnotationStyle.NONE;
			}
			@Override
			public SourceType getSourceType() { // set config option by overriding method
				return SourceType.JSONSCHEMA;
			}
		};
		
	}
`

The absolutely only dependency I am using is the following plus Java8:

`		
	<dependencies>

		<dependency>
			<groupId>org.jsonschema2pojo</groupId>
			<artifactId>jsonschema2pojo-core</artifactId>
			<version>0.4.29</version>
		</dependency>

	</dependencies>
`

A sample of the kind of output I am getting is the following:

`

package x.y.z;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "resourceId",
    "timestamp",
    "name",
    "description",
    "ratingCode",
    "ratingValue",
    "ratingCountry",
    "publicationStatus"
})
public class Rating {

    @JsonProperty("resourceId")
    private String resourceId;
    @JsonProperty("timestamp")
    private Long timestamp;
    @JsonProperty("name")
    private String name;
    @JsonProperty("description")
    private String description;
    @JsonProperty("ratingCode")
    private String ratingCode;
    @JsonProperty("ratingValue")
    private Long ratingValue;
    @JsonProperty("ratingCountry")
    private List<Object> ratingCountry = null;
    @JsonProperty("publicationStatus")
    private List<Object> publicationStatus = null;

    @JsonProperty("resourceId")
    public String getResourceId() {
        return resourceId;
    }

    @JsonProperty("resourceId")
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    @JsonProperty("timestamp")
    public Long getTimestamp() {
        return timestamp;
    }

    @JsonProperty("timestamp")
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @JsonProperty("description")
    public void setDescription(String description) {
        this.description = description;
    }

    @JsonProperty("ratingCode")
    public String getRatingCode() {
        return ratingCode;
    }

    @JsonProperty("ratingCode")
    public void setRatingCode(String ratingCode) {
        this.ratingCode = ratingCode;
    }

    @JsonProperty("ratingValue")
    public Long getRatingValue() {
        return ratingValue;
    }

    @JsonProperty("ratingValue")
    public void setRatingValue(Long ratingValue) {
        this.ratingValue = ratingValue;
    }

    @JsonProperty("ratingCountry")
    public List<Object> getRatingCountry() {
        return ratingCountry;
    }

    @JsonProperty("ratingCountry")
    public void setRatingCountry(List<Object> ratingCountry) {
        this.ratingCountry = ratingCountry;
    }

    @JsonProperty("publicationStatus")
    public List<Object> getPublicationStatus() {
        return publicationStatus;
    }

    @JsonProperty("publicationStatus")
    public void setPublicationStatus(List<Object> publicationStatus) {
        this.publicationStatus = publicationStatus;
    }

}
`

Should you want me to provide more detail, just ask me for it!

Thanks a lot for your great support!!!

**Comment by joelittlejohn** [comment]
Great thanks.

Try changing this line:

````java
SchemaMapper mapper = new SchemaMapper(new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore()), new SchemaGenerator());
```
to
````java
SchemaMapper mapper = new SchemaMapper(new RuleFactory(config, new NoopAnnotator(), new SchemaStore()), new SchemaGenerator());
```

:+1:

**Comment by fcarriedos** [comment]
Worked as expected with NoopAnnotator. Thanks a lot! 👍

**Comment by Kulasangar** [comment]
Thanks @joelittlejohn.. that worked like a charm.
