### ISSUE TITLE
allof not working

### ISSUE THREAD

**Issue by mankr1981** [joelittlejohn/jsonschema2pojo#680]
I am using version 0.4.30 and trying to use allof feature, here is my schema
"xyz" json schema
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema#",
"allof": [
    	{"type":"object","$ref" : "common/abc.json"}
]
}

but when it generates the pojo, I dont see any property in class xyz.java
Am I missing anything here, searched the issue logged but couldnt find anything complaining same.

thanks

**Comment by joelittlejohn** [comment]
Hi. allOf isn't supported by this tool. For a complete reference, see https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference

**Comment by activey** [comment]
Any plans for supporting it? ;)
