### ISSUE TITLE
Enum generation produces upper case names

### ISSUE THREAD

**Issue by fcarriedos** [joelittlejohn/jsonschema2pojo#682]
Hello,

When generating Java Enums I am getting modified names for the constant part of the enum. Example:

```json
                    {
                        "value": "ContentProvider",
                        "description": "Content Provider",
                        "title": "Content Provider",
                        "regex": null
                    },
                    {
                        "value": "Distributor",
                        "description": "Distributor",
                        "title": "Distributor",
                        "regex": null
                    },
                    {
                        "value": "ProductionStudio",
                        "description": "Production Studio",
                        "title": "Production Studio",
                        "regex": null
                    },
                    {
                        "value": "SpecialEffects",
                        "description": "Special Effects",
                        "title": "Special Effects",
                        "regex": null
                    }
```

produces

```java
    CONTENT_PROVIDER("ContentProvider"),
    DISTRIBUTOR("Distributor"),
    PRODUCTION_STUDIO("ProductionStudio"),
    SPECIAL_EFFECTS("SpecialEffects");
```

Is there a way for not altering the constant part of the enum? In other words, a way to produce this instead? 

```java
    ContentProvider("ContentProvider"),
    Distributor("Distributor"),
    ProductionStudio("ProductionStudio"),
    SpecialEffects("SpecialEffects");
```
Thanks a lot for the support!

**Comment by joelittlejohn** [comment]
No, this tool doesn't support customising how the constant names are generated, we use standard Java conventions to name them.

If you really need to do this you could create a custom RuleFactory that returns a custom EnumRule that names the types as you wish.

**Comment by fcarriedos** [comment]
Implemented and working!

Thanks for the suggestion.

Any interest in integrating it in the code and committing the change? As I see it, for anyone relying on the naming convention received in the JSON schema this feature could be nice to have, but the decision is yours.

Thanks a lot for your great support! 👍

**Comment by joelittlejohn** [comment]
There's a cost to supporting and maintaining every one of these configuration options and I think we have to draw the line somewhere. When it comes to minor aesthetic things about the code like this I don't think we should be trying to support this in the core. We follow Java conventions and adding configuration arguments to stray from that would never end.

It would be really useful for others if you could share your code as a personal GitHub repo though. I'm sure people who need to will find this via Google, and may even use it as a good example of how to create customer a RuleFactory and rules.

**Comment by fcarriedos** [comment]
Makes sense.

Will do and provide the link to my repo in this thread.

Thanks for the support! 👍

**Comment by fcarriedos** [comment]
[Sample customization project uploaded to: https://github.com/fcarriedos/jsonschema2pojoCustomization](https://github.com/fcarriedos/jsonschema2pojoCustomization)

It shows an extension of RuleFactory and EnumRule providing the functionality asked in this thread.
