### ISSUE TITLE
References not creating classes with correct names

### ISSUE THREAD

**Issue by opncity** [joelittlejohn/jsonschema2pojo#684]
I have a reference like below.

**"buyer": {
	"description": "Person who buys .... ",
	"$ref": "#/definitions/Person"
}**

This generated a class by name Buyer, what was wrong in my schema? or is this a Bug?

**Comment by joelittlejohn** [comment]
When using refs it's advisable to use javaType to give your schema a definitive Java name, this way it doesn't matter where the ref first appears, it will always use the same name.

**Comment by sytolk** [comment]
@joelittlejohn I have the same issue and define javaType to ref object fix this. But disadvantage is that javaType cannot have relative value -> "Person" instead of "com.package.generated.Person" this turn this ref object into package specific (I cannot copy this Person object in another project without to change this hardcoded javaType)

**Comment by joelittlejohn** [comment]
@sytolk have you tried using `"javaName":"Person"`?

**Comment by sytolk** [comment]
@joelittlejohn yes I have try it but it's have new issue:
```json
 "startLocation": {
            "$ref": "TripLocation.json",
            "description": "start location of the trip"
        },
        "endLocation": {
            "$ref": "TripLocation.json",
            "description": "end location of the trip"
        }
```
and reference:
```json
{   "title": "TripLocation",
    "type": "object",
    "javaName": "TripLocation",
    "additionalProperties": false,
    "properties": {
        "tripId": {
            "type": "string",
            "required": true
        },
        "latitude": {
            "type": "number",
            "description": "latitude"
        },
        "longitude": {
            "type": "number",
            "description": "longitude"
        }
    }
}
```
The problem is that this will generate getters and setter with the same names:

```java
    public TripLocation getTripLocation() {
        return startLocation;
    }
    public void setTripLocation(TripLocation startLocation) {
        this.startLocation = startLocation;
    }
    public TripLocation getTripLocation() {
        return endLocation;
    }
    public void setTripLocation(TripLocation endLocation) {
        this.endLocation = endLocation;
    }

```

**Comment by joelittlejohn** [comment]
@sytolk `javaType` is your only option here I'm afraid.
