### ISSUE TITLE
Is AllOf supported?

### ISSUE THREAD

**Issue by chakravarthyvp** [joelittlejohn/jsonschema2pojo#685]
Hi, 
   I am using this plugin and it's a great tool for generating POJOs. One problem that I found is that it does not support allOf. Is this planned to be supported?
   If not, can you suggest an alternate way without having to duplicate schema defs within the file?

Best Regards
Chakravarthy

**Comment by joelittlejohn** [comment]
There's a lot of discussion of allOf on other issues, and many issues have been opened about this. Please search (either using Google or GitHub) before raising new issues. It's on the 'roadmap'.
