### ISSUE TITLE
2 attributes referring to same schema def does not generate appropriate names

### ISSUE THREAD

**Issue by chakravarthyvp** [joelittlejohn/jsonschema2pojo#686]
Hi,
    For a schema def as below that is referred by 2 different attributes as below,
```json
`"name-value-pair": {
            "type": "object",
            "required": [ "name","value"],
            "properties": {
                "name": {
                    "type": "string",
                    "pattern": ".+",
                    "minLength" : 4
                },
                "value": {
                    "type": "string",
                    "pattern": ".+",
                    "minLength" : 4
                }
            }
        },
        "env-args": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/name-value-pair" }
        },
        "app-args": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/name-value-pair" }
        },
```

the generated POJO contains an array list that refers to the same attribute...
as below
```java
@JsonProperty("env-args")
    private List<EnvArg> envArgs = new ArrayList<EnvArg>();
    @JsonProperty("app-args")
    private List<EnvArg> appArgs = new ArrayList<EnvArg>();
```

Is this a bug?

**Comment by joelittlejohn** [comment]
Hi. When using refs, it's a good idea to use `javaType` in your schema to give types like `name-value-pair` a definitive Java name, otherwise the name is chosen the first time this type is seen. In this case, EnvVar is the first property to use this, so that's the name it gets. You can override this like:

```json
"name-value-pair": {
    "javaType": "com.example.NameValuePair"
    "type": "object",
```

**Comment by chakravarthyvp** [comment]
Hi,
    AFAIK 'javaType' is not part of the spec and it does corrupt the schema with concreted type information. Is there  a way to avoid this?

**Comment by joelittlejohn** [comment]
Yes, the spec supports any additional properties you require. These don't corrupt the schema or make it invalid. It helps to give each type a definitive and clear name.

There is currently no other way to ensure all your schemas have the exact Java name you want. One way to make generation more predictable is to put schemas like `name-value-pair` into their own file and ensure these are generated first (e.g. though file or directory naming). I prefer `javaType`.
