### ISSUE TITLE
issue with dots in type names during code generation

### ISSUE THREAD

**Issue by massfords** [joelittlejohn/jsonschema2pojo#690]
There's an error during code generation with the maven plugin when a referenced type has dots in its name. It looks to me like the dots are being used as part of a JSON path and failing. In this case, the dots should be escaped.

`Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.30:generate failed: Path not present: org -> [Help 1]`

The $ref in this case contains dots in it:

`            "$ref": "#/definitions/org.opentravel.ota.2003_05.OriginDestinationOptionType"`

Apologies if this isn't allowed by the json schema definition. I'm working with a 3rd party schema here. The full schema can be found on the Sabre developer site [1]. 

[1] http://files.developer.sabre.com/doc/providerdoc/STPS/bfm/v1951/BargainFinderMax_v1.9.5.1_Request.jsonschema

**Comment by joelittlejohn** [comment]
Hi, are you working with @Tovkal by any chance?

We can do something about this I'm sure. There is already an open issue: #688

**Comment by Tovkal** [comment]
I'm planning on taking a look on the weekend
