### ISSUE TITLE
Option to fail generation if javaType doesn't already exist

### ISSUE THREAD

**Issue by lucjross** [joelittlejohn/jsonschema2pojo#693]
I want to be able to qualify a jsonType as one that I expect to be already present, and that I don't want generated. This would prevent a generation of an inappropriate type due to a typo in the class name, a failure to pull in the dependency, or some other mistake. For example, if the existing class is "com.example.Awesome" and I have this json with the currently-non-existent "javaTypeExists" parameter, then I expect generation to fail:
```
{
    "type": "object",
    "properties": {
        "awesome": {
            "type": "object",
            "javaType": "com.example.Radical",
            "javaTypeExists": true
        }
    }
}
```

Does this already exist, or is there already some way to accomplish this? Thanks :-)

**Comment by joelittlejohn** [comment]
Sorry, there's no way to achieve this through any existing configuration options. 

The best option you have right now is to implement a custom RuleFactory and change how the ObjectRule works. There are some examples of this here:

* https://github.com/fcarriedos/jsonschema2pojoCustomization
* https://github.com/bacta/jsonschema2pojo-bacta/tree/master/src/main/java/com/ocdsoft/bacta/soe/json/schema

**Comment by lucjross** [comment]
Thanks, those examples are helpful.

Still, would this feature be desirable?

**Comment by joelittlejohn** [comment]
I'm not currently interested in adding this to the core as I don't think it has wide enough applicability. Happy to reopen if this issue starts to gather more support.
