### ISSUE TITLE
Update Jackson2Annotator to support @JsonFormat annotation.

### ISSUE THREAD

**Issue by rakeshcusat** [joelittlejohn/jsonschema2pojo#698]
Jackson supports [JsonFormat](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations#deserialization-and-serialization-details) but the current annotator (Jackson2Annotator) doesn't support it. This would be super useful in case we convert a date-time format string to a Date object. Check [this link](http://www.baeldung.com/jackson-serialize-dates) to see some example.

```
public class Event {
    public String name;
 
    @JsonFormat
      (shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy hh:mm:ss")
    public Date eventDate;
}
```

**Comment by joelittlejohn** [comment]
Yes, we support the JsonFormat annotation for dates. You just need to set `<formatDateTimes>true</formatDateTimes>` in your configuration.

**Comment by rakeshcusat** [comment]
Thank you @joelittlejohn for pointing out the documentation. The Gradle plugin documentation is not update. I think we should update the documentation.
 I used this configuration to generate code for date-time field, but the current default format is `yyyy-MM-dd'T'HH:mm:ss.SSS`. I think it is following [ISO-860 format](https://en.wikipedia.org/wiki/ISO_8601).  Ideally it should have followed the[ RFC-339 format](https://tools.ietf.org/html/rfc3339). 

I tried to look jsonSchema standard documentation and did find any reference of `customDateFormat` field. Is `customDateFormat` part of standard jsonschema?
I don't want to use `customDateFormat` because the schema is shared between different teams who generate code in different languages and may not like to add a custom field.

**Comment by joelittlejohn** [comment]
@rakeshcusat no, customDateFormat is not part of the standard. There are a variety of 'extension' properties that this library provides, and since the standard allows _any_ additional properties to be included there is no conflict there.

I'm not sure what you mean about the how the format should have followed RFC-3339. Can you elaborate about how you'd like the default date format to be different? RFC-3339 is a subset of ISO 8601 and the dates we produce are valid RFC-3339 dates.

**Comment by joelittlejohn** [comment]
I can understand not wanting to add the custom property to your schema though. Another option you have here is to ignore the formatDateTimes configuration option and instead configure the your Jackson ObjectMapper to set the format you want globally.
