### ISSUE TITLE
jsonFormat ignored when using Java 8 date & time

### ISSUE THREAD

**Issue by CheeseE** [joelittlejohn/jsonschema2pojo#699]
I have some date fields defined  as following:
```
        "effectiveDate": {
          "type": "string",
          "format": "date",
          "customDateTimePattern": "yyyy-MM-dd"
        }
```
In my maven plugin I've configured the plugin to use java.time.* for date fields as following:
```
    <configuration>
      <dateTimeType>java.time.LocalDateTime</dateTimeType>
      <dateType>java.time.LocalDate</dateType>
     </configuration>
```
After generating the classes the jsonFormat annotation is not applied to the classes:
```
    @JsonProperty("effectiveDate")
    private LocalDate effectiveDate;
```
Because of this all the date fields are serialized as array of integers.

**Comment by joelittlejohn** [comment]
I think the new customDateTimePattern only applies for fields that have `"format": "date-time"`:

https://github.com/joelittlejohn/jsonschema2pojo/blob/8c50832998e587f6bed126ab5213df0bd39b9137/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java#L143

We should add some further support for `"format": "date"` fields I think.
