### ISSUE TITLE
jsonschema2pojo-gradle-plugin : maven dependency problem

### ISSUE THREAD

**Issue by s13o** [joelittlejohn/jsonschema2pojo#702]
Maven build failed.
Can't resolve the org.gradle:gradle-base-services-groovy:jar:1.6 in public repos.
The lowest version is 2.1 (pls check the [repo.gradle.org](https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-base-services-groovy/) or [mvnrepository.com](http://mvnrepository.com/artifact/org.gradle/gradle-base-services-groovy))

**Comment by joelittlejohn** [comment]
Thanks for reporting this.

This dependency comes from https://repo.spring.io, and it appears to still be present:

http://repo.spring.io/plugins-release/org/gradle/gradle-base-services-groovy/1.6/

I can resolve this perfectly well when building the project, as this Spring repo is defined in our pom here:

https://github.com/joelittlejohn/jsonschema2pojo/blob/9f1688e237a4fd5f9d747cc8cd8b9c99cd8f5fd4/pom.xml#L434

Maybe this was a transitive problem with repo.spring.io?

**Comment by s13o** [comment]
I think it will be better just to update such dependencies to latest versions. But it is not so easy - now wth version 2.2 I'm getting a 'java.lang.ClassNotFoundException: org.gradle.model.internal.registry.ModelRegistryScope'. No idea what is it...
I'm behind a firewall and just Nexust (as a proxy) provides me mainly central M2 repo

**Comment by joelittlejohn** [comment]
You'll need to ask someone to add http://repo.spring.io/plugins-release to your list of repos mirrored by Nexus.

**Comment by s13o** [comment]
Do you mean this?

>         <repository>
>            <id>gradle-workaround</id>
>            <url>http://repo.spring.io/plugins-release</url>
>            <snapshots>
>              <enabled>false</enabled>
>            </snapshots>
>        </repository>

**Comment by joelittlejohn** [comment]
Yes, you need to add that to Nexus if you want to resolve dependencies from it.
