### ISSUE TITLE
org.jsonschema2pojo.ContentResolverTest require internet connection

### ISSUE THREAD

**Issue by s13o** [joelittlejohn/jsonschema2pojo#704]
This unit test is not an integratoinal test. Also a special setting like '-DforkMode=never' required for maven-surefire-plugin when it runs behind firewall. Will be better to start a simple local HTTP-server for such tests

**Comment by joelittlejohn** [comment]
Hi. Could you explain what you mean by:

> Also a special setting like '-DforkMode=never' required for maven-surefire-plugin when it runs behind firewall.

?

**Comment by joelittlejohn** [comment]
Yes you're right about this unit test, it's a little lazy. We could use https://github.com/rest-driver/rest-driver to avoid external http calls.

**Comment by ctrimble** [comment]
@joelittlejohn [WireMock](http://wiremock.org/) has a nice [JUnit rule](http://wiremock.org/docs/junit-rule/) for mocking out http endpoints.

**Comment by s13o** [comment]
Well, the "rest-driver" is an overkill for such simple test.
As I can see the main idea of it is just to test real http connection & exception handling  flow.
I did a pull request #705 - please check it, does it appropriative?

And about the '-DforkMode=never' - I'm working behind a proxy & firewall and it damn unconfortable to configure proxy settings in JVM and they are flashed what tests performed in a forked process...

**Comment by s13o** [comment]
The 'WireMock' is really nice! Many thanks for the link.
But how many http-tests we have? the only one?
We can refactor this test later when we will desire to implement one more

**Comment by thachhoang** [comment]
Fixed by #705.
