### ISSUE TITLE
JSON to POJO generation empty

### ISSUE THREAD

**Issue by krishnasatya** [joelittlejohn/jsonschema2pojo#708]
JSON to POJO generation is empty.  Preview does not render any classes and downloaded zip is empty.  Is there a way to see the error relating to the conversion ?

Thanks.

**Comment by joelittlejohn** [comment]
Are you using JSON Schema or JSON? If you enter JSON be sure to select *Source type: JSON*.

**Comment by krishnasatya** [comment]
I have used the conversion tool so many times, yet this one time I did have the source type incorrect.  I apologize for raising an invalid issue.  Thanks for pointing it out.
