### ISSUE TITLE
Suggestion: copy constructors

### ISSUE THREAD

**Issue by raould** [joelittlejohn/jsonschema2pojo#712]
hi, Thanks for the amazing tool. A possibly helpful feature would be to generate copy constructors.
```
class Foo {
 private int bar;
 public Foo( int bar) { this.bar = bar; } // already supported.
 public Foo( Foo other ) { this.bar = other.bar; } // <-- this kind of stuff here.
}
```

**Comment by joelittlejohn** [comment]
Hi @raould. It sounds like you want to clone another instance. I think this request exists already as #230.
