### ISSUE TITLE
Support customDatePattern and customDateTimePattern as global config options

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#716]
We can currently turn on default formatting with `formatDates`/`formatDateTimes` and also customize the pattern by adding `customPattern` to an individual field inside the schema. It would be good to be able to set a custom pattern globally (via a config option).

**Comment by joelittlejohn** [comment]
This will also satisfy requests like #698

**Comment by sbyron15** [comment]
@joelittlejohn Is there a reason why `customTimePattern` isn't supported?

I'm using `<timeType>java.time.LocalTime</timeType>`, and would like to be able to specify a pattern and have my `LocalTime` fields be annotated with `@JsonFormat`.

I noticed that `Jackson2Annotator` only annotates `date` and `date-time`.

**Comment by joelittlejohn** [comment]
@sbyron15 I don't see any reason that we shouldn't fix that for you. I'll take a look.

**Comment by sbyron15** [comment]
@joelittlejohn I went ahead and added support myself. Please see #740 

Thanks!
