### ISSUE TITLE
Adding field names as members in POJO

### ISSUE THREAD

**Issue by rmisra1234** [joelittlejohn/jsonschema2pojo#717]
Hi There,

Is it possible to define field names as static final variables in the generated POJO so that they can be referenced from other classes directly. e.g:

Test.java
---------
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Test {

    public static final String ID_KEY = "_id";

    @JsonProperty(ID_KEY)
    private String Id;
    @JsonProperty(ID_KEY)
    public String getId() {
        return Id;
    }

    @JsonProperty(ID_KEY)
    public void setId(String Id) {
        this.Id = Id;
    }
}

Thanks a lot!

**Comment by joelittlejohn** [comment]
I don't see a problem with adding these. We'd probably have to add config option to turn this on because there are a lot of people that don't like additional cruft in their generated types unless they have a specific use for it.

This would be quite an easy change.

**Comment by rmisra1234** [comment]
Thanks for your reply.
Could you please guide me with the changes. Will it be in PropertyRule.java?

**Comment by rmisra1234** [comment]
Any chance you have a few mins to help me with the changes please ? Thanks

**Comment by rmisra1234** [comment]
This can be done by adding the following line in PropertyRule.java:

jclass.field(JMod.PUBLIC | JMod.FINAL | JMod.STATIC, String.class, propertyName.toUpperCase(), JExpr.lit(propertyName));

**Comment by joelittlejohn** [comment]
@rmisra1234 Sorry, I didn't have time to look at this but I'll try to include this as a config option in a release soon.

**Comment by rmisra1234** [comment]
Thank u. Actually I am using Raml-to-Jaxrs plugin which in turn uses an older version 0.4.20 of jsonschema2pojo so I will have to request if latest release of Raml-to-Jaxrs can use the newer version(with the change above) as well. Any rough idea about the new release dates ?
