### ISSUE TITLE
Feature request: Self-Describing Jsonschema support

### ISSUE THREAD

**Issue by dashirov-ga** [joelittlejohn/jsonschema2pojo#718]
Self Describing  Jsonschema is a little known standard introduced by [Snowplow Analytics in 2014](http://snowplowanalytics.com/blog/2014/05/15/introducing-self-describing-jsons/). The main differentiating factors between jsonschema and self-describing jsonschema are further documented [here](https://github.com/snowplow/iglu/wiki/Self-describing-JSON-Schemas).  A repository containing collections of SDJS' are commonly stored in iglu repository format either on a file systems, s3 object store or api driven services. Each schema is stored the following a naming convention: 

`
$REPOSITORY_ROOT/${vendor}/${name}/${format="jsonschema"}/${version}
`

where the file node at the end of the path contains a self describing jsonschema content that may look like the following:
```
{
    "$schema": "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
    "self": {
        "vendor": "com.example",
        "name": "ad_click",
        "format": "jsonschema",
        "version": "7-3-1"
    },
    "type": "object",
    "properties": {
        "bannerId": {
            "type": "string"
        }
    },
    "required": ["bannerId"],
    "additionalProperties": false
}
```

This lends itself to automated discovery of related concepts in jsonschema2pojo:
$.schema.vendor maps to packageName ( E.g. "com.snowplowanalytics" )
$.schema.name maps to className (E.g. "AdClick")

Additionally, to handle multiple versions of self-describing jsonschemas we could introduce a concept of versioned static inner classes:

$.schema.version potentially maps to static inner className  (E.g. "AdClick.v1_0_0" )
    assuming it is good taste to have an outer class AdClick with multiple static inner classes: one for each version of the schema found during scan.

One thing to think about is annotation and corresponding jsonschema property to signal a deprecation warning 

An iglu repository can we walked to produce a corresponding java class library which will contain multiple versions of logical units. Traversal of a file system is not required though, as each individual schema already contains all the necessary information that would otherwise be derived from the file system structure to identify package and class names.

Current feature set provided by CLI and Maven Plugin does not easily lend itself to generating a complete self-describing jsonschema repository java class library counterpart. One can get quite far, but not far enough.

**Comment by ben-manes** [comment]
I designed a registry with a similar capability, but included both `active` and `inactive` schemas. This way if a schema is removed from an instance, the historic data can be retained as read-only. I toyed with the idea of extending js2p, but haven't tried to yet. For home grown extensions, I think using a `customRuleFactory` would be appropriate and may not require any changes to this project.

**Comment by dashirov-ga** [comment]
All schemas are active at all times. Different pieces of software are using different schema versions - similar to how maven dependencies are versioned. So there must be capability to create a pojo based on any registered (stored in the repository) version of a self described jsonschema. 

So far, I wasn't able to generate a super-library based on repository contents, but I got very close.

**Comment by ben-manes** [comment]
What I meant by active/inactive is when using schemas to model roles. In a logistics scenario a user might be a driver, dispatcher, accountant, etc. If a driver is promoted to a dispatcher then future loads cannot be assigned to him, but historic loads may link to his driver details. This way there is flexibility to allow changes without losing information. Otherwise roles would have to be decoupled from the entity or more rigidly expressed, which adds complexity by making the entity less self-describing.

I imagine other metadata driven applications would have their own extensions, which is why I'd hope the generator is flexible enough without needing to directly support custom formats. Identifying missing extension points would probably be more valuable than format support.

**Comment by joelittlejohn** [comment]
This is an interesting area of research and no doubt a powerful tool for your organisation, but it isn't something we would support in the core.  This project does provide ways that you can extend the behaviour to support new keywords though, as Ben mentioned, e.g. via a customer rule factory.
