### ISSUE TITLE
NoClassDefFoundError ToStringBuilder from generated class

### ISSUE THREAD

**Issue by maneeshbhunwal** [joelittlejohn/jsonschema2pojo#721]
Hi Team,

Thank you for this awesome plugin.

I am trying to return object of a class generated by jsonschema2pojo from a spring mvc project. 
it is giving me 
`Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/ToStringBuilder`
The problem is coming even if I try to do 
`object.toString()`
I am using version
 <version>0.4.34</version>
I have checked everywhere and could not find solution can you please check.

Thanks
Maneesh

**Comment by maneeshbhunwal** [comment]
I have commons-lang3 (3.4) in my pom, but this guy is searching for 
org/apache/commons/lang/builder/ToStringBuilder
will I have to downgrade my commons-lang ?

**Comment by joelittlejohn** [comment]
Hi @maneeshbhunwal. You can choose commons-lang3 as a configuration option if you wish, then the generated output will use commons-lang3 classes.

See https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.34/generate-mojo.html#useCommonsLang3
