### ISSUE TITLE
Object holding a JSON Array not initialized while creating Parcelable of JSON string

### ISSUE THREAD

**Issue by droidluv** [joelittlejohn/jsonschema2pojo#723]
```json
{
	"test_object": []
}
```

Result:
```java
package com.example;

import java.util.List;
import android.os.Parcel;
import android.os.Parcelable;
import android.os.Parcelable.Creator;

public class Example implements Parcelable
{

public List<Object> testObject = null;
public final static Parcelable.Creator<Example> CREATOR = new Creator<Example>() {


@SuppressWarnings({
"unchecked"
})
public Example createFromParcel(Parcel in) {
Example instance = new Example();
in.readList(instance.testObject, (java.lang.Object.class.getClassLoader()));
return instance;
}

public Example[] newArray(int size) {
return (new Example[size]);
}

}
;

public void writeToParcel(Parcel dest, int flags) {
dest.writeList(testObject);
}

public int describeContents() {
return 0;
}

}
```

Expected result:
In writeToParcel method it should be
```java
if (testObject == null) {
dest.writeByte((byte) (0x00));
} else{
dest.writeByte((byte) (0x01));
dest.writeList(video);
}
```
and in createFromParcel it should be
```java
if (in.readByte() == 0x01) {
video = new ArrayList<Video>();
in.readList(video, Video.class.getClassLoader());
} else {
video = null;
}
```
Issue:
If the generated class is directly used atleast in the deserializing part code will crash because object in read from parcel is not initialized.

**Comment by joelittlejohn** [comment]
This is the object responsible for generating the Parcelable implementation:

https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ParcelableHelper.java

I wrote this from a basic understanding of Parcelables but I'm no expert. Thanks for providing the output you expect. Do you think you can understand the ParcelableHelper enough to propose a PR for this?

**Comment by droidluv** [comment]
I am in the midst of deployment and in a 14 hour shift to make heads or tails of your Parcelable Helper, but I can help you with the implementation logic, any List object should be initialized, so in a scenario where the **list will never be null** the simplest fix would be initializing

public List<Object> testObject = null;
as
public List<Object> testObject = new ArrayList<>();

in case of possibility of null  (which is almost always)
you have to do null handling like I have written above

**Comment by yccheok** [comment]
Yes. I can confirmed @droidluv finding. Without explicit initialization on the `List`, NPE will be thrown.

Here's some info 

https://stackoverflow.com/a/6300744/72437

**Comment by joelittlejohn** [comment]
We do have an option `initializeCollections` that should help here. If you set this on does it solve the problem for you?

I realise that null can still be set and we could implement some kind of check byte to indicate null. I'm just curious to know whether `initializeCollections` help. We could force this option on when the `parcelable` option is on.

**Comment by joelittlejohn** [comment]
By default we initialise all collections, so I don't think there is anything to do here.
