### ISSUE TITLE
Make generated POJO implements Serializable without change on json schema

### ISSUE THREAD

**Issue by guillaume-aecf** [joelittlejohn/jsonschema2pojo#724]
Hi

Is there a way that generated POJO classes from json Schema could implements both Serializable and Cloneable interfaces, even if the input schemas doesn't declare
`"javaInterfaces" : ["java.io.Serializable", "Cloneable"],`

I don't have a hand on the schema so maybe an option would be nice to force this behavior?

Best regards,

**Comment by joelittlejohn** [comment]
Hi @guillaume-aecf. There's an option to force `java.io.Serializable`:

https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.34/generate-mojo.html#serializable

You can't force Cloneable since we don't have an option to implement `Object#clone()`.

**Comment by guillaume-aecf** [comment]
Perfect! Could you update this page https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference 
with this information? I didn't known about this option which isn't referenced in this documentation. :-)

Thanks!

**Comment by joelittlejohn** [comment]
@guillaume-aecf That page on the wiki is a reference of schema rules and how they are supported, including any custom schema rules that we have added. It doesn't include any info about the configuration options as these are documented in the usual way e.g. [Maven goal docs](https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.34/generate-mojo.html), [Ant task docs](https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.34/Jsonschema2PojoTask.html), CLI `--help` output, etc.
