### ISSUE TITLE
API breakage between 0.4.31 and 0.4.32

### ISSUE THREAD

**Issue by dantran** [joelittlejohn/jsonschema2pojo#729]
Latest schema2json-core introduces additional arg for 

Schema SchemaStore.create(Schema parent, String path, String refFragmentPathDelimiters)

How  do I migrate from 0.4.31 which has this

Schema SchemaStore.create(Schema parent, String path)

?

**Comment by dantran** [comment]
sorry about the noise the answer is here https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.34/generate-mojo.html

**Comment by joelittlejohn** [comment]
Ah great, so I guess you just wanted to know the default value (`#/.`)?

**Comment by dantran** [comment]
fyi, json2schema-core does get used, so you may want to deprecate the method first

not too late to reintroduce the method and call new one with the default value (#/.)
