### ISSUE TITLE
Ant tool is not generating the classes. Instead giving below errors.

### ISSUE THREAD

**Issue by ab48917** [joelittlejohn/jsonschema2pojo#730]
C:\_SelfStart\WsdlAnt\build.xml:93: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;

This is my target and taskdef--->

<taskdef name="jsonschema2pojo" classname="org.jsonschema2pojo.ant.Jsonschema2PojoTask">
  	<classpath> 
  		<fileset dir="${basedir}/lib/">
  		   <include name="*.jar"/>
  		 </fileset>
  	 </classpath>
  </taskdef>
              	    
     <target name="generateJsontoJava">
     <jsonschema2pojo source="${basedir}/wsdl/geo.json" 
        targetDirectory="${basedir}/build/generated-types" 
     	 targetPackage="ctl.geo"/>
      </target>

**Comment by joelittlejohn** [comment]
This looks like a Jackson library version issue. Which version of Jackson are you using?

**Comment by joelittlejohn** [comment]
I think the tutorial must be out of date, I'll update it.

Please use jackson-databind v2.5 or later. It would also make sense to use the same version for all three Jackson libraries you have listed.
