### ISSUE TITLE
entire ANT setup has jar conflicts.

### ISSUE THREAD

**Issue by ab48917** [joelittlejohn/jsonschema2pojo#731]
Seems entire ANT setup has jar conflicts. Would you please test the compatibility and let me know to use which all versions of jars need to be used.

**Comment by joelittlejohn** [comment]
Hi @ab48917 . The latest versions are all here:

https://github.com/joelittlejohn/jsonschema2pojo/blob/master/pom.xml

You can use the versions listed there for each of the jars mentioned in the Getting Started page. Let me know what you end up using and I we can update the help page.

**Comment by ab48917** [comment]
It seems jsonschema2pojo-ant-0.4.35 inself upgraded to jsonschema2pojo-ant-0.4.36. Can we get all this at one place?
jsonschema2pojo-ant-0.4.36
jsonschema2pojo-cli-0.4.36
jsonschema2pojo-core-0.4.36

**Comment by ab48917** [comment]
I do not see these jars even in https://github.com/joelittlejohn/jsonschema2pojo/releases/tag/jsonschema2pojo-0.4.35 

Do we have only option to get these from maven repositories or by building this project

**Comment by joelittlejohn** [comment]
> It seems jsonschema2pojo-ant-0.4.35 inself upgraded to jsonschema2pojo-ant-0.4.36. Can we get all this at one place?
> jsonschema2pojo-ant-0.4.36
> jsonschema2pojo-cli-0.4.36
> jsonschema2pojo-core-0.4.36

Sorry, I don't understand what you mean by this. 0.4.36 is not released.

The jars are best downloaded from Maven central using the​ links in the Getting Started page.

**Comment by ab48917** [comment]
Hi Joe,

I dont understand as why its not creating the classes with below plugin in
ant. I ran the github project and placed all those snapshots jars generated
through project of core, cli and jsonschema2pojo-ant-0.4.36-SNAPSHOT.

Below is ant script. Please suggest if you see anything-

 <taskdef name="jsonschema2pojo"
classname="org.jsonschema2pojo.ant.Jsonschema2PojoTask">
      <classpath> 
                <fileset dir="${basedir}/lib/">
                   <include name="*.jar"/>
                 </fileset>
             </classpath>
  </taskdef>

     <target name="generateJsontoJava">
     <jsonschema2pojo source="${basedir}/wsdl/geo.json"
        targetDirectory="${basedir}/src/"
          targetPackage="ctl.geo"/>
      </target>

**Comment by ab48917** [comment]
Hi Joe,

It was required to mention sourceType="JSON " and classes are generated.
But seems duplicate classes are generated with ______________
these types of line. Any clue to replace underscore with certain numbers.

**Comment by joelittlejohn** [comment]
If you want different parts of the data to reuse the same type then you need to use a schema with `$ref`. If you want to continue to use JSON instead of JSON Schema, then you will need to ensure you provide a _minimal_ example so that you don't get additional classes generated. This plugin cannot guess which parts of your JSON data represent the same type and which do not.
