### ISSUE TITLE
Update to commons-lang3

### ISSUE THREAD

**Issue by ChrissW-R1** [joelittlejohn/jsonschema2pojo#735]
Please update to the new 3.x version of commons-lang. We need this for some projects, were we already use the newest version.

* https://commons.apache.org/proper/commons-lang/article3_0.html
* https://mvnrepository.com/artifact/org.apache.commons/commons-lang3

**Comment by joelittlejohn** [comment]
@ChrissW-R1 what do you mean by update exactly? You bring your own commons-lang version when you compile sources generated by this plugin, we don't decide your commons-lang version.

If you want to generate commons-lang3 compatible Java output, just use:

```xml
<useCommonsLang3>true</useCommonsLang3> 
```

**Comment by ChrissW-R1** [comment]
Sorry, I had overlooked this option
