### ISSUE TITLE
Support custom format value mappings to java types

### ISSUE THREAD

**Issue by seprich** [joelittlejohn/jsonschema2pojo#736]
Please support a possibility to provide custom mapper methods or otherwise customize the current, often not good default mappings, of formats to java types.
E.g
Currently `"format": "date"` is mapped to "String" - but I would prefer java 8 "java.time.LocalDate" (String is quite unusable forcing me to manually validate and convert everywhere where I would use the generated DTO)
Also `"format": "date-time"` -> "java.util.Date"  is critically flawed (loosing timezone information in the converison) compared to "java.time.LocalDateTime"

**Comment by joelittlejohn** [comment]
@seprich We have extensive configuration options in this area.

Check out:
```xml
<useJodaDates>true</useJodaDates>
<useJodaLocalDates>true</useJodaLocalDates>
<useJodaLocalTimes>true</useJodaLocalTimes>
```

**Comment by joelittlejohn** [comment]
If you want to truly configure your own types, check out:

```xml
<dateType>...</dateType>
<dateTimeType>...</dateTimeType>
```

**Comment by seprich** [comment]
Joda time is good for pre-8 java, for java8 I rather use java.time
Where are configuration options documented? Only place I found is https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-gradle-plugin
listing the "useJodaDates" option but no "dateType" is mentioned.

**Comment by joelittlejohn** [comment]
Thanks for mentioning. I've added these to the gradle readme.
