### ISSUE TITLE
Extend existing java class

### ISSUE THREAD

**Issue by mmueller-abacus** [joelittlejohn/jsonschema2pojo#741]
How can I extend from an existing class, which should and cannot be generated?
```json
{
  "additionalProperties": false,
  "type": "object",
  "extends": {
    "$ref": "java:/org.example.foo.baa"
  },
  "properties": {
    "type": {
      "type": "string",
    },
  }
}
```
Execution failed for task ':Example:generateJsonSchema2PojoForDebug'.

> Couldn't read content from the classpath, file not found: java:/org.example.foo.baa

I also tried with:

`"$ref": "java:/org.example.foo.baa.class"`
`"$ref": "java:/org.example.foo.baa.java"`

**Comment by joelittlejohn** [comment]
Try:

```json
{
  "additionalProperties": false,
  "type": "object",
  "extends": {
    "type": "object",
    "javaType": "org.example.foo.Baa"
  },
  "properties": {
    "type": {
      "type": "string",
    },
  }
}
```

**Comment by mmueller-abacus** [comment]
That seems to work, but the "org.example.foo.Baa" class is generated.

**Comment by joelittlejohn** [comment]
org.example.foo.Baa needs to be on the classpath if you want it to be re-used and not generated.

**Comment by mmueller-abacus** [comment]
Okey perfect, thank you.
