### ISSUE TITLE
Generating 2 constructors

### ISSUE THREAD

**Issue by locofrank** [joelittlejohn/jsonschema2pojo#742]
The latest build was generating 2 constructors for several of my classes

I needed to roll back to 0.4.35 to fix my project

**Comment by joelittlejohn** [comment]
Are you using Parcelable classes by any chance?

**Comment by joelittlejohn** [comment]
And are the constructors duplicates? Do the classes compile? It would be useful to have some more detail here. Thanks!

**Comment by yomik** [comment]
Oh, I think I'm the one to blame for that.
I reproduced this by setting the includeConstructors = true in the configuration. I overlooked that one.
I'm going to provide a fix for this, but now I wonder what other settings might affect the changes....
For instance, the code refers to isConstructorsRequiredPropertiesOnly, which is not in the documentation (some configuration that was added recently ?).

Anyway, I'm trying to fix this ASAP, and try to see what other side effects might come from other settings as well.

Sorry for the trouble

**Comment by joelittlejohn** [comment]
Thanks for reporting this quickly @locofrank. Closed by #743.

**Comment by joelittlejohn** [comment]
I'll release 0.4.37 shortly.

**Comment by locofrank** [comment]
Wow! You folks are on top of it. Sorry I didn't respond quickly. Thanks for the quick fix.
