### ISSUE TITLE
GenerateJsonSchemaJavaTask automatically sets outputs.upToDateWhen { false }

### ISSUE THREAD

**Issue by Slady32** [joelittlejohn/jsonschema2pojo#744]
Hi,

I was trying to optimize the generation of my models within my build process and encountered that the `GenerateJsonSchema2Pojo` task automatically applies `outputs.upToDateWhen { false }` which makes it hard to skip the generation of the model classes if the JSON schema file doesn't change.

Do you have any plans to remove this behaviour and let the developers decide whether they want to apply `outputs.upToDateWhen { false }` if needed or not?

Thank you in advance.

Kind regards,
Slady

**Comment by joelittlejohn** [comment]
How do you intend to set this?

I don't currently know of a mechanism by which we can easily either remove this or set it more intelligently. Presumably if we don't set this, then there is a risk that generated sources will not be recompiled when they change.

**Comment by Slady32** [comment]
As far as i know it should be sufficient if you set the `inputs.files` and `outputs.files` property in the `generateJsonSchema2Pojo` task

I tried to override your `GenerateJsonSchemaJavaTask ` (as `CustomGenerateJsonSchemaJavaTask`) but without the `outputs.upToDateWhen { false }` behaviour and it worked to get the `up-to-date` notification from the task only if the JSON schema file changed.

Here's my gradle config (simplified):
```groovy
def schema = file("$pathToMyJsonSchemaFile")

jsonSchema2Pojo {
	// Location of the JSON Schema file(s).
	source = files(schema)
	// ...
}

// remove the original generateJsonSchema2Pojo task to override it with my custom task
tasks.remove(generateJsonSchema2Pojo)
task generateJsonSchema2Pojo(type: CustomGenerateJsonSchemaJavaTask) {
	inputs.files files(schema)
	outputs.files files(jsonSchema2Pojo.targetDirectory)
}
// attach it into the build process
compileJava.dependsOn generateJsonSchema2Pojo
```

It may be simplified by setting `inputs.files` as the `sourceFiles `from the `jsonSchema2Pojo` configuration:
```groovy
task generateJsonSchema2Pojo(type: CustomGenerateJsonSchemaJavaTask) {
	inputs.files files(jsonSchema2Pojo.sourceFiles)
	outputs.files files(jsonSchema2Pojo.targetDirectory)
}
```

Further reading for my configuration was: https://docs.gradle.org/3.5/userguide/more_about_tasks.html#sec:up_to_date_checks

Kind regards,
Slady

**Comment by ben-manes** [comment]
@joelittlejohn The intent is to ensure Gradle knew to re-run the task when the inputs differ. If no signal is provided Gradle will always skip the task. The plugin currently forces a run no matter what to ensure correctness and the proposal suggests to only do so if an input file changes (or the output is removed).

@Slady32 I think a PR to change this would be fine. The `upToDateWhen` was a quick solution when I wrote the plugin because I had inconsistencies with input/outputs (this was around Gradle 1.0 when I was busy writing plugins to migrate an Eclipse-only build). The imperfect nature of this hack hasn't been a problem for me because the generation is fast and the compile task skips by observing that the checksum hasn't changed. So while I don't think you should worry about it, I agree that using the smarter mechanism would be cleaner.

**Comment by Slady32** [comment]
Sure, I haven't worked on a Gradle plugin myself yet but I will do the change and create a pull request.

Thank you for the reply!

Kind regards
Slady

**Comment by joelittlejohn** [comment]
One more question on this:

Does Gradle consider that the task needs to be rerun if the configuration changes? Is the scope of this check limited to repeated invocations in a single build (and hence a single configuration)?

**Comment by ben-manes** [comment]
That is a good point. If the configuration changes but that is not registered as a "task input", probably next build will not rerun the task. In most plugins a configuration change doesn't invalidate the task, so this would have to be an explicit decision. Their [documentation](https://docs.gradle.org/4.0/javadoc/org/gradle/api/tasks/TaskInputs.html) includes adding properties, where we could put the entire configuration object if made serializable. Then it would rerun on a `jsonSchema2Pojo` change.

**Comment by Slady32** [comment]
I just tested this case and you are right, the task is not rerunning because it just uses the input sources (JSON files) as reference for the up-to-date check but not the configuration.

In my opinion a configuration change has a bigger influence in the creation process so in this case an explicit `clean` call may be appropriate anyway.

**Comment by joelittlejohn** [comment]
I don't think we can expect users to explicitly `clean` whenever they change the configuration. This will lead to a never-ending flow of issues raised here as to why a certain option is not working as expected.

Reading more here: https://docs.gradle.org/3.3/userguide/more_about_tasks.html#sec:up_to_date_checks

Is there a way we can easily annotate each config option as an 'input'? (without having to introduce some new aggregated config object). We don't have explicit getters for the config fields here:

https://github.com/joelittlejohn/jsonschema2pojo/blob/d1e093258c042e7ecf3610958a4422649b38902f/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy

because I assume groovy is generating these. Is it possible to indicate that the getter should have an annotation? Or maybe Gradle also allows the `@Input` annotation on a field?

**Comment by joelittlejohn** [comment]
The annotation itself can be added to fields, which is a good sign:

https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Input.html

**Comment by joelittlejohn** [comment]
@Slady32 Could you try adding `@Input` to [every field here](https://github.com/joelittlejohn/jsonschema2pojo/blob/d1e093258c042e7ecf3610958a4422649b38902f/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy#L35) and then do some more tests?

**Comment by Slady32** [comment]
As far as I see this the `@Input` or `@InputFile(s)` annotations only work for task properties but not for plugin extions properties which are in this case set for the plugin but not for the task itself.

So a restructuring would be necessary in order to use the up-to-date checks from the annotations

**Comment by joelittlejohn** [comment]
Okay, would it be enough to mark [this field](https://github.com/joelittlejohn/jsonschema2pojo/blob/d1e093258c042e7ecf3610958a4422649b38902f/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy#L29) with `@Input` and make the configuration serializable?

**Comment by Slady32** [comment]
Unfortunately no because in the JsonSchemaExtension are some fields defined with an interface as datatype and those can't be serialized.

I added `implements Serializable` to the `JsonSchemaExtensions` class but following error occurs:
```
Caused by: org.gradle.messaging.serialize.MapSerializer$EntrySerializationException: Unable to write entry with key: 'configuration' and value: 'generateBuilders = false
usePrimitives = false
source = [C:\Git\jsonschema2pojo-slady32\jsonschema2pojo-gradle-plugin\example\java\build\resources\main\json]
targetDirectory = C:\Git\jsonschema2pojo-slady32\jsonschema2pojo-gradle-plugin\example\java\build\generated-sources\js2p
targetPackage = example
propertyWordDelimiters = [_]
useLongIntegers = false
useBigIntegers = false
useDoubleNumbers = true
useBigDecimals = false
includeHashcodeAndEquals = true
includeConstructors = false
includeToString = true
toStringExcludes = []
annotationStyle = jackson
inclusionLevel = class org.jsonschema2pojo.InclusionLevel
customAnnotator = org.jsonschema2pojo.NoopAnnotator
customRuleFactory = org.jsonschema2pojo.rules.RuleFactory
includeJsr303Annotations = true
includeJsr305Annotations = false
sourceType = jsonschema
removeOldOutput = false
outputEncoding = UTF-8
useJodaDates = false
useJodaLocalDates = false
useJodaLocalTimes = false
dateTimeType = null
dateType = null
timeType = null
useCommonsLang3 = false
parcelable = false
serializable = false
initializeCollections = true
classNamePrefix =
classNameSuffix =
fileExtensions = []
includeAccessors = true
targetVersion = 1.6
includeDynamicAccessors = false
formatDates = false
formatTimes = false
formatDateTimes = false
customDatePattern = null
customTimePattern = null
customDateTimePattern = null
refFragmentPathDelimiters = #/.
sourceSortOrder = OS
     '.
        at org.gradle.messaging.serialize.MapSerializer.write(MapSerializer.java:50)
        at org.gradle.api.internal.changedetection.state.InputPropertiesSerializer.write(InputPropertiesSerializer.java:40)
        ... 76 more
Caused by: java.io.NotSerializableException: org.jsonschema2pojo.gradle.JsonSchemaExtension_Decorated
        at org.gradle.messaging.serialize.DefaultSerializer.write(DefaultSerializer.java:53)
        at org.gradle.messaging.serialize.MapSerializer.write(MapSerializer.java:48)
        ... 77 more
```
when running `mvn install` on the `jsonschema2pojo-gradle-plugin`.

**Comment by ben-manes** [comment]
Can we call the API directly and iterate the properties? 

Alternatively the value could be the toString of the configuration object.

**Comment by joelittlejohn** [comment]
Annotate `toString` with `@Input`?

**Comment by ben-manes** [comment]
Use [task.inputs](https://docs.gradle.org/4.0/javadoc/org/gradle/api/tasks/TaskInputs.html) directly, e.g. `inputs.property("configuration", configuration.toString())`. Ideally instead we'd iterate over the properties and dispatch to the best method, but that might not be necessary.

**Comment by Slady32** [comment]
After retrying with the `@Input` annotation I have to say that another error caused the above mentioned `NotSerializableException`. Nonetheless it can't be serialized anyway when being executed with `gradle build`.

However I tried the solution @ben-manes suggested and it is working. After a successful build and another configuruation change the task is out-of-date and rerunning.

So this would be the suggested configuration for successful up-to-date/out-of-date checks:
```groovy
inputs.property("configuration", configuration.toString())
inputs.files project.files(configuration.sourceFiles)
outputs.files project.files(configuration.targetDirectory)
```

@joelittlejohn does this look good to you?
