### ISSUE TITLE
VVIP Generated Java Class doesn't have all properties

### ISSUE THREAD

**Issue by helloosuman** [joelittlejohn/jsonschema2pojo#747]
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "javaType": "com.flight.cc.catalog.message",
  "description": "Clear Cache Schema",
  "properties": {
    "items": {
      "type": "array",
      "element": {
        "type": "object",
        "properties": {
          "cckey": {
            "description": "ex: part id number",
            "type": "string"
 },
          "originatedtime": {
            "type": "string",
            "description": "last updated time from originated system"
 },
          "source": {
            "type": "string",
            "description": "source values"
 }
        },
        "required": [
          "cckey",
          "originatedtime"
 ]
      }
    }
  },
  "required": [
    "items"
 ]
}

**Comment by joelittlejohn** [comment]
Please see GitHub's markdown guide and format this code block appropriately:

https://guides.github.com/features/mastering-markdown/

Which Java class are you referring to and which properties were missing?

**Comment by helloosuman** [comment]
I used jsonschema2pojo-maven-plugin to generate java classes for the above schema. However, all fields like cckey, originatedtime, source etc. are missing. See message.txt as generated java file and jsonschema.txt as json schema file for reference

[message.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/1093080/message.txt)
[jsonschema.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/1093086/jsonschema.txt)

**Comment by joelittlejohn** [comment]
'element' is not valid JSON Schema. You need to use 'items'.

**Comment by helloosuman** [comment]
thank you so much ....John. Appreciate your help.
