### ISSUE TITLE
Javascript error when I click on Preview/Zip button

### ISSUE THREAD

**Issue by doppiak** [joelittlejohn/jsonschema2pojo#754]
When I click on Preview or Zip button, I receive a Javascript error

![immagine](https://user-images.githubusercontent.com/29733640/27592727-70231d92-5b55-11e7-9e93-5d9f89f736d0.png)

**Comment by joelittlejohn** [comment]
What browser are you using? What version?

Also, could you 'hard refresh' the page and try again? See:
https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

**Comment by doppiak** [comment]
I'm using Chrome 59.0.3071.109 and Firefox 54.0

**Comment by joelittlejohn** [comment]
I'm afraid I have no idea what the problem is. If you open the Chrome console and load the page, do you see any errors? I can't reproduce any errors at all with any browser I try. It seems like this might be a problem with your internet connection. Are you on a corporate network?

The logs and analytics suggest that people are still using the site without a problem. I can see many people previewing and generating Java.

**Comment by doppiak** [comment]
Maybe this is a problem with my internet connection. I'm on a corporate network, but in the past there wasn't any problem with this site. I don't know, maybe a recent change in my corporate network. I just tried to open you site with a mobile connection and there is no problem.

**Comment by joelittlejohn** [comment]
Here is the list of external things we include in the website:

```html
    <link href="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/bootstrap.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.5/clipboard.min.js"></script>
    <script src="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/codemirror-compressed.js"></script>
    <script src="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/runmode.js"></script>
    <script src="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/js.cookie.js"></script>
    <script src="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/index.js"></script>

    <link rel="stylesheet" href="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/codemirror.css">
    <link rel="stylesheet" href="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/eclipse.css">
    <link rel="stylesheet" href="http://joelittlejohn.github.io/jsonschema2pojo/resources/public/index.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
```

It sounds to me like http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js may have been blocked by your corporate firewall. The browser network console may be able to tell you more.
