### ISSUE TITLE
Unable to generate classes from CLI

### ISSUE THREAD

**Issue by raharida** [joelittlejohn/jsonschema2pojo#755]
I executed the following command in mac

jsonschema2pojo --target /Users/Raharida/src/ --source /Users/Raharida/Downloads/address

I get the below exception 

readlink: illegal option -- f
usage: readlink [-n] [file ...]

Version used : 0.4.37

**Comment by joelittlejohn** [comment]
On macOS it may be better to install jsonschema2pojo via brew if you can.

I never realised that the current script `jsonschema2pojo` is not  macOS compatible. We should fix this.

**Comment by joelittlejohn** [comment]
Also, could you tell me what you see when you use this command:

```
echo $0
```

?

**Comment by raharida** [comment]
its -bash. 

How does installing through homebrew fix this? Is there a version which is tested against mac?

**Comment by joelittlejohn** [comment]
Ah, maybe it doesn't. I thought that the homebrew formula must already bundle a macOS-compatible script but I could be wrong about this. It's possible that people using that formula simply have core-utils installed.

I no longer use macOS so I don't have a good environment to test this in right now.

**Comment by raharida** [comment]
Oh Thank you. I will test it with homebrew and update this.

**Comment by joelittlejohn** [comment]
It might be good for us to update our script here to use a strategy like this if we detect that we can't use readlink as expected: https://stackoverflow.com/a/3572105/125825

**Comment by raharida** [comment]
Installing through homebrew did not fix the problem . 

Edited : jsonschema2pojo.sh to use greadlink instead of readlink which fixed it.

**Comment by joelittlejohn** [comment]
For any Mac users reading this, there are a few options. 

You'll need to do **ONE OF** the following:

1. Use `brew install jsonschema2pojo`. You wont see the readlink error.
1. Install `coreutils` (`brew install coreutils`) then add something like this to your .bash_profile:

        # Get list of gnubin directories
        if type brew &>/dev/null; then
          HOMEBREW_PREFIX=$(brew --prefix)
          for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
          for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnuman; do export MANPATH=$d:$MANPATH; done
       fi

1.  Install `coreutils` (`brew install coreutils`) and modify the script to use `greadlink` instead of `readlink`, as @raharida did above.
1. Create your own script to run jsonschema2pojo, using the one brew generates as an example:

        #!/bin/bash
        export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home}"
        exec "${JAVA_HOME}/bin/java"  -jar "/usr/local/Cellar/jsonschema2pojo/1.0.2_2/libexec/lib/jsonschema2pojo-cli-1.0.2.jar" "$@"
