### ISSUE TITLE
Generated "standalone" Enums are unusable (since v0.4.32)

### ISSUE THREAD

**Issue by raphaeldirksen** [joelittlejohn/jsonschema2pojo#757]
Since version 0.4.32 you cannot use Enums if you decalre them in this way:
```javascript
{
  "type":"object",
  "enum": [
    "foo",
    "bar",
    "baz"
  ]
}
```

because the generated Enum looks like this:
```java
public enum Example {

FOO(null),
BAR(null),
BAZ(null);
private final Example_ value;
private final static Map<Example_, Example> CONSTANTS = new HashMap<Example_, Example>();

static {
  for (Example c: values()) {
    CONSTANTS.put(c.value, c);
  }
}

private Example(Example_ value) {
  this.value = value;
}

public Example_ value() {
  return this.value;
}

public static Example fromValue(Example_ value) {
  Example constant = CONSTANTS.get(value);
  if (constant == null) {
    throw new IllegalArgumentException((value +""));
  } else {
    return constant;
  }
}

}
```

The Problem is initializion with NULL.

**Comment by thachhoang** [comment]
```js
{
  "type":"object",
  "enum": [
    "foo",
    "bar",
    "baz"
  ]
}
```

I'm not sure about this schema: you're expecting an object, but the allowed values are strings. The enum works if you change the type to "string" instead.

**Comment by joelittlejohn** [comment]
@raphaeldirksen As @thachhoang says, this schema is rather strange, there is no value that can satisfy it since `"foo"`, `"bar"` and `"baz"` are the only acceptable values, but these values are not of type 'object'.

Do you really need this to work?

To be fair this is a valid schema.

**Comment by raphaeldirksen** [comment]
oh ok, i missed the possiblity to use "type":"string" to build the enum i need, thanks for this info.

But as i wrote, this worked until v0.4.32
