### ISSUE TITLE
Add Java extension for adding custom annotations to the generated fields

### ISSUE THREAD

**Issue by sshcherbakov** [joelittlejohn/jsonschema2pojo#758]
Sorry if I'm missing an existing  feature but I've also seen similar unanswered requests for similar feature in the mail group, e.g. [here](https://groups.google.com/forum/#!topic/jsonschema2pojo-users/7FGbS_Mn1GA).

Is it possible to add a Java extension to annotate generated Java fields/properties with custom user defined (not Jackson or JSR-303 only) annotations?

Please let me know if a PR for that could be helpful.

**Comment by thachhoang** [comment]
There are hooks into the library that let you modify generated classes/methods ([customRuleFactory](http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.37/generate-mojo.html#customRuleFactory)) and annotations ([customAnnotator](http://joelittlejohn.github.io/jsonschema2pojo/site/0.4.37/generate-mojo.html#customAnnotator)). This way you don't need to wait for changes to the library.

For Swagger annotations specifically, there was a stale pull request that needed tests: #585. I'm sure @joelittlejohn would welcome updates for it.

**Comment by joelittlejohn** [comment]
@sshcherbakov As @thachhoang says, a custom annotator is what you need. Check out the existing annotator implementations for help on how to do this. They're quite simple to implement.

**Comment by sshcherbakov** [comment]
Thanks you @thachhoang @joelittlejohn 
that approach works very well for me.

**Comment by krajkumar303** [comment]
Here is the approach I have followed to include swagger related annotation. This may help some one. 

- I have created the **CustomAnnotator** class under my library project (Separate maven project). 

```
import org.jsonschema2pojo.AbstractAnnotator;

import com.fasterxml.jackson.databind.JsonNode;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JFieldVar;

import io.swagger.annotations.ApiModelProperty;

public class CustomAnnotator extends AbstractAnnotator {
    @Override
    public void propertyField(JFieldVar field, JDefinedClass clazz, String propertyName, JsonNode propertyNode ) {
        super.propertyField(field, clazz, propertyName, propertyNode);

        if (propertyNode.has("description") && propertyNode.has("examples")) {
            field.annotate(ApiModelProperty.class).param("value", propertyNode.get("description").asText())
                    .param("example",propertyNode.get("examples").asText());
        }
        else if (propertyNode.has("description")) {
            field.annotate(ApiModelProperty.class).param("value", propertyNode.get("description").asText());
        }
    }
}
```

- I have included following dependency in my library project pom.

```
<dependency>
	<artifactId>jsonschema2pojo-maven-plugin</artifactId>
	<version>0.4.34</version>
	<groupId>org.jsonschema2pojo</groupId>
</dependency>
<dependency>
	<groupId>io.swagger</groupId>
	<artifactId>swagger-annotations</artifactId>
	<version>1.5.0</version>
</dependency>
```

Finally, on the main project where I had json schema, made the following changes on pom.xml.

Specified the fully qualified CustomAnnotator class name under plugin configuration and also the library project as a dependency to the plugin.

```
<plugin>
	<groupId>org.jsonschema2pojo</groupId>
	<artifactId>jsonschema2pojo-maven-plugin</artifactId>
	<version>0.4.34</version>
	<configuration>
		<sourceDirectory>${basedir}/src/main/resources/schemas
		</sourceDirectory>
		<outputDirectory>src/main/java</outputDirectory>
		<targetPackage>com.mycompany.json.pojo</targetPackage>
		<useCommonsLang3>true</useCommonsLang3>
		**<customAnnotator>com.utils.CustomAnnotator</customAnnotator>**
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
	**<dependencies>
		<dependency>
			<groupId>com.utils.lib</groupId>
			<artifactId>custom-library</artifactId>
			<version>1.0.0</version>
		</dependency>
	</dependencies>**
</plugin>
```

**Comment by terrancesnyder** [comment]
On this I'm looking to get the filename that generated the schema. This would be useful to annotate the class with something like ```@JsonSchemaValidation("classpath:jsonschema/book.json")```. But when implementing a ```AbstractAnnotator``` I dont see where or how I could get the current name of the file. I suppose I could add a custom node or attribute on the file itself but this seems redundant.
