### ISSUE TITLE
automatically remove 's' from class name if( 's' present at end)

### ISSUE THREAD

**Issue by kdblu3** [joelittlejohn/jsonschema2pojo#760]
i found small bug if i create class like Details (look in image)
![bug1](https://user-images.githubusercontent.com/17172841/28386852-8961ac3c-6cea-11e7-917a-00944b2cb7e9.png)

after that see in Preview section you will get result 
 class name like Detail . here i don't know why its remove  's'  from class name. (look in image)
![bug2](https://user-images.githubusercontent.com/17172841/28386986-00868d46-6ceb-11e7-9322-966638b19b8b.png)

**Comment by joelittlejohn** [comment]
This is by design. You have used Details to represent an array, so individual items within that array are a 'Detail'.

If you want to use 'Details', just paste an array item instead of the array.

**Comment by kdblu3** [comment]
thank you!
