### ISSUE TITLE
Can't get action logs

### ISSUE THREAD

**Issue by crazy4groovy** [joelittlejohn/jsonschema2pojo#762]
The docs say "All actions are logged at the info level."

However, when I set the `gradlew -i generateJsonSchema2Pojo` flag, I see almost no INFO logs related to work that generateJsonSchema2Pojo is doing. I'm wondering what do I need to set to get those logs?

(BTW I'm trying to figure out why the plugin is not generating pojos for 2 of my 70 schemas on a Windows machine, but works fine on Mac & Linux. So I'd like to see the logs during each schema file conversion. I suspect maybe it has to do with schema ref paths..)

logs:

```
. . .
10:19:47.318 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :tractr-web-api-model:generateJsonSchema2Pojo (Thread[Daemon worker Thread 7,5,main]) started.
10:19:47.319 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :tractr-web-api-model:generateJsonSchema2Pojo
10:19:47.319 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':tractr-web-api-model:generateJsonSchema2Pojo'
10:19:47.319 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':tractr-web-api-model:generateJsonSchema2Pojo' is up-to-date
10:19:47.319 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':tractr-web-api-model:generateJsonSchema2Pojo' (up-to-date check took 0.0 secs) due to:
  Task.upToDateWhen is false.
10:19:47.319 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':tractr-web-api-model:generateJsonSchema2Pojo'.
10:19:47.320 [INFO] [org.gradle.api.Task] Using this configuration:
generateBuilders = true
usePrimitives = false
. . .
sourceSortOrder = OS

10:19:47.685 [DEBUG] [org.gradle.api.internal.changedetection.state.CachingTreeVisitor] Visiting directory 'C:\service\api-model\build\generated-sources\java'
10:19:47.694 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':tractr-web-api-model:generateJsonSchema2Pojo'
10:19:47.695 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :tractr-web-api-model:generateJsonSchema2Pojo (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.376 secs.

. . .
```

**Comment by ben-manes** [comment]
The plugin itself logs at `INFO` level, but all it does is feed the configuration into the code generator. Therefore the logging is the configuration it is running with, which could be incorrect either due to user configuration or a bug.

`sourceSortOrder = OS` sounds likely a good candidate, since that controls the order of evaluation.

I'm not sure about the code generator, but worst case you could enable the debugger to step through during the Gradle build.
