### ISSUE TITLE
Generating pojo that handel null

### ISSUE THREAD

**Issue by Abdelsattar** [joelittlejohn/jsonschema2pojo#765]
we just need to use it after parsing it from coming data that not through exception when access it so add a checker in get() to check nullability of the attribute

**Comment by joelittlejohn** [comment]
Sorry, I don't know what you mean. Could you give an example of what you code you get right now and what code you want?

**Comment by Abdelsattar** [comment]
i mean like this 
 public Result getResult() {
       return (result != null) ? result : new Result();
   }

**Comment by joelittlejohn** [comment]
I'm not going to include that in the core of this project in afraid, however you are free to fork and customize it.
