### ISSUE TITLE
Jackson TypeReference for dynamically loaded pojo class

### ISSUE THREAD

**Issue by tarunz001** [joelittlejohn/jsonschema2pojo#767]
I have a requirement to get json input Pojo instance and i am using Jackson 2 library and below readValue method could do that using typeReferencing :

> POJO_ClassName p = mapper.readValue(new TypeReference< POJO_ClassName >() {});

But the problem is as POJO is created and loaded at runtime dynamically, how do I get JSON to POJO instance as I do not have fully qualified class (POJO_ClassName) name for above code statement??

Note: I am using jsonSchema2pojo library to generate POJO classes at runtime.

For more information : 
https://stackoverflow.com/questions/45460995/using-jackson-typereferencing-for-runtime-generated-pojo-classes
I am trying to use custom classloader and following below example 
https://analyzejava.wordpress.com/2014/09/25/java-classloader-write-your-own-classloader/
http://www.journaldev.com/349/java-classloader#comment-38886

But most of the examples use Reflection to invoke methods but I need POJO instance for input JSON (as above) but as classes would be loaded dynamically typeReference would not be possible as before running my code fully qualified class name would not be available. I am stuck as I do not have JSON to POJO instance :-(

**Comment by tarunz001** [comment]
Is there some way, I could get Object in return from codeModel as jsonSchema2Json is being used at run time to produce dynamic POJO classes which are loaded into class loader and If I could get deserialized instance from jsonSchema2Pojo library , i wont need to replace POJO instance. 

This is what i am doing further:
static class TestClassLoader extends ClassLoader {
            @Override
            public Class<?> loadClass(String name) throws ClassNotFoundException {
                if (name.equals("com.EnrichmentService.Thread72.EsRootDoc")) {
                    try {
                        InputStream is = Indexer.class.getClassLoader().getResourceAsStream("com/EnrichmentService/Thread72/EsRootDoc.class");
                        byte[] buf = new byte[is.available()];
                        int len = is.read(buf);

                        Class<?> c=defineClass(name, buf, 0, len);
                        resolveClass(c);
                        return c;


                    } catch (IOException e) {
                        throw new ClassNotFoundException("", e);
                    }
                }
                return getParent().loadClass(name);
            }
        }

I have tried using above TestClassLoader custom class loader as an alternative way is like this :
Class cls = new      TestClassLoader().loadClass("com.EnrichmentService.Thread72.EsRootDoc");
    Object obj = cls.newInstance();
    cls.getMethod("getCrawlerSource").invoke(obj);
    p=mapper.readValue(json, cls);  // but here i am getting the same deserialization exception as earlier

**Comment by joelittlejohn** [comment]
This doesn't look like an issue that I can provide help with, and the StackOverflow link is now a 404. I'm closing this one as it looks like a question for Jackson project.

**Comment by dsinghvi** [comment]
any resolution here?
