### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by elabi3** [joelittlejohn/jsonschema2pojo#769]
Hi,

I love this tool and i use it every time i need to deal with json, it was awesome the integration with moshi. Since Google officially support kotlin in Android apps i started using this language in projects.

I find that it would be really interesting the possibility that this tool also generate kotlin code.... I don't know what is the process of generating code but https://github.com/square/kotlinpoet seems interesting to acomplish this task.

I see that people talk about this in stackoverflow: https://stackoverflow.com/questions/44180346/create-pojo-class-for-kotlin but it would be awsesome that the website generate final kotlin code. 

Is exist any possibility that the best tool that i ever find to generate java objects include this support? 

Thank you.

**Comment by joelittlejohn** [comment]
Hi @elabi3. I'm going to close this as we already have #593.

Do you know of any tool out there that can attempt to convert Java to Kotlin, that works **outside** Intellij?
