### ISSUE TITLE
Handling of List<Map<String, String>>

### ISSUE THREAD

**Issue by guruprasadkk** [joelittlejohn/jsonschema2pojo#773]
I have to create one java class where one of the variable is of type List<Map<String, String>>. I am not getting how to represent this is in json schema. Can you please help me with this. I have searched a lot over the internet could not get any working example.

Thanking you,
Guruprasad

**Comment by joelittlejohn** [comment]
Of course there is no way to represent this specific Java type in JSON Schema. If you really need to represent the list items as a map and not a generated type, you can `javaType` (which is not part of JSON Schema but is an extension provided by this tool).

Try:

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "javaType": "java.util.Map<String, String>"
  }
}
```
