### ISSUE TITLE
Gradle plugin - different configuration for different builds

### ISSUE THREAD

**Issue by faerytea** [joelittlejohn/jsonschema2pojo#774]
I want to have .toString() method in debug, but if `includeToString = true` I also should add apache library to dependencies. It is only one place where this library is needed, and these methods are redundant in release version.

Also there are two tasks — geterateJsonSchema2Pojo**ForDebug** and geterateJsonSchema2Pojo**ForRelease**.

I can add this dependency for debug build only, so I need to remove .toString() methods from release build. I don't see correct way to achieve this.

**Comment by ben-manes** [comment]
Why not use a property to set the value? For example,
 - if you have a release phase then you might use 'gradle.taskGraph.hasTask(tasks.xyz)`
 - if you use an environmental property, e.g. `System.env.'xyz'`
 - if you have a project property, e.g. directly `xyz` or `rootProject.hasProperty('xyz')` if you need to escape

You might also be able to extend the task using `type: GenerateJsonSchemaJavaTask` though it may need to be made public (earlier Gradle versions made it public by default, but now has to be explicit).
