### ISSUE TITLE
Weirdly - name of variable got changed.

### ISSUE THREAD

**Issue by sripathitk** [joelittlejohn/jsonschema2pojo#777]
I have attached Json schema and generated POJO . 
1) The json schema has "LineItemTaxes" Object. but when pojo beans are generated it gave it a name as "LineItemTaxis" . in case of duplicate , it should have been either _ . but changing the name is confusing. 

2) "connecTechInstallationOptions" is overriden with "connecTechInstallationOption". only the pojo bean got changed while definition remained same. 

Please check the pojo beans of these files against the schema definition.
[fedAPI5.7Jar - Unmodified.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/1286191/fedAPI5.7Jar.-.Unmodified.zip)

**Comment by joelittlejohn** [comment]
This is a feature of this library. If you have an array named, e.g. 'books', then the items in the array will be named 'book'. If you have an array named 'options' then an item in this array will be named 'option' (each one of the 'options' is an 'option').

**Comment by sripathitk** [comment]
Hi, 
LineItemTaxes - is an array  defined as "lineItemTaxes": { "type": "array",.......}. 

It is translated to 
private List<LineItemTaxis> lineItemTaxes = new ArrayList<LineItemTaxis>();

Each item notation would be better be called "LineItemTax"- instead of "LineItemTaxis".  
so , question is can we control this feature ? Can we have any option to enforce using annotation to Json schema / or any arguments during conversion so that it does not sound too bad.

**Comment by joelittlejohn** [comment]
Okay, I think this is covered by #783.
