### ISSUE TITLE
error on attempting to generate POJO

### ISSUE THREAD

**Issue by Styris** [joelittlejohn/jsonschema2pojo#779]
Hello I went to the website http://www.jsonschema2pojo.org/ on my Mac and whenever I choose my parameters and click on Preview or Gnerate Zip, I always get an error. I have no clue why. Please help (screenshot attached)
<img width="951" alt="screen shot 2017-09-12 at 11 49 23 am" src="https://user-images.githubusercontent.com/31900819/30342991-9ef7520e-97b0-11e7-93cc-5cfcef94873f.png">

**Comment by joelittlejohn** [comment]
Strange, can you hard refresh the page? (Ctrl-F5 or Shift-F5)

Is there an error message shown in the red box?  This works fine for me. Are you inside a network that could be blocking this? Do you have some other issue with your internet connection?

**Comment by joelittlejohn** [comment]
I see one error in the logs at 17:42 UTC, but it doesn't look like it's related to your schema.

**Comment by Styris** [comment]
No there is no error message in the red box. The weird part is that when I try out the same thing from my iPhone 6 it works just fine.
Wonder what the problem is.

**Comment by Styris** [comment]
@joelittlejohn also the funny part is that I only see that error when I use my work MacBook Pro.
I am successfully able to get the JSON when I use my personal MacBook Pro.

Any idea?

**Comment by joelittlejohn** [comment]
Only thing I can recommend is clearing your browser cache (hard refresh). Have you tried other browsers on the same machine? (try Chrome, Safari, Firefox).

If all browsers fail, I think there is something installed on your laptop that is messing with the site. You can try the browser's developer tools to understand more. See the network tab. You may see a network request being blocked by a plugin there.

I can't help much more than that I'm afraid. When people have had issues in the past from one browser but not another they have found that there is a corporate proxy blocking some of their requests. Could this be the case?
