### ISSUE TITLE
jsonschema2pojo website returns HTTP 500 for using TreeNode example in the wiki

### ISSUE THREAD

**Issue by jeremyhill-up** [joelittlejohn/jsonschema2pojo#781]
In https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#ref

There is:
```
Example treeNode.json using a self reference to build a tree:
{
  "description": "Tree node",
  "type": "object",
  "properties": {
    "children": {
      "type": "array",
      "items": {
        "$ref": "#"
      }
    }
  }
}
```

Attempting to generate the provided example returns HTTP ERROR: 500   java.lang.StackOverflowError.

**Comment by joelittlejohn** [comment]
Thanks for reporting this. We do some funny things to ensure we can support refs in the web interface. I suspect this would work from Maven/Gradle etc.

I'll take a look though. Something has regressed it seems.

**Comment by teresalazar13** [comment]
@joelittlejohn Hello. Have you fixed this issue? I'm having the same problem. Is there any way to work around this?
