### ISSUE TITLE
includeAdditionalProperties is not in the documentation.

### ISSUE THREAD

**Issue by salemdar** [joelittlejohn/jsonschema2pojo#782]
I had to dig through [this PR](https://github.com/joelittlejohn/jsonschema2pojo/commit/e697dd84183568e37bb6e9298ea7cdaa55a7f70b) to find `includeAdditionalProperties` property. 

I think it should be included in the documentation in the main README file.

**Comment by joelittlejohn** [comment]
Are you using Gradle?

**Comment by salemdar** [comment]
Yes I am.

**Comment by joelittlejohn** [comment]
Feel free to submit pull requests for any property you see missing from that README.md.
