### ISSUE TITLE
Array elements behavior controlling.

### ISSUE THREAD

**Issue by sripathitk** [joelittlejohn/jsonschema2pojo#783]
Hi,
I have attached Json schema and generated POJO .
[fedAPI5.7Jar.-.Unmodified.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/1307459/fedAPI5.7Jar.-.Unmodified.zip)

The json schema has "LineItemTaxes" Object. but when pojo beans are generated it gave it a name as "LineItemTaxis" . in case of duplicate , it should have been either _ . but changing the name is confusing.

LineItemTaxes - is an array defined as "lineItemTaxes": { "type": "array",.......}.

It is translated to
private List lineItemTaxes = new ArrayList();[fedAPI5.7Jar.-.Unmodified.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/1307458/fedAPI5.7Jar.-.Unmodified.zip)
)

Each item notation would be better be called "LineItemTax"- instead of "LineItemTaxis".
so , question is can we control this feature ? Can we have any option to enforce using annotation to Json schema / or any arguments during conversion so that it does not sound too bad.

**Comment by joelittlejohn** [comment]
Yeah, let's fix this in the inflector.
