### ISSUE TITLE
Same object is being created two time 

### ISSUE THREAD

**Issue by sukhvinder1** [joelittlejohn/jsonschema2pojo#784]
Hi, I am using maven plugin to generate java class from json. 

The northeast under bound is same object as northeast under viewport, but the plugin is generating two different objects. 

1. Northeast
2. Northeast_

is there something that can be done to avoid duplication of same object ?

```json
"geometry": {
        "bounds": {
          "northeast": {
            "lat": 37.42198310000001,
            "lng": -122.0853195
          },
          "southwest": {
            "lat": 37.4214139,
            "lng": -122.0860042
          }
        },
        "location": {
          "lat": 37.4216548,
          "lng": -122.0856374
        },
        "location_type": "ROOFTOP",
        "viewport": {
          "northeast": {
            "lat": 37.4230474802915,
            "lng": -122.0843128697085
          },
          "southwest": {
            "lat": 37.4203495197085,
            "lng": -122.0870108302915
          }
        }
      },
```

**Comment by joelittlejohn** [comment]
Hi. If you want to avoid this you'll have to write a schema and use a $ref to indicate that these properties share the same schema. If you do this, I'd recommend also using javaType to declare a permanent Jav name for 'Northeast'.

**Comment by zygimantus** [comment]
@joelittlejohn can you provide an example or a link which shows how to declare a reference to share same scheme or object?

**Comment by joelittlejohn** [comment]
@zygimantus try https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#ref

The value of `"$ref"` can be a location in the same file (e.g. `"#/definitions/thing"`) or a URL, or a path to another file, or a resource on the classpath, etc.

**Comment by zygimantus** [comment]
Thank you, this is very handy.
