### ISSUE TITLE
JAXB XSD annotations?

### ISSUE THREAD

**Issue by chrismelikian** [joelittlejohn/jsonschema2pojo#786]
Hi, thanks for creating jsonschema2pojo! It's very useful!

Would it be possible to include JAXB annotations to the generated POJO classes so that an XSD can be generated from them? We need to be able to convert from XML to JSON using the JSON schema from an external provider and our service needs to provide a contract (XSD) to another service that gives us XML to send to the REST API. 

So:-

JSON REST API <--JSON--->  Us <--XML--> Internal service

**Comment by joelittlejohn** [comment]
You could write your own annotator to do this. The annotator could add the jaxb annotations you need. Pass this to the plugin as customAnnotator.

If you can live without the XSD (or create it some other way) then you might find Jackson's XML support useful:

https://github.com/FasterXML/jackson-dataformat-xml/blob/master/README.md

It can take a Jackson annotated class and serialize/deserialize to/from XML.
