### ISSUE TITLE
Fix sourceType docs to include YAML/YAMLSCHEMA in Maven, Gradle and Ant

### ISSUE THREAD

**Issue by flemming-n-larsen** [joelittlejohn/jsonschema2pojo#787]
I have tried out using YAML schema (issue #778) with the newest version of jsonschema2pojo, and it seems to work perfect. Thanks! :-)
However, the tools for generating Java code is not supporting YAML Schema in version 0.5.0 and 0.5.1. It would be cool, if the Maven, Gradle, and Ant tool support YAML schema as well.
Personally, I use the Maven plugin to generate POJOs from .json files, but should love you use .yaml / .yml files instead.

**Comment by joelittlejohn** [comment]
Hi. 

Sorry, could you explain how this is not supported? Are you having trouble using sourceType `yaml` or `yamlschema`?

**Comment by joelittlejohn** [comment]
Closing this as I think there's nothing to do. Feel free to re-open if you think I've missed something.

**Comment by flemming-n-larsen** [comment]
Thanks. The sourceType works as a charm. I have now converted all my JSON types into YAML types and use the Maven plugin to generate the POJOs for GSON. 👍 

However, I am missing your description for `yamlschema` and `yaml` on the description for the Maven plugin here:
https://joelittlejohn.github.io/jsonschema2pojo/site/0.5.1/generate-mojo.html

**Comment by joelittlejohn** [comment]
Yeah, I must have missed updating the docs here. Thanks!
