### ISSUE TITLE
Fix incorrect logic between -da, -ds and -dg in CLI

### ISSUE THREAD

**Issue by nqzero** [joelittlejohn/jsonschema2pojo#790]
it seems that unless -da is given, the -ds and -dg flags are ignored

it would seem more natural if, and the help page seems to suggest this, -da implied both -ds and -dg, and if either of the -ds or -dg flags was given without a -da, that they would take effect

the current behavior also breaks backwards compatibility, ie scripts that used to generate public fields without getters or setters now generate private fields with getters and setters

workaround: use -da -dg -ds

**Comment by joelittlejohn** [comment]
Yes agreed, -dg should imply -da, and -ds should imply -da too. Will fix this ASAP.

**Comment by nqzero** [comment]
i just tried out the alpha2 release and it appears that by itself `-da` does nothing. `-dg -ds` does disable both and make the fields public. seems like `-da` should either be an alias for `-dg -ds` (for backwards compatibility) or should just be deleted
