### ISSUE TITLE
Is there an example for going from JSON (not schema) to Java class using the Java API?

### ISSUE THREAD

**Issue by allisonking** [joelittlejohn/jsonschema2pojo#791]
I'd like to have the same functionality the website has of converting a JSON (not schema) into a POJO but it seems like the documentation only has an example for converting a JSON schema. Any help would be appreciated!

**Comment by afxgroup** [comment]
`import java.io.File;
import java.io.IOException;
import java.net.URL;

import org.jsonschema2pojo.SchemaGenerator;
import org.jsonschema2pojo.SchemaMapper;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.sun.codemodel.JCodeModel;

public class JsonToJava {

	public static void main(String[] args) throws IOException {
		JCodeModel codeModel = new JCodeModel();

		URL source = new URL("file:///C:/file.json");

		
		SchemaGenerator sg = new SchemaGenerator();

		ObjectNode jsonschema = sg.schemaFromExample(source);
		SchemaMapper mapper = new SchemaMapper();
		
		mapper.generate(codeModel, "ClassName", "com.package", jsonschema.toString());

		codeModel.build(new File("outputDir"));
	}

}
`

**Comment by joelittlejohn** [comment]
Thanks @afxgroup. @allisonking I hope this helps.
