### ISSUE TITLE
Unable to generate @JsonIgnoreProperties(ignoreUnknown = true) in POJO from json

### ISSUE THREAD

**Issue by bobchinski** [joelittlejohn/jsonschema2pojo#795]
We're using jsonchema2pojo maven plugin to generate POJOs at the build (compile) time from json-schema based files. Code has to be immune against new fields (aka properties) introduced at "the other end" by the third parties. Common solution is to use JsonIgnoreProperties annotation at the class level of POJOs. Is it possible to introduce corresponding field to json schema to be able to generate that annotation at the compile time? I tried to use  "additionalProperties": false, did not help. Thanks beforehand!

**Comment by joelittlejohn** [comment]
Hi. 

You can either

* Set this as a deserialization feature on your Jackson ObjectMapper (see [`FAIL_ON_UNKNOWN_PROPERTIES` in the jackson-databind wiki](https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features#failure-handling))

or

* Omit the `additionalProperties` rule from your schema. By default `additionalProperties` are allowed, and hence a map is created on your class to hold them. Values of unrecognized properties will be added there, and will not cause the deserialization to fail.
