### ISSUE TITLE
No 'buy me a coffee'-option

### ISSUE THREAD

**Issue by vulkman** [joelittlejohn/jsonschema2pojo#796]
I'd really love to buy you guys a coffee but right now I can't :-(

Maybe add one of those widgets to your Wiki, like https://ko-fi.com or something?

**Comment by joelittlejohn** [comment]
Thanks vulkman! The sentiment is always appreciated. The only thing I collect donations for is the domain renewal on jsonschema2pojo.org. There's a donate button there if you have PayPal.

**Comment by vulkman** [comment]
Perfect, completely overlooked that! Done :)
