### ISSUE TITLE
jsonschema2pojo:generate nothing generated

### ISSUE THREAD

**Issue by sekaijin** [joelittlejohn/jsonschema2pojo#798]
Hi I'm trying to generate sources
I've copied the project: https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-maven-plugin/src/test/resources/example
I've deleted the json files

and I've placed in same directory the files: https://www.hl7.org/fhir/fhir.schema.json.zip
these are the schemas of the FHIR norm
I've compiled but no files are generated

I've tried to add includes, sourcespaths etc.
But nothing is generated.
No errors but nothing is generated.

Thank.
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fr.aphp.fhir</groupId>
  <artifactId>json-fhir</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>json-fhir</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>  <build>
  	<plugins>
	  <plugin>
        <groupId>org.jsonschema2pojo</groupId>
        <artifactId>jsonschema2pojo-maven-plugin</artifactId>
        <version>0.5.1</version>
         <configuration>
            <sourceDirectory>${basedir}/schema</sourceDirectory>
            <targetPackage>com.example.types</targetPackage>
            <includes>
              <include>**/*.json</include>
            </includes>
            <includeHashcodeAndEquals>false</includeHashcodeAndEquals>
            <includeToString>false</includeToString>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
  	</plugins>
  </build>
</project>`

**Comment by joelittlejohn** [comment]
Hi. I see a lot of these schemas use `allOf`. From a quick browse, it looks like every schema is defined using allOf. This library does not support allOf.

**Comment by sekaijin** [comment]
Thank.
Do you know a way to explore to get to the result, another lib?
Making a Maven plugin is not a problem for me.
