### ISSUE TITLE
Couldn't get code compiled ([ERROR] Failed to execute goal on project jsonschema2pojo-core)...!

### ISSUE THREAD

**Issue by sudhirsksps** [joelittlejohn/jsonschema2pojo#799]
Plz, guide me...how to resolve...!

[INFO] jsonschema2pojo .................................... SUCCESS [  8.084 s]
[INFO] jsonschema2pojo-scalagen ........................... SUCCESS [02:32 min]
[INFO] jsonschema2pojo-core ............................... FAILURE [ 24.472 s]
[INFO] jsonschema2pojo-ant ................................ SKIPPED
[INFO] jsonschema2pojo-cli ................................ SKIPPED
[INFO] jsonschema2pojo-gradle-plugin ...................... SKIPPED
[INFO] jsonschema2pojo-maven-plugin ....................... SKIPPED
[INFO] jsonschema2pojo-integration-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:09 min
[INFO] Finished at: 2017-11-03T11:08:46-04:00
[INFO] Final Memory: 21M/177M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jsonschema2pojo-core: Could not resolve dependencies for project org.jsonschema2pojo:jsonschema2pojo-core:jar:0.5.2-SNAPSHOT: Could not transfer artifact org.jsonschema2pojo:jsonschema2pojo-scalagen:jar:0.5.2-SNAPSHOT from/to maven-central (http://repo1.maven.org/maven2): Connection refused: connect -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jsonschema2pojo-core

**Comment by joelittlejohn** [comment]
What maven command are you running? Have you made any changes to the project?

Here is the output I get when I run `mvn compile` with Maven 3.3.9 and OpenJDK 8:

https://pastebin.com/raw/dWWbDXVX

**Comment by joelittlejohn** [comment]
Looks to be a networking problem:

```
(http://repo1.maven.org/maven2): Connection refused: connect 
```
