### ISSUE TITLE
oneOf was not implemented

### ISSUE THREAD

**Issue by jiaofan** [joelittlejohn/jsonschema2pojo#802]
Have a json schema:
...
"ip-address": {
      "description": "",
      "type": "string"
    },
    "unnumbered-id": {
      "description": "",
      "type": "integer",
      "format": "int64"
    },
    "oneOf": [
      { "required": [ "ip-address" ] }, 
      { "required": [ "unnumbered-id" ] }
    ],
...

But in the Java code, "oneOf" is a generic Java Object, and so is "required"

**Comment by thachhoang** [comment]
This library does not support "oneOf" (#392).
