### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yp25** [joelittlejohn/jsonschema2pojo#806]
This project is awesome. I would like to say many thanks for all people who involved and developed this project. 
by the way is it possible to configure this project to run offline in windows environment ? I am a beginner, would like to ask some help how to do it. Thank you

**Comment by joelittlejohn** [comment]
Hi. Do you mean you want to generate some code in your local project instead of using the website?

You can use this tool via Maven, Gradle, Ant, CLI or as a Java library. Are any of these good for you?

**Comment by yp25** [comment]
Hi @joelittlejohn . Yes I want to use in my local website, my aim is use your project in local environment with no internet connectivity. 
Thanks for pointing about Maven, etc. I will try it
