### ISSUE TITLE
Develop pojo for Room Database Android

### ISSUE THREAD

**Issue by Mohsin92** [joelittlejohn/jsonschema2pojo#807]
There are many users including me who are suffering from huge model classes.
Recently google announce Room Database Library for Android

https://developer.android.com/training/data-storage/room/index.html

Please develop pojo class who support Room Database Annotations.
This is just suggestions hope you understand.

Thank you.

**Comment by joelittlejohn** [comment]
Thanks for raising this idea! It isn't really the goal of this project to support every possible set of persistence annotations to different database technologies, so I don't think this is a feature that belongs in the core of jsonschema2pojo.

However, I think what you've described sounds like a useful addition and one that is certainly possible. You would implement this as a custom annotator:

http://joelittlejohn.github.io/jsonschema2pojo/site/0.5.1/generate-mojo.html#customAnnotator

https://stackoverflow.com/a/48411162/125825

If you do decide to implement a custom annotator for this, it would be really useful if you could share it on GitHub for others to use too.
