### ISSUE TITLE
Referring external JSON Schema Only once instead at the property level. [Question Related to #813]

### ISSUE THREAD

**Issue by lvimalchandran** [joelittlejohn/jsonschema2pojo#815]
Hi, This question is related to #813 
I have a Schema A which refers some of its entity from Schema B. Now instead of referring schema B in Schema A wherever we need reference. Is there any options to refer only once at schema level and use it across wherever it is necessary.

Use case: I don't want to use all the entities available in Schema B but it has to referred globally in schema A at once.

Please let me know if we have any options.

Thanks, Vimal.

**Comment by joelittlejohn** [comment]
Sounds like a JSON Schema question, and not a jsonschema2pojo question. You could bring all of B into A with a $ref, then refer to the schema parts within B with a shorter $refs to the imported location. I'd recommend just referring to B where you need it though, even if this takes more characters (it's a lot simpler).
