### ISSUE TITLE
[feature request] Add comment "This file was generated by" 

### ISSUE THREAD

**Issue by danibs** [joelittlejohn/jsonschema2pojo#818]
Hi,
because I usually commit the classes your plugin generate, to be sure that no one build war with something accidentally changed, I would like to have an option that add at the top of the class a comment like JAXB:

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.03 at 12:09:05 PM CEST 
//

Thanks

**Comment by joelittlejohn** [comment]
I think you could do this using http://code.mycila.com/license-maven-plugin/

**Comment by danibs** [comment]
I mean, in the classes your Maven's plugin generate, it will be nice to add that comment, so people that open the source code of one of these classes can immediately understand that the source code is generated automatically.


Thanks

**Comment by joelittlejohn** [comment]
I've found in the past that people don't like this kind of addition in their source code, in particular when they have an existing project and this kind of change appears. I don't want to have to make a configuration option just for this, so I'm going to leave this out for now. Thanks for the suggestion though, I might revisit this at some point in the future.
