### ISSUE TITLE
Adding class level annotations to generated Java files from jsds

### ISSUE THREAD

**Issue by jeevanbmanoj** [joelittlejohn/jsonschema2pojo#819]
I want to add the following annotation to my generated java file from jsd files.( Want a mechanism to specify that in the jsd file)
 @JsonIgnoreProperties(ignoreUnknown = true)
 I went through the documentation here https://github.com/joelittlejohn/jsonschema2pojo , but couldn't find anything. Looking forward to hearing from you.

**Comment by joelittlejohn** [comment]
The only option here is a custom annotator:

http://joelittlejohn.github.io/jsonschema2pojo/site/0.5.1/generate-mojo.html#customAnnotator

https://stackoverflow.com/a/48411162/125825

**Comment by josesmithesh** [comment]
I have created a custom annotator for adding the class level annotation @JsonIgnoreProperties(ignoreUnknown = true) - https://github.com/josesmithesh/jsonschema2pojo-ignoreunknown-annotator. Even though it is simple, it may not be straight forward for a beginner to implement it.

@joelittlejohn Do you have any concerns if I go ahead and publish it in maven central?

**Comment by joelittlejohn** [comment]
That's great. Go for it!

**Comment by jeevanbalanmanoj** [comment]
Fantastic!
