### ISSUE TITLE
Stitch multiple schema files together

### ISSUE THREAD

**Issue by rao-anant** [joelittlejohn/jsonschema2pojo#825]
Hi,
Is it possible for jsonschema2pojo to spit out a combined JSON schema file from multiple schema files interconnected by "$ref" as it parses thru them to generate the POJOs?
Basically, dereference all "$ref"s.

Thanks!

**Comment by joelittlejohn** [comment]
There's no feature like this. I think it would be a good idea for you to fork this library and customize it to achieve what you need.
