### ISSUE TITLE
Add Lombok option 

### ISSUE THREAD

**Issue by jpomykala** [joelittlejohn/jsonschema2pojo#827]
Hey, I got feature request. Is there any posibility to add option for adding `@Data` lombok annotations to created classes?

`@Data`
https://projectlombok.org/features/Data
or 
`@Getter` and `@Setter`
https://projectlombok.org/features/GetterSetter

**Comment by joelittlejohn** [comment]
Hi. Thanks for raising this. This already exists as request #166. Feel free to add a :+1: there.
