### ISSUE TITLE
Custom maven repository key leads to timeouts within custom repository structure

### ISSUE THREAD

**Issue by DennisRippinger** [joelittlejohn/jsonschema2pojo#832]
When the plugin is executed within a strict nexus/artifactory environment it tries to download dependencies from custom repositories which are not reachable. 
```
[INFO] --- jsonschema2pojo-maven-plugin:0.5.1:generate (default) @ myapp ---
Downloading: http://repo1.maven.org/maven2/io/grpc/grpc-core/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/grpc/grpc-core/maven-metadata.xml
Downloading: http://repo.spring.io/plugins-release/io/grpc/grpc-core/maven-metadata.xml
```
The parent pom defines two (with the oss-parent three) custom repositories. One of them is maven central with the key `maven-central`. I assume the default is explicitly listed regarding some problem with gradle ([original commit](https://github.com/joelittlejohn/jsonschema2pojo/commit/a9d697e0066293c0c34d712fb1fe5559ba84c545)). 

I would suggest changing the key to `central`, which is the default key and usually handled in a nexus/artifactory environment as mirror.

**Comment by joelittlejohn** [comment]
Closed by #833
