### ISSUE TITLE
Add Lombok Support

### ISSUE THREAD

**Issue by wenerme** [joelittlejohn/jsonschema2pojo#839]
From this comment https://github.com/joelittlejohn/jsonschema2pojo/issues/166#issuecomment-44333569

> I think it's just too much work and not useful to enough users.

For 2014, I think this is correct, but 2018 now, the lombok have a huge adoption, jhipster, springboot, mapstruct all support and recommend lombok. When lombok compatible with mapstruct, we reduced ~30k LOC in our project.

Please consider support lombok.

**Comment by joelittlejohn** [comment]
Sounds fair. Let's reopen #166.
