### ISSUE TITLE
Getter Setter wrong names

### ISSUE THREAD

**Issue by radlik01** [joelittlejohn/jsonschema2pojo#840]
In the latest.integration gradle plugin we are facing the issue with the getter/setter names generation.

in case of json like
`
{
  "id": "http://some.site.somewhere/entry-schema#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "schema for risks data",
  "type": "object",
  "javaInterfaces": ["java.io.Serializable", "Cloneable"],
  "required": ["ris_id"],
  "properties": {
    "v_item_hidden": {
      "type": "boolean",
      "default": "false"
    },
    ....
  }
}
`

the generated getter/setter for v_item_hidden is get**v**ItemHidden() instead of get**V**ItemHidden().

**Comment by joelittlejohn** [comment]
Hi. I assume you are using the default propertyWordDelimiters, and so the Java name for this field is `vItemHidden`. Is that right?

The Java Bean convention (that defines how getters and setters should be named) dictates that a getter called `getVItemHidden` relates to a Java field named `VItemHidden`. If you have a field named `vItemHidden` then the correct name for the getter is `getvItemHidden`.

This relates to changes made in #756. It's one of the breaking changes that have forced the latest releases to move from v0.x to v1.x. There's more information about this particular quirk of the Java Bean spec here:

* fasterxml/jackson-databind#653
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=322223

If you have some other tool or library that expects the gett for `vItemHidden` to be `getVItemHidden` then that library or tool has a bug.

**Comment by radlik01** [comment]
Thank you for perfect description. We will change our code to follow new
rules.

Regards

Jan

2018-03-08 16:17 GMT+01:00 Joe Littlejohn <notifications@github.com>:
