### ISSUE TITLE
Generate simple enum when enum names are Java-compatible

### ISSUE THREAD

**Issue by amarkevich** [joelittlejohn/jsonschema2pojo#841]
Currently generated enums have a string value and have custom fromValue method:

`public enum ScheduleType {
    NOW("now")
...
    public static ScheduleType fromValue(String value) {...}
}`

In case enum generation as is like

`public enum ScheduleType {
    now
}`

allow to use ScheduleType.valueOf method which used by default in frameworks

**Comment by joelittlejohn** [comment]
Thanks for raising this. Unfortunately this one is not going to be implemented I'm afraid.

Our goal with this project is to not to optimize the code output for readability, it's to use a strategy that will work for every use-case. The more we add special cases in like this, the harder jsonschema2pojo becomes to maintain. There are also downsides to this approach, in that when you have to add a new enum value the structure of the enum may change drastically and break all code that uses the enum (but adding a new enum value should not, ideally, be a breaking change).

There are thousands of ways we could generate this source code according to the preference of one user or another, but all of these ways requires maintenance. The strategy we use to generate enums allows any enum value to be supported, so it's the one we use, even though the code is larger than necessary.
