### ISSUE TITLE
Generating Wrong Object Name

### ISSUE THREAD

**Issue by mirkara** [joelittlejohn/jsonschema2pojo#843]
The first field generates an object called wearaesf.
The second field generates an object called Date.

How can I get the first field to change it's name from wearaesf to User?

```
{
  "type" : "object",
  "properties" : {

    "wearaesf": {
      "$ref" : "./user.json"
    },
    "RANDOM": {
      "$ref" : "./date.json"
    }
  }
}
```

**Comment by joelittlejohn** [comment]
There's some explanation of what you're seeing in #164.

Can you try using 1.0.0-alpha2? This should provide what you need. It's a major change to the way classes are named so I am running some alpha releases (and throwing in a few more breaking changes) before finalising 1.0.0.
