### ISSUE TITLE
Using plugin twice

### ISSUE THREAD

**Issue by christweekie** [joelittlejohn/jsonschema2pojo#844]
Hi

I've been using the maven plugin to generate POJOs from JSON schema. I am noticing that after a clean, I have to run mvn compile / test (or whatever), twice for the desired class to be generated. 

`mvn clean test
`
The first time, I get a class , let's call it "Person" with no properties / getters and setters but it does have a toString and equals / hashCode if that is how I configured it. There is also a Person__1.java file which looks like it's the thing I need. I've got compilation errors because my code is looking at "Person". So I run this now...

`mvn test`

"Person" now has the fields and is complete. compilation errors are gone. 

This happens with 0.4.7 and 1.0.0-alpha2.

I don't want to have to run these targets twice every time I clean. Is this normal or has it been observed before ?

Thanks

Chris

**Comment by joelittlejohn** [comment]
Could you give me an example schema and configuration that demonstrates the problem? I'm confused by your description, I don't understand how any bug could cause the behaviour that you describe.

**Comment by joelittlejohn** [comment]
Closing as we need more information. I haven't seen a bug of this nature before so I'm going to assume there was something wrong in your diagnosis. If you can provide more information I will investigate.
