### ISSUE TITLE
FR Add support for additional XML annotations

### ISSUE THREAD

**Issue by robertsearle** [joelittlejohn/jsonschema2pojo#846]
I would like the option to create objects that support both XML and json.  I assume you would want to use  javax.xml.bind.annotation.XmlValue for object references and javax.xml.bind.annotation.XmlAttribute for simple string / int.  At the top of the class, I assume 
@XmlRootElement(name = "objectName")
@XmlType(propOrder = {..})

 But anyway it is done is terrific.

**Comment by joelittlejohn** [comment]
Hi, have a look at https://github.com/joelittlejohn/jsonschema2pojo/issues/786#issuecomment-331079830

Thanks

**Comment by robertsearle** [comment]
Hi Joe,

I have written an annotator for it.  I can publish it, even though it's not finished.  Would you be willing to review it and give general approval and feedback to my idea.  It's a small change but if you say no there is no point continuing work on it.

Sent from my iPad

On Apr 1, 2018, at 8:19 AM, Joe Littlejohn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, have a look at #786 (comment)<https://github.com/joelittlejohn/jsonschema2pojo/issues/786#issuecomment-331079830>

Thanks

**Comment by joelittlejohn** [comment]
Sure. I suggest you just create a new repo for it on GitHub with a readme etc. I haven't used JAXB in about 7 years so I don't know if I will be able to offer much advice. If you are seeing the output you want then that's probably enough.

**Comment by robertsearle** [comment]
Can you look at this patch.  Its untested but gives a good idea of what I am trying.  Basically it will use your composite to add a XML annotations to the json being created.
