### ISSUE TITLE
Specify multiple Annotator implementations

### ISSUE THREAD

**Issue by skoskav** [joelittlejohn/jsonschema2pojo#853]
Using e.g. Maven, I would like to specify two (or more) annotators to use. I naively assumed comma-separated Annotators would be accepted, such as:

```
<plugins>
    <plugin>
        <groupId>org.jsonschema2pojo</groupId>
        <artifactId>jsonschema2pojo-maven-plugin</artifactId>
        ...
        <configuration>
            ...
            <customAnnotator>org.skoskav.jsonschema.annotator.DeprecatedAnnotator,org.skoskav.jsonschema.annotator.NoLogAnnotator</customAnnotator>
```

Unfortunately it tries to find a single class with that name. I did find `org.jsonschema2pojo.CompositeAnnotator` which can combine multiple annotators, but it lacks a default constructor, making it clear that it's only intended for internal use.

Our current workaround is to create a combiner class for each possible combination of Annotator implementations (e.g. `DeprecatedAndNoLogAnnotator`), which becomes unmanageable at three different Annotators.

So unless I'm missing something, could I suggest supporting multiple Annotators?

**Comment by joelittlejohn** [comment]
Hi. This is what the CompositeAnnotator is for. You should use this constructor:

```java
    public CompositeAnnotator(Annotator... annotators) {
        this.annotators = annotators;
    }
```

**Comment by skoskav** [comment]
Alright, I went with:
```
public class DeprecationAndNoLogAnnotator
    extends CompositeAnnotator {

    public DeprecationAndNoLogAnnotator() {
        super(new DeprecationAnnotator(), new NoLogAnnotator());
    }
}
```

It does reduce the boiler-plate. I still would have preferred an array of Annotators in Maven's pom.xml, but I guess this is better than nothing.

Thanks!

**Comment by aksh1618** [comment]
+1 for supporting multiple annotators from maven without having to define boilerplate `CompositeAnnotator` subclass

**Comment by reda-alaoui** [comment]
> Hi. This is what the CompositeAnnotator is for. You should use this constructor:
> 
>     public CompositeAnnotator(Annotator... annotators) {
>         this.annotators = annotators;
>     }

Hi,

IMHO, this prevents the development of an Annotator ecosystem. If a user wants to combine 2 annotators from 2 independent providers, the former has to create a Java module to statically unite them with `CompositeAnnotator`.

It would be much simpler to allow users to provided multiple annotators to the maven plugin configuration.
