### ISSUE TITLE
Integer range is not checking in POJO class creation

### ISSUE THREAD

**Issue by suryaphani1729** [joelittlejohn/jsonschema2pojo#854]
Hi, I am trying to generate POJO from the tool it is not calculating Range of Integer. 
In my json  mobile number ("mobile": 2525252580) is given like this. But it crosses the Integer range(-2,147,483,648 .. 2,147,483,647) in java so please rectify  to long in this scenario.

Thanks

**Comment by joelittlejohn** [comment]
Hi. If you want to use Long instead of Integer, use the useLongIntegers configuration option.
