### ISSUE TITLE
Not able to preview and genrate zip from last 2 or three days

### ISSUE THREAD

**Issue by developerhuman12** [joelittlejohn/jsonschema2pojo#856]
Using the website from Chrome Version 66.0.3359.117 (Official Build) (64-bit) Ubuntu
Not able to preview the pojo class.
![screenshot from 2018-04-27 16-13-41](https://user-images.githubusercontent.com/15534661/39359065-07a781c4-4a36-11e8-9a4d-340288d1cf9c.png)

**Comment by joelittlejohn** [comment]
Maybe you have the wrong Source Type selected?

The site works fine for me (Chrome 66.0.3359.117 (Official Build) (64-bit), Ubuntu) so I'm going to assume this is something wrong with the options you have selected.

**Comment by developerhuman12** [comment]
@joelittlejohn  yes you are correct.
