### ISSUE TITLE
Can't override generation config for specific schema

### ISSUE THREAD

**Issue by epam-iantonenko** [joelittlejohn/jsonschema2pojo#858]
Hi, this is really nice tool. I am using gradle plugin to generate pojos from set of json schemes. But I was wondered that I have not found a way to override configuration for specific schema. For example I want to enable JSR-303 only for one schema and left all other schemes not affected. 

So is there a way to override configuration properties for some specific schema?
Thanks in advance for help.

**Comment by joelittlejohn** [comment]
No, there's no config per schema. The only option is to invoke the plugin multiple times, with a different configuration for each invocation.
