### ISSUE TITLE
Support for custom Annotator classes

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#86]
_Original author: marst...@gmail.com (January 28, 2013 19:05:34)_

Hi,
It seems current logic only handles &quot;properties&quot; array to generate POJOs. Is there any programmatic way to extend this logic to additionally support link-relationships representation in POJOs?

---

Specifically, jersey-server-linking defines @Ref/@Binding annotations that allows to specify resource and template parameter binding. 

Sample that comes with the library is a representation bean (POJO) as follows:

public class ItemRepresentation {

```
@XmlElement
private String name;

@Ref(
    resource=ItemResource.class,
    style = Style.ABSOLUTE,
    bindings=@Binding(name=&quot;id&quot;, value=&quot;${resource.id}&quot;)
)
@XmlElement
URI self;

@Ref(
    resource=ItemResource.class,
    style = Style.ABSOLUTE,
    condition=&quot;${resource.next}&quot;,
    bindings=@Binding(name=&quot;id&quot;, value=&quot;${resource.nextId}&quot;)
)
@XmlElement
URI next;

@Ref(
    resource=ItemResource.class,
    style = Style.ABSOLUTE,
    condition=&quot;${resource.prev}&quot;,
    bindings=@Binding(name=&quot;id&quot;, value=&quot;${resource.prevId}&quot;)
)
@XmlElement
URI prev;

public ItemRepresentation() {
    this.name = &quot;&quot;;
}

public ItemRepresentation(String name) {
    this.name = name;
}
```

}

Right now, the following schema:
{
  &quot;type&quot;:&quot;object&quot;,
  &quot;properties&quot;: {
    &quot;foo&quot;: {
      &quot;type&quot;: &quot;string&quot;
    },
    &quot;bar&quot;: {
       &quot;type&quot;: &quot;integer&quot;
     },
    &quot;baz&quot;: {
      &quot;type&quot;: &quot;boolean&quot;
    }
  },
  &quot;links&quot;: [
    {
        &quot;rel&quot;: &quot;self&quot;,
        &quot;href&quot;: &quot;clients/{id}&quot;
    }]
}

... generates same POJO as following schema (without links):
{
  &quot;type&quot;:&quot;object&quot;,
  &quot;properties&quot;: {
    &quot;foo&quot;: {
      &quot;type&quot;: &quot;string&quot;
    },
    &quot;bar&quot;: {
       &quot;type&quot;: &quot;integer&quot;
     },
    &quot;baz&quot;: {
      &quot;type&quot;: &quot;boolean&quot;
    }
  }
}

And since POJO generation is dynamic, I would like to be able to either decorate the generated POJOS dynamically, or to influence the code generating the classes in the first place, to add additional annotations in the generated code.

Beside the obvious decoupling from Jersey, do you see why links are not generated (at all) in the POJOs? Should I specifically add a bag of properties to have the defined links listed?

Thanks for your help.

_Original issue: http://code.google.com/p/jsonschema2pojo/issues/detail?id=86_

**Comment by mgudivada** [comment]
Guys, Can you please let me know how do I generate POJO for my json with annotation "@JacksonXmlProperty(isAttribute=true)"?
