### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by brisanocturna** [joelittlejohn/jsonschema2pojo#861]
when i try to convert this JSON throws internal server error

[
    {
        "id": "1",
        "name": "Enano",
        "description": "descripcion",
        "abilityScores": [
            {
                "constitucion": "2"
            }
        ],
        "speed": "25",
        "size": "medium",
        "traits": [
            {
                "trait": "1"
            },
            {
                "trait": "2"
            },
            {
                "trait": "3"
            },
            {
                "trait": "4"
            },
            {
                "trait": "6"
            }
        ]
    },
    {
        "id": "2",
        "name": "Enano de la colina",
        "description": "descripcion",
        "abilityScores": [
            {
                "constitucion": "2"
            },
            {
                "sabiduria": "1"
            }
        ],
        "speed": "25",
        "size": "medium",
        "traits": [
            {
                "trait": "1"
            },
            {
                "trait": "2"
            },
            {
                "trait": "3"
            },
            {
                "trait": "4"
            },
            {
                "trait": "5"
            },
            {
                "trait": "6"
            }
        ]
    },
    {
        "id": "3",
        "name": "Elfo",
        "description": "descripcion",
        "abilityScores": [
            {
                "destreza": "2"
            }
        ],
        "speed": "30",
        "size": "medium",
        "traits": [
            {
                "trait": "6"
            },
            {
                "trait": "7"
            },
            {
                "trait": "8"
            },
            {
                "trait": "9"
            }
        ]
    },
    {
        "id": "4",
        "name": "Alto Elfo",
        "description": "descripcion",
        "abilityScores": [
            {
                "destreza": "2"
            },
            {
                "inteligencia": "1"
            }
        ],
        "speed": "30",
        "size": "medium",
        "traits": [
            {
                "trait": "6"
            },
            {
                "trait": "7"
            },
            {
                "trait": "8"
            },
            {
                "trait": "9"
            },
            {
                "trait": "10"
            }
        ]
    },
    {
        "id": "5",
        "name": "Mediano",
        "description": "descripcion",
        "abilityScores": [
            {
                "destreza": "2"
            }
        ],
        "speed": "25",
        "size": "small",
        "traits": [
            {
                "trait": "11"
            },
            {
                "trait": "12"
            },
            {
                "trait": "13"
            }
        ]
    },
    {
        "id": "6",
        "name": "Pies Ligeros",
        "description": "descripcion",
        "abilityScores": [
            {
                "destreza": "2"
            },
            {
                "carisma": "1"
            }
        ],
        "speed": "25",
        "size": "small",
        "traits": [
            {
                "trait": "11"
            },
            {
                "trait": "12"
            },
            {
                "trait": "13"
            },
            {
                "trait": "14"
            }
        ]
    },
    {
        "id": "7",
        "name": "Humano",
        "description": "descripcion",
        "abilityScores": [
            {
                "fuerza": "1"
            },
            {
                "destreza": "1"
            },
            {
                "constitucion": "1"
            },
            {
                "inteligencia": "1"
            },
            {
                "sabiduria": "1"
            },
            {
                "carisma": "1"
            }
        ],
        "speed": "30",
        "size": "medium",
        "traits": [
            {
                "": null
            }
        ]
    }
]

**Comment by joelittlejohn** [comment]
This tool can't currently handle empty property names, like you have here:

```json
"traits": [
{
"": null
}
]
```
Try removing this.
