### ISSUE TITLE
json to jsonschema

### ISSUE THREAD

**Issue by jorgeviana** [joelittlejohn/jsonschema2pojo#862]
would it make sense to have a json to jsonschema conversion?

from:
```
{
  "name": "Toto"
}
```
to:
```
{
  "type": "object", 
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
```

**Comment by joelittlejohn** [comment]
This is actually what we do to support JSON as a source. We use Jackson to convert the JSON into JSON Schema, and then proceed as normal with the generated JSON Schema.

You could easily make a different maven plugin to acheive this. I feel like it's outside of the scope of this project.

**Comment by jorgeviana** [comment]
I see what you mean. I ended up using Jackson to build a small class to achieve this, it was not much trouble after all. Thanks.
