### ISSUE TITLE
java 8 Optional<T> supports for optional fields

### ISSUE THREAD

**Issue by prayagupd** [joelittlejohn/jsonschema2pojo#865]
Can json-schema-2-pojo support java8 `Optional`? [I did not see that happening](https://github.com/duwamish-os/json-schema-2-java) but it would be great if we can have that.

JSON Schema
---------------

I have two fields required but one `Optional` which should be presented as `Optional<T>` for java8+.

```javascript
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "artistName": {
      "type": "string"
    },
    "started": {
      "type": "string"
    }
  },
  "required": ["id", "artistName"]
}
```

expected java object
----------------------

```java

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "id",
    "artistName",
    "started"
})
public class Music {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("id")
    private Integer id;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("artistName")
    private String artistName;

    @JsonProperty("started")
    private Optional<String> started;

...

}
```

instead of `(Required)` comments

```java

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "id",
    "artistName",
    "started"
})
public class Music {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("id")
    private Integer id;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("artistName")
    private String artistName;

    @JsonProperty("started")
    private String started;

...

}
```

**Comment by joelittlejohn** [comment]
This feature is present already, it was released in 1.0.0-alpha1.

**Comment by hockeybpr25** [comment]
Instead of saying it's present, it would be great if you actually provided how to do it so when someone stumbles on this thread they don't have to go looking for it.  Also, it looks like this is now deprecated? https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference

Still is a desirable feature.

**Comment by joelittlejohn** [comment]
@hockeybpr25 The `optional` on that page refers to the deprecated JSON Schema rule `optional`. In draft04, `optional` was removed from JSON Schema and replaced with `required`.

Until the docs are updated, this link will help:

https://github.com/joelittlejohn/jsonschema2pojo/pull/344
