### ISSUE TITLE
Improper code generation when a property is resolved to be Map<String, ANonYetExistingObject>

### ISSUE THREAD

**Issue by metacosm** [joelittlejohn/jsonschema2pojo#866]
I have the following field in my JSON Schema:
```json
"metrics": {
          "type": "object",
          "description": "",
          "additionalProperties": {
            "$ref": "#/definitions/istio_adapter_dogstatsd_Params_MetricInfo",
            "javaType": "me.snowdrop.istio.adapter.dogstatsd.MetricInfo"
          },
          "javaType": "java.util.Map\u003cString,me.snowdrop.istio.adapter.dogstatsd.MetricInfo\u003e"
        },
```
This properly creates a `Map<String,MetricInfo>` with a proper import, however, the `ref` is never resolved and therefore the `MetricInfo` class is never created, even though the schema properly contains a `istio_adapter_dogstatsd_Params_MetricInfo` definition.
The issue seems to be in `ObjectRule.createClass` in particular this [part](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java#L280-L283) which resolves the type as `Map` and throws `ClassAlreadyExistsException`.

**Comment by piyush1594** [comment]
I am also facing the same issue. My JSON Schema looks like:
```
"dependencies": {
          "type": "object",
          "description": "",
          "additionalProperties": {
            "$ref": "#/definitions/kubernetes_apiextensions_JSONSchemaPropsOrStringArray",
            "javaType": "io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaPropsOrStringArray"
          },
          "javaType": "java.util.Map\u003cString,io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaPropsOrStringArray\u003e"
        },
```
and the defination is 
```
"kubernetes_apiextensions_JSONSchemaPropsOrStringArray": {
      "type": "object",
      "description": "",
      "properties": {
        "Property": {
          "type": "array",
          "description": "",
          "items": {
            "type": "string",
            "description": ""
          }
        },
        "Schema": {
          "$ref": "#/definitions/kubernetes_apiextensions_JSONSchemaProps",
          "javaType": "io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps"
        }
      },
      "additionalProperties": true,
      "javaType": "io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaPropsOrStringArray",
      "javaInterfaces": [
        "io.fabric8.kubernetes.api.model.KubernetesResource"
      ]
    },
```

This does not create the respective class.

**Comment by joelittlejohn** [comment]
I think you're expecting too much from javaType. This isn't improper code generation.

If you define a javaType of `Map<String,Foo>`, this plugin has no idea how the class Foo relates to anything. It will have no idea where the schema for Foo is supposed to come from.

It looks like you're attempting to force `Map<String,Foo>` so that you can shortcut an intermediate class being created and force your class to be a map that uses the additional properties schema for its values. This doesn't generalise though, because you could easily add a property with a conflicting type, for example:

```json
{
  "type": "object",
  "properties": {
    "something": {
      "type":"integer"
     }
   },
  "additionalProperties": {
    "$ref": "#/definitions/kubernetes_apiextensions_JSONSchemaPropsOrStringArray",
    "javaType": "io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaPropsOrStringArray"
  },
  "javaType": "java.util.Map\u003cString,io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaPropsOrStringArray\u003e"
}
```

If you stop attempting to make this class `java.util.Map`, then it will work.

**Comment by piyush1594** [comment]
Hey @joelittlejohn Thanks for the inputs but we need that variable to be a map. Is there any other way to achieve that or changing type is the only way. TIA

**Comment by joelittlejohn** [comment]
If you simply add a top-level schema file with a $ref to `#/definitions/kubernetes_apiextensions_JSONSchemaPropsOrStringArray` then the type you need will be generated. Then you can refer to it in the same way in your Map definition.

**Comment by piyush1594** [comment]
Thanks works for me that way.

**Comment by metacosm** [comment]
@joelittlejohn I guess I don't quite understand why the type cannot be resolved from the Map since all the information is right there. I'll check the generation code but it looks to me that this is bug. The ref is there in the `additionalProperties` field and the type is properly generated independently in the JSON Schema. `jsonchema2pojo` just won't process it unless a direct reference is made to it, which seems wrong to me.

**Comment by joelittlejohn** [comment]
Closing this as I don't agree that there is work to do here. You'll need to use the workaround above.
