### ISSUE TITLE
"toString" should honor disabled "Commons-Lang3"

### ISSUE THREAD

**Issue by ullenboom** [joelittlejohn/jsonschema2pojo#870]
When "Use Commons-Lang3" is _not_ checked the code should not have a reference to Commons Lang in a generated toString method.

**Comment by joelittlejohn** [comment]
When Use Commons-Lang3 is not checked, this means use commons-lang 2.x.

If you're interested in removing commons-lang altogether, 1.0.0-alpha2 works in this way (thanks to @ehrmann). We will update the website when 1.0.0 GA is released.
