### ISSUE TITLE
Variable name is not correct

### ISSUE THREAD

**Issue by piyush1594** [joelittlejohn/jsonschema2pojo#871]
My JSON schema looks like 
```
        "enum": {
          "type": "array",
          "description": "",
          "javaOmitEmpty": true,
          "items": {
            "$ref": "#/definitions/kubernetes_apiextensions_JSON",
            "javaType": "io.fabric8.kubernetes.api.model.apiextensions.JSON"
          }
        },
        "default": {
          "$ref": "#/definitions/kubernetes_apiextensions_JSON",
          "javaType": "io.fabric8.kubernetes.api.model.apiextensions.JSON"
        }
```

Variable in class getting created has name` _default` and `_enum` Any pointers, may be I am doing it wrongly. TIA

**Comment by joelittlejohn** [comment]
default and enum are reserved words in Java

**Comment by joelittlejohn** [comment]
(we use annotations to ensure the JSON name will still be correct)

**Comment by piyush1594** [comment]
Can you point me to an example regarding fixing this?

**Comment by joelittlejohn** [comment]
Sorry, I don't understand what you mean. We add an underscore because 'enum' and 'default' are not allowed to be used as Java identifiers. They're keywords of the language.

This plugin will add annotations to every field so that the JSON name remains correct.

What is the issue?

**Comment by piyush1594** [comment]
I have JSON schema which has objects by the name, default and enum. I am further using java class to create fluent classes which are failing if the variable name is _default and _enum. Is there any workaround I can do to et java classes with the name of variable default. I have only one class like this. TIA

**Comment by joelittlejohn** [comment]
Please try creating a field in a Java class called `enum` or `default`. You'll see it's a compile error. We can't work around that, it's a restriction of the language:

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html
