### ISSUE TITLE
Root POM defines <repositories>

### ISSUE THREAD

**Issue by lucjross** [joelittlejohn/jsonschema2pojo#877]
I contend that this is bad for this reason: I have a local maven repository from which my projects obtain ALL dependencies. It itself pulls from maven central but there are also proprietary artifacts deployed there that we need. If I configure jsonschema2pojo-maven-plugin to pull in one of these dependencies (sometimes a snapshot), it tries to go to `http://repo1.maven.org/maven2` because that is what is defined in the jsonschema2pojo root POM, even though i defined central/snapshots repos in my settings.xml. My repo configuration strategy is pretty common for enterprises, so I think this project's `<repositories>` config should be removed, especially since this project doesn't seem to rely upon any repos other than the default one. For the spring.io repo, I think gradle users can reasonably be expected to add that repository as a workaround.

**Comment by joelittlejohn** [comment]
You should define a **mirror** in your settings.xml.

**Comment by lucjross** [comment]
Will fork and fix for myself then
