### ISSUE TITLE
maven plugin output directory should default to "generated-sources/jsonschema2pojo"

### ISSUE THREAD

**Issue by sdettmer** [joelittlejohn/jsonschema2pojo#878]
I read that Maven convention for the storing location for generated source code is `target/generated-sources/PLUGIN`, so we should use

  `target/generated-sources/jsonschema2pojo`

as output directory name.

According to https://stackoverflow.com/a/38394608 and https://stackoverflow.com/q/19325525 this is **not** in Mavens [Standard Directory Layout](http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), **but it is a common convention**.

One official looking page suggest the same:
  https://maven.apache.org/guides/mini/guide-generating-sources.html points to   http://www.antlr.org/api/maven-plugin/latest/ which says:

> The plugin will then produce .java and .tokens files in the output directory `target/generated-sources/antlr4/org/foo/bar`

Other projects are using "generated-sources/*" as well, for example:

- Netbeans: https://netbeans.org/bugzilla/show_bug.cgi?id=198650
- Eclipse: https://github.com/querydsl/apt-maven-plugin/issues/50
- GWT: https://github.com/tbroyer/gwt-maven-plugin/issues/35
- ONAP: https://jira.onap.org/browse/SDNC-127

So users may like adding:
  `<outputDirectory>${project.build.directory}/generated-sources/jsonschema2pojo/</outputDirectory>`
to the `configuration` section in the `POM.xml` file.

Unless there is a special reason for the current default output directory (`java-gen`), **I think this should be considered as default instead:**

  `target/generated-sources/jsonschema2pojo`

**Comment by joelittlejohn** [comment]
More discussion on the mailing list, initiated by @sdettmer:

https://groups.google.com/forum/#!topic/jsonschema2pojo-users/gkzpNn09TQ0

@sdettmer If you submit a PR for this, I'll merge.

This is probably a breaking change for some people, however since the jsonschema2pojo-maven-plugin itself automatically adds the output directory as a maven 'compile source root' it should not be a breaking change for most users.
