### ISSUE TITLE
maven-plugin broken due to typo in Jsonschema2PojoMojo Line 728: @parameter property contains dangling '}'

### ISSUE THREAD

**Issue by SKuettner** [joelittlejohn/jsonschema2pojo#880]
Maven Plugin in 1.0.0-alpha3 is broken and unusable. Remove the '}' to fix this.

```
/**
     * The type of code that will be generated.
     * <p>
     * Supported values:
     * <ul>
     * <li><code>java</code> (Generate .java source files)</li>
     * <li><code>scala</code> (Generate .scala source files, using scalagen)</li>
     * </ul>
     *
     * @parameter property="jsonschema2pojo.targetLanguage"
     *            default-value="java"
     * @since 0.5.0
     */
    private String targetLanguage = "java";

```

**Comment by joelittlejohn** [comment]
Hi Stefan. Thanks for reporting this. I've pushed a commit that fixes a few of these errors. I don't have time to build and verify this right now, would you be able to `mvn install` a snapshot version from the current HEAD and try that version?

**Comment by SKuettner** [comment]
Seems to work now. Closed.

**Comment by joelittlejohn** [comment]
@SKuettner Did you build the latest snapshot to verify this?

**Comment by SKuettner** [comment]
@joelittlejohn: Yes, I did. Can't build the whole multimodule because I don't get the gradle plugin module test accessing the internet to run behind our Firewall but I excluded it and was able to build the latest SNAPSHOT from master. I've tested the maven-plugin with our modules and it did the job as well as the stable version (0.5.1).
