### ISSUE TITLE
Online generator not working

### ISSUE THREAD

**Issue by Ramgopalbhat10** [joelittlejohn/jsonschema2pojo#883]
I'm trying to generate the POJO files in online by pressing ZIP button after pasting my schema. But nothing is happening.

**Comment by joelittlejohn** [comment]
It's working fine for me. After you click 'Zip' you will get a zip created and delivered to the page, just click the link to download.

**Comment by Ramgopalbhat10** [comment]
After pasting my JSON schema and on clicking preview, popup is empty and not showing anything.
![popup](https://user-images.githubusercontent.com/19610022/42025617-a4eb3f70-7ae2-11e8-8a47-6d24333641a7.PNG)

**Comment by joelittlejohn** [comment]
I expect there are no types produced. Can you put the schema here? Do you have the correct Source Type selected?
