### ISSUE TITLE
Introduce targetPackage placeholder for javaType property

### ISSUE THREAD

**Issue by RuralYak** [joelittlejohn/jsonschema2pojo#884]
Sometimes json schema produce classes with same name. In such cases resolution happens by adding a counter value to the tail of each class with the same name. My proposal is to extend functionality of javaType property to the level where it could understand some placeholder and substitute it with targetPackage value, so one could specify relative package and class name.

for instance this would produce duplicate named classes:

```
"foo": {
  "type" : "object",
  "properties": {
      "bar": {
        "type" : "object",
         "properties": {
            foo: {
              "type" : "object"
            } 
          }
       }
   }
}
```

Foo.java
Bar.java
Foo__1.java

having targetPackage set to com.some.package
one would obtain following:

com.some.package.Foo.java
com.some.package.Bar.java
com.some.package.Foo__1.java

Of course there is still option to specify javaType for each conflicting or all the classes like that
```
"foo": {
  "type" : "object",
  "javaType" : "com.some.package.subpackage1.Foo",
  "properties": {
      "bar": {
        "type" : "object",
         "properties": {
            foo: {
              "type" : "object"
             "javaType" : "com.some.package.subpackage2.Foo",
            } 
          }
       }
   }
}
```

but this approach introduces unnecessary package information to the schema which could be avoided by replacing constant part of fully qualified class names with placeholder ":" which will represent targetPackage:
```
"foo": {
  "type" : "object",
  "javaType" : ":subpackage1.Foo",
  "properties": {
      "bar": {
        "type" : "object",
         "properties": {
            foo: {
              "type" : "object"
             "javaType" : ":subpackage2.Foo",
            } 
          }
       }
   }
}
```

where ":" replaced with targetPackage + "." + actual value
That will minimize amount of non schema related information in schema.

**Comment by joelittlejohn** [comment]
Hi. If you write JSON blocks like this:

    ```json
    {
        etc
    }
    ```

they are a lot more readable

I think what you're proposing is a good idea. This has been raised before and is discussed in #195. The proposal there (which I quite like) is to use a `.` character to indicate that the targetPackage value goes there, like this:

```json
{
  "javaType" : ".subpackage2.Foo"
}
```
