### ISSUE TITLE
Force to not create javatype

### ISSUE THREAD

**Issue by hector-m** [joelittlejohn/jsonschema2pojo#886]
I currently have something like this
"type": "array",
          "items": {
            "javaType": "path.to.AnExistingInterface",
            "type": "object"
          }
As of right now, pojo keeps creating this AnExistingInterface as an empty class with only the default methods. Is there any way to 1) actually create an interface is pojo or 2) force pojo to not create this class and use the existing one.

Thanks!

**Comment by joelittlejohn** [comment]
Yes, use `existingJavaType`. This is the behaviour of the current alpha and will be the only way to reuse an existing type in 1.0.0.

**Comment by vantose56** [comment]
Thanks for the quick response. Yes, I saw that solution on another post, but I'm using the maven plugin which I believe is on 0.4.2. Is there any solution of this old version. Sorry for not mentioning that in my original post.

When I use existingJavaType:

```
"example": {
          "type": "array",
          "items": {
            "existingJavaType" : "path.to.AnExistingInterface"
          }
```

I get:
```
@JsonProperty("examples")
    private List<Object> examples = new ArrayList<Object>();
```
but I want:
```
@JsonProperty("examples")
    private List<AnExistingInterface> examples = new ArrayList<AnExistingInterface>();
```

**Comment by joelittlejohn** [comment]
On 0.4.2 I believe there is a hack you can use. Try this:

```json
"type": "array",
"items": {
"javaType": "path.to.AnExistingInterface"
}
```

**Comment by vantose56** [comment]
That also gives me the same as above. 
```
@JsonProperty("examples")
    private List<Object> examples = new ArrayList<Object>();
```
Would this mean that it can not find the class?
When I run generate it does not give any errors so I would assume it was able to find it.

**Comment by joelittlejohn** [comment]
Yes actually you're right. If the type is found on the classpath then your very first example should do what you want.

**Comment by vantose56** [comment]
Ok I'll try to figure out whats wrong with my paths. I'm using the correct package so i'm not entirely sure whats going on. I'll let you know if I have any more questions. Thanks so much for the help!

Is there a way to add this interface as a dependency to pojo? Because my fear is that when I am maven clean and packaging it just so happens that pojo is run before the existing interface and other classes are actually compiled and thats why it can't find it.

**Comment by joelittlejohn** [comment]
Ah, if you have this type in the same module, that won't work. Sources are generated before the compile phase, because of course they need to be compiled.

I suggest you split your modules.

**Comment by vantose56** [comment]
That worked! Thanks so much you're a life saver!
