### ISSUE TITLE
Cannot generate a complex type for lists. 

### ISSUE THREAD

**Issue by shmsi** [joelittlejohn/jsonschema2pojo#890]
Hi, 

I was trying to generate java classes for the following json schema. 

```json
{
  "type":"object",
  "properties": {
      "container": {
          "items": [
            {
              "item1": {
                "type": "string"
              }
            },
            {
              "item2": {
                "type": "string"
              }
            }
            ],
        "type":"array"
          }
  }
}
```
It seems jsonschema2pojo cannot generate a type for list. 
In java classes the list container has the type Object .

```java private List<Object> container = new ArrayList<Object>(); ```

However i would expect something like this.  

`private List<Container> container = new ArrayList<Object>(); `

And the corresponding container class. 

```java
class Container {
     private String item1; 
     private String item2; 
    // getters and setters 
    .... 
}
```

Is it a bug or is there some parameter to be specified to do this? 

Regards, 
Shamsi

**Comment by joelittlejohn** [comment]
Do you mean like this:
```json
{
  "type":"object",
  "properties": {
    "container": {
      "items": {
        "type":"object",
        "properties":{
          "item1": {
            "type": "string"
          },
          "item2": {
            "type": "string"
          }
        }
      },
      "type":"array"
    }
  }
}
```
?

**Comment by shmsi** [comment]
No, my autogenerated json schemas which are generated from yang data models using pyang are  similar to the json example in my post.

**Comment by joelittlejohn** [comment]
But I don't know what this is:
```
          {
              "item1": {
                "type": "string"
              }
            }
```
It's not a schema.

**Comment by shmsi** [comment]
The example seems like perfectly fine schema. You can find similar ones [here](https://cswr.github.io/JsonSchema/spec/arrays/)

**Comment by joelittlejohn** [comment]
What is the thing inside the array? Is it an object with a property called item1? That schema would look like this:

```json
{
  "type":"object",
  "properties":{
    "item1": {
      "type": "string"
    }
  }
}
```

Show me where, in the link you provided, there is an example that looks like yours.
