### ISSUE TITLE
Preview Not Working

### ISSUE THREAD

**Issue by troy21688** [joelittlejohn/jsonschema2pojo#891]
Why is my preview not working? I am expecting three model classes to be generated:

![image](https://user-images.githubusercontent.com/16483832/42979159-754aa296-8b96-11e8-8b9a-57319d3156b6.png)

**Comment by joelittlejohn** [comment]
You have selected input type JSON Schema but you have not entered a JSON Schema.

**Comment by troy21688** [comment]
This would be regular JSON then?

**Comment by joelittlejohn** [comment]
Yep. Select source type: JSON.
