### ISSUE TITLE
Issue with generating Setters and Getters

### ISSUE THREAD

**Issue by harishkumarreddy12** [joelittlejohn/jsonschema2pojo#892]
Hi Team,
I am trying to exclude setters and getters by setting 
**includeGetters = false
includeSetters = false**
but still, it is generating after setting false also. The default value is not overriding

**Comment by joelittlejohn** [comment]
What version are you using, and are you using grade?

I think this may be a bug. Could you try adding `includeAccessors = false`?

**Comment by joelittlejohn** [comment]
includeAccessors will be gone in 1.0.0 because of problems like this, so I'm closing this.
