### ISSUE TITLE
Generate extended classes

### ISSUE THREAD

**Issue by ilyako87** [joelittlejohn/jsonschema2pojo#893]
Hi everyone,
Please help me if someone can.
I need to get the generated Java classes: Parent & child-classes.
For example:
`public class Parent {
    @JsonProperty("message")
    private String message;
    @JsonProperty("tags")
    private String tags;
}
`
And
`public class Child extends Parent {
    @JsonProperty("meta_data")
    private String metaData;
}
`
Does this plug-in (jsonschema2pojo) allow this?
How can I describe the json-scheme to get a similar result?

Thanks. 
Regards,
Ilya Weber

**Comment by joelittlejohn** [comment]
Yes, you can use the old `"extends"` rule for this.

**Comment by joelittlejohn** [comment]
https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#extends

**Comment by ilyako87** [comment]
Oh, thank you!
Indeed, I tried to make it, but made a mistake.
Now it works.
