### ISSUE TITLE
Use Optional On Getters is not configurable in Maven pom configuration

### ISSUE THREAD

**Issue by mbramwell1** [joelittlejohn/jsonschema2pojo#894]
I have a fix for it done, but getting permission denied when trying to push up my feature branch...

**Comment by joelittlejohn** [comment]
Hi Martin. Thanks for looking at this.

If you fork this repo, you can update your git remote to point at your own fork. Then push the branch to your fork and create a PR.

**Comment by mbramwell1** [comment]
Cool will do, cheers!

**Comment by mbramwell1** [comment]
PR Created https://github.com/joelittlejohn/jsonschema2pojo/pull/895

**Comment by joelittlejohn** [comment]
Thanks!!
