### ISSUE TITLE
Cant apply this plugin into plugins {} in gradle

### ISSUE THREAD

**Issue by Enigamitsuj** [joelittlejohn/jsonschema2pojo#896]
What is the plugin id ?

i cant use `buildscript{}` and `plugins{}` at the same time and `jsonSchema2Pojo` as an id doesnt work its says it cant find the plugin.

> Plugin [id: 'jsonSchema2Pojo', version: '1.0.0-alpha2'] was not found in any of the following sources:

Is it even possible or im missign soemthing ?

**Comment by joelittlejohn** [comment]
Hi. Check out https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/README.md

**Comment by Enigamitsuj** [comment]
I did and the way the readme suggests to apply the plugin is to use the `buildscript` which is old way used in gradle 1.x and I am using plugins block which excludes using `buildscript` block you see, build script needs to be before plugins but then plugins need to be first in the build.gradle.

**Comment by joelittlejohn** [comment]
Sorry, I'm not a gradle user. This might be a good question for StackOverflow.

**Comment by Enigamitsuj** [comment]
@joelittlejohn erm, but you own this repository, right? Are you the author of the plugin? is this supported to be used in gradle then? Im confused.

**Comment by joelittlejohn** [comment]
This plugin supports Maven, Ant, Gradle - I don't use all three. Each of these ways of using this plugin has a community of users.

Someone who does use jsonschema2pojo on Gradle might reply here, but you might find a quicker answer to this kind of question at StackOverflow.

**Comment by Enigamitsuj** [comment]
I see, thank you for a quick reply.

**Comment by Enigamitsuj** [comment]
@joelittlejohn I've found a way to sort it out

maybe this will lead you to the idea how to make it work as its something with the names space id etc.

https://stackoverflow.com/questions/51766423/cant-use-jsonschema2pojo-gradle-plugin-in-plugins-block/51769604#51769604

**Comment by AceHack** [comment]
Please fix this plugin to work with gradle kotlin dsl

**Comment by eirnym** [comment]
@AceHack @Enigamitsuj Published a plugin, 100% compatible (for now) with the original one  https://plugins.gradle.org/plugin/com.github.eirnym.js2p Gradle 5.6 is a minimum

**Comment by renannprado** [comment]
@eirnym thanks, seems to be working for us, even with Kotlin dsl. Could you send a pull request to this repo?

**Comment by AceHack** [comment]
Yes would love for that to be contributed to this repo

**Comment by wellington-aquino-dev** [comment]
This is working for me also. I think would be a good addition to the official library as support.
