### ISSUE TITLE
POJO class Properties are generating with public access modifier if I off setter and getter methods

### ISSUE THREAD

**Issue by harishkumarreddy12** [joelittlejohn/jsonschema2pojo#901]
Hi Team,
I am facing an issue while generating POJO's from schema.
While generating pojo classes if I off setter and getter methods to generate only properties for respective POJO class,It is not creating the private access modifier instead it it taking all public access modifiers.

Generated Code:
public class Example {

public String foo;
public Integer bar;
public Boolean baz;

}

Expected Code:
public class Example {

private String foo;
private Integer bar;
private Boolean baz;
}

Could you please help me to resolve the issue.

**Comment by joelittlejohn** [comment]
What are you expecting to do with a class that has no getters and setters and private fields?

**Comment by harishkumarreddy12** [comment]
I want to generate only private access modifiers instead of public.Planning to implement lombok

**Comment by joelittlejohn** [comment]
This is not a bug, it's the intended design. If you turn off accessors, then the fields will be directly accessible instead.

We have an open ticket for Lombok support, please add your :+1: there.
