### ISSUE TITLE
dots in source package get changed to underscore in output

### ISSUE THREAD

**Issue by kkuo** [joelittlejohn/jsonschema2pojo#902]
I have some sources in subfolders:
```
A/
  B/
    C/foo.json
```
This used to get generated as A.B.C.foo.java

Today, using version 0.5.1 we are getting A_B_C.foo.java, which is making us having to go and change our imports everywhere, not to mention it is ugly. Is there a flag or toggle to change this behavior?

The previous version I think was 0.4.9. We had to upgrade because of some import conflicts after upgrading to java 9.

**Comment by joelittlejohn** [comment]
This should get generated as:

A/B/C/foo.java

Do you mean the package name is `A_B_C`? Could to provide minimal example project that shows this error?

**Comment by joelittlejohn** [comment]
Need more info if we're going to investigate this.
