### ISSUE TITLE
Error: Unable to initialize main class org.jsonschema2pojo.cli.Jsonschema2PojoCLI

### ISSUE THREAD

**Issue by arya6000** [joelittlejohn/jsonschema2pojo#914]
I downloaded jsonschema2pojo-cli-0.5.1.jar, but when I run the following command

`java -jar jsonschema2pojo-cli-0.5.1.jar  -a GSON -T JSON -s json.txt -t ./recs -p "test.model.users" -bi`

I get the following error

```
Error: Unable to initialize main class org.jsonschema2pojo.cli.Jsonschema2PojoCLI
Caused by: java.lang.NoClassDefFoundError: org/jsonschema2pojo/GenerationConfig
```

**Comment by joelittlejohn** [comment]
It looks like you're missing all the important jars from your classpath. I'd recommend downloading a proper release package and using the wrapper scripts to run the cli.

**Comment by joelittlejohn** [comment]
See https://github.com/joelittlejohn/jsonschema2pojo/releases
