### ISSUE TITLE
When will 1.0.0-beta1 release

### ISSUE THREAD

**Issue by mbramwell1** [joelittlejohn/jsonschema2pojo#919]
Hey, could do with a release build building to include the optional stuff, any idea when 1.0.0-beta1 will release?

Cheers,
Martin

**Comment by jrehwaldt** [comment]
FYI it is [released](https://mvnrepository.com/artifact/org.jsonschema2pojo/jsonschema2pojo-core/1.0.0-beta1)

**Comment by joelittlejohn** [comment]
I've done the doc updates now (I have to wait a little time for these so I usually do them the day after release). Thanks for contributing!
