### ISSUE TITLE
Allow disabling enum generation

### ISSUE THREAD

**Issue by posto** [joelittlejohn/jsonschema2pojo#927]
Generating java enums from schemas generates problems with backwards compatibility. If a new values is ever added to an enum, all clients must be upgraded first, otherwise they would break, which makes upgrades very slow and costly.

Please allow disabling enum generation using a configuration switch, in which case just `String`s would be generated for the specific fields (since they mostly have type: String, in jsonschema).

**Comment by joelittlejohn** [comment]
Feel free to submit a pull request for this. It would be good to implement a new optional called `useEnumForEnums`.
