### ISSUE TITLE
additionalProperties not created when annotationStyle is set to gson

### ISSUE THREAD

**Issue by eirikandre** [joelittlejohn/jsonschema2pojo#928]
The combination gson annotationStyle and the use of additionalProperties to generate map does not work. Seems to be the same behaviour in both latest stable and beta1.

This is the maven configuration:
```xml
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <configuration>
        <sourceDirectory>${basedir}/src/test.json</sourceDirectory>
        <targetPackage>my.package</targetPackage>
        <annotationStyle>gson</annotationStyle>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
Given the schema
```
{
  "type":"object",
  "properties": {
    "foo": {
      "type": "object"
    }
  }
}
```
Should produce Foo.java that would have
```
private Map<String, Object> additionalProperties = new HashMap();
```
Instead it is producing empty Foo.java with only toString, hashCode etc.

**Comment by eirikandre** [comment]
Not sure if I follow your question. It is the other way around? I do not make any annotations. The plugin will generate annotations based on the configuration in the maven plugin?

I am trying to get the plugin to work as described here: https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#additionalproperties

What I am trying to say is that it is not working when the annotationStyle is configued to gson as referenced here https://joelittlejohn.github.io/jsonschema2pojo/site/0.5.1/generate-mojo.html .

**Comment by joelittlejohn** [comment]
I mean, what Gson annotation can jsonschema2pojo add to you method/field that will cause Gson to put unrecognised values into that map during it binding? I don't think Gson has this feature.

As far as I know, there is no way to support additional/unknown property names with Gson if you are binding JSON to a custom Java object. If you don't know all the key names, you have to use a Map. jsonschema2pojo cannot help here.

**Comment by eirikandre** [comment]
ok, got you now. Ok, then I guess this issue can be closed then. Thanks.
