### ISSUE TITLE
JsonFactory.requiresPropertyOrdering()Z

### ISSUE THREAD

**Issue by hannesa2** [joelittlejohn/jsonschema2pojo#929]
I use this example https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-gradle-plugin with this change

```
annotationStyle = 'gson'
sourceType = 'json'
```

and receive this

> * What went wrong:
> Execution failed for task ':RxCommJson:generateJsonSchema2Pojo'.
> > com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z

I can include implementation `'com.fasterxml.jackson.core:jackson-databind:2.9.7'` or not, it makes no differnece

Any clue what I did wrong ?

**Comment by joelittlejohn** [comment]
Looks like you have a Jackson dependency conflict. Make sure you have no other, older, versions of the Jackson libraries on the classpath.
