### ISSUE TITLE
Class.forName returns ClassNotFoundException for classes generated using jsonschema2pojo

### ISSUE THREAD

**Issue by srivshreya** [joelittlejohn/jsonschema2pojo#934]
I am unable to use newly generated classes with ObjectMapper as gives me ClassNotFoundException.
ClassName is dynamic
Below is my code:

```
JCodeModel codeModel = new JCodeModel();

	GenerationConfig config = new DefaultGenerationConfig() {
			@Override
			public boolean isGenerateBuilders() { // set config option by
													// overriding method
				return true;
			}
		};
		
		SchemaMapper mapper = new SchemaMapper(
				new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore()), new SchemaGenerator());
		mapper.generate(codeModel, className, "com.xyz.example", json);
		
		File root = new File("src\\main\\java");
		codeModel.build(root);
              Class<?> clazz =Class.forName("com.xyz.example."+className);  //fails here
				Object obj = mapper.readValue(data, clazz);
				map.put(key, obj); 
```

**Comment by joelittlejohn** [comment]
You can't refer to classes until they have been compiled. Jsonschema2pojo generates Java source files, you need to compile them.

**Comment by srivshreya** [comment]
Thank you for your quick answer. I needed class files. I was wondering if there is an easy way out to get class files. Tried this but it's a bit tricky. Or should I use BeanGenerator.

```
JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
		
		compiler.run(null, null, null, "../com/example/*.java");
		// Load and instantiate compiled class.
		URL url1 = (new java.io.File("com/example/"+className+".java")).toURI().toURL();
		URLClassLoader classLoader = URLClassLoader.newInstance(new URL[] { url1 });
		Class<?> cls = Class.forName(className, true, classLoader); // Should print "hello".
		return cls;
```

**Comment by srivshreya** [comment]
I am having trouble compiling the files. It's giving lombok error. 
`Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment

public class Employee {
       ^
  	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:426)

  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:89)
`

I'll take it from here. Thanks for your help. You have done pretty cool stuff.
