### ISSUE TITLE
Equals in scalagen is wrong

### ISSUE THREAD

**Issue by matteuan** [joelittlejohn/jsonschema2pojo#936]
I'm using the release 0.5.1 with generated scala classes. The generation of equals add this to the code:
```
 if (other == this) {
        return true;
 }
```
This is correct in Java, but doesn't work in Scala, since == is the same as equals. This problem creates an infinite loop of comparisons that produces StackOverflow.

**Comment by joelittlejohn** [comment]
Interesting. So I guess the scalagen conversion should convert `==` in Java to `eq` in Scala.

**Comment by matteuan** [comment]
Yes, I guess it should be like that

**Comment by joelittlejohn** [comment]
Superseded by #1199
