### ISSUE TITLE
1.0.0-beta1: javaType of java.math.BigDecimal generates custom type

### ISSUE THREAD

**Issue by LarsKrogJensen** [joelittlejohn/jsonschema2pojo#937]
Hi,

if I have a simple schema 
`{
  "type":"object",
  "properties": {
    "foo": {
      "type": "object",
      "javaType": "java.math.BigDecimal"
    }
  }
}`

the maven generator plugins generates a custom java.math.BigDecimal instead of using the jdk version. This looks wrong as the docs says that it will omit generating class if it is available in the classpath.

**Comment by LarsKrogJensen** [comment]
Sorry about this, but found out that I should use 'existingJavaType' fixes this.

**Comment by joelittlejohn** [comment]
Hopefully we can ship a GA or 1.0.0 soon and update the docs :)
