### ISSUE TITLE
Please add an option to configure toString method. Need to string with no extra info, but just name and its value

### ISSUE THREAD

**Issue by etsybaev** [joelittlejohn/jsonschema2pojo#941]
When you use ToStringBuilder - it also includes full path and class name. It's very uncomfortable to read by eyes (during debugging or testing), in reports in case of assertion fails, etc.  Please add an option to generate toString with no Extra information, but add just name and value. 

For example to make it looks like this:
` @Override
    public String toString() {
        return "Reminder{" +               
                "id=" + id +
                ", reminderDate=" + reminderDate +
                ", reminderText='" + reminderText + '\'' +
                ", reminderIsEnabled=" + reminderIsEnabled +
                '}';
    }`

Many thanks in advance!

**Comment by joelittlejohn** [comment]
We have too many configuration options in this plugin already. I'm afraid supporting different toString styles is just too much. Every time we support a new strategy for doing this kind of thing, it is more code to support and more features to carry forward and extend.

If you'd like to modify this, you are free to clone this repo and customize the plugin however you like.

**Comment by mplain** [comment]
Wouldn't it make sense to have toString() output in a json format?

**Comment by tomerzvirsh** [comment]
@joelittlejohn can you please consider supporting JSON format for toString?

**Comment by joelittlejohn** [comment]
Implementing a JSON serializer isn't in the scope of this project, and if we use an existing serializer (like the Jackson ObjectMapper) this creates a can of worms around allowing the ObjectMapper to be configured as needed. I think it's best you serialize things to JSON yourself if you need to, rather than simply calling toString.
