### ISSUE TITLE
Take some credit!

### ISSUE THREAD

**Issue by Zag24** [joelittlejohn/jsonschema2pojo#944]
Hi.  I don't really have an issue, I mostly wanted to say thanks for this tool, it has really helped me out in my latest project.  

But since I'm writing an issue, I want to suggest that you add a comment to the top of every generated file, something like 

// Generated by jsonschema2pojo.  Find us at http://www.jsonschema2pojo.org/.

Thanks again.

**Comment by joelittlejohn** [comment]
Thank you @Zag24, your thanks is very much appreciated!

We use to add an `@Generated("jsonschema2pojo")` annotation on these types, but this caused a little hassle for Android users. It looks like there's away forward now with #835 so maybe this will make an appearance again soon :)
