### ISSUE TITLE
update homebrew formula version...

### ISSUE THREAD

**Issue by rpus** [joelittlejohn/jsonschema2pojo#946]
... now that v1.0.0 is out/final?

https://github.com/Homebrew/homebrew-core/blob/master/Formula/jsonschema2pojo.rb

Maybe there are other (post-)release 'steps' that also need to be performed/updated now that v1 is out of pre-release?

I would update the brew script myself (via a PR), but I'm not sure of the protocol/workflow!

**Comment by joelittlejohn** [comment]
Me neither, I didn't create the brew formula :)

I don't think there is any special workflow though. Just update the version number and submit a PR.
