### ISSUE TITLE
BUG:  Objects defined as strings being generated as Pattern

### ISSUE THREAD

**Issue by LouPaloma** [joelittlejohn/jsonschema2pojo#948]
An object defined to be a string type with a regex pattern is being generated as a java.util.regex.Pattern, not a string.  This is obviously incorrect.  For example, generate classes from the following schema, planId field is a Pattern, not the expected String:

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "test schema",
  "definitions": {
    "test_id_type": {
      "type": "string",
      "format": "regex",
      "pattern": "^[0-9]{1,19}$"
    },
    "TestPlan": {
      "type": "object",
      "title": "plan",
      "description": "Representation used to identify a distinct User Plan.",
      "properties": {
        "plan_id": {
          "description": "This element is only populated on READ. Exception thrown on POST.",
          "$ref": "#/definitions/test_id_type"
        }
      }
    }
  },
  "properties": {
    "test_payload": {
      "$id": "#/properties/test_payload",
      "type": "object",
      "title": "The test_payload Schema",
      "properties": {
        "plans": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TestPlan"
          }
        }
       }
    }
  }
}

**Comment by joelittlejohn** [comment]
Hi. Pattern is used when format is 'regex'.

**Comment by LouPaloma** [comment]
Blech, so the "format" field is superfluous... if the user intends a string field meeting the regex.  (As written in the original post, the "test_id_type" is a String which is a Regex which must meet the defined Pattern... definitely not what the user intended, I suspect)
