### ISSUE TITLE
Using jsonschema2pojo-maven-plugin with test classes and resources only, and schema->code and code->schema references

### ISSUE THREAD

**Issue by jasonCodesAway** [joelittlejohn/jsonschema2pojo#949]
Greetings,

Does the maven plugin support working exclusively in test code (i.e. src/test/[java,resources])? Try as I did, I couldn't get maven to test-compile or install successfully. Here is a [gist](https://gist.github.com/jasonCodesAway/54888b6e7f514818d34ec3e0b8603dfd). I reference generated code from java test code as well as java test code (an interface) from the schema - is that supported!? 

Here is maven's output during compilation:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project test: Compilation failure: Compilation failure: 
> [ERROR] /D:/code/tmp/jsonschema-test/target/generated-test-sources/com/jsanity/jsonSchemaTest/TestSchema.java:[6,18] package schemaTest does not exist
> [ERROR] /D:/code/tmp/jsonschema-test/target/generated-test-sources/com/jsanity/jsonSchemaTest/TestSchema.java:[8,36] cannot find symbol

I did try attaching the execution to:

> &lt;phase>test-compile&lt;/phase>

But that didn't seem to help, mvn test-compile will result in the same error as above.

Thank you from Florida, USA!

**Comment by jasonCodesAway** [comment]
Interesting, if I attach the plugin to the 

> &lt;phase>process-test-resources&lt;/phase>

then I can get past a mvn clean compile, no problem. But mvn install fails:

> Compilation failure: 
> [ERROR] /D:/code/tmp/jsonschema-test/src/test/java/schemaTest/SchemaReference.java:[3,34] package com.jsanity.jsonSchemaTest does not exist
> [ERROR] /D:/code/tmp/jsonschema-test/src/test/java/schemaTest/SchemaReference.java:[6,12] cannot find symbol

What fails is the regular java code's reference to the auto-generated schema elements - shouldn't those exist after the process-test-resources phase completes? I'm not very familiar with maven phases...

**Comment by joelittlejohn** [comment]
Sorry I can't be more helpful here, but I think you just need to study the full list of maven phases that's here:

https://maven.apache.org/ref/3.6.0/maven-core/lifecycles.html#default_Lifecycle

and always remember that you can't reference types from the classpath until after they are compiled, and you can't reference resources until after they are processed.
