### ISSUE TITLE
Is there a way to create a byte array using this plugin

### ISSUE THREAD

**Issue by der55757** [joelittlejohn/jsonschema2pojo#951]
I am trying to add a byte array for an Attachment Object

this is the class I am trying to generate

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attachment", propOrder = {
  "attachmentId",
  "name",
  "fileType",
  "content",
})
public class Attachment   {
  @JsonProperty("attachmentId")
  private String attachmentId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("fileType")
  private String fileType = null;

  @JsonProperty("content")
  private byte[] content = null;

Here is my json schema file

"Attachments":[
        {
          "Base64Data":"String content",
          "Data":"Byte[]",
          "fileType":"String content",
          "Name":"String content"
        }
      ]

Not sure of the syntax of what Data should be to make a private byte data object

**Comment by joelittlejohn** [comment]
You can't do this with example JSON, only with a JSON schema.

In a JSON schema you can use

```
  "media": {
    "binaryEncoding": "base64"
  }
```

Inside the property schema.
