### ISSUE TITLE
Add an ability to initialize Map in the same way as List/Set is initialized

### ISSUE THREAD

**Issue by sleshchenko** [joelittlejohn/jsonschema2pojo#955]
There is configuration parameter `initializeCollections` to initialize `List` and `Set` fields with an empty collection instead of null.
It makes sense to add an ability to initialize Map in the same way as List/Set is initialized.

I think it may be Map initialized when `initializeCollections` is set to true since it doesn't really implement `Collection` interface but is a part of java collection framework.
Maybe it would be better and easier from backward compatibility to configure Map initialization with a separate configuration parameter but not `initializeCollections`.

Dear maintainers, please leave your opinion about this issue.
Sorry if it is already implemented and I did not found it.

**Comment by joelittlejohn** [comment]
I think we don't use `initializeCollections` to initialize maps because we don't generally create Map fields. Could you help me understand how you are using a Map in your types?

**Comment by sleshchenko** [comment]
I'm a maintainer of Eclipse Che project https://github.com/eclipse/che.

We lazy initialize `List`s, `Set`s, `Map`s values in our POJOs objects to avoid null checks.
```java
MyObject{
  Map<String, String> properties;
  
  public Map... getProperties() {
    if (properties == null) {
        properties = new HashMap<>();
    }
    return properties;
  }
}
```
For example https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/workspace/model/WorkspaceImpl.java#L114

It allows us to write
```java
myObject.getProperties().contains("configurationProperty")
```
instead of 
```java
myObject.getProperties() != null && myObject.getProperties().contains("configurationProperty")
```

Or 
```java
myObject.getProperties().put("configurationProperty", "value");
```
instead of 
```java
if (myObject.getProperties() == null) {
  myObject.setProperties(new HashMap<>());
}
myObject.getProperties().put("configurationProperty", "value");
```

**Comment by sleshchenko** [comment]
Not sure If it can be useful but added maven plugin configuration we use

**Comment by joelittlejohn** [comment]
Ah, so when you use `"javaType": "java.util.Map<String, String>"` you would like to have these value initialized? Which implementation should we choose to initialise the value? HashMap? 

It seems like this is not something that jsonschema2pojo can decide. When you use `javaType`, you are using an escape hatch that lets you change the types, the plugin can't do anything with this field after you have decided to use javaType.

**Comment by sleshchenko** [comment]
@joelittlejohn HashMap would be just fine.
So, should this issue be closed as `won't fixed` or maybe there is some way to implement it?

**Comment by joelittlejohn** [comment]
I'm closing this as wontfix because I'm not too interested in trying to implement defaults when javaType has been used.
