### ISSUE TITLE
Support for JsonTypeInfo to add type information for Jackson1/Jackson2

### ISSUE THREAD

**Issue by ddcruver** [joelittlejohn/jsonschema2pojo#958]
I would like to create json-schema generated classes where type information added to the class.  This is useful in cases when you want to enable polymorphism.

My primary use case is to add this to the top of generated classes:
 `@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="@class")`

Also my primary use case is Jackson 2 but Jackson 1 has similar classes and functionality.

**Comment by ddcruver** [comment]
@joelittlejohn Do you think you could look over this and merge it in if you like it?

**Comment by dsegoviat** [comment]
This feature would be very useful! I would like to benefit from that too.

**Comment by ddcruver** [comment]
@dsegoviat This feature is already implemented.  Make sure you update to version 1.0.2.
