### ISSUE TITLE
Is there any way to set field With Deprecated using Custom Annotators??

### ISSUE THREAD

**Issue by Sanjay007** [joelittlejohn/jsonschema2pojo#961]

**Comment by joelittlejohn** [comment]
There's an example of this in our own tests:

https://github.com/joelittlejohn/jsonschema2pojo/blob/3b80b3452f3d34901ee1e1e886c946c6986aaec1/jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomAnnotatorIT.java#L112

Inside the annotator you can put whatever logic you like to decide when the annotation should be added.
