### ISSUE TITLE
Can jsonschema2pojo use json schemas generated by jsonix-schema-compiler?

### ISSUE THREAD

**Issue by tasosz** [joelittlejohn/jsonschema2pojo#962]
Using a Json-schema that gets generated by jsonix-schema-compiler looks to not produce any POJOs.
An example schema, from the jsonix-schema-compiler project: 
[PurchaseOrder.jsonschema](https://github.com/highsource/jsonix-schema-compiler/blob/master/demos/po-npm/mappings/PurchaseOrder.jsonschema)

Using this schema directly on the online tool produces no output.
Is there something in the jsonix-produced structure that needs to be changed in order for jsonschema2pojo to understand it?

Thanks

**Comment by tasosz** [comment]
While experimenting with various things, I have seen that adding this line after the "id" line, does seem to produce a single POJO -> PurchaseOrderType.
`"$ref": "#/definitions/PurchaseOrderType",`

This is promising, but is there a way to get jsonschema2pojo to generate all types?
I.e. Items.Item, Items & USAddress (as well as PurchaseOrderType)

**Comment by joelittlejohn** [comment]
The problem here is that this schema makes extensive use of allOf and anyOf, and we don't support these (#392). The semantics of these are very difficult to map faithfully to Java.

**Comment by tasosz** [comment]
I see.
If I remove all the allOf constraints, will this help? I.e. have these references only implied. 
Eg. from:
`"allOf":[{
"$ref":"http://www.jsonix.org/jsonschemas/w3c/2001/XMLSchema.jsonschema#/definitions/string"
}], `
to just:
`"$ref":"http://www.jsonix.org/jsonschemas/w3c/2001/XMLSchema.jsonschema#/definitions/string"`

Also, in the PurchaseOrder.jsonschema schema example, the anyOf constraints appear at "top-level". I'm not 100% sure how they help in this example, but could they get "merged" in a way that jsonschema2pojo can process it?
From the original [XSD](https://github.com/highsource/jsonix-schema-compiler/blob/master/demos/po-npm/schemas/purchaseorder.xsd) it looks that these could have been modelled as "properties"... (??)

**Comment by tasosz** [comment]
I have manually done all the changes I had suggested in order to test what will happen. The online tool now generates the 2 "merged" properties. But...   ...the types of the fields are just Object. No mapping to the #definitions types... Any ideas?

[PurchaseOrder_no-constraints.jsonschema.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/2975913/PurchaseOrder_no-constraints.jsonschema.txt)
