### ISSUE TITLE
toooooooo many

### ISSUE THREAD

**Issue by dzw1113** [joelittlejohn/jsonschema2pojo#963]
Whether to support the generation of internal classes from objects in complex json, otherwise too many objects will be generated in large projects, or as a developer, it will be difficult to understand the overall project relationship! Internal words can be much simplified.

是否支持把复杂json里的对象生成内部类，否则在大项目中生成出的对象太多了，或者作为一个开发人员需要了解整体项目关系，这样会很困难！内部类的话能精简很多

**Comment by joelittlejohn** [comment]
Thanks, I think we have this request open already as #125
