### ISSUE TITLE
Optional getter for required field bug

### ISSUE THREAD

**Issue by KuchinRussia** [joelittlejohn/jsonschema2pojo#965]
I have a schema with a required field which is a reference. jsonschema2pojo v1.0.0 generates an Optional getter for it instead of ordinary one.

Seems like https://github.com/joelittlejohn/jsonschema2pojo/pull/964 cures this bug.

Please merge and release 1.0.1 version!

**Comment by joelittlejohn** [comment]
Cool. Did you try building a snapshot from that fork to test the fix? I think we can release this soon.

**Comment by KuchinRussia** [comment]
> Cool. Did you try building a snapshot from that fork to test the fix? I think we can release this soon.
Yeah, just built it. Works fine.

**Comment by joelittlejohn** [comment]
Closed by #964
