### ISSUE TITLE
Ignore Field for generation

### ISSUE THREAD

**Issue by 029vaibhav** [joelittlejohn/jsonschema2pojo#966]
Problem statement

I have a concrete class where a field is defined say "fieldX"

Now i have json schema in which i need to validate fieldX using json schema validator also i am generating class from json schema which extends the above mentioned class so i dont want the jsonSchema2pojo to generate that field.

Eg.
```
public class concreteClassA{
private String email
}
```

```
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "_id": "http://example.com/root.json",
  "extendsJavaClass": "concreteClassA",
  "type": "object",
  "title": "The Root Schema",
  "properties":{
"fieldA": {
      "_id": "#fieldA",
      "type": "string",
      "title": "The fieldA Schema",
      "pattern": "^(.*)$"
    },
"email": {
      "_id": "#email",
      "type": "string",
      "title": "The fieldA Schema",
      "pattern": "email"
    },

}
}
```

so i dont want email field to be generated

**Comment by joelittlejohn** [comment]
This isn't a use-case we want to support I'm afraid. This library is about generating types to represent your JSON, not for supporting any possible Java requirement to build different types.
