### ISSUE TITLE
Have the default or example values of Array  in Pojo

### ISSUE THREAD

**Issue by jokumar** [joelittlejohn/jsonschema2pojo#970]
Is there a way to get the default value of the array in the pojo ?

For example my default json is : 
```
{
  "checked": false,
  "dimensions": {
    "width": 11,
    "height": 10
  },
  "id": 1,
  "name": "A xxxx door",
  "price": 12.5,
  "tags": [
    "home",
    "green"
  ]
}
```

I would like to have the values of tags in the pojo as it is a default value 
Attaching the schema as well . 
[schema.txt](https://github.com/joelittlejohn/jsonschema2pojo/files/3080931/schema.txt)

**Comment by joelittlejohn** [comment]
Sorry, the example JSON is supposed to be a shortcut to generate types that can represent it. If you want more advanced features, like defaults, create a schema.
