### ISSUE TITLE
OSGI compatibility

### ISSUE THREAD

**Issue by rleonardco** [joelittlejohn/jsonschema2pojo#972]
OSGI has the concept of an api bundle, and a provider bundle.  The purpose of the API bundle is to provide Java interfaces to the implementation classes found in the provider bundle.

It would be great if your maven plugin would auto-generate an interface class for each POJO, which could then be copied to the api bundle.

**Comment by joelittlejohn** [comment]
I don't think we'll do this for OSGI compatibility, but you might be interested in upvoting #1080.
