### ISSUE TITLE
Nested java classes always null / not initialized

### ISSUE THREAD

**Issue by kmualem** [joelittlejohn/jsonschema2pojo#974]
When there is a json object in the schema, which results as a new nested class, the generated parent class with the nested class is always null, thus the default of the nested class is wrong.

An example for such schema:

>  "dimensions": {
>       "$id": "#/properties/dimensions",
>       "type": "object",
>       "title": "The Dimensions Schema",
>       "description": "An explanation about the purpose of this instance.",
>       "readOnly": true,
>       "writeOnly": false,
>       "required": [
>         "width",
>         "height"
>       ],
>       "properties": {
>         "width": {
>           "$id": "#/properties/dimensions/properties/width",
>           "type": "integer",
>           "title": "The Width Schema",
>           "description": "An explanation about the purpose of this instance.",
>           "default": 0,
>           "examples": [
>             5
>           ],
>           "readOnly": true,
>           "writeOnly": false
>         },
>         "height": {
>           "$id": "#/properties/dimensions/properties/height",
>           "type": "integer",
>           "title": "The Height Schema",
>           "description": "An explanation about the purpose of this instance.",
>           "default": 0,
>           "examples": [
>             10
>           ],
>           "readOnly": true,
>           "writeOnly": false
>         }
>       }
> 

In the generated POJO parent class I'm expecting to see new Dimensions(), but instead, the
object is not initlaized and always null.

This is super critical for us, becuase we use the POJOs and transform it later on to JSON structure.

Can you please advise?

Any help is appriciated!

Thanks,
Kobi.

**Comment by kmualem** [comment]
Hi Guys,

Can you please advise? Is it a known issue? Is there a way to workaround it?

**Comment by joelittlejohn** [comment]
There is no feature of this library that would create new Dimensions() in the parent class. Why would you expect this?

**Comment by kmualem** [comment]
I've expected to have an option to initialize all known Objects (defined as JSON objects in the schema), in the parent POJO class like there is in option to initlaize java collection.

Think that there is a default for the Dimensions JSON object, then, I'm expecting that a JSON transformation of the POJO will results with a Dimentions object JSON that contains the default values from the schema.
Currently, the Dimensions object is null, so there is no representation in the JSON transformation at all.

**Comment by joelittlejohn** [comment]
I'm afraid this library will not introduce empty objects like you expect. It is not a known issue, the feature does not exist.

Regarding default, we support simple scalar defaults but not complex objects.

**Comment by kmualem** [comment]
I understand. Maybe do you know if there is some library that could help me to achive my goal?
Generally, I need to create a default JSON document from a given JSON schema (that includes the defaults)?

Thanks a lot for the quick reply!

**Comment by joelittlejohn** [comment]
No idea I'm afraid. I hope you find what you need though.
