### ISSUE TITLE
Add support for immutable objects

### ISSUE THREAD

**Issue by joelittlejohn** [joelittlejohn/jsonschema2pojo#98]
_Original author: stevedun...@gmail.com (April 10, 2013 00:49:55)_

My Jackson-enabled POJOs are immutable. They look like this:

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonProperty;

public final class ImmutableLabel {

```
private final String label;

@JsonCreator
public ImmutableLabel(@JsonProperty(value = &quot;label&quot;) String aLabel) {
    label = aLabel;
}

public String getLabel() { return label; }
```

}

It would be really cool if there was an &quot;immutable&quot; switch I could throw.

Thanks!

Steve

_Original issue: http://code.google.com/p/jsonschema2pojo/issues/detail?id=98_

**Comment by ESTSky** [comment]
Hey Joe. When are you planning to do this?

**Comment by samskiter** [comment]
@joelittlejohn This is something I might be interested in picking up. I'm mainly interested in limiting visibility of setters as well (making them protected would allow me to subclass a model object to expose the setter if I wish).

**Comment by jurgc11** [comment]
This would be a great addition for me.
+1

**Comment by joelittlejohn** [comment]
No need for us to implement all this code ourselves when there are many other libraries that can do it. We'll support this by adding support for Lombok, Vert.x or Immutables (see other issues).

**Comment by a-panayotopoulos** [comment]
This comes up as the top Google result for "jsonschema2pojo immutable objects". It's weird that nobody's mentioned that you can prompt objects such as the above to be created via the following combination of switches:

- includeGetters = true
- includeSetters = false
- includeConstructors = true

**Comment by lukelast** [comment]
> This comes up as the top Google result for "jsonschema2pojo immutable objects". It's weird that nobody's mentioned that you can prompt objects such as the above to be created via the following combination of switches:
> 
> * includeGetters = true
> * includeSetters = false
> * includeConstructors = true

If you do that there's no way to make a modified copy right?
