### ISSUE TITLE
Comparing newly created class with an already existed class structures

### ISSUE THREAD

**Issue by 1geeky** [joelittlejohn/jsonschema2pojo#986]
Hi,

I'm making new classes using a set of json string responses and saving the .java class files. 
I need to compare the json response structure with an already created .java file (if exists) every time before making a class of that json string.

**Does jsonschema2pojo have an inner tool to do this comparison?** In the absence of such a tool, I thought of try mapping (by Jackson Object mapper) the json response to the already existed class, if the fields don't match and Object mapper throws an error (hopefully), Then we could continue with the task of replacing this new file with the older version .java file.
Something like this:

		JCodeModel codeModel = new JCodeModel();

		GenerationConfig config = new DefaultGenerationConfig() {

			@Override
			public SourceType getSourceType() {
				return SourceType.JSON;
			}
		};

		SchemaMapper mapper = new SchemaMapper(
				new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore()), new SchemaGenerator());

		mapper.generate(codeModel, action, packageName, apiResultString);

		codeModel.build(Files.createTempDirectory("test").toFile());

		// Compile the .java file ...

		try {
			objectMapper.reader(apiResultAsString, CreatedClass.class);
			
			//Remove the CreatedClassTemp.java file since the old class apparently matches the current json response structure
		
		} catch (Exception e) {
			
			// Replace CreatedClass.java file with the new file CreatedClassTemp.java
		}

However, This has an overhead while needs to create and compile a temporary class, in every attempt.
What do you suggest?

Thanks

**Comment by joelittlejohn** [comment]
There's nothing in this project that will do this for you. Sorry, this has nothing to do with this project at this point, maybe talk this through with a colleague?

**Comment by 1geeky** [comment]
Thanks for the response Anyway :)
