### ISSUE TITLE
Get the names of generated classes in an attempt

### ISSUE THREAD

**Issue by 1geeky** [joelittlejohn/jsonschema2pojo#988]
jsonschema2pojo generates Java classes recursively based on every existed object in the json string. 

for example with a json result like this:
```
{
    "error": {
        "message": "A view with the same name already exists.",
        "code": 5162
    }
}
```

and the given class name as `View`, it generates `View.java` and `Error.java` files using below code:
```
mapper.generate(codeModel, className, packageName, apiResultString);

codeModel.build(new File("src").getAbsoluteFile());
```

How could we get a list of the names (or classes) which are generated based on nested objects in json body, so we know which classes are added to our package in addition to the root one explicitly named by us?

An issue is when I pass a plural name as class name to `mapper.generate()` (e.g. listDevices which is a json array in the first level, and objects in the second level) , jsonschema2pojo automatically singularizes it (i.e listDevice), so can't accurately reference the file name to compile that. What's the workaround for this?

Thanks

**Comment by 1geeky** [comment]
Any Idea?

**Comment by joelittlejohn** [comment]
Try `JCodeModel#packages()`, then call `JPackage#classes()` on each ¯\_(ツ)_/¯

**Comment by 1geeky** [comment]
@joelittlejohn Thanks a lot and ✌(ツ)
