### ISSUE TITLE
Make the generated class from Json string, Implementing an interface or Inheriting a Class

### ISSUE THREAD

**Issue by 1geeky** [joelittlejohn/jsonschema2pojo#989]
I saw there's a way to make a generated class inherit from another class by adding `JType` property to the JSON Schema, But how could we add an implementation/inheritance to the generated class when our source is a JSON string, not a schema?

The code is this:

```
JCodeModel codeModel = new JCodeModel();

GenerationConfig config = new DefaultGenerationConfig() {
	@Override
		public SourceType getSourceType() {
			return SourceType.JSON;
			}
		};

SchemaMapper mapper = new SchemaMapper(new RuleFactory(config, new Jackson2Annotator(config), new SchemaStore()), new SchemaGenerator());

mapper.generate(codeModel, action, packageName, apiResultAsString);

codeModel.build(new File("src").getAbsoluteFile());
```

The `JCodeModel` has the option to implement Interface in a class ( `_implements()` ), But I can't utilize it in the above code:

```
// _implements() works on a JDefinedClass, 
// To get JDefinedClass we need to run _getClass() on a generated codeModel (after mapper.generate() ), 
// But What should be provided as a fully qualiflied class name for the argumanet of _getClass(),
// where or .java file isn't built yet, so the class file.

codeModel._getClass("com.foo.Bar")._implements(JsonResponseObject.class);
```

**Comment by joelittlejohn** [comment]
This a CodeModel question.

Look at the Javadocs for CodeModel. You'll see there there is another version of `_implements` that takes a JType argument. You can create a JType without having the class on the classpath, just use the `JCodeModel#directClass(String)` method.

I'm more than happy to help you if you have a problem with *this project*, but for any other topic please take it to StackOverflow.

**Comment by 1geeky** [comment]
Thank you Joe,

I see. Sorry for the inconvenience.

P.s: The `_implements()` method on the `JClass` is just an iterator which returns current interfaces, and doesn't apply a new implementation to the codeModel.

**Comment by joelittlejohn** [comment]
Look at the javadoc for JDefinedClass. You'll see what you need.
