### ISSUE TITLE
Convert from one date format to another

### ISSUE THREAD

**Issue by tha022** [joelittlejohn/jsonschema2pojo#991]
Hi guys

In my JSON document in MongoDB we have stored dates with format: "dd.MM.yyyy", which is not valid JSON schema date time (which is yyyy.MM.dd). I got it working by setting these configuration parameters in pom

```
<formatDates>true</formatDates>
        <formatTimes>true</formatTimes>
        <dateTimeType>java.time.LocalDateTime</dateTimeType>
<dateType>java.time.LocalDate</dateType>
```

And the Java code got generated correctly:
```
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd.MM.yyyy")
@JsonProperty("renewalDate")
@JsonPropertyDescription("Renewal date of the policy")
private LocalDate renewalDate;
```

But this will output date in invalid JSON schema format. Is there any way I can read date with one format (dd.MM.yyyy) and output it in other (yyyy.MM.dd)?

**Comment by joelittlejohn** [comment]
This is one to solve outside this library I'm afraid. I'm sure you can customize either Jackson or the serialization step before you read/write Mongo.
