### ISSUE TITLE
Issue with maven-plugin using useCommonsLang3

### ISSUE THREAD

**Issue by rohitrj2ee** [joelittlejohn/jsonschema2pojo#996]
Hello,

I am trying to use the following snippet and i see a warning with `[WARNING] useCommonsLang3 is deprecated. Please remove it from your config..` I am setting this value to true and i still see that the generated code has regular hashcode, equals and toString methods instead of using apache commons. Am i missing something?

```
            <plugin>
                <groupId>org.jsonschema2pojo</groupId>
                <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                <version>1.0.1</version>
                <configuration>
                    <sourcePaths>src/main/resources/api/JSONSchema.json</sourcePaths>
                    <targetPackage>com.abc.model</targetPackage>
                    <useCommonsLang3>true</useCommonsLang3>
                    <useBigDecimals>true</useBigDecimals>
                    <includeJsr303Annotations>true</includeJsr303Annotations>
                    <outputEncoding>${project.build.sourceEncoding}</outputEncoding>
                    <sourceType>jsonschema</sourceType>
                    <annotationStyle>jackson2</annotationStyle>
                    <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
                    <serializable>true</serializable>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by joelittlejohn** [comment]
We don't use commons-lang for hashcode, equals and toString any more, so asking to specify which version of commons-lang to use is irrelevant. The config option has no effect, so you should remove it.

**Comment by cgjones255** [comment]
I work for a large company and we make use of jsonschema2pojo in many places. The problem we have with the new java implementation for hashcode, equals and toString is that they break our standard pmd and spotbugs rules. The commons-lang3 implementation was significantly better for this although not perfect. We would prefer to have to option of using commons-lang3 as an alternative option that allows for more flexibility. Would this not be possible?

**Comment by joelittlejohn** [comment]
Can we satisfy this by annotating these methods to be ignored by spotbugs and pmd? I'm also interested to know, would this be solved by reintroducing the @Generated annotation on the generated class files? We removed this to make using this project from Android simpler.

**Comment by cgjones255** [comment]
This would resolve the issues but we have a firmwide Sonar instance that would still catch them. I would also argue that spotbugs/pmd issues should be fixed regardless of whether the class is generated or not as can highlight security issues. I guess this is a separate issue though. 

The commons-lang3 functionality would be a nice to have and given the functionality was there before, should be fairly straightforward to reinstate as an alternative.

**Comment by joelittlejohn** [comment]
Can you elaborate on what the issues raised by static analysis are? Maybe we can fix these.

When source code is generated and not hand written, hashcode/equals/toString that is implemented without commons-lang is superior in every way. There's no reason for us to maintain support for both types of generation in this project, because this also has a cost, and there's no intrinsic reason that people should choose a commons-lang version in future. We need to look for a way to resolve your issues with the new implementation (and I'm sure this will make things better for everyone, assuming the issues your analysis has raised are real problems).

**Comment by cgjones255** [comment]
I'll collate the different spotbugs problems and raise a separate issue. Will take some time to list them all with examples.
