### ISSUE TITLE
Enumeration name fallback for JSON serialization

### ISSUE THREAD

**Issue by ddcruver** [joelittlejohn/jsonschema2pojo#999]
The use case is I would like to use enumerations in JSON that follow the "human-readable" convention but also except the generate numeration name during JSON deserialization.  This is for legacy reasons and completeness.  i.e. we might be coming from an existing POJO or developers that may be to use to using the enumeration name in JSON instead of a better "human-readable" version.

In my example Digit POJO I would like the user to define a digit as "One", "Two" ... "Nine" in JSON but also support using the generated names "ONE", "TWO", "THREE" ... "NINE" as well.

Example Schema Definition:
```json
{
  "$id": "https://example.com/schemas/math/Digit.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "string",
  "javaType": "com.example.api.math.Digit",
  "description": "All the digits.",
  "enum": [
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine"
  ],
  "required": [],
  "definitions": {},
  "additionalProperties": false
}
```

Example Generated POJO:
```java

package com.example.api.math;

import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


/**
 * All the digits.
 * 
 */
public enum Digit {

    ONE("One"),
    TWO("Two"),
    THREE("Three"),
    FOUR("Four"),
    FIVE("Five"),
    SIX("Six"),
    SEVEN("Seven"),
    EIGHT("Eight"),
    NINE("Nine");
    private final String value;
    private final static Map<String, Digit> CONSTANTS = new HashMap<String, Digit>();
    private final static Map<String, Digit> NAMES = new HashMap<String, Digit>();

    static {
        for (Digit c: values()) {
            CONSTANTS.put(c.value, c);
        }
        for (Digit c: values()) {
            NAMES.put(c.name(), c);
        }
    }

    private Digit(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return this.value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Digit fromValue(String value) {
        Digit constantValue = CONSTANTS.get(value);
        if (constantValue == null) {
            {
                Digit nameValue = NAMES.get(value);
                if (nameValue == null) {
                    throw new IllegalArgumentException(value);
                } else {
                    return nameValue;
                }
            }
        } else {
            return constantValue;
        }
    }

}
```

**Comment by ddcruver** [comment]
@joelittlejohn Here is a draft implementation of the feature without unit tests or a way to turn on/off the feature.  Do you think this feature would require configuration property to enable it?  If so should it be on or off by default?

**Comment by joelittlejohn** [comment]
@ddcruver I'm afraid I don't think this is something we should add to jsonschema2pojo. You're asking for the types to support data that is invalid according to the schema, and to encourage multiple different representations of the same data in the wild. Also, the difference between the 'human readable' and the constant name is almost zero (they're both human readable).

I don't want to say you don't have a valid reason for wanting this, because I'm sure you're dealing with an awkward situation, it's just not something we should be including in the core and supporting forever more. I think in this case you should just fork this library and use a custom version in the places you have this requirement, or alternatively, create custom RuleFactory and replace the EnumRule (then there is no need to fork).

**Comment by ddcruver** [comment]
My term 'human readable' maybe should be more like displayable to end user.  The names (Java Enum Name) generated by the EnumRule are human readable to an programmer but are not natural to an end user.  Many of our types have a getDisplayFriendly() field which was defined by an interface I created that allows us to provide a value that can be displayed to an end user.  With the migration of our types to jsonschema it is hard to provide this except if we just use the name we want to display to user in the definition of the schema.

The problem I am describing to you is based on converting existing types to support the display friendly name and balance the changes to not cause disruption to other developers on our project and existing configurations that are now invalid because of these changes.   The fallback to the name (Java Enum Name) would reduce these cases.

I could put an warning logger in the fromValue method but I don't believe loggers are supported by the jsonschema2pojo generation yet. (SLF4J would be nice).

I do agree with it being invalid but their is a one-to-one mapping between the value and the enum name generated.

We want to avoid forking the repository but I do understand you hesitation with having jsonschema2pojo support invalid json.  I could implement it off by default but will respect your decision to not include it in the project.  I will have to end up writing some custom Jackson serializes to support this use case on our project.
